### ISSUE TITLE
Is there any directives for input control? I can't find any directives for it.

### ISSUE THREAD

**Issue by mobilestar2015** [valor-software/ng2-bootstrap#1053]
Specifically I want to set the mask of the input but I can't find.

**Comment by Martin-Wegner** [comment]
Could you please provide the orginal bootstrap widget?

**Comment by mobilestar2015** [comment]
Hello @Martin-Wegner 

I wanted to use standard <input> tag with mask but I couldn't find anything on this library.
So I found other npm package(angular2-text-mask) for input mask.

**Comment by Martin-Wegner** [comment]
Hmmm OK, but I really don't know if this is realted to bootstrap? @valorkin what do you think?

**Comment by mobilestar2015** [comment]
I think input mask is mandatory , so I only want to integrate this function into your library.
Hope this library supports all components.

**Comment by valorkin** [comment]
Most probably not >.<
