### ISSUE TITLE
modal on hide make the app reload to http://localhost/?#

### ISSUE THREAD

**Issue by nampdn** [valor-software/ng2-bootstrap#1136]
I'm using the latest ng2-bootstrap. 
When I close a modal, I don't know why it can make the entire app reload, check out the Network tab in the developer console, it sends a request to http://localhost:myport/?#, and then whole app reloads the current page.
This problem just happens 2-3 days ago.
Please help me figure this out.

**Comment by andrewwiik** [comment]
did you ever solve this?
