### ISSUE TITLE
Tooltip bubble arrow is not properly centered with bootstrap 4

### ISSUE THREAD

**Issue by liofal** [valor-software/ng2-bootstrap#3940]
### Bug description or feature request:
Tooltip bubble arrow is not properly centered with bootstrap 4

It can be easily produced in the demo website
https://valor-software.com/ngx-bootstrap/#/tooltip

Hovering over any tooltip in the tooltip demo site, for Bootstrap4 website will render differently than for bootstrap3
![image](https://user-images.githubusercontent.com/717272/37094050-d7d36d60-2211-11e8-8cdd-7d0edc00a3c5.png)

Also, we have the feeling this problem did not occur previously before a change was introduced to fix the same issue for Bootstrap3:
https://github.com/valor-software/ngx-bootstrap/pull/3405/files

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap@2.0.2

@angular/core@5.2.4

bootstrap@4.0.0

### Build system:
Angular CLI

**Comment by cristianmartinez** [comment]
Hey @liofal, you are right. There is a small issue when positioning the tooltip arrow.

I think this is a possible solution:

```
 ...
  styles: [
    `
    :host.tooltip {
      display: block;
    }
    :host.bs-tooltip-top .arrow, :host.bs-tooltip-bottom .arrow {
      left: 50%;
      /* Subtract the 50% of the width with negative margin */
      margin-left: -0.4rem;
    }

    :host.bs-tooltip-left .arrow, :host.bs-tooltip-right .arrow {
      top: 50%;
      /* Subtract 50% of the height with negative margin */
      margin-top: -0.2rem;
    }
  `
  ],
...
```

Is this a clean solution?

**Comment by liofal** [comment]
Thanks for your answer.

Sorry for a delayed answer from my end,

For us, this commit solved our issue:
https://github.com/valor-software/ngx-bootstrap/commit/0b1d8e721f04c96d7d7e070e369f57bc834cc58d

We validated through testing, for me we can close this issue.

Kr,
Lionel
