### ISSUE TITLE
Dropdown remains open when clicking inside another dropdown on the same page

### ISSUE THREAD

**Issue by masoomar** [valor-software/ng2-bootstrap#4258]
### Bug description or feature request:
This happens when you have multiple ngx-bootstrap dropdowns on the same page.
When you click on one dropdown to open it, and then click on another dropdown to open the second one, the first one still remains open, even when autoClose is not set to false. However, it does close when you click anywhere outside other than the dropdowns. Expected behavior should be that the dropdown should close even when one clicks inside another dropdown.

Note: This happens only when $event.stopPropagation(); is called inside toggleDropdown method.

### Plunker that reproduces the issue:
https://plnkr.co/edit/zgFNXHgVHV8cfZZlqowo?p=preview

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 2.0.4

Angular: 4

Bootstrap: 3

### Build system: 
webpack

**Comment by valorkin** [comment]
Stop propagation blocks population of dropdown click event, so second dropdown will not know about first click.
