### ISSUE TITLE
Add language translation for Afrikaans, Xhosa, and Zulu

### ISSUE THREAD

**Issue by grant-marrow** [valor-software/ng2-bootstrap#4325]
Hello, I would like to know if it is possible to add language translations for afrikaans, xhosa, and zulu. It is 3 of the most popular languages in South Africa. 

Please let me know, what the process is? Thanks for a great library and for all your help. 

Regards
Grant

**Comment by valorkin** [comment]
Hey, adding locales is very easy. Search closed PRs for word 'locale' and you will find samples

Basically you need to take locale and test for it from moment.js and convert it by exampe from already merged PRs
