### ISSUE TITLE
Feature: Upgrade to use pipeable operators

### ISSUE THREAD

**Issue by sherlock1982** [valor-software/ng2-bootstrap#4332]
Recently Angular6 based on RxJS6 weas released. Starting from approx RxJS 5.5 I think they introduced new feature: pipeable (formerly lettable) operators.
This could significantly reduce bundle size and also more import compatible ( no need to patch .prototype ) e.t.c.
So would be nice to upgrade to pipeable. Probably we can even keep compatibility with RxJS 5 up to some version.
RxJS 6 contains only pipeable operators if rxjs-compat is not used.

I can make a PR request in case you're intrested.

**Comment by valorkin** [comment]
Check ngv6 branch, it's done already.
Stuck with bundling a bit

**Comment by valorkin** [comment]
Thanks for proposing a help anyway :)
