### ISSUE TITLE
Nested Modal with component is limited to parent width

### ISSUE THREAD

**Issue by mrjohnr** [valor-software/ng2-bootstrap#4333]
Hi
Angular 6.0.0
ngx bootstrap:	2.0.5

trying to use nested modals with component for editing some data.I need to open a modal from inside another modal/component.The problem is that last opened modal (child) is limited to the width of parent modal,even if I set it larger
[here is example,see the last modal](https://stackblitz.com/edit/angular-nested-component-modal-ngx-bootstrap-not-working-e4az86?file=app%2Fapp.component.ts)
thanks

**Comment by argygkou** [comment]
I have the same issue. Please help!
Angular 6.0.0
ngx bootstrap:	3.0.0

**Comment by mrjohnr** [comment]
Any chance to see an answer to this question/problem? thanks

**Comment by mrjohnr** [comment]
found a [fix](https://stackoverflow.com/questions/46815629/ngx-bootstrap-modal-opens-up-as-small-instead-of-large/46816646#comment89543746_46816646 )
