### ISSUE TITLE
How to prevent Accordion to switch groups in some circumstance.

### ISSUE THREAD

**Issue by neodown** [valor-software/ng2-bootstrap#4338]
Hi guys , I am using the accordion but I`m trying to use a function that might not be implemented. On every click (to change the accordion group showed) I want to show a confirmation modal , which then according to the choice of the modal , stays on the currently opened accordion element or switches it to the one that has been clicked. I am trying to show the modal on (isOpenChange) of the accordion group , but I cannot prevent the closing of the current group , because the event happens after it. Therefore , I think I need something like beforeChanged or something like that , to be able to preventDefault() of the change(i.e. close of the current), but there is no such event implemented. Am I wrong and can it be done in another way ? Thanks

**Comment by valorkin** [comment]
Hi

You are right preventable events are not yet implemented, but it's planned feature and is a part of roadmap.

But what you can do:
- use custom accordion header and prevent events bubbling or disable it at all
- add custom logic on acc header click and manually trigger panel events
