### ISSUE TITLE
Popover positioning auto not working as expected on right side of screen?

### ISSUE THREAD

**Issue by rscherer** [valor-software/ng2-bootstrap#4339]
### Bug description:

I'm trying to implement some popovers on our application, and the problem is that when using 'auto' positioning, some popovers on the right side of screen doesn't work as expected.  Both Left and Center elements work as intended, placing the popover on top or right positioning, but the right side still sets it to 'top', and tries to resize the popover area.

Since a lot of our content is dynamic I don't have a way to determine when it's gonna happen and fix it like, for example, manually setting it to 'left'.

It would be nice if in this case the content could be on the left side of the button. Any other help or advice would be nice too.

### Reproduction:

I could not set a stackBlitz to work and show this bug, but we're generating the popover with the following code:
`<button popoverTitle="Info" popover="auto auto auto auto auto auto" placement="auto" container="body" triggers="hover tap">
            Right
        </button>`

Left button works as expected, setting the content to right:
![image](https://user-images.githubusercontent.com/30807941/40071867-6a0b1266-5848-11e8-8284-69b33c4f1150.png)

Center button also works as expected, setting the content to top:
![image](https://user-images.githubusercontent.com/30807941/40071930-8900c472-5848-11e8-91de-e7a59c704d4a.png)

But right button set it to top and tries to resize it (the content changes its size some times before standing still):
![image](https://user-images.githubusercontent.com/30807941/40071971-b809bc6a-5848-11e8-9077-648b8899b169.png)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.5

Angular: 6.0.1

Bootstrap: 4.1.1

### Build system: Angular CLI, System.js, webpack, starter seed:

Webpack: 4.8.3

**Comment by valorkin** [comment]
Known issue, auto position in this implementation more like experimental feature, after upgrade to ng v6 (already published as v3 rc.1) I will be able to reimplement from stretch.
This point is in roadmap

Closing issues as duplicate
