### ISSUE TITLE
How to apply an angular directive to the div with .modal-dialog class?

### ISSUE THREAD

**Issue by tavai89** [valor-software/ng2-bootstrap#4347]
The problem that by documentation my modal template contain .modal-header, .modal-body and .modal-footer elements. I can't define whole modal template, since ngx modal automatically wraps the content into .modal-content>.modal-dialog.

I tried to apply directive with class selector, but this is also not working, since I think ngx module doesn't know anything about my module where the directive declared and exported.

I looking for may be some options to be able to define whole template of modal and other way to apply directive to the .modal-dialog level.

To be more specific I have create directive to make the modal draggable and I need to apply it exactly to the .modal-dialog level

Thank you for you help

**Comment by tarusin** [comment]
@tavai89 
There's no need to open an issue here if you want to ask a general question. Use <a href="https://stackoverflow.com/questions/tagged/ngx-bootstrap">StackOverflow</a> or <a href="https://ngx-slack.herokuapp.com/">Slack</a> instead.
Looks like it might solve your request https://stackoverflow.com/questions/49266902/how-to-change-ngx-bootstrap-modal-width/52742148#52742148.
