### ISSUE TITLE
Datepicker remove name attribute from input

### ISSUE THREAD

**Issue by jscharett** [valor-software/ng2-bootstrap#4348]
### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: tested 2.0.3, 2.0.4, 2.0.5
Angular: 5.2.10
Bootstrap: 3

When adding the bsDaterangepicker to as input, it seem to drop the inputs name attribute.  We use the name attribute for automated tests.

**Comment by jscharett** [comment]
This only happens when used as a bound property like `[name]="controlName"`.  When used as a static property, the name persists.

**Comment by valorkin** [comment]
Try [attr.name] 
BsDatepicker doesn't know about name attribute at all, so I am not sure how it could be fixed
