### ISSUE TITLE
Extend popover module by adding option to create a "backdrop" similar to a modal

### ISSUE THREAD

**Issue by suparnavg** [valor-software/ng2-bootstrap#4362]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Bug description or feature request:
Feature request: Ability to have a backdrop in the popover module - similar to modals. So that everything except the item to which the popover is anchored is "dimmed out".

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.0-rc.0

Angular: 4.4.6

Bootstrap: 4.1.0

### Build system: Angular CLI, System.js, webpack, starter seed:
@angular/cli: 1.4.9
node: 6.11.4
os: win32 x64
@angular/animations: 4.2.4
@angular/cli: 1.4.9
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/compiler-cli: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/language-service: 4.2.4
typescript: 2.4.2

**Comment by YuriiKrvc** [comment]
@suparnavg We adhere to the behavior of the Bootstrap functionality, therefore, this feature will not be implemented soon.

**Comment by suparnavg** [comment]
Thanks Yuriy, I understand. Found a workaround for my use case

**Comment by rkhunt007** [comment]
> Thanks Yuriy, I understand. Found a workaround for my use case

@suparnavg Can you let me know the workaround that you used for this?
