### ISSUE TITLE
zone.min.js:1 GET http://localhost:XXXX/node_modules/ngx-bootstrap/accordion.js 404 (Not Found)

### ISSUE THREAD

**Issue by M-Sivanraj** [valor-software/ng2-bootstrap#4368]
I am using ngx-bootstrap latest(3.0.0) with angular 5 and try to load an accordion it gives me an  following exception and i have tried all the solution provided by google, kindly help me to resolve this..

```
GET http://localhost:4022/node_modules/ngx-bootstrap/accordion.js 404 (Not Found)

Error: Fetch error: 404 Not Found
  Instantiating http://localhost:XXXX/node_modules/ngx-bootstrap/accordion.js
  Loading http://localhost:XXXX/app/app.module.js
  Loading app/main.js
```

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.0

Angular: 5.0

Bootstrap: 3.7

**Comment by valorkin** [comment]
File resolution is not configured properly.
With systemjs you should import ngx-bootsrap.
Like written in docs
