### ISSUE TITLE
Changing the templateOptionField to number field type doesnt work.

### ISSUE THREAD

**Issue by bandhavya** [valor-software/ng2-bootstrap#4369]
I have changed the templateOptionField to id. on changing the id value no typeahead dropdown is seen.
It is only searching based on string fields.

https://valor-software.com/ngx-bootstrap/#/typeahead#option-field

**Comment by ghost** [comment]
@bandhavya `typeaheadOptionField` supports only string type. You can convert an id into a string. 
If you still have questions, please provide more information. Please, use Plunker or StackBlitz that reproduces your issue.
