### ISSUE TITLE
adding [hidden]="true" does not hide tab heading

### ISSUE THREAD

**Issue by dolphinsd** [valor-software/ng2-bootstrap#4373]
`  <tab customClass="m-tabs__item" [hidden]="true" >
                            <ng-template tabHeading>
Tab1 
                            </ng-template>
</tab>`

The code above does hide tab content but not tab heading.

**Comment by Joklogh** [comment]
Hi @dolphinsd 
You can try to use `*ngIf` instead of `[hidden]` if you want to not attach tab into DOM. However if you need to attach the element into DOM try to add this line into component css : 
`[hidden] {
  display: none !important;
}`
Let me know if, it solves your problem
