### ISSUE TITLE
Manually trigger the .next() to fetch next set of results

### ISSUE THREAD

**Issue by bandhavya** [valor-software/ng2-bootstrap#4379]
From the example provided in docs https://valor-software.com/ngx-bootstrap/#/typeahead#async-data
Is there any possibility to trigger the .next() manually and fetch the next set of results ?

**Comment by tarusin** [comment]
@bandhavya
There's no need to open an issue here if you want to ask a general question, use <a href="https://stackoverflow.com/questions/tagged/ngx-bootstrap">StackOverflow</a> or <a href="https://ngx-slack.herokuapp.com/">Slack</a> instead.
