### ISSUE TITLE
Question: how to use ngx-perfect-scrollbar on ngx-bootstrap typeahead results?

### ISSUE THREAD

**Issue by ujtordai** [valor-software/ng2-bootstrap#4384]
### Question description :

I would like to use ngx-perfect-scrollbar on results typeahead of ngx-bootstrap.
Is it possible to do this anyway?
I appreciate if somebody has a valuable idea for it.

ngx-bootstrap: ~2.0.5
Angular: ^5.0.0
@angular/cli ^1.5.0

**Comment by YuriiKrvc** [comment]
There's no need to open an issue here if you want to ask a general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead
