### ISSUE TITLE
Popover close from within the element itself

### ISSUE THREAD

**Issue by vicky-rain** [valor-software/ng2-bootstrap#4392]
I want to create a popover with a template and within that template a button "close" wich closes this popover.
I have the following code:
html:
```
<button *ngFor="let lists of listsInfo"  [popover]="options" #pop="bs-popover" [outsideClick]="true"   [popoverContext]="{'context':lists}" placement="right">
</button>
    
<template #options  let-obj="context">
    <table>
        <tr>
            <td>姓名</td>
            <td>
                <strong>{{obj.name}}</strong>
            </td>
            <button  type="button" (click)="pop.hide()">
                &times;
            </button>
        </tr>
    </table>
</template>
```

ts:

```
import { Component } from '@angular/core';
 
@Component({
  selector: 'demo-popover-context',
  templateUrl: './popover-context.html'
})
export class DemoPopoverContextComponent {
  listsInfo=[
    {
      "id":1,
      "name":"vicky1"
    },
    {
      "id":2,
      "name":"xiaoyu3"
    },
    {
      "id":3,
      "name":"shanyao3"
    }
  ]
}
```

**Comment by vicky-rain** [comment]
error message:
ERROR TypeError: Cannot read property 'hide' of undefined

**Comment by vishranti5** [comment]
Any updates on this?, i am also getting this issue, if i add condition using *ngIf, if i remove *ngIf="!isPreview it is working fine

Here is my html,

```
<div *ngIf="!isPreview">
<button type="button" #pop="bs-popover" [outsideClick]="true" [popover]="addSectionTemplate" 
 popoverTitle="Add section name" placement="top" (click)="add()" title="Add Section" class="btn btn-default padding-top-bottom-7">
Add Section</button></div>

<ng-template #addSectionTemplate>
        <form (ngSubmit)="updateSection(sectionForm.value,pop);" class="form-inline" [formGroup]="sectionForm">
            <div [class]="sectionForm.controls.name.touched && !sectionForm.controls.name.valid ? 'form-group has-error' : 'form-group' ">
                <input type="text" class="form-control" name="name" formControlName="name">
            </div>
            <button type="submit" class="btn btn-sm" [disabled]="!sectionForm.valid" style="background-color: transparent">
                <i class="fa fa-check greenTick"></i>
            </button>
            <button type="button" class="btn btn-sm" (click)="onAddSectionCancel(pop)" style="background-color: transparent">
                <i class="fa fa-times Customcancel"></i>
            </button>
        </form>
</ng-template>
```




in TS file, 

 ```
Preview:Boolean =false;  property 
 updateSection(section: QuestionSetSection,pop:any) {
    this.store.dispatch(new UpdateSection(section));
    pop.hide();
    this.questionSet$.subscribe(result=>{
      this.questionset = result;
    });
 this.saveQuestionSet(this.questionset);
  }
 onAddSectionCancel(popup:any){
    popup.hide();
  }

```

**Comment by Ronald-13** [comment]
@vishranti5 you could probably do something this way. Since pop is undefined because of ngIf.
```
<button type="button" #pop="bs-popover" [outsideClick]="true" [popover]="addSectionTemplate" 
 popoverTitle="Add section name" placement="top" (click)="openPopover(pop)" title="Add Section" class="btn btn-default padding-top-bottom-7"> 

<ng-template #addSectionTemplate>
        <form (ngSubmit)="updateSection(sectionForm.value,pop);" class="form-inline" [formGroup]="sectionForm">
            <div [class]="sectionForm.controls.name.touched && !sectionForm.controls.name.valid ? 'form-group has-error' : 'form-group' ">
                <input type="text" class="form-control" name="name" formControlName="name">
            </div>
            <button type="submit" class="btn btn-sm" [disabled]="!sectionForm.valid" style="background-color: transparent">
                <i class="fa fa-check greenTick"></i>
            </button>
            <button type="button" class="btn btn-sm" (click)="closePopover()" style="background-color: transparent">
                <i class="fa fa-times Customcancel"></i>
            </button>
        </form>
</ng-template>
```

```
popover : any;
  openPopover(pop){
    this.popover = pop;
  }
  closePopover(){
    this.popover.hide();
  }
```

**Comment by tarusin** [comment]
@vicky-rain 
Please try to use this example:
**html**
![bed1b41715](https://user-images.githubusercontent.com/20521698/47094812-9e411d80-d234-11e8-8d8a-acc44bf5749c.jpg)
**ts**
![6480b2caa8](https://user-images.githubusercontent.com/20521698/47094797-941f1f00-d234-11e8-82a3-2f1205ba7bba.jpg)

**Comment by maleet** [comment]
One nice way without methods, variables:
```
<div [popover]="myTooltipTemplate" #popover="bs-popover" [popoverContext]="{popover: popover}"></div>

<ng-template #myTooltipTemplate let-node="node" let-popover="popover">
...
</ng-template>

```

**Comment by ajithanageswari** [comment]
> @vishranti5 you could probably do something this way. Since pop is undefined because of ngIf.
> 
> ```
> <button type="button" #pop="bs-popover" [outsideClick]="true" [popover]="addSectionTemplate" 
>  popoverTitle="Add section name" placement="top" (click)="openPopover(pop)" title="Add Section" class="btn btn-default padding-top-bottom-7"> 
> 
> <ng-template #addSectionTemplate>
>         <form (ngSubmit)="updateSection(sectionForm.value,pop);" class="form-inline" [formGroup]="sectionForm">
>             <div [class]="sectionForm.controls.name.touched && !sectionForm.controls.name.valid ? 'form-group has-error' : 'form-group' ">
>                 <input type="text" class="form-control" name="name" formControlName="name">
>             </div>
>             <button type="submit" class="btn btn-sm" [disabled]="!sectionForm.valid" style="background-color: transparent">
>                 <i class="fa fa-check greenTick"></i>
>             </button>
>             <button type="button" class="btn btn-sm" (click)="closePopover()" style="background-color: transparent">
>                 <i class="fa fa-times Customcancel"></i>
>             </button>
>         </form>
> </ng-template>
> ```
> 
> ```
> popover : any;
>   openPopover(pop){
>     this.popover = pop;
>   }
>   closePopover(){
>     this.popover.hide();
>   }
> ```


This is very helpful and working fine

**Comment by raviagheda** [comment]
> @vishranti5 you could probably do something this way. Since pop is undefined because of ngIf.
> 
> ```
> <button type="button" #pop="bs-popover" [outsideClick]="true" [popover]="addSectionTemplate" 
>  popoverTitle="Add section name" placement="top" (click)="openPopover(pop)" title="Add Section" class="btn btn-default padding-top-bottom-7"> 
> 
> <ng-template #addSectionTemplate>
>         <form (ngSubmit)="updateSection(sectionForm.value,pop);" class="form-inline" [formGroup]="sectionForm">
>             <div [class]="sectionForm.controls.name.touched && !sectionForm.controls.name.valid ? 'form-group has-error' : 'form-group' ">
>                 <input type="text" class="form-control" name="name" formControlName="name">
>             </div>
>             <button type="submit" class="btn btn-sm" [disabled]="!sectionForm.valid" style="background-color: transparent">
>                 <i class="fa fa-check greenTick"></i>
>             </button>
>             <button type="button" class="btn btn-sm" (click)="closePopover()" style="background-color: transparent">
>                 <i class="fa fa-times Customcancel"></i>
>             </button>
>         </form>
> </ng-template>
> ```
> 
> ```
> popover : any;
>   openPopover(pop){
>     this.popover = pop;
>   }
>   closePopover(){
>     this.popover.hide();
>   }
> ```

It was helpful, thank you @Ronald-13 🚀
