### ISSUE TITLE
Date input format is not working on daterangepicker....

### ISSUE THREAD

**Issue by PrashanthGowda** [valor-software/ng2-bootstrap#4397]
### Bug description or feature request:
Date input format, 

`[bsConfig]="{ dateInputFormat: 'MMMM Do YYYY' }"`

when configured with 

> datepicker

 i am getting correct view in my input text box, 

example: "May 26th 2018"

But the same configuration if i apply on 

> daterangepicker 

it is not giving me correct result. It gives output as below,

> 06/11/2018 - 07/18/2018 

i am using 

`
"ngx-bootstrap": "^3.0.0",

Angular CLI: 6.0.3
Node: 10.0.0
OS: linux x64
Angular: 6.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cli                      6.0.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3`

**Comment by clabnet** [comment]
+1 Same problem. see https://stackblitz.com/edit/ngx-bootstrap-bsdatepicker-bug with error.

**Comment by PrashanthGowda** [comment]
It was my mistake, i would have used `{ rangeInputFormat: 'MMMM DD, YYYY' }` instead of `{ dateInputFormat: 'MMMM DD, YYYY' }`. 
Closing the issue...
