### ISSUE TITLE
Add active to typeaheadItemTemplate exposed variables

### ISSUE THREAD

**Issue by rbrewington** [valor-software/ng2-bootstrap#4400]
### Bug description or feature request:
Feature request: When customizing list items using the typeaheadItemTemplate, there is no way to know whether the item is active. I would like to be able to apply an active class to an element inside the template so I can style it based on the container's active status.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 1.9.3

Angular: 4.4.6

**Comment by ghost** [comment]
@rbrewington can you be more specific why you need to apply an active class to an element inside the template? Because you can add styles in such way `.active "your element/class" {...styles}`

**Comment by rbrewington** [comment]
@svetoldo4444ka I honestly can't recall. Sorry for the trouble.
