### ISSUE TITLE
The latest published npm package depends on angular/forms 6.0.1

### ISSUE THREAD

**Issue by Toktik** [valor-software/ng2-bootstrap#4411]
### Bug description or feature request:
The github's package.json does not contain this peerDependency, but the npm published one has, which prevents proper upgrade to latest angular.
`"@angular/forms": "6.0.1"`

Look here: https://npm.runkit.com/ngx-bootstrap/package.json?t=1528067302533

**Comment by mrjohnr** [comment]
Hi
same issue here,can't upgrade angular of this error: 

> Package "ngx-bootstrap" has an incompatible peer dependency to "@angular/forms" (requires ">=7.0.0 rc.0 <8.0.0||6.0.1", would install "6.0.3")

**Comment by Toktik** [comment]
@valorkin any chance to do proper release?

**Comment by Toktik** [comment]
I think we must not explicitly depend on angular/forms. We just need to do release & npm publish.

**Comment by Yalrafih** [comment]
@valorkin can we release a new version that contains https://github.com/valor-software/ngx-bootstrap/commit/550af9c2749d6ce793a94b5bd666fe59bb005c21

**Comment by FrancescoBorzi** [comment]
I have the same issue, it is currently blocking us to upgrade to angular 6.x

**Comment by valorkin** [comment]
https://travis-ci.org/valor-software/ngx-bootstrap/builds/394020373
