### ISSUE TITLE
Typeahead retaining dropdown values on input clear when typeaheadMinLength is used

### ISSUE THREAD

**Issue by paulparas** [valor-software/ng2-bootstrap#4412]
Hi

I've recently upgraded the ngx-bootstrap from 1.8.1 to 2.0.2 . After the upgrade type ahead doesn't seem to work as expected. I'm using this example :
[https://valor-software.com/ngx-bootstrap/#/typeahead#async-data](https://valor-software.com/ngx-bootstrap/#/typeahead#async-data)

with [typeaheadMinLength]="3" 

Now , if I search, lets say "abcdef" then it starts searching after 3 characters have been typed that is abc and then abcd, abcde, abcdef and so on which is fine.

But now if I delete everything in input textbox using backspace in once go, that is I make abcdef to empty by pressing backspace until it is empty, then once input is empty, it shows drop down values again which correspond to min length which is abc. 

Ideally it should clear drop down values but looks like when you delete it very fast using backspace, it retains the values corresponding to min length token string.

It is more visible when data is fetched from a service and the data is huge, so it takes some time to load and clear.

Could you please help on this?

Thanks
Regards
Paras
![3a0789b4-48af-4812-9a17-09303e42e44d](https://user-images.githubusercontent.com/11719013/42310482-270c0cac-8059-11e8-8186-709668a3d263.gif)

**Comment by llysenko** [comment]
Please provide a reproduction via stackblitz

Starter templates:
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by paulparas** [comment]
> Please provide a reproduction via stackblitz
> 
> Starter templates:
> StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

this doesn't need any reproduction on stackblitz as I have already posted a GIF from the official ngx-bootstrap website. This can be seen here [https://valor-software.com/ngx-bootstrap/#/typeahead#delay](url)

**Comment by Pizzicato** [comment]
Any news about this? If this helps anybody, I'm doing this in the Observable creation:
```
new Observable(
      (observer: Subscriber<string>) => observer.next(this.searchInput)
    ).pipe(
      filter(() => this.searchInput.length >= this.minLength),
      mergeMap(() => this.service.search(this.searchInput))
    );
```

**Comment by apotapcukv** [comment]
Dear paulparas! As per our check this issue is fixed in the latest version, so we’re closing the issue.
Please don’t hesitate to let us know if you face further issues.
