### ISSUE TITLE
Dynamic injected Modal isn't working with a child componet

### ISSUE THREAD

**Issue by akash-potdar7** [valor-software/ng2-bootstrap#4416]
I am trying to use an alert component in a dynamic modal, saying that I have included my modal in entryComponents Array. And also have tried the child AlertComponent.
The modal just doesn't show up.
Need a solution please.

`<div class="modal-header"></div><div class="modal-body"><app-alert [alert]="alertObj"></app-alert></div><div class="modal-footer"><div id="modalActions"></div></div>`

**Comment by ghost** [comment]
@akash-potdar7 Did you add ModalModule and AlertModule to imports? We have an [example](https://valor-software.com/ngx-bootstrap/#/modals#modal-with-popups). Maybe it will help you. If not,
please provide a reproduction of this issue.
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts

**Comment by Domainv** [comment]
There has been no response. That's why the issue was closed
