### ISSUE TITLE
Why tooptip is under some layers

### ISSUE THREAD

**Issue by abbymrs** [valor-software/ng2-bootstrap#4419]
Our project used `Angular 5`. 
When I used `tooltip` of `ngx-bootstrap`, found that the `tooltip` always is under some layers(the later content or later tooltips), event it has the highest z-index, it is too strange.... 
Know how to fix this issue? 
Thanks a lot.

**Comment by Joklogh** [comment]
Hi @abbymrs 
Did you set `container` property to `body`? When you are using styles that have `overflow : hidden`, this can  fix issue.
Please let me know if it is solution

**Comment by tarusin** [comment]
@abbymrs can you be more specific or/and provide a reproduction of this issue.
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by abbymrs** [comment]
it works if I set container="body", but is still have another problem: if the tooltip trigger element is on the right boundary, and the placement is also right, then the tooltip layer will outside the viewport or will expand the screen width on mobiles
