### ISSUE TITLE
Model dialog not popup

### ISSUE THREAD

**Issue by javvadisreenu** [valor-software/ng2-bootstrap#4423]
Dear All,
  I am new in Angular I have develop on sample app using dialog model.When i am click to one button dialog not popup and the div data is show on parent page.Please help me.

Using : Angular : 5.0.0
           : "ngx-bootstrap": "^3.0.0"

**Comment by Joklogh** [comment]
Hi @javvadisreenu 
I don't understand your issue. Currently there is no dialog model in ngx-bootstrap's components.
Can you post here some example code, where is your issue?
