### ISSUE TITLE
Typeahead on reactive Forms - typeahead doesnt show up

### ISSUE THREAD

**Issue by MarcoLeko** [valor-software/ng2-bootstrap#4424]
### Bug description or feature request:
Since the doc on typeahead with reactive forms is very 'limited' I cant tell if this is a bug or the problem sits in front of the pc.^^
**Issue:**
I want to make a async http call everytime my form changed. So far this happens and I get everytime a new result when my form updates (it is what i want). **BUT** The typeahead with the array doesn't appear.

### CODE:
html:
````
<input type="text"
                   class="form-control"
                   required minlength="3"
                   name="selectedClanNameOrClanTag"
                   placeholder="Enter clan id or name..."
                   formControlName="selectedClanNameOrClanTag"
                   [(ngModel)]="filterModel.selectedClanNameOrClanTag"
                   typeaheadOptionField="tag"
                   [typeaheadItemTemplate]="clanSearchResultTamplate"
                   [typeaheadOptionsInScrollableView]="2"
                   [typeahead]="dataSource | async"
                   [typeaheadOptionsLimit]="100"
                   [typeaheadScrollable]="true"
                   [typeaheadAsync]="true"
                   (typeaheadLoading)="changeTypeaheadLoading($event)">
````
And the component:
```
   this.dataSource = this.form.valueChanges.pipe(
      debounceTime(500),
      switchMap((form) => {
        return this.service.getstats(form).map((result:someTypedArr[]) => {
           return result;
        });
      })
    );
  }
```
**_Note: I have the async pipe in the Observable binding - that means - I subscribe to it in the html template._**
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.3

Angular: 5.2.4

Bootstrap: 4.1.1

**Comment by Kaidanov** [comment]
Did you solve it?

**Comment by Kaidanov** [comment]
I think it's or ngModel or formControlName not together

**Comment by ghost** [comment]
@MarcoLeko please provide a reproduction of this issue.
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts

**Comment by MarcoLeko** [comment]
I am really unreliable, for this late response - when u guys are trying to help me out.^^ Sry for that.
I asked the same question at [stackoverflow](https://stackoverflow.com/questions/50840415/typeahead-on-reactive-forms-typeahead-doesnt-show-up) and my issue is already solved a while ago. But after reading my question I have to cringe, just because i mix up template-driven-form approach with reactive forms. Please never ever do that!

**Comment by Domainv** [comment]
Closes as outdated
