### ISSUE TITLE
ngx bootstrap progress-bar is not working

### ISSUE THREAD

**Issue by RA344710** [valor-software/ng2-bootstrap#4425]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

**Comment by RA344710** [comment]
my code : 
         <progressbar 
          class="progress-bar progress-bar-striped progress-bar-animated" 
          [value]="80" 
          [max]="100"
          style="height: 50px !important;">
          <span style="position: relative;"> success </span>

          </progressbar>

**Comment by MarcoLeko** [comment]
you need to set the width as well

**Comment by YuriiKrvc** [comment]
@RA344710 Please provide a reproduction of this issue.
You can use one of the starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts
