### ISSUE TITLE
how to create Tree menu with accordion like this : https://bootsnipp.com/snippets/REyGB

### ISSUE THREAD

**Issue by RA344710** [valor-software/ng2-bootstrap#4430]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

**Comment by tarusin** [comment]
@RA344710
You can create a Tree menu via accordion. It can look like this
![c3cede623c](https://user-images.githubusercontent.com/20521698/47084245-9fb21c00-d21b-11e8-89e1-4d12b27414e9.jpg)
Here is an example code
![82be8180bf](https://user-images.githubusercontent.com/20521698/47084279-b5bfdc80-d21b-11e8-9ead-33f640b4dfc5.jpg)
