### ISSUE TITLE
Validation is not working on manual entry 

### ISSUE THREAD

**Issue by monis01** [valor-software/ng2-bootstrap#4437]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

Hi 
I am using v#2.0.0-beta.8 and facing issue regarding validation. If user enters the value e.g. 99:99 the fields does not get validated.
what can be issue 
Thanks

**Comment by ghost** [comment]
@monis01 Could you be more specific and provide a reproduction of this issue.
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts
