### ISSUE TITLE
(Typeahead ) I need to show "name" and save "ID"

### ISSUE THREAD

**Issue by andrejm7** [valor-software/ng2-bootstrap#4440]
I'm having trouble displaying Typeahead in the Description field and saving the id.

My example
https://stackblitz.com/edit/angular-rmihct?file=src%2Fapp%2Fapp.component.html

on the console I need the "id"

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.0

Angular: 5.0

Bootstrap: 4.0.1

**Comment by vsilva472** [comment]
@andrejm7 
You can use the **[typeaheadOnSelect](https://valor-software.com/ngx-bootstrap/#/typeahead#on-select)** event to get entire selected item structure.
Take a look at https://stackblitz.com/edit/angular-6yytsz and open up the console tab

**Comment by ghost** [comment]
@vsilva472 you are right.  @andrejm7 you can easily get an id from typeaheadOnSelect output
 https://valor-software.com/ngx-bootstrap/#/typeahead#on-select
