### ISSUE TITLE
Date Selected in Datepicker does not match with the date received in object

### ISSUE THREAD

**Issue by mrugank84** [valor-software/ng2-bootstrap#4441]
I have implemented ngx-bootstrap daterangepicker.  In that when i select any date from previous month the date goes one day back then the selected in json object. Even it shows perfect selection in browser for input of daterange picker.

I can also replicate in the website example shown. You can check **Reactive forms** section 
https://valor-software.com/ngx-bootstrap/#/datepicker#reactive-forms

In Date range picker select any day of previous month and see the json output below it.

![image](https://user-images.githubusercontent.com/39330311/41585598-2f92e0d2-73c8-11e8-9898-1c07763d81be.png)

Can you suggest the solution for same?

**Comment by Domainv** [comment]
duplicates of #4437
