### ISSUE TITLE
popover RTL wrong position

### ISSUE THREAD

**Issue by NurdinDev** [valor-software/ng2-bootstrap#4442]
did anyone use popover with RTL page?

I have an issue with it, it shows in the wrong position how fix this?

**Comment by Yuriy777** [comment]
@NuruddinBadawi 
Please provide a reproduction of this issue.
You can use one of the starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by YuriiKrvc** [comment]
@NuruddinBadawi 
Please provide a reproduction of this issue.
You can use one of the starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by ghost** [comment]
There has been no response. That's why the issue was closed
