### ISSUE TITLE
ngx-bootstrap 3.0.1 typeahead, dropdown typeahead container is not added on dom.

### ISSUE THREAD

**Issue by bandhavya** [valor-software/ng2-bootstrap#4444]
Updated the version from 2.0.5 to 3.0.1, dropdown is not displaying. Typeahead result are bound to observable but typeahead is not showing matches i.e. dom is not added

This happens when typeahead is an observable of array of objects.
[typeahead]="typeaheadDataSource"

works when typeaheadDataSource is directly an array of string and not observable

**Comment by davidgallegolobato** [comment]
Any progress on this?

**Comment by jagadeesh1492** [comment]
same issue

**Comment by usuf13** [comment]
try add [typeaheadAsync]="true"

**Comment by TarasKovalenko** [comment]
@usuf13 work fine for me. Thanks.

**Comment by ghost** [comment]
@bandhavya Could you add more information, if you question wasn't resolved?
https://valor-software.com/ngx-bootstrap/#/typeahead#async-data It was added demo for async data.
