### ISSUE TITLE
rxjs filter issue in bs-directive.js in Angular 6.0

### ISSUE THREAD

**Issue by chorlick** [valor-software/ng2-bootstrap#4449]
Looks like there may be an issue in the naming context for the filter operator in the rxjs refactor updates using angular 6.0; although i think its actually a bug stemming from the rxjs library. 

line 3 in bs-directive.js needs to be changed from 
import 'rxjs/add/operator/filter';

to 

import { map, filter, scan } from 'rxjs/operators';

Should i generate a pull request?

**Comment by fchiumeo** [comment]
in what file ?

**Comment by valorkin** [comment]
@chorlick you should use v3+, it has all imports fixed for rxjs v6
or use rxjs compat with ngx-bs v2+
