### ISSUE TITLE
How to manually set custom Time Zone instead of current system time zone

### ISSUE THREAD

**Issue by SathyaChenniappan** [valor-software/ng2-bootstrap#4450]
I am using angular 5 with ngx-bootstrap datepicker.
When I tried to use the date picker, it uses the current system timezone. I need to set to the custom time zone like PST or EST.
I did not find any config options to set the time zone for datepicker.
Please help me!!

**Comment by tarusin** [comment]
@SathyaChenniappan 
There's no need to open an issue here if you want to ask a general question. Use <a href="https://stackoverflow.com/questions/tagged/ngx-bootstrap">StackOverflow</a> or <a href="https://ngx-slack.herokuapp.com/">Slack</a> instead.
