### ISSUE TITLE
Ability to add custom class date picker  

### ISSUE THREAD

**Issue by pavinthan** [valor-software/ng2-bootstrap#4451]
Ability to add custom class date picker

**Comment by Joklogh** [comment]
Hi @pavinthan 
Actually, you can provide custom class to the wrapping `div` of the date picker using `bsConfig`.
Example : `[bsConfig]="{ dateInputFormat: 'DD-MM-YYYY', containerClass: 'theme-red' }"`
In the example I am assigning class `theme-red` to the div element via `containerClass` property.

**Comment by pavinthan** [comment]
@Joklogh How can we use it by condition, I mean how to use it for a specify date?

**Comment by Joklogh** [comment]
@pavinthan  You mean for specific date?

**Comment by pavinthan** [comment]
@Joklogh Yes, is there are any way?

**Comment by Joklogh** [comment]
@pavinthan 
Here is example. https://stackblitz.com/edit/angular-ngx-bootstrap-iptnje
Basically, you can bind object in template to `bsConfig` property, then if you change `containerClass` in that object whole Datepicker will reflect these changes. In example you can see how color can be changed from the template(clicking button) as well as from the controller (using `changeColor` function).
Color of the Datepicker is determined which day was selected in picker.
If you have any questions, let me know.

**Comment by pavinthan** [comment]
@Joklogh OK in the example I need to change color to red in July 14 and 15 how can I do it?
for an example : We need to highlights July 14 and 15, because It's our offer days to book rooms in our hotel.

**Comment by Joklogh** [comment]
@pavinthan 
Change condition on line 28 to this : `(event.getDate() == 15 || event.getDate() == 14) && event.getMonth() == 6` It will apply red theme if you choose July 14 or 15

**Comment by Joklogh** [comment]
@pavinthan 
Did it help?

**Comment by pavinthan** [comment]
@Joklogh No, I need to configure the color as well

**Comment by ghost** [comment]
@pavinthan thank you for your question. But this is a general question. Please,
use <a href="https://stackoverflow.com/questions/tagged/ngx-bootstrap">StackOverflow</a> or <a href="https://ngx-slack.herokuapp.com/">Slack</a> instead

**Comment by pavinthan** [comment]
@svetoldo4444ka It's not general question, It's feature request. please keep this open because We can track the feature
