### ISSUE TITLE
[Question] Setting local to datepicker

### ISSUE THREAD

**Issue by piernik** [valor-software/ng2-bootstrap#4453]
I want to localize datepicker.
 When importing `BsDatepickerModule` I have also code : 
```
import {defineLocale} from 'ngx-bootstrap/chronos';
import {plLocale} from 'ngx-bootstrap/locale';

defineLocale('pl', plLocale);
```

But then calendar is still in english.
When I code in component:
```
constructor(private localeService: BsLocaleService) {
  }

  ngOnInit() {
    this.localeService.use('pl');
  }
```
It is in polish.

Step in component is necessary?

**Comment by tumit** [comment]
Did you import "BsDatepickerModule" in AppModule already ?
`
// RECOMMENDED (doesn't work with system.js)
import { BsDatepickerModule } from 'ngx-bootstrap/datepicker';
// or
import { BsDatepickerModule } from 'ngx-bootstrap';

@NgModule({
  imports: [BsDatepickerModule.forRoot(),...]
})
export class AppModule(){}
`

**Comment by piernik** [comment]
Yes.

**Comment by frostbtn** [comment]
Just place both calls to `defineLocale` and `localeService.use` into `AppComponent.ngOnInit` and be done with it. No need to call `localeService.use` from every component you use the datepicker on.
