### ISSUE TITLE
Datepicker arrows don't respond

### ISSUE THREAD

**Issue by emilgadzaev** [valor-software/ng2-bootstrap#4457]
Hi,
My team and I is using ngx-bootstrap datepicker.
Our app is using angular/upgrade": "^5.2.2",
The issue is - **navigation arrows don't work** , nothing is happens on click.

Dependencies:

uirouter/angularjs": "^1.0.14",
    angular/animations": "^5.0.0",
    angular/common": "^5.0.0",
    angular/compiler": "^5.0.0",
    angular/core": "^5.0.0",
    angular/forms": "^5.0.0",
    angular/http": "^5.0.0",
    angular/platform-browser": "^5.0.0",
    angular/platform-browser-dynamic": "^5.0.0",
    angular/router": "^5.0.0",
     angular/upgrade": "^5.2.2",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14",
    "ngx-bootstrap": "^2.0.4"

Any ideas why? or similar issues?

**Comment by Joklogh** [comment]
Hi @emilgadzaev 
Can you provide more information? Arrow is not rotating on click or is not shown at all.
Image of the situation would be great

**Comment by YuriiKrvc** [comment]
@emilgadzaev Please provide more information or reproduction of this issue.
You can use one of the starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by ghost** [comment]
There has been no response. That's why the issue was closed
