### ISSUE TITLE
ModalOptions not working when using ModalService

### ISSUE THREAD

**Issue by thaison316** [valor-software/ng2-bootstrap#4458]
I was able to get a component popup using the ModalService, however, I cannot seem to get the Modal Options to take.  Tried replicating the first example on here everything works except for the options.
https://valor-software.com/ngx-bootstrap/#/modals#service-component

I then tried something very simple, 

`let t:BsModalRef = this.bsModalService.show(PopUp,{show:true});`

still does not seem to take in the options.  any thoughts?

**Comment by Lroca88** [comment]
@thaison316 I had the exact same issue you are presenting. I found a way to pass in the options, the key is that **you need to have initialized your variables in the modal component.**

Let me explain this more clearly, using the [same example you are referencing](https://valor-software.com/ngx-bootstrap/#/modals#service-component):

1. With the exact example as shown below, I only get to display the **list** item, title is not displayed.
```
export class ModalContentComponent implements OnInit {
  title: string;
  closeBtnName: string;
  list: any[] = [];
 
  constructor(public bsModalRef: BsModalRef) {}
 
  ngOnInit() {
    this.list.push('PROFIT!!!');
  }
}
``` 

2. With these changes I'm able to debug and see the values coming through.

```
export class ModalContentComponent implements OnInit {
  title: string = '';
  closeBtnName: string = '';
  list: any[] = [];
 
  constructor(public bsModalRef: BsModalRef) {}
 
  ngOnInit() {
    this.list.push('PROFIT!!!');
  }
}
``` 

What I've seen is, that even when the variables get initialized , The modal-footer still shows **Close** instead the value I have sent for `closeBtnName`. This is due the next line of code located in **demo-modal-service-component**:
`this.bsModalRef.content.closeBtnName = 'Close';`

You can either get rid of it, or use it as is.

**Comment by MarkJAmes1217** [comment]
can you please tell me what exactly you want to do.

**Comment by ghost** [comment]
@thaison316 Please tell us what is your goal, and could you provide a reproduction of your code
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts

**Comment by ghost** [comment]
There has been no response. That's why the issue was closed
