### ISSUE TITLE
Testing: StaticInjectorError BsDropdownDirective -> ComponentLoaderFactory WITH forRoot()

### ISSUE THREAD

**Issue by werthdavid** [valor-software/ng2-bootstrap#4459]
### Bug description or feature request:
I updated my project to latest Angular version and also updated the dependencies. The application is running fine now but when I run the tests (ng test) I'm experiencing the following error in my AppComponent (app.component.spec.ts):

`
Error: StaticInjectorError(DynamicTestModule)[BsDropdownDirective -> ComponentLoaderFactory]: 
  StaticInjectorError(Platform: core)[BsDropdownDirective -> ComponentLoaderFactory]: 
    NullInjectorError: No provider for ComponentLoaderFactory!
`

app.component.spec.ts:
```
declarations: [
        AppComponent,
        ForbiddenComponent
      ],
      imports: [
        HttpClientTestingModule,
        APP_IMPORTS
      ]
```

app.imports.ts:
```
export const APP_IMPORTS = [
  BrowserModule,
  FormsModule,
  HttpClientModule,
  RouterModule.forRoot(ROUTE_CONFIG, {enableTracing: false}),
  TranslateModule.forRoot({
    loader: {
      provide: TranslateLoader,
      useFactory: (createTranslateLoader),
      deps: [HttpClient]
    }
  }),
  StoreModule.forRoot(reducers),
  EffectsModule.forRoot([]),
  STORE_DEV_TOOLS_IMPORTS,
  ToastrModule.forRoot({
    maxOpened: 3,
    preventDuplicates: true,
    timeOut: 7000,
    progressBar: true,
    positionClass: "toast-bottom-left",
  }),
  BsDropdownModule.forRoot(),
  DatepickerModule.forRoot(),
  TooltipModule.forRoot(),
...
];
```

also adding `BsDropdownModule.forRoot(),` directly to app.component.spec.ts imports doesn't help. Any idea?

### Plunker/StackBlitz that reproduces the issue:
None

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.1

Angular: 6.0.6

Bootstrap: bootstrap-sass 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed:

Angular CLI 6.0.8

**Comment by lucasa** [comment]
I have this error too.
Does anyone knows any fix?

**Comment by werthdavid** [comment]
Only happens in app.component.spec.ts! Other Tests that are using ngx-bootstrap as well work fine

**Comment by tarusin** [comment]
@werthdavid 
Please try to provide _BsDropdownModule.forRoot()_ into imports.

**Comment by sgda021992** [comment]
Still facing same issue... not working fine 

Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[BsDropdownDirective -> ComponentLoaderFactory]: 
  StaticInjectorError(Platform: core)[BsDropdownDirective -> ComponentLoaderFactory]: 
    NullInjectorError: No provider for ComponentLoaderFactory!
NullInjectorError: StaticInjectorError(AppModule)[BsDropdownDirective -> ComponentLoaderFactory]: 
  StaticInjectorError(Platform: core)[BsDropdownDirective -> ComponentLoaderFactory]:

**Comment by jaiprajapati3** [comment]
Face the same issue, also import BsDropdownModule.forRoot(). 

```
RecipeDetailsComponent.html:14 ERROR Error: StaticInjectorError(AppModule)[BsDropdownToggleDirective -> BsDropdownDirective]: 
  StaticInjectorError(Platform: core)[BsDropdownToggleDirective -> BsDropdownDirective]: 
    NullInjectorError: No provider for BsDropdownDirective!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:8896)
    at resolveToken (core.js:9141)
    at tryResolveToken (core.js:9085)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:8982)
    at resolveToken (core.js:9141)
    at tryResolveToken (core.js:9085)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:8982)
    at resolveNgModuleDep (core.js:21218)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:21907)
    at resolveDep (core.js:22278)
```

**Comment by Et3rnal** [comment]
I had the issue and it was `dropdown` directive missing from the upper div

**Comment by lcnvdl** [comment]
I have the same issue, using Angular 13.1.0
