### ISSUE TITLE
Accordion is getting closed after enter button clicked inside input (3.0.1)

### ISSUE THREAD

**Issue by ghost** [valor-software/ng2-bootstrap#4460]
### Bug description:
Accordion sections inside the _form_ are getting closed after enter _button_ is clicked inside the form _input_ in order to submit the _form_. The issue was not true in ^2.0.3 version.

### StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-db8fk1?file=src/app/app.component.html

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap:
3.0.1
Angular:
6.0.6
Bootstrap:
3.3.7
### Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLI

**Comment by ghost** [comment]
Seems like it is possible to overcome the issue by using an alternative way to pass header and use _div_ instead of _button_ tag (which is used by default). _button_ is the culprit of that behaviour.
```
<form role="form">
  <accordion [closeOthers]="true">
    <accordion-group [isOpen]="true">
      <div accordion-heading>Angular</div>      
      <input type="text">
    </accordion-group>
    <accordion-group>
      <div accordion-heading>Angular</div>      
      <input type="text">
    </accordion-group>
  </accordion>
</form>
```

**Comment by teahou** [comment]
I am having this issue as well, i think.  Here is my accordion: when any of the buttons inside the accordion are clicked, the openPanel() method is fired, but that should only fire when the accordion is opened.

      <accordion [closeOthers]=true>
        <accordion-group *ngFor="let activity of activities"
                         [heading]="activity.Name"
                         (click)="openPanel(activity)"
                         (isOpenChange)="openStatusChange($event)"
                         [panelClass]="customPanelClass">
          <p>Select a chemical to edit it, or click a button below to perform an action.</p>
          <button type="button" class="btn btn-primary" (click)="addExistingChemical(activity)">Add Existing Chemical</button>
          <button type="button" class="btn btn-default" routerLink="/chemical/edit/0">Add New Chemical</button>
          <button type="button" class="btn btn-default">Upload Excel FIle</button>

        </accordion-group>
      </accordion>

my versions:

angular: 5.2.0
ngx-bootstrap: 2.0.5
bootstrap: 3.3.7

**Comment by tarusin** [comment]
@ViktorSoroka 
To implement your request, we have created two solutions. But each of them is not suitable for certain requirements. One of them affects accessibility, the other affects the structure. 
At the moment we will not change the structure of the component. We adhere to the behavior of the <a href="https://getbootstrap.com/docs/4.1/components/collapse/">Bootstrap</a> functionality.
