### ISSUE TITLE
it can be possible to use datepicker without input field. use only with icon?

### ISSUE THREAD

**Issue by ShaileshInfyom** [valor-software/ng2-bootstrap#4466]
it can be possible to use datepicker without input field. just click on the icon and then select a date and got date selection event

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: ^3.0.1

Angular: 6.0.6

Bootstrap: ^4.1.1

### Build system: Angular CLI,

**Comment by ShaileshInfyom** [comment]
yes possible with    <span bsDatepicker
                    #dp="bsDatepicker" (bsValueChange)="onShown($event)"></span>

Thanks

**Comment by amcastror** [comment]
Hi @ShaileshInfyom, how can I pass the current value for the datepicker? With an input, a [(ngModel)] does the job, but I can't use that without an input.

Thanks!

**Comment by Aleccc** [comment]
Here's a more complete example:

```
<!-- Button to open calendar -->
<button type="button" (click)="d.toggle()">
    Open Calendar
</button>
<!-- Calendar -->
<span bsDatepicker
#d="bsDatepicker"
placement="right"            <!-- config inline -->
[bsConfig]="dateConfig"  <!-- config stored in component variable-->
[bsValue]="date"               <!-- initial value-->
(bsValueChange)="onShown($event)"></span>
```

**Comment by N1RESH14** [comment]
is it possible to display date picker click the calendar icon only? (I want input field and not display date picker focus on the input).
