### ISSUE TITLE
Expected Identifier. Error on IE 11 

### ISSUE THREAD

**Issue by suriish** [valor-software/ng2-bootstrap#4469]
The host object has the key as '**class**' which is the reserved key word for IE , that throwing error as 'Expected identifier' on vendor bundle. Enclose the class key within the single quotes may fix the issue. 

ngx-bootstrap 3

AccordionPanelComponent.decorators = [
  ........
                host: {
                    **class**: 'panel',
                    style: 'display: block'
                }
       ......
];

**Comment by valorkin** [comment]
@suriish this is generated code, by AoT compiler, so you should report it to angular repo please

**Comment by valorkin** [comment]
drop a link here, when you will create or find one corresponding issue
