### ISSUE TITLE
bsDatepicker should align right below the text-box.

### ISSUE THREAD

**Issue by MansoorAhmed70** [valor-software/ng2-bootstrap#4470]
I want the date picker to align bottom right of text box. But when I use placement="bottom right" the datepicker starts from end of the text box. Where as the datepicker should end below the textbox and should not go beyond the textbox.
currently i am getting datepicker as below.
![1](https://user-images.githubusercontent.com/12175132/42074125-203d1fc2-7b88-11e8-878f-baf258f79467.png)

Need something as below.
![2](https://user-images.githubusercontent.com/12175132/42074108-02a9d824-7b88-11e8-8b87-384c6d1c174d.png)

**Comment by rhlkumar234** [comment]
@valorkin  is this implemented and available in 3.3.0? tried using placement="bottom right" it doesn't work

**Comment by rhlkumar234** [comment]
@MansoorAhmed70 did you find a way to do this? Thanks

**Comment by MansoorAhmed70** [comment]
@rhlkumar234 Didn't find any way to do this using ngx-bootstrap lib. But implemented using custom CSS to place the date-picker to desired location.

**Comment by rhlkumar234** [comment]
@MansoorAhmed70 okay. This issue was closed, so expected it would have been implemented but doesn't seem to be working. Anyways thanks
