### ISSUE TITLE
Date picker does not return focus

### ISSUE THREAD

**Issue by jscharett** [valor-software/ng2-bootstrap#4472]
When selecting a data/date-range, the date picker dialog closes but does not return focus to the input the triggered it.  This seems like an accessibility issue.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.5

Angular: 5

Bootstrap: 3

**Comment by valorkin** [comment]
yes, you are right
this issue consists of 2 parts:
1. datepicker should trap focus on open
2. and giveback focus on close
