### ISSUE TITLE
Datepicker: manual input accepts invalid date

### ISSUE THREAD

**Issue by KapilSachdev** [valor-software/ng2-bootstrap#4477]
### Bug description:
Datepicker does not respect/detect the input field value and switches to (invalid) date even when the min or max conditions are defined.

#### Plunker/StackBlitz that reproduces the issue:
The documentation site itself has the issue https://valor-software.com/ngx-bootstrap/#/datepicker#min-max.
Select a valid date and change the date manually from the input field, the date switches., which should not be the case.

#### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.1 

Angular: 6.0.7

Bootstrap: 4.1

**Comment by valorkin** [comment]
@KapilSachdev thanks for reporting :)

**Comment by svetoldo4444ka** [comment]
@KapilSachdev can you provide a reproduction of this issue. 
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts

**Comment by Domainv** [comment]
Closes as outdated

**Comment by limbanmichael** [comment]
I'm experiencing the same issue.

**Comment by Domainv** [comment]
@limbanmichael You are right
