### ISSUE TITLE
ngx-bootstrap - Dropdown alignment not working

### ISSUE THREAD

**Issue by pulidovpe** [valor-software/ng2-bootstrap#4479]
#Bug description or feature request:

If I have a navbar and a button on the top middle of the page which opens a dropdown, the dropdown opens but it does to the left corner. I'm setting the dropdown menu with no align, however, when I do this the dropdown only aligns to the left.

#Here is a sample code that replicates the issue:

```html
<li class="nav-item" id="button-basic" dropdown>
   <a id="button-basic" dropdownToggle class="nav-link dropdown-toggle" aria-controls="dropdown-basic">
         Button dropdown <span class="caret"></span>
   </a>
   <div id="dropdown-basic" *dropdownMenu class="dropdown-menu" role="menu" 
   aria-labelledby="button-basic">
      <a class="dropdown-item" role="menuitem" href="#">Action</a>
      <a class="dropdown-item" role="menuitem" href="#">Another action</a>
      <a class="dropdown-item" role="menuitem" href="#">Something else here</a>
      <hr class="divider dropdown-divider">
      <a class="dropdown-item" role="menuitem" href="#">Separated link</a>
   </div>
</li>
```
Only works if I re-write the class dropdown-menu:
```css
.dropdown-menu {
    right: auto !important;
    left: auto !important;
}
```
#Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.0

Angular: 5.2.0

Bootstrap: 4.1.0

#Build system: Angular CLI, System.js, webpack, starter seed:

CLI, Webpack & SystemJS

**Comment by YuriiKrvc** [comment]
@pulidovpe I share your concern and I would like to ask you to try to use this type of drop down. Looks like it might solve your problem
https://valor-software.com/ngx-bootstrap/#/dropdowns#menu-alignment

**Comment by pulidovpe** [comment]
Hi. I've already finished that project. I'm busy with other things right now. Thanks for your suggest

**Comment by Domainv** [comment]
duplicates of #4575

**Comment by Blindfold-treacherous** [comment]
@pulidovpe https://monstrous-dallas.github.io/kMKLR1S5fLlN8p-CQPok_aAS5DA9sdQjocy60AUNp_XDzv7shUqAP7E-Y9jRAAovwvlxjoo/
