### ISSUE TITLE
Dropdown retains scroll position. 

### ISSUE THREAD

**Issue by learnuser521** [valor-software/ng2-bootstrap#4481]
### Bug description or feature request:
Open the dropdown and scroll to the bottom and close the dropdown. Open the dropdown again, the scroll state is retained. Should not the scroll position be at the top when the dropdown is opened. 

https://stackblitz.com/edit/ngx-bootstrap-h3s29c

**Comment by Joklogh** [comment]
Hi @learnuser521 
I implemented this feature here.
https://stackblitz.com/edit/ngx-bootstrap-gjwp8r
Basically, I call `scrollTo` after dropdown is being closed in order to reset scroll position.
I hope this will help to fix your issue, let me know

**Comment by learnuser521** [comment]
This works. Thank you @Joklogh
