### ISSUE TITLE
Modal padding-right=0

### ISSUE THREAD

**Issue by rafalschmidt97** [valor-software/ng2-bootstrap#4484]
### Bug description or feature request:
After closing modal body lose class modal-open but add padding-right=0 which is weird.
![bug](https://user-images.githubusercontent.com/14861637/42367531-d6d98bb8-8104-11e8-8716-1fc70bb0934d.gif)

If its not a bug just close it.

### Plunker/StackBlitz that reproduces the issue:
(it shows up on docs)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: ^3.0.1

Angular: ^6.0.7

Bootstrap: 4.1.1

**Comment by pishangujeniya** [comment]
And in my case after opening, Its adding `padding-right:17px;` to the body.

I don't want my whole body to get shifted.

**Comment by Drageaux** [comment]
Why was this closed? No plunker? 

This is a problem. Modal should not be adding inline style on close, otherwise it will dictate style of the whole body without allowing any CSS to fix it.

Couldn't it just be
```scss
body:not(modal-open){
  // padding here
}
```

**Comment by Drageaux** [comment]
> And in my case after opening, Its adding `padding-right:17px;` to the body.
> 
> I don't want my whole body to get shifted.

It's because some js code is measuring the screen width on open/close. This is especially trouble some for nested scrolling modals.

**Comment by sarvagyajain1997** [comment]
> And in my case after opening, Its adding `padding-right:17px;` to the body.
> 
> I don't want my whole body to get shifted.

did u find any solution

**Comment by pishangujeniya** [comment]
> > And in my case after opening, Its adding `padding-right:17px;` to the body.
> > I don't want my whole body to get shifted.
> 
> did u find any solution

No 😢
