### ISSUE TITLE
Datepicker: allow selection for days from adjacent months.

### ISSUE THREAD

**Issue by xerocostdistraction** [valor-software/ng2-bootstrap#4485]
### Feature request:
Datepicker doesn't allow selection of days that don't belong to the displayed month.
This behavior is hard-coded [here](https://github.com/valor-software/ngx-bootstrap/blob/b4c0bcb18732713c4732992b6987ed1d11990941/src/datepicker/themes/bs/bs-daterangepicker-container.component.ts#L64) for date range picker and [here](https://github.com/valor-software/ngx-bootstrap/blob/b4c0bcb18732713c4732992b6987ed1d11990941/src/datepicker/themes/bs/bs-datepicker-container.component.ts#L62) for single date picker.

It would be great to have an option in datepicker config to allow this.
Ideally picker would change the current month as well to the one the selected day belongs to.

Styling may still indicate that the day is from another month.

**Comment by stormit-vn** [comment]
We also interesting if this feature is added. Basically, a user can able to select any date in the picker unless it is disabled

**Comment by dottodot** [comment]
Yes please add this.

**Comment by mc-suchecki** [comment]
I've added a sketch of PR - so far without a flag to turn this feature on/off. I'll try to move this feature forward if the core team accepts it. 😉

**Comment by shlomiah** [comment]
This UX is very not pleasant, can someone give an estimation when it will be fixed?
