### ISSUE TITLE
"this.scheduler is undefined" bs-datepicker

### ISSUE THREAD

**Issue by praveenrengarajan** [valor-software/ng2-bootstrap#4488]
Getting error **this.schedulre is undefined bs-datepicker-container.component.ngfactory.js:75:79"
Included both Module in app.module and in child module
  `DatepickerModule.forRoot(),
  BsDatepickerModule.forRoot(),`
in component html
` <input class="form-control" type="text" bsDatepicker #dp="bsDatepicker" [bsValue]="bsValue">`
but when click on the input field am getting the error and not showing datepicker. Included css in angularcli file.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:3 .0.1

Angular: 5

Bootstrap: 4

**Comment by ghost** [comment]
@praveenrengarajan please, provide a reproduction of this issue.
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts

**Comment by ghost** [comment]
There has been no response. That's why the issue was closed
