### ISSUE TITLE
btnRadioGroup does not work

### ISSUE THREAD

**Issue by psined1** [valor-software/ng2-bootstrap#4489]
Radio button group does not work.

See [example on StackBlitz](https://stackblitz.com/edit/ngx-bootstrap-bfekfh?file=app%2Fapp.component.html)

The model value does not change when you click either radio. Neither works in reactive forms nor template forms.

**Comment by rakesh-shrivas** [comment]
I am aware this is old thread; however, above mentioned issue is resolved in latest package of 3.0.1.
