### ISSUE TITLE
popover title  heading contains no content.

### ISSUE THREAD

**Issue by sripalreddyadamala** [valor-software/ng2-bootstrap#4493]
Hi,
           I am using ngx popover in my application and I am getting  empty heading contains  no content as critical error when I run audit reports with wave tool bar. My requirement is not to have title in the popover. If you see the html since hidden as display none css property this element is still in the DOM and audit fails. Is  there any way you can completely remove the element from dom when it has empty title?

<h3 _ngcontent-c1="" class="popover-title" hidden=""></h3>

Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap:1.8.1
Angular:4.0.0
ngx-popover:0.0.16
![image](https://user-images.githubusercontent.com/17653691/42597593-421fdcc6-8527-11e8-9706-20971bd88096.png)

**Comment by Joklogh** [comment]
Hi @sripalreddyadamala 
All popovers will have empty title or only some?

**Comment by sripalreddyadamala** [comment]
My requirements has few popovers to be titled. But when I leave title as empty wave tool throws critical errors for accessibility Since we are making AA complaint.

**Comment by Joklogh** [comment]
@sripalreddyadamala 
Are you using `*ngFor` for looping popovers?

**Comment by sripalreddyadamala** [comment]
I mean we are using ng for for security questions labels. For username ,password,re-enter passowrd we are not using any loop. So basically you need to write  code in a way that if we do not have any title for popover then we  need to completely remove that title element from DOM So  that wave tool will not throw empty title as critcial issue .
FYI(I have raised another defect for popover):
popover is not a valid role value in the ARIA specification. I believe that you're most likely looking for tooltip for such a case, and that the ngx-popover element is your culprit (see PopoverContent.ts#L13).

**Comment by Joklogh** [comment]
@sripalreddyadamala 
I don't understand how the popover is inserted in template. By hand, you write popover where you need it? How is passed popover title? I will be glad for part of the template where is popover inserted in code not see console

**Comment by sripalreddyadamala** [comment]
![image](https://user-images.githubusercontent.com/17653691/42700328-66cacb38-8691-11e8-80d8-d3c25464f0cc.png)


![image](https://user-images.githubusercontent.com/17653691/42700535-0bfd1160-8692-11e8-907a-e7c6adc3e911.png)

**Comment by Joklogh** [comment]
@sripalreddyadamala 
Here is example how you can remove title from DOM
https://stackblitz.com/edit/angular-a37mhs
If you don't understand how the code works, let me know.
I hope this will solve error.

**Comment by sripalreddyadamala** [comment]
Thanks Joklogh!
can we able to remove role="popover" Since this is not a valid role form w3c and our audit fails with axe and chrome plugin or do i need wait for the updated version so that you put a valid role in to popover

**Comment by Joklogh** [comment]
@sripalreddyadamala 
I updated example, replace role selector with ordinary class selector.

**Comment by Joklogh** [comment]
@sripalreddyadamala 
Did it help?

**Comment by sripalreddyadamala** [comment]
Thank you sir your solution worked for me. Now my website is 100% accessible with popover fix.
