### ISSUE TITLE
How to set up an annual view or month view in ‘bsConfig’ ？

### ISSUE THREAD

**Issue by carlos-cls** [valor-software/ng2-bootstrap#4497]
The old version has this setting, but how to set it in the new version?

**Comment by tarusin** [comment]
@LuisKen 
There's no need to open an issue here if you want to ask a general question.
Use <a href="https://stackoverflow.com/questions/tagged/ngx-bootstrap">StackOverflow</a> or <a href="https://ngx-slack.herokuapp.com/">Slack</a> instead.
