### ISSUE TITLE
Loop through object in typeahead. for and in are not parsed

### ISSUE THREAD

**Issue by Vishesh-Gupta** [valor-software/ng2-bootstrap#4506]
### Bug description

The bug that I am facing is not able to understand for in the token and same with in

Error
```
Parser Error: Unexpected token 'for' at column 24 in [organization.legalName for organization in searchOrganizations($event)] in ng:///AppModule/OrgProfileContentComponent.html@154:17 ("iv class="col-md-8">
          <input [(ngModel)]="affiliationSearch.searchText"
                 [ERROR ->][typeahead]="organization.legalName for organization in searchOrganizations($event)"
               "): ng:///AppModule/OrgProfileContentComponent.html@154:17
```

HTML
```
 <input [(ngModel)]="affiliationSearch.searchText"
                 [typeahead]="organization.legalName for organization in searchOrganizations($event)"
                 (typeaheadNoResults)="typeaheadNoResults($event)"
                 [typeaheadMinLength]="4"
                 (typeaheadLoading)="loadingOrganizions"
                 (typeaheadOnSelect)="onSelect($event)"
                 [readonly]='viewState.isInROMode'
                  placeholder="{{'searchAffiliation'|translate}}"
                  class="form-control">
```

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 3.0.1
Angular: 6.0.7
Bootstrap: 3

**Comment by ghost** [comment]
@Vishesh-Gupta please, provide a reproduction of this issue.
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts

**Comment by Vishesh-Gupta** [comment]
I can't reproduce it anymore as I don't have the access to the company code anymore. I used to work there as an intern when I posted this but the issue was basically not able to find the for loop in my ts code to loop around the object in the ngx-bootstrap typeahead
