### ISSUE TITLE
Show number of entries along with pagination

### ISSUE THREAD

**Issue by nkdweb** [valor-software/ng2-bootstrap#4508]
### Description:

Do we have option of implementing show entries dropdown along with pagination as attached for your reference.

Please let me know if anyone implemented this before or is this an feature request.

![entries](https://user-images.githubusercontent.com/2375291/42862699-4a42f1d4-8a7e-11e8-82cc-daa7bf3f5907.JPG)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.1

Angular: 5.2.11

Bootstrap: 4

**Comment by tarusin** [comment]
@nkdweb 
There is no such functionality at the moment.
We will consider your request in future releases.
