### ISSUE TITLE
Use ng cli workspace to build library?

### ISSUE THREAD

**Issue by cmckni3** [valor-software/ng2-bootstrap#4513]
### Bug description or feature request:

Use Angular cli to build the library and use the underlying `ng-packagr` (Angular cli integrates with this).

```
ng new ngx-bootstrap-app
ng g lib ngx-bootstrap
```

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.1

Angular: 6.0.8

Bootstrap: 4.1.1

### Build system: Angular CLI, System.js, webpack, starter seed:

Angular cli

**Comment by valorkin** [comment]
@cmckni3 could work, can you do a PR?
BUT file structure should not change
thanks in advance

**Comment by cmckni3** [comment]
File structure at the top level would change some. The contents of `src` would go under `projects/ngx-bootstrap` for example.

**Comment by cmckni3** [comment]
I can put together a PR for some feedback though.

**Comment by Domainv** [comment]
ng-packagr already used from 3.1.1.
Closing for now.
