### ISSUE TITLE
Tab with reactive forms -> Select event triggered on doubleclick

### ISSUE THREAD

**Issue by Stan92** [valor-software/ng2-bootstrap#4515]
Hi,
I notice a strange behavior while using a reactive form with the tab component.
If you double click on a textbox field inside this form, the tabset select event is triggered.

I use ngx-bootstrap 3.0.1 & Angular 6.0

I didn't notice the behavior using Angular 5.0 and ngx-bootstrap 2.0.5

**Comment by felipesuazo** [comment]
We are having the same behavior here

**Comment by JoepKockelkorn** [comment]
Yep, I can confirm that

**Comment by klassiksharma** [comment]
the tabset select event is triggered even with tab key sometimes. anyway to solve this?

**Comment by Tushar-S-K** [comment]
Having same behaviour here, any solution ??

**Comment by llysenko** [comment]
Please provide a reproduction via stackblitz

Starter templates:
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by Domainv** [comment]
Closes as outdated
