### ISSUE TITLE
Customize Placement of Nav and Content for Tabs

### ISSUE THREAD

**Issue by prindacerk** [valor-software/ng2-bootstrap#4516]
There's no way to customize the placement of the nav and the tabs. I can do that using Bootstrap but not using ngx-bootstrap. 

I have attached an example of how I wish I could render the nav-tabs to appear. I can do this in Bootstrap but ngx-bootstrap can't do it because it renders the entire nav-tabs on it's own and bind it tightly with the tab-content inside the tabset. 

<img width="843" alt="tabs" src="https://user-images.githubusercontent.com/4536573/43055699-749fccd0-8e7b-11e8-871f-6fcc1ea96728.png">

Would be great if we can set a placeholder location inside the `<tabset>` where we want the rendered nav and the tab contents to appear. Like `<tab-nav>` and `<tab-content>` tags with their own custom class properties so they will be applied for them directly. That would allow me to place them in the right locations where I want them to appear.

**Comment by tucq88** [comment]
+1 . Facing similar problem. Was about to write my own tabs in order to solve this. It's awesome If it could be support by ngx :+1:

**Comment by ghost** [comment]
@prindacerk you can use CSS styles. For example, you can add `display: flex; justify-content: space-between` to `tab-container`, etc.
We are going to completely refactor this component. We will consider all wishes. Thank you for your question

**Comment by prindacerk** [comment]
@svetoldo4444ka css won't help if we want to control the placement of the
tab header links. The header placement is autogenerated. Even if I put the
tab tag inside a col-8 div, the tab contents will also be within the col-8
div. We can't have the header in col-8 div and the tab contents in a
complete new row. Look at the screenshot I provided which explains what I
mean.

Good that you are refactoring this component. Looking forward to the new
one. Please give more control on the tab header and content placement to
user so they can display it as they see fit.

Appreciate the hard work.
