### ISSUE TITLE
how to select a year instead of dates?

### ISSUE THREAD

**Issue by yashwp** [valor-software/ng2-bootstrap#4519]
Instead of showing dates in a calendar and selecting it, how can I show only years and make the user select the 1 year of his/her choice instead of date?

**Comment by tarusin** [comment]
@yashwp 
There's no need to open an issue here if you want to ask a general question. 
Use <a href="https://stackoverflow.com/questions/tagged/ngx-bootstrap">StackOverflow</a> or <a href="https://ngx-slack.herokuapp.com/">Slack</a> instead
