### ISSUE TITLE
bsDaterangepicker date string format

### ISSUE THREAD

**Issue by elvispdosreis** [valor-software/ng2-bootstrap#4523]
I would like to know how do I make a link with reactive form using a date string and get the same speak as string, today I can only work by creating an object of type date

that.filter = that.fb.group({
            range: [['2018-07-01', '2018-08-01']]
});

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.1

Angular: 6.0.9

Bootstrap: 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed: 
Angular CLI

**Comment by YuriiKrvc** [comment]
There's no need to open an issue here if you want to ask a general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead
