### ISSUE TITLE
How do I set size for the time picker? 

### ISSUE THREAD

**Issue by Kapperchino** [valor-software/ng2-bootstrap#4526]
I couldn't set size with css and there isn't a parameter for size in the component.

**Comment by tarusin** [comment]
@Kapperchino Please, can you be more specific or/and provide a reproduction of this issue.
You can use one of the starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by ghost** [comment]
There has been no response. That's why the issue was closed
