### ISSUE TITLE
Cannot select a month in datepicker if first day is disabled  

### ISSUE THREAD

**Issue by makeitbetter-su** [valor-software/ng2-bootstrap#4528]
### Bug description:

If the first date of month is a disabled date (e.g. a day off ), then it is not possible to pick a whole month from the monthpicker. 

**Expected:**
Month is available if at least one day is available.

**reproduce**:
https://ngx-bootstrap-rntbw1.stackblitz.io/

### Versions:

ngx-bootstrap: 2.0.5
Angular: 4.4.7
Bootstrap: 3

### Build system: 

webpack

**Comment by YuriiKrvc** [comment]
@makeitbetter-su 
Thanks for the demo. This is the old version of datepicker and we don't support it.
