### ISSUE TITLE
Value of bsDaterangepicker is inconsistent

### ISSUE THREAD

**Issue by igorcemim** [valor-software/ng2-bootstrap#4529]
The value of bsDaterangepicker is inconsistent.

Value vary based on user input:
- **No input:** `null`
- **Invalid input:** `[null]`
- **Invalid input with hypen separator:** `[null, null]`
- **Valid date and invalid date with hypen separator:** `[Date, null]`
- **Invalid date and valid date with hypen separator:** `[null, Date]`

**Suggestion:** keep only `null` or [Date, Date] values, since multiple values added unecessary complexity to code and lead to bugs.

**Angular version:** 5.2.9
**ngx-bootstrap version:** 2.0.3
**Build system:** Angular cli

# Sample use case:

## HTML:
```
<input
                type="text"
                class="form-control"
                id="intervaloDatas"
                name="intervaloDatas"
                bsDaterangepicker
                [(ngModel)]="intervaloDatas"
                [bsConfig]="{ rangeInputFormat: 'DD/MM/YYYY' }"
                (bsValueChange)="onChangeIntervaloDatas($event)" />
```

## Component:
```
intervaloDatas: Date[] = null;

onChangeIntervaloDatas(intervaloDatas: Date[]) {
        this.intervaloDatas = intervaloDatas;
}
```

If you need more details ask and I will be glad to help.

**Comment by ghost** [comment]
@igorcemim Could you please provide a reproduction of this issue. 
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts
