### ISSUE TITLE
 Ability to disable certain days of the week.

### ISSUE THREAD

**Issue by sanguine-my-brother** [valor-software/ng2-bootstrap#4531]
### feature request:

Ability to disable certain days of the week.

**Comment by sanguine-my-brother** [comment]
See pull request #4491

**Comment by gkaran** [comment]
Also an alternative allowing for more control is #4602

**Comment by ludmilanesvitiy** [comment]
Fixed in https://github.com/valor-software/ngx-bootstrap/pull/4491
