### ISSUE TITLE
Angular Schematics support

### ISSUE THREAD

**Issue by sulco** [valor-software/ng2-bootstrap#4532]
This is a feature request to have a possibility to run `ng add ngx-bootstrap` that would
- "npm install" the module (no big gain here)
- and add the style link to index.html (so developers don't need to find & copy it by hand)

**Comment by sulco** [comment]
I've prepared this kind of solution for other projects already so I'll be glad to help with this if you are opened to such contribution.

**Comment by Domainv** [comment]
thank you, will be added soon
