### ISSUE TITLE
mgechev/angular-seed Can't resolve all parameters for e

### ISSUE THREAD

**Issue by Ssuri013** [valor-software/ng2-bootstrap#4535]
### Bug description or feature request:
https://github.com/valor-software/ngx-bootstrap/blob/development/docs/getting-started/angular-seed.md
this procedure doesnt seem to work.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: ^3.0.1

Angular: 6.1

Bootstrap: 4.1.3

### Build system: ,System.js, :
The document was follwed on latest angular-seed by mgechev for angular 6.
![screenshot 23](https://user-images.githubusercontent.com/20540100/43581679-6dffd600-9677-11e8-9913-9206071c857c.png)

**Comment by hongminzhu** [comment]
I have the exact same issue when attempting to upgrade to version 3.0.1, no issues with 2.0.5.
