### ISSUE TITLE
Outside click to dismiss dropdown does not work on iOS (Safari or Chrome) on physical device.

### ISSUE THREAD

**Issue by aks1994** [valor-software/ng2-bootstrap#4537]
### Bug description or feature request:

Outside click (tap) to dismiss dropdown does not work on iOS (Safari or Chrome) on physical device.

In regular bootstrap, outside tap to dismiss works fine.

### Plunker/StackBlitz that reproduces the issue:

Issue can be seen on demo itself: https://valor-software.com/ngx-bootstrap/#/dropdowns

**Comment by greatkeke** [comment]
This issue is caused by iOS : https://www.quirksmode.org/blog/archives/2014/02/mouse_event_bub.html

Reference: https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js
