### ISSUE TITLE
node-modules/ngx-bootstrap/datepicker.js 404 Not Found error

### ISSUE THREAD

**Issue by gspeedtech** [valor-software/ng2-bootstrap#4538]
I have successfully implemented ngx-bootstrap/datepicker in an angular 5 app. But when I try to use the same component and same configuration in myAsp.Net MVC withAngular app, I get the following error.

Error: Fetch error: 404 Not Found
  Instantiating http://localhost:xxxxx/node_modules/ngx-bootstrap/datepicker.js

It appears to be trying to find datepicker.js which does not exist.

I have tried adding the following to systemjs.config.js
   
'ngx-bootstrap/datepicker':
                { main: 'index.js', defaultExtension: 'js' },

And I get this error:
   
Error: Unable to dynamically transpile ES module
   A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.
  Instantiating http://localhost:xxxxx/node_modules/ngx-bootstrap/datepicker/index.js

I have tired other variations like:
    main: 'datepicker.component.js, 
    main: 'bs-datepicker.js, 
    main: 'datepicker.module.js, 
etc.. 
They all result in the same transpile error.

This is my Systemjs.config.js
   
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/',
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: '/app',

            // angular bundles
            '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
            '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
            '@angular/platform-browser/animations':
                'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic':
                'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            // other libraries
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
            'ng2-bs3-modal': 'npm:/ng2-bs3-modal',
            'primeng': "npm:/primeng",
            'charts': "npm:/charts.js",
            'ag-grid-angular': "npm:/ag-grid-angular",
            'ag-grid': "npm:/ag-grid",
            'ag-grid-enterprise': "npm:/ag-grid-enterprise",
            'moment': "npm:/moment",
            'angular2-toaster': 'npm:angular2-toaster/bundles/angular2-toaster.umd.js',
            // ngx bootstrap
            "ngx-bootstrap": "npm:ngx-bootstrap",
            // ng2 typeahead
            "ng2-typeahead": "npm:ng2-typeahead@1.2.0"

        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: 'main.js',
                defaultExtension: 'js'
            },
            rxjs: {
                defaultExtension: 'js',
                main: "rx.js"
            },

            'ngx-bootstrap':
                { format: 'cjs', main: 'index.js', defaultExtension: 'js' },

            'ng2-bs3-modal':
            { main: '/bundles/ng2-bs3-modal.js', defaultExtension: 'js' },
            'ngx-bootstrap/datepicker':
                { main: 'index.js', defaultExtension: 'js' },
            'charts': { defaultExtension: 'js' },
            'primeng': {
                defaultExtension: 'js'
            },'ag-grid': {
                defaultExtension: 'js', main: "main.js"
            }, 'ag-grid-angular': {
                defaultExtension: 'js', main: "main.js"
            }, 'ag-grid-enterprise': {
                defaultExtension: 'js', main: "main.js"
            },
            'moment': {
                defaultExtension: 'js'
            },
            'angular2-moment': {
                main: './index.js',
                defaultExtension: 'js'
            },
        }
    });

Any suggestions on how to resolve this would be greatly appreciated.

**Comment by ghost** [comment]
@gspeedtech you should try a new ngx-bootstrap version - 3.1.1 (we have an example using with system.js [here](https://github.com/valor-software/angular2-quickstart) and if something goes wrong please provide a reproduction of this issue.
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts
