### ISSUE TITLE
range Input Format

### ISSUE THREAD

**Issue by ceyon** [valor-software/ng2-bootstrap#4539]
I use the syntax below on a input filed. The date is presented correctly.

 08-01-20158
[bsConfig]="{ rangeInputFormat : 'MM-DD-YYYY'}"   

When I check the Value by binding it i get and output of "DateOfSerice":["2018-08-01T:19:2258.000z"]

Is there a way to fix this so I just get the date output. I read through the comments etc. but can't seem to find a solution. Thanks any help is appreciated.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:
ngx-bootstrap": "^3.0.1

Angular:
6.0.9
Bootstrap:
4.1.2

### Build system: Angular CLI, System.js, webpack, starter seed:
ng-build

**Comment by ghost** [comment]
@ceyon Could you be more specific what's the problem? Did you have a problem with converting output data? You can convert it with data pipe. Or something else?  Or you can provide a reproduction of this issue.
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts

**Comment by ghost** [comment]
There has been no response. That's why the issue was closed
