### ISSUE TITLE
Add Datepicker auto placement option

### ISSUE THREAD

**Issue by jscharett** [valor-software/ng2-bootstrap#4540]
The Datepicker has a placement option which can be set to one of 4 possibilities: top, bottom, left, right.  It would be nice to have a fifth option, auto, in which the component picks the "best" of the previous 4.  This would allow the component to be more flexible without having to set it for each use case.

For example, in our application, we built a component for use with the @angular2-json-schema-form library that incorporates the datepicker.  However, depending on the form and its location, we need to specify a specific placement for the datepicker to prevent it from going off screen, as it appears center itself with the bound input.  Having a auto option here would remove the need set specific placements.  

Also, being that its bootstrap and responsive, having a auto placement would help when trying to support multiple resolutions.  Consider the 2 column layout for example.  On larger screens, you show the left hand column to the left in which the datepicker would be best represented with right placement.  However, on smaller screens, the columns typically stack to converse space, in which a top/bottom placement would not only be preferred, but likely required.  An auto option would help here I think.

**Comment by Valery-vs** [comment]
+1

**Comment by afiqwazien** [comment]
+1

**Comment by chase9** [comment]
+1 as I believe this feature is highly necessary when dealing with responsive layouts. 

Something to note is what kind of behavior we would like the date picker to exhibit when drawing off screen. Would we like the date picker to automatically pick between a layout (top, bottom, left, or right) which will fit on the screen, or would we like the date picker to keep its layout but nudge itself to it's all visible?

Personally, I believe the default behavior should be to nudge itself back onscreen (with a config option to turn that off) and that we should also add an additional 'auto' layout which will pick the best fitting of the four regular layouts.

**Comment by MrHOY** [comment]
+1 This feature is important when we make the responsive layout

**Comment by ankitvadariya** [comment]
+1 This feature is important.

**Comment by chase9** [comment]
I cloned the repo today to start work on this feature but it looks like the maintainers had read my mind!

This functionality is present in the current development build, and it looks like it was added in 66ae92d804779b0244e97bff6032632165000932.

Thank you for your hard work, everyone involved!

**Comment by chase9** [comment]
This was merged with #5065 and is included in the 4.0 release.

**Comment by ludmilanesvitiy** [comment]
Closed as outdated, see https://valor-software.com/ngx-bootstrap/#/datepicker#adaptive-position

**Comment by cristianbalint** [comment]
> Closed as outdated, see https://valor-software.com/ngx-bootstrap/#/datepicker#adaptive-position

Is not complete. This feature handles only top and bottom boundaries, but there are also left and right.

**Comment by UdayAppam** [comment]
Any solution for left and right position adjustment ?
![image](https://user-images.githubusercontent.com/10434967/75524468-f9437100-5a33-11ea-92c8-84200b645752.png)

**Comment by axell9641** [comment]
@cristianbalint @KernelLora  any solution for the left and right?

**Comment by rukesha93** [comment]
@axell9641 @cristianbalint  I had a similar issue in the responsive layout and it got resolved by adding the below CSS in the styles.css.
bs-datepicker-container {
  transform: translate3d(33px, 130px, 0px) !important;
}

**Comment by ulisesmorenomassachusetts** [comment]
I liked current solution, but Left and Right would be better, and also instead of using bsConfig, as initially mentioned, it had placement="auto", it is more untuitive.
