### ISSUE TITLE
TypeError: Ce.getComputedStyle(...) is null Firefox

### ISSUE THREAD

**Issue by RogelioCornejo** [valor-software/ng2-bootstrap#4543]
**TypeError: Ce.getComputedStyle(...) is null**

This is happening only in firefox and is related with the following bugs:

https://bugzilla.mozilla.org/show_bug.cgi?id=548397

https://bugzilla.mozilla.org/show_bug.cgi?id=1467722

This is happening with the ModalDirective when the modal component is hidden, the show action is going to fail if the modal is inside an iFrame and the modal is not visible in that momment (iFrame showing something else).

Using:

**"ngx-bootstrap": "3.0.1" and Angular 6**

**Comment by RogelioCornejo** [comment]
Some more details:

ERROR TypeError: Ce.getComputedStyle(...) is null
Stack trace:
Me</e.prototype.setScrollbar@URL
Me</e.prototype.show@URL

**Comment by ghost** [comment]
@RogelioCornejo Could you provide a reproduction of this issue?
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts
