### ISSUE TITLE
Element stay hover style when mouse leave it (Microsoft Edge)

### ISSUE THREAD

**Issue by liuyiffan** [valor-software/ng2-bootstrap#4544]
I found that it is a problem caused by ngx-bootstrap with Microsoft Edge.
I use the pseudo-class (:hover) to implement hover style in element, and use tooltip in ngx-bootstrap.
Steps:
1. Move the mouse into the ELEMENT, such as an icon
2. Leave the mouse out of the ELEMENT in same direction of the tooltip(If the tooltip is lying on the bottom of the ELEMENT, move the mouse towards bottom)
3. The ELEMENT will stays hover style.

Also, you can view https://valor-software.com/ngx-bootstrap/#/tooltip#examples on Microsoft Edge and follow my steps to see the problem.

**Comment by YuriiKrvc** [comment]
@liuyiffan Thanks. This issue will be fixed in the future releases.

**Comment by daniloff200** [comment]
Not reproducible with Chrome and FE
Also, checked on Edge (80.0.361.50) and IE 11 (11.0.9600)
