### ISSUE TITLE
Dropup menu with Bootstrap 4 doesn't open next to the button

### ISSUE THREAD

**Issue by Getz85** [valor-software/ng2-bootstrap#4545]
Using dropup="true" on a dropdown component, the menu is not displayed near the button:

![dropup](https://user-images.githubusercontent.com/5981479/43964513-455f353c-9cbd-11e8-9f2d-77c3896dc7d2.jpg)

https://stackblitz.com/edit/ngx-bootstrap-yrz4qu

ngx-bootstrap: 3.0.1
Angular: 6.1.2
Bootstrap: 4.1.3

**Comment by Getz85** [comment]
[This comment](https://github.com/valor-software/ngx-bootstrap/issues/2891#issuecomment-410346819) provide a solution:

```
.dropdown-menu {
  transform: none !important;
}
```

**Comment by zaiddabaeen** [comment]
This issue exists on Firefox for me. Chrome/Safari/Opera are all fine.
The comment about by @Getz85 does not resolve it.

**Comment by svetoldo4444ka** [comment]
@Getz85 @zaiddabaeen  It was css changes in different bootstrap's version. If you are using ngx-bootstrap's version - 4, then you should use the same bootstrap's version. It will help you to fix this issue.

**Comment by pieterdb4477** [comment]
Same issue here:
bootstrap: 4.1.3
ngx-bootstrap: 3.1.3
angular: 7.0.5

@Getz85 comment fixed the issue

**Comment by pieterdb4477** [comment]
It seems that something has changed in bootstrap which fixed the issue with dropups.

If I use @Getz85 now, the dropup appears as a dropdown. If I remove the fix, everything is back to normal.

bootstrap: 4.13 -> 4.2.1
ngx-bootstrap: 3.1.3 -> 3.1.4
angular: 7.0.7

**Comment by daniloff200** [comment]
That's not reproducible with the version 5.5.0, so, I will close it
