### ISSUE TITLE
Add onDrag listener to Sortable parent element

### ISSUE THREAD

**Issue by TannerPlauche** [valor-software/ng2-bootstrap#4548]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

#### Currently an item must be drug over an existing list item in order for the the Sortable component to add it to the list. The user should be able to hover over the parent element itself, below any list 
You can use one of starter templates:

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.1

Angular: 5

Bootstrap: 4

### Build system: Angular CLI, System.js, webpack, starter seed:
6.2.0

**Comment by ghost** [comment]
@TannerPlauche Could you be more specific and provide a reproduction or example
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts

**Comment by ghost** [comment]
There has been no response. That's why the issue was closed
