### ISSUE TITLE
Do you know why days disappearing randomly from the calendar?

### ISSUE THREAD

**Issue by rafalkasa** [valor-software/ng2-bootstrap#4549]
### Bug description or feature request:

I have a problem with datapicker control because some dates disappearing randomly.
Below you will see examples from your site?

**1. First example show missing 19th December 2021**
![image](https://user-images.githubusercontent.com/19885116/44151608-bffc1e94-a0ab-11e8-8e7f-3d7712356984.png)

**2. Second example show missing 4th December 2021**
![image](https://user-images.githubusercontent.com/19885116/44151616-c4ec6c10-a0ab-11e8-91b3-18feebb3a6e9.png)

**3. Third example show missing 15th January 2022**
![image](https://user-images.githubusercontent.com/19885116/44151623-c9a1b832-a0ab-11e8-9643-5f7cc77c0a40.png)

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 2.0.5, 3.0.1
Angular: 5, 6
Bootstrap: 4

### Locale: Web Browser Locale: Poland

**Comment by paulotokimatu** [comment]
Hmm, I checked here:
https://valor-software.com/ngx-bootstrap/#/datepicker

But even after refreshing and opening different datepickers many times I wasn't able to replicate the issue. I am using the latest version of Firefox.

Can you give more details about how to replicate it?

**Comment by tarusin** [comment]
@rafalkasa 
Please, can you be more specific or/and provide a reproduction of this issue.
You can use one of the starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by ghost** [comment]
@rafalkasa There has been no response. That's why the issue was closed
