### ISSUE TITLE
Angular 6 AOT Build issue

### ISSUE THREAD

**Issue by arunkumar200695** [valor-software/ng2-bootstrap#4552]
`ERROR in : "let-" is only supported on ng-template elements. ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" [ERROR ->]let-rowz="$implicit" let-index="i
ndex">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].sec")
: "let-" is only supported on ng-template elements. ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" let-rowz="$implicit" [ERROR ->]let-index="i
ndex">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].secondary && rowz[6].s
`ec")`

**ERROR in : "let-" is only supported on ng-template elements. ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" [ERROR ->]let-rowz="$implicit" let-index="i
ndex">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].sec")
: "let-" is only supported on ng-template elements. ("
  </thead>
  <tbody>
    <template ngFor [ngForOf]="rows" let-rowz="$implicit" [ERROR ->]let-index="i
ndex">
      <tr *ngIf="!(datePicker.onlyCurrentMonth && rowz[0].secondary && rowz[6].s
`ec")**`

**Comment by fchiumeo** [comment]
what version it's used ?

**Comment by arunkumar200695** [comment]
i'am using ngx-bootstrap@3.0.1 with Angular 6

**Comment by fchiumeo** [comment]
what file?

**Comment by igormap42** [comment]
The same issue with angular 5.
In my case it says that date-picker making problems (not sure what file exactly), but the error looks similar to @arunkumar200695's

**Comment by Domainv** [comment]
soon be fixed in new release
