### ISSUE TITLE
An error is generated while running ng build --prod

### ISSUE THREAD

**Issue by john-md86** [valor-software/ng2-bootstrap#4554]
### Bug description or feature request:
An error is generated by running ng build --prod, which refers to the Tabs component. The line that gives error in my code is equivalent to 2 in the stackblitz.

![image](https://user-images.githubusercontent.com/29717874/44289335-b222d000-a241-11e8-9473-abab25097096.png)

![image](https://user-images.githubusercontent.com/29717874/44289305-93bcd480-a241-11e8-889c-f25172f35113.png)

`ERROR in src/app/blog/container-blog/container-blog.component.html(6,30): : Expected 2 arguments, but got 1.`

### Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/ngx-bootstrap-q66cqd

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.1

Angular: 6.1.3

Bootstrap: 4.1.1

### Build system: 
Angular CLI

**Comment by fchiumeo** [comment]
filterBy need 2 arguments,only 1 is provide

**Comment by john-md86** [comment]
Sorry... my bad.
