### ISSUE TITLE
MODAL ( MOBILE BACK )

### ISSUE THREAD

**Issue by MarkJAmes1217** [valor-software/ng2-bootstrap#4555]
I m expecting that the modal will be close  if i tap the back button in my mobile

any solutions for this issue.

**Comment by Domainv** [comment]
We are not planning on adding any router interaction to modals. The reason for this is that different users want to have different modal <-> router interactions:

some people want all modals to be closed when a route change (like in your case);
some people want prevent route change if a modal is opened.
We can't decide for our users so we decided to not have arbitrary logic and have users code preferred modal <-> router interactions on their end.

Closing as won't fix.

**Comment by Domainv** [comment]
example of solution
```
import { PlatformLocation } from '@angular/common';

...

  constructor(
    private modalService: BsModalService,
    private location: PlatformLocation
  ) {
    // closes modal when back button is clicked
    location.onPopState(() => this.modalService.hide());
  }
```
