### ISSUE TITLE
daterangepicker default month for second calendar is not always correct 

### ISSUE THREAD

**Issue by bartes** [valor-software/ng2-bootstrap#4560]
when setting min/max date range in the past by default we get unavailable month visible

stackblitz.com/edit/ngx-bootstrap-vyztmj

Current Behaviour :
By default current and next month are displayed

Expected: 
By default current and previous (accessible) month should be displayed

so calendar for second datepicker should pick either next or previous month based on min/max values (it super fine to have 'next month' as a default like now but not in a case where previous is accessible and next isn't)

**Comment by daniloff200** [comment]
we right now have https://github.com/valor-software/ngx-bootstrap/issues/5386 this functionality, which available in 5.4.0.

Does it resolve this issue?
