### ISSUE TITLE
ModalOptions#initialState - better type definition

### ISSUE THREAD

**Issue by adros** [valor-software/ng2-bootstrap#4561]
As I have found in one of the issues, `initialState` property of ModalOptions should be used to pass arguments to modal constructor.
But as long as the initialState has type Object, those properties cannot be read easily (e.g. I have to do type assertion `(options.initialState as any).myProp`).
I would suggest to change `Object` to indexable type like: `{ [key: string]: any }`  

(https://www.typescriptlang.org/docs/handbook/interfaces.html#indexable-types)

**Comment by leo6104** [comment]
https://github.com/valor-software/ngx-bootstrap/pull/5019
