### ISSUE TITLE
Modal with custom width!

### ISSUE THREAD

**Issue by t-zander** [valor-software/ng2-bootstrap#4562]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Bug description or feature request:
feature request
### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:
Okay, let's assume I use modal.
Sure I can specify width by 
this.modalService.show(template, {class: 'modal-lg'});
But what if I need modal which is wider than 'lg' How do I overwrite this??
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:
latest
Bootstrap:
latest

**Comment by tarusin** [comment]
@t-zander You can use only CSS styles to change the width of the container. Change **max-width** property for **.modal-dialog** class, in some cases for **.modal-sm class**.

**Comment by Kluskey** [comment]
I don't believe the above comment works because of Angular's view encapsulation. The `.modal-dialog` class is too nested for it to be directly modifiable in the component's CSS file.

**Comment by gnchiesa** [comment]
Is there some kind of workaround for this? Thx

**Comment by bech-t** [comment]
i use custom CSS / SCSS and it work for me :

@media (min-width: 992px) {.modal-lg {max-width: 980px;}}
@media (min-width: 1200px) {.modal-lg {max-width: 1150px;}}

**Comment by aardva13** [comment]
This works for me but it has to be in styles.css:

.modal-lg {
    max-width: 600px !important;
}
