### ISSUE TITLE
Weird things happen with pagination component when we set maxSize to a constant

### ISSUE THREAD

**Issue by nvmkpk** [valor-software/ng2-bootstrap#4564]
### Bug description or feature request:
Upon debugging, I found out that when maxSize is set to "1" in html, the property gets a string value and `startPage + this.maxSize - 1` results in `10` rather than `1` (in line 172 of pagination.component.js). This probably also applies for other inputs.

### Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/ngx-bootstrap-qhornh

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap:
Angular:
Bootstrap:

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLI

**Comment by 7185** [comment]
It makes sense because you're explicitly asking to use a string value, so you get
`1 + "1" - 1 = 11 - 1 = 10` and `2 + "1" - 1 = 21 - 1 = 20`.
To use the right type (number), you have to use `[maxSize]="1"` for your input instead of `maxSize="1"`.

**Comment by nvmkpk** [comment]
Why not convert the string to number in code? It will be little more easier to use.
