### ISSUE TITLE
DST date gets doubled on IOS

### ISSUE THREAD

**Issue by cauescuderi** [valor-software/ng2-bootstrap#4572]
### Bug description or feature request:

Steps to reproduce:
1- get an IOS device (ipad or iphone);
2- Change its timezone setting to (Sao Paulo/GMT-3 hours);
3- Navigate to the examples page of ngx-bootstrap/datepicker; ( https://valor-software.com/ngx-bootstrap/#/datepicker)
4- Open a calendar and navigate to november 3rd;
5- november 3rd appears twice on the calendar, pushing all subsequent dates a weekday forward.

**Comment by cauescuderi** [comment]
Addition to the error: it only happens when navigating with the arrows. If month is selected by its button, it doesn't occur.

**Comment by dmitry-zhemchugov** [comment]
Hi @cauescuderi ! This issue has reproduced only in 2018, and I reproduced it when I select month by the button. But in subsequent years it doesn't reproduce. In the 2029 year days of the week are the same located as in 2018 but this issue doesn't reproduce too. So I think we able to close this issue.
