### ISSUE TITLE
Dropdown menu position at the viewport edge

### ISSUE THREAD

**Issue by Disane87** [valor-software/ng2-bootstrap#4575]
### Bug description or feature request:
We have a dropdown which is pretty near the right viewport border. We want to open the dropdown to the left side, to prevent an overflow over the right edge of the viewport. At the moment is looks like this:

![image](https://user-images.githubusercontent.com/956158/44781206-06a04680-ab84-11e8-92a3-b2a2bb4018cd.png)
 

With the given options there is no possibility to achieve this. The menu should open into the left direction or auto (wenn the space to the right doesn't fit to show the entire menu):
![image](https://user-images.githubusercontent.com/956158/44782036-3c462f00-ab86-11e8-9946-5d815ff1b80a.png)

### Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/dropdown-menu-placement

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.5

Angular: 5.2.11

Bootstrap: 4.1.2

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular-CLI

**Comment by Disane87** [comment]
Any updates about this?

**Comment by YuriiKrvc** [comment]
@Disane87  I share your concern and I would like to ask you to try to use this type of drop down. 
Looks like it might solve your problem
https://valor-software.com/ngx-bootstrap/#/dropdowns#menu-alignment
