### ISSUE TITLE
display the disabled dates and disable the date range picker if contains the disabled dates in between start and end range ??????????????

### ISSUE THREAD

**Issue by hemanth-sp** [valor-software/ng2-bootstrap#4585]
**display the disabled dates** and **disable the date range picker if contains the disabled dates in between start and end range** .. is this feature available or do we need to override your component?

**Comment by Domainv** [comment]
There's no need to open an issue here if you want to ask a general question.
Use <a href="https://stackoverflow.com/questions/tagged/ngx-bootstrap">StackOverflow</a> or <a href="https://ngx-slack.herokuapp.com/">Slack</a> instead

**Comment by chinthu** [comment]
> **display the disabled dates** and **disable the date range picker if contains the disabled dates in between start and end range** .. is this feature available or do we need to override your component?

Did you got solution for this ?

**Comment by hemanth-sp** [comment]
no. i used airbnb calender

**Comment by chinthu** [comment]
> no. i used airbnb calender

But is there angular version available for that ?

**Comment by hemanth-sp** [comment]
its just warpper of react calender but good

**Comment by chinthu** [comment]
@hemanth-sp Anyway to find it online ?
