### ISSUE TITLE
Issue when detecting Bootstrap version

### ISSUE THREAD

**Issue by FrancescoBorzi** [valor-software/ng2-bootstrap#4591]
### Bug description or feature request:
In my project we currently use **Bootstrap 3**.
After upgrading my Angular version from `6.1.3` to `6.1.6` there is something wrong with the detection of the bootstrap version:

![image](https://user-images.githubusercontent.com/75517/45083860-1fb57400-b0fd-11e8-87c8-e3218bb67e27.png)

The issue is in `_guessBsVersion()` function when it checks `rect.top === 0 ? 'bs4' : 'bs3'`.

Sometimes `rect.top` is `0` so it thinks it's boostrap 4 (even if it's bootstrap 3):

![image](https://user-images.githubusercontent.com/75517/45084527-d8c87e00-b0fe-11e8-8d16-5c0f0700d003.png)

Sometimes `rect.top` is `1` so it returns `bs3`:

![image](https://user-images.githubusercontent.com/75517/45084700-3ceb4200-b0ff-11e8-8783-50b2d617bb27.png)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.1

Angular: **6.1.6** (it does NOT affect 6.1.3)

Bootstrap: 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed:

Angular CLI: 6.1.4
Node: 10.9.0
OS: linux x64
Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

```
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.4
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.7.4
@angular-devkit/schematics        0.7.4
@angular/cli                      6.1.4
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.4
@schematics/update                0.7.4
rxjs                              6.3.1
typescript                        2.9.2
webpack                           4.8.3

```

**Comment by YuriiKrvc** [comment]
@ShinDarth 
I can't reproduce it
Please provide a reproduction of this issue.
You can use one of the starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts
