### ISSUE TITLE
Choosing page after the content has changed.

### ISSUE THREAD

**Issue by calldeludo** [valor-software/ng2-bootstrap#4596]
Hello, i am using the ngx-bootstrap pagination and i have a question... there is any method to change the current page? i am using this paginate for view the content that i have in my Array, but i have a searcher that modify the Array... so if you are in the page 2, and then you search something, the content changes... and the page still on 2... and i would like that after search anything, it starts again in the page 1. 
Can i set the page by code? or something?

**Comment by nvmkpk** [comment]
I am running into same issue. I tried following [this example](https://valor-software.com/ngx-bootstrap/#/pagination#manual-switching) but it is not working for me.

**Comment by Joklogh** [comment]
Hi @calldeludo @nvmkpk 
I have no issues setting page manually in code using example in https://valor-software.com/ngx-bootstrap/?gclid=Cj0KCQjwlqLdBRCKARIsAPxTGaX54C_p2kRXeyLzIuJRiS5PYxgVZ6-5FzKZGaeGu5wUTgo_6IztaeAaAqQKEALw_wcB#/pagination#manual-switching

See example in Stackblitz : https://stackblitz.com/edit/ngx-bootstrap-ot9dqb

Let me know if you were successful in getting manual page switching work

**Comment by calldeludo** [comment]
great i could adapt it perfectly ! thank you, everything working 👍

**Comment by raviraj16** [comment]
I had also faced the same issue, the issue was that I was not able to reset to the first page if **totalItemsCount** changed. For a quick fix, I have written the following code.

`setTimeout(() => {
      this.currentPage = 1;
    }, 0);`
