### ISSUE TITLE
Don't close daterangepicker after dates are selected

### ISSUE THREAD

**Issue by gaetanparis** [valor-software/ng2-bootstrap#4603]
Hi guys,

currently when i chosse two dates on my dateRangePicker, it closes immediately after i chose the second one.

Is there any way to let it open even when i selected two dates ?

Thank you !

**Comment by Joklogh** [comment]
Hi @gaetanparis 
You can pass boolean value to the `isOpen` input of datepicker. Like `[isOpen] = "true"`.
This should enable behaviour you are looking for
Let me know if this resolves your issue.

**Comment by Sebi11** [comment]
Hi @Joklogh 
This will not work, I have already tried myself. 

The code in charge of closing automatically the datepicker after selecting a date is in the "ngx-bootstrap\datepicker\bs-datepicker.component.ts" file I guess, inside the `show` function : 
```javascript
// if date changes from picker (view -> model)
this._subs.push(
  this._datepickerRef.instance.valueChange.subscribe((value: Date) => {
    this.bsValue = value;
    this.hide(); // <-- this line !!!
  })
);
```

Indeed, the `hide` method does close the datepicker if `isOpen === true`. The purpose of this parameter is only to set the initial state of the datepicker I guess. 

Moreover, I guess this feature request is the same as [#4203](https://github.com/valor-software/ngx-bootstrap/issues/4203)

**Comment by valorkin** [comment]
There are planned feature: 2-3 buttons
Apply, Reset, Cancel
Which will lead to your desired behaviour
