### ISSUE TITLE
Timepicker placeholder are not full lenght

### ISSUE THREAD

**Issue by JeepLavoie** [valor-software/ng2-bootstrap#4610]
### Bug description or feature request:
Hi, 

The placeholder of the timepicker are a little bit crop on the end of the "M" and "H"

I found this problem with my web app and when I go  on [Timepicker](https://valor-software.com/ngx-bootstrap/#/timepicker) we can see the crop on the last "M" of the minutes section.

A screenshot of my web app 
![image](https://user-images.githubusercontent.com/3975143/45524206-331aac00-b79b-11e8-8324-53d21a80f165.png)

A screenshot of the ngx-bootstrap website
![image](https://user-images.githubusercontent.com/3975143/45524126-d4edc900-b79a-11e8-8138-1b11ae2c2cf5.png)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.1

Angular:  6.1.2

Bootstrap: 4.1.3

**Comment by Joklogh** [comment]
Hi @xaraskas 
Try to solve this problem with CSS. You can change `width` property of `bs-timepicker-field` class in your styles. Try `width : 55px`, this helps to solve issue with timepicker input.
Let me know if this resolves your issues
