### ISSUE TITLE
Ngx Timepicker

### ISSUE THREAD

**Issue by IustinSaraholu** [valor-software/ng2-bootstrap#4621]
Is there any method to let ngx timepicker to use only numbers in input (hours and minutes inputs) ?

![timepicker](https://user-images.githubusercontent.com/34652813/45693672-472d2780-bb66-11e8-8ef7-421d8564fe76.png)

**Comment by Joklogh** [comment]
Hi @IustinSaraholu 
Can you better describe your problem?
I don't quite get the issue

**Comment by valorkin** [comment]
There are 2 ways:
input type number - no go cuz browsers will display  scrolls
Or add validation on keypress and set previous value if not number - it could be added
 Cc @Domainv
It's a simple thing
