### ISSUE TITLE
Open modal from component WITHOUT having to create a component class

### ISSUE THREAD

**Issue by heitorb** [valor-software/ng2-bootstrap#4623]
I have a modal created in the HTML and I want to trigger that modal to be opened from the component, not by clicking anything on the page.

In the docs, you only mention one way of doing this, which is by creating a new class inside the component class.

How can I, inside the ts file, get a reference from a template in the HTML and pass that to the "show" method?

Again, this modal is supposed to open without the user doing anything. It is a session timeout warning modal, that comes when there is 60 seconds left in the session. So when it is time to open, I need to get a reference to the ng-template in the HTML.

**Comment by Joklogh** [comment]
Hi @heitorb 
You can pass template reference to the the method of BsModal Service `show` .
See example on this url : https://stackblitz.com/edit/ngx-bootstrap-xbahme
The modal is open automatically after 5 seconds.
Let me know if this solves your issue or have any other questions.

**Comment by heitorb** [comment]
Yes. It did. Thank you!
