### ISSUE TITLE
How to show modal auto open when page load ?

### ISSUE THREAD

**Issue by surya5353** [valor-software/ng2-bootstrap#4633]
How to call modal ngOninit when after initialised component. without html button click event ? I want to show modal on page load.

**Comment by surya5353** [comment]
Thank You.
I got the code in documentation .
https://valor-software.com/ngx-bootstrap/#/modals#directive-auto-shown
I added [config]="{ show: true }" in modal div

**Comment by jfonseca10** [comment]
trank you, very good
