### ISSUE TITLE
How to custom Language in BSDatepicker

### ISSUE THREAD

**Issue by vietdq1291** [valor-software/ng2-bootstrap#4635]
Angular: 6.0

Bootstrap: 3.0.1

As i know : 
ngx-bootstrap/chronos  & BsLocaleService (ngx-bootstrap/datepicker) doesn't support vietnamese language 
How to I Custom this language and using in BSdatepicker

**Comment by valorkin** [comment]
Please closed issue,  I have answered couple of times. Look at add new locale prs for a sample
