### ISSUE TITLE
Bs-sortable not refresh after renamed item.

### ISSUE THREAD

**Issue by sz09** [valor-software/ng2-bootstrap#4654]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

### Build system: Angular CLI, System.js, webpack, starter seed:

I want to rename an item. But it isn't show data as expected.

Here is html
`
                                                <div class="row">
                                                    <bs-sortable [(ngModel)]="selectedProperties"
                                                                 name="selectedProperties"
                                                                 [itemTemplate]="itemTemplate"
                                                                 fieldName="name"
                                                                 itemClass="sortable-item"
                                                                 itemActiveClass="sortable-item-active"
                                                                 placeholderItem="{{ 'objectTypes.PlaceholderItem' | translate }}"
                                                                 placeholderClass="sortable-item"
                                                                 [ngModelOptions]="{standalone: true}"
                                                                 (onChange)="selectedPropertiesChange($event)"
                                                                 wrapperClass="sortable-wrapper"></bs-sortable>
                                                        <ng-template #itemTemplate let-item="item" let-index="index">
                                                            <div *ngIf="item.initData.isLabel">
                                                                <div *ngIf="!editing[index]" class="row">
                                                                    <div class="col-md-2"></div>
                                                                    <div class="col-md-10" (dblclick)="editing[index] = true; isEditing = true">
                                                                        <span class="pull-left">
                                                                            <strong> {{ item.value }} </strong>
                                                                        </span>
                                                                    </div>
                                                                </div>
                                                                <div *ngIf="editing[index]">
                                                                    <input type="text" class="inline-editor" autofocus (keydown)="onKeyPress($event, index)" (blur)="updateLabelName($event, index)" [value]="item.value" />
                                                                </div>
                                                            </div>
                                                            <div *ngIf="!item.initData.isLabel">
                                                                <span> {{ item.value }} </span>
                                                                <span class="pull-right">
                                                                    <button type="button" (click)="setDefaultValue(item)" class="btn btn-default-property"
                                                                            [ngClass]="{ 'btn-success': item.initData.defaultValue, 'btn-default' : !item.initData.defaultValue }">
                                                                        <i *ngIf="!item.initData.defaultValue" class="fa fa-cog" aria-hidden="true"></i>
                                                                        <i *ngIf="item.initData.defaultValue" class="fa fa-check" aria-hidden="true"></i>
                                                                    </button>
                                                                </span>
                                                            </div>
                                                        </ng-template>
                                                </div>`
And here is typescript code: 
`onKeyPress(event, rowIndex) {
        if (event.key == "Enter") {
            this.updateLabelName(event, rowIndex);
        }
    }

  updateLabelName(event, rowIndex) {
        this.selectedProperties[rowIndex].name = event.target.value;
        this.editing[rowIndex] = false;
        this.isEditing = false;
        this.selectedProperties = [...this.selectedProperties];
    }`

It try to using 
`setTimeout(() => { this.selectedProperties = [...this.selectedProperties]; }, 50);` 
and it will show expected result. But I think it is a bad solution.

**Comment by YuriiKrvc** [comment]
Please provide a reproduction of this issue.
You can use one of the starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by Yuriy777** [comment]
Please provide a reproduction of this issue.
You can use one of the starter templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by ghost** [comment]
There has been no response. That's why the issue was closed
