### ISSUE TITLE
how to change week days from 3 letter to 2 letters? ("Su Mo Tu" etc...)

### ISSUE THREAD

**Issue by Yulin777** [valor-software/ng2-bootstrap#4668]
![capture](https://user-images.githubusercontent.com/14194649/46461055-32c76c80-c7ad-11e8-8cba-8011fc3fcdd1.PNG)

**Comment by Domainv** [comment]
Unfortunately, this functionality is currently not implemented.
We will consider your wishes in the future.

**Comment by Yulin777** [comment]
Made it myself. I'll send pr if you want

**Comment by Domainv** [comment]
@Yulin777 It's will be great

**Comment by Domainv** [comment]
@Yulin777 temporary solution for it
```
import { Component, OnInit } from '@angular/core';
import { setTheme } from 'ngx-bootstrap/utils';
import { BsLocaleService } from 'ngx-bootstrap/datepicker';
import { defineLocale } from 'ngx-bootstrap/chronos';
import { enGbLocale } from 'ngx-bootstrap/locale';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'app';

  constructor(private localeService: BsLocaleService) {
    setTheme('bs4');
    enGbLocale.weekdaysShort = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
    enGbLocale.week.dow = 0;
    defineLocale('en', enGbLocale);
  }

  ngOnInit() {
    this.localeService.use('en');
  }

}
```

**Comment by codestitch** [comment]
I tried using your solution @Domainv. The week heading works perfectly, but everything else was messed up.

![Capture](https://user-images.githubusercontent.com/5573444/55154089-e5203100-514b-11e9-8a8d-51df71bada49.PNG)

Version: "^4.0.0"

**Comment by Domainv** [comment]
@codestitch Try please 
npm i ngx-bootstrap@next

**Comment by codestitch** [comment]
I did but still won't work.. I tested it in stackblitz..
https://stackblitz.com/edit/angular-kxsuae

**Comment by rphelan** [comment]
I ran into the same issue as @codestitch and was able to fix it by using 'en-gb' for the locale name rather than just 'en':

```
constructor(
  private localeService: BsLocaleService
) {
  enGbLocale.weekdaysShort = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
  enGbLocale.week.dow = 0;
  defineLocale('en-gb', enGbLocale);
  this.localeService.use('en-gb');
}
```

**Comment by rdeshpande29** [comment]
> en-gb

Thank you so much for taking time to put your workaround.I have been breaking my head since 2 days :) It worked for me!
