### ISSUE TITLE
ngx bootstrap datepicker range split into two input

### ISSUE THREAD

**Issue by samuelkavin** [valor-software/ng2-bootstrap#4671]
When we select start date and end date. Is it possible to put it in two different input. Something like this: 
<img width="410" alt="screen shot 2018-10-05 at 11 03 31 am" src="https://user-images.githubusercontent.com/5300968/46514101-6c23d900-c88e-11e8-913d-89543ecc6618.png">

Any idea?

**Comment by YuriiKrvc** [comment]
@samuelkavin There's no need to open an issue here if you want to ask a general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead.
