### ISSUE TITLE
Tab through Accordion

### ISSUE THREAD

**Issue by daniel-seitz** [valor-software/ng2-bootstrap#4673]
When having accordion-groups with content, form inputs in my case, the user wants to go to the next input when pressing the tab key.

That works within one group if that content is visible, however once the last input of that group is reached, the next group is not opened automatically *that is the wanted feature*.

I see that this is not trivial because there could be tabindex set, or i.e. the last element could be a textarea... so one attempt to solve this is to specify a tabindex manually on the accordion-group (in thIe order which I want, ...here it would be '0'). Then I can also add an focus / keyup listener to the tag.

However I dont see a way to manually trigger open for the next group. Here it throws an error "ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'."

This would make sense to add as a standard as I can see that all devs would find this feature very useful.

**Comment by tarusin** [comment]
@daniel-seitz 
We adhere to the behavior of the <a href="https://getbootstrap.com/docs/4.1/components/collapse/">Bootstrap</a> functionality. That's why we cannot implement your request.
