### ISSUE TITLE
Typeahead - how to fire an event when the input is cleared ?

### ISSUE THREAD

**Issue by sgentile** [valor-software/ng2-bootstrap#4675]
I'm not getting any event when the input is cleared - any advice on how to handle this event ?

ie they do a search, they select an item, then they clear the item.

**Comment by YuriiKrvc** [comment]
@sgentile There's no need to open an issue here if you want to ask a general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead.
