### ISSUE TITLE
Circular dependencies detected in "chronos" folder

### ISSUE THREAD

**Issue by Sebi11** [valor-software/ng2-bootstrap#4682]
### Bug description:
There are a lot of circular dependencies between the files of the "src/chronos" folder. This is considered as a very bad practice since it can lead to bugs and bad performance.
The warnings are only shown during development, they are not visible for someone importing the ngx-bootstrap library.

### To reproduce the issue:
- Checkout this repo.
- Run `npm install` at the root of the project folder.
- Run `npm run build.watch` in a first terminal.
- Run `npm start` in a second terminal.
- Go to "http://localhost:4200/#/"

You can see all the warnings inside the developer console of your browser or in the second terminal.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.5

### Solving the issue

It is quite hard to analyse with an external eye to the code and without any explanation of how the configuration is initialized, since the circular dependencies are quiet large... 
There is a _TODO_ in the "ngx-bootstrap\src\chronos\create\from-string-and-format.ts" file, at the beginning of the `configFromStringAndFormat` function. It will not solve all the circular dependencies, but it can be a starting point.

**Comment by valorkin** [comment]
As license file should state, chronos is 1to1 migration of moment.js to typescript. 
Initial plan was to migrate and split into pure es6 functions + publish independently or propose it as a PR
