### ISSUE TITLE
Datepicker popup is fixed by scrolling in modal popup

### ISSUE THREAD

**Issue by gregor-doroschenko** [valor-software/ng2-bootstrap#4683]
### Bug description or feature request:

I use bootstrap modals in my app. In an modal I have form with datepicker input. When I open datepicker popup in my modal, that will be fixed by scrolling in modal-body (see stackblitz example).

In the linked github below repo you will find video of reproducing.

![bug-gif](https://user-images.githubusercontent.com/2324240/46813640-61c67b00-cd77-11e8-9d7e-03e973590e01.gif)

### Plunker/StackBlitz that reproduces the issue:

GitHub Demo-Repo: https://github.com/gregor-doroschenko/ngx-bootstrap-datepicker-bug

StackBlitz: https://stackblitz.com/github/gregor-doroschenko/ngx-bootstrap-datepicker-bug?file=src%2Fapp%2Fapp.component.html

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.5

Angular: 5.2.9

Bootstrap: 4.1.3

### Build system: Angular CLI, System.js, webpack, starter seed:

package.json
```
{
  "name": "ngx-bootstrap-datepicker-bug",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.9",
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/forms": "^5.2.9",
    "@angular/http": "^5.2.9",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "@angular/router": "^5.2.9",
    "bootstrap": "^4.1.3",
    "core-js": "^2.4.1",
    "ngx-bootstrap": "^2.0.5",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.4",
    "@angular/compiler-cli": "^5.2.9",
    "@angular/language-service": "^5.2.9",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
```

**Comment by izikf89** [comment]
i not sure why but this script fix the problem.. 
`document.querySelector('modal-container').addEventListener('scroll', function() {});`

**Comment by raideltorres** [comment]
I'm also having this issue and not in a modal so the code shared by @izikf89 is not working for me and that is only removing any scroll event code that can be coming from the library, so this is an issue in the library.

**Comment by nirajkuverma** [comment]
> i not sure why but this script fix the problem..
> `document.querySelector('modal-container').addEventListener('scroll', function() {});`

Where to  write this code in ts file??

**Comment by izikf89** [comment]
in ngOnInit(){} function in modal component, something like this:

```
ngOnInit() { 
    this.getData();

    this.minDate.setDate(this.minDate.getDate() - 1);

    // this fix bug ui of datapicker when scrool page or change size of window and datapicker is load, dont touch
    document.querySelector('modal-container').addEventListener('scroll', function() {});
    window.addEventListener("resize", ()=>{});
  }
```

**Comment by nirajkuverma** [comment]
Sorry, In my case it is not working.

I am using datarangepicker in a model.

Model is -  import { NgbModule } from '@ng-bootstrap/ng-bootstrap';

Datarangepicker is - import { BsDatepickerModule } from 'ngx-bootstrap/datepicker';
