### ISSUE TITLE
Typeahead: Possibility to open link in a new tab with ctrl+click

### ISSUE THREAD

**Issue by cakeinpanic** [valor-software/ng2-bootstrap#4685]
Using typeahead I want to have possibility to open links in a new tab.
By now it it not possible at all, cause all clicks are set to preventDefault and ctrl+click or mousewheel can not be differed – the only case is to use `<a>` tag and a context menu

**Comment by svetoldo4444ka** [comment]
Sorry, but a possibility to open link in a new tab is contrary to standard typeahead's behavior

**Comment by valorkin** [comment]
interesting, thanks

**Comment by IraErshova** [comment]
@cakeinpanic Hi! I am not sure that we are going to add this functionality to typeahead component. But you can use `typeaheadOnSelect` event to add functionality for opening any URL in a new tab. Could you please check my example in Stackblitz?
https://stackblitz.com/edit/angular-8ioart
