### ISSUE TITLE
On custom input event, Typeahead dropdown doesnt show up in IE11. Works in Chrome.

### ISSUE THREAD

**Issue by ajbx** [valor-software/ng2-bootstrap#4698]
**Requirement**
Text box and button are combined to be styled to make it look like drop down. On click drop down handle, need to show type ahead drop down options. 

**Implementation**
On button click event, native element is assigned a random character ( ~) and custom input event is raised. This custom character is removed before observer.next. 

This makes type ahead performs search for empty input and shows all the drop down options. 

To simulate server api call, have used observable with delay. This works in chrome ( latest ) , Firefox ( latest ) but not in IE 11. If i remove .delay(1000), seems to be working in IE 11 too.

Looks like on custom event, type ahead doesn't detect and display async result.

**Versions** 
angular 5.4.2
ngx-bootstrap - 2.0.5

**Stackblitz**
https://stackblitz.com/edit/angular-hwx6qb

Any help on this issue is highly appreciated.

**Comment by valorkin** [comment]
thanks
