### ISSUE TITLE
Modal dialog only closes on backdrop click (on Internet Explorer)

### ISSUE THREAD

**Issue by phrkdll** [valor-software/ng2-bootstrap#4713]
### Bug description or feature request:
I'm having issues with modal dialogs in Internet Explorer 11.

I'm using version 3.0.1 of ngx-bootstrap in an Angular 6 (6.1.9) application created via Angular CLI.
The modal dialog is in its own component and is opened via BsModalService using something like this:

'this.modalService.show(ComponentName, { 'class': 'modal-xl', initialState });'

I have the bsModalRef inside the dialog component. The .hide() method is called in the click events of the buttons.

So, the dialog should close if I click on the X, the backdrop or the close- / save-button in the footer.
This works perfectly fine on any Firefox version, but on Internet Explorer 11 the dialog only closes when I click the backdrop.

### Versions
ngx-bootstrap: 3.0.1
Angular: 6.1.9
Bootstrap: 3.3.7

### Build system:
Angular CLI

**Comment by sonicpro** [comment]
This issue is not reproduced with the latest version of ngx-bootstrap.

#### The test configuration is like the following:

ngx-bootstrap: 5.5.0
Angular: 8.2.0
Bootstrap: 3.3.7
