### ISSUE TITLE
[NPM] v3.1.0 is not available in npm

### ISSUE THREAD

**Issue by sibiraj-s** [valor-software/ng2-bootstrap#4722]
<img width="773" alt="screenshot 2018-10-21 at 3 39 51 pm" src="https://user-images.githubusercontent.com/20282546/47265569-912f7180-d547-11e8-9993-f2071779bb0c.png">

Version 3.1.0 isn't available in npm. https://www.npmjs.com/package/ngx-bootstrap

**Comment by sibiraj-s** [comment]
@valorkin

**Comment by valorkin** [comment]
Yeah, I know. When our CI was building ng 7 was released and @latest build failed ;)
So I will publish it or manually or v3.1.1 from CI

**Comment by cbysterv** [comment]
@valorkin Is there an ETA on when you expect to have v3.1.1 published?

**Comment by valorkin** [comment]
QAs is doing smoke testing of dev branch, today/max tomorrow I should have a green light for publish

**Comment by valorkin** [comment]
3.1.1 is published with @next tag
we will test it with real projects on Monday, that publish went well
cuz npm sometimes has bad publishes
and on Monday it will become the @latest label
