### ISSUE TITLE
The demo links are broken.

### ISSUE THREAD

**Issue by ghost** [valor-software/ng2-bootstrap#4726]
The demo links on the github page are broken.

**Comment by valorkin** [comment]
which ones? there are dozen of links
and all this links are working fine https://github.com/valor-software/ngx-bootstrap#usage--demo

**Comment by ghost** [comment]
All the links to documentation and demos, including the one you put in your comment go here:
https://ngx-bootstrap-latest.surge.sh/#/
or here:
https://valor-software.com/ngx-bootstrap/#/
... a page that promises the existence of demos and documentation.
Could you please identify links to actual documentation and demos?
Thank you.

**Comment by valorkin** [comment]
Mm. Links you added are working for me.
Which browser are you using?
