### ISSUE TITLE
(typeaheadOnSelect) prevent default behavior

### ISSUE THREAD

**Issue by t-zander** [valor-software/ng2-bootstrap#4729]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://ngx-slack.herokuapp.com/) instead

### Bug description or feature request:
I need to parse the object, in fact I put tag for selected result, like this:
http://prntscr.com/l9heg2
It works fine, but when (typeaheadOnSelect) is fired, I see [object Object] in my input for a second.
I understand that this is the default behaviour but is there any solutions to this?

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:
last version
Angular:
6
Bootstrap:

**Comment by ghost** [comment]
@t-zander please provide a reproduction of this issue.
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts

**Comment by Domainv** [comment]
Closes as outdated
