### ISSUE TITLE
Modal not working in angular universal

### ISSUE THREAD

**Issue by harishkrishnan24** [valor-software/ng2-bootstrap#4730]
### Bug description:
When I try to build angular universal build I am getting error 
![screen shot 2018-10-24 at 3 03 00 pm](https://user-images.githubusercontent.com/27828200/47421332-fa102700-d79d-11e8-87ab-522441bddc21.png)

The issue is with modals.

### Versions of Angular, ng-bootstrap and Bootstrap:
Angular: 6.1.3

ng-bootstrap: 3.0.1

Bootstrap: 4.1.3

**Comment by Domainv** [comment]
In the near future, there will be a release with this solved the error.

**Comment by harishkrishnan24** [comment]
Can you provide a rough time estimate on when it would be ?

**Comment by harishkrishnan24** [comment]
@Domainv Also, until then is there any workaround. I also face similar issues with accordion, tooltip, dropdown

**Comment by smartman** [comment]
> In the near future, there will be a release with this solved the error.

Same issue here. 

@Domainv Is this fix in ngx-bootstrap and if not then in what project?
Any task trackers to follow for keeping up to date with issue resolution the status?

**Comment by ceciliazcx** [comment]
@Domainv @harishkrishnan24  Anyone know whether the issue is solved?
