### ISSUE TITLE
[Daterangepicker] calendar month moved when start date click

### ISSUE THREAD

**Issue by inhyeok** [valor-software/ng2-bootstrap#4757]
### Bug description or feature request:
I have a question regarding this source. Currently, when there are October and November and when the user click on November calender, October disappears. November calendar shift to where October was and December appears on where November was. Are there anyway that I can use this source without making new month coming out when user select the second month from the option? Thank you!

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.2

Angular: 5.2.0

Bootstrap: 4.0.0

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLI

**Comment by Domainv** [comment]
close as outdated

**Comment by EricSong8612** [comment]
Having the same need. Is there any workaround?

**Comment by inhyeok** [comment]
@EricSong8612 I resolved using datepicker options that minDate and triggers.

**Comment by tatighm** [comment]
I'm still trying to find a way to make the calendar not move from right to left whenever I choose a starting date on the right-side calendar. I can't have a minDate since we want to give the ability to users to pick from earlier dates, even months earlier. I know this issue is closed, but I still need to find a way around this. Any help would be appreciated :-)

**Comment by daniloff200** [comment]
set minDate  as 01-01-1970, for example.
Very strange workaround I should say, but, can be useful for your case @tatighm

**Comment by tatighm** [comment]
Thank you for your reply @daniloff200 but unfortunately, this did not work for me. Right now the two months that show when it opens is Feb and March. If I go back one month to show Jan and Feb and then choose the starting date from Feb, it will shift to now show Feb and March.
