### ISSUE TITLE
Can't resolve 'ngx-bootstrap/tabs/tab.directive'

### ISSUE THREAD

**Issue by clabough** [valor-software/ng2-bootstrap#4760]
### Bug description or feature request:

ng build throws this error
`"Error: Can't resolve 'ngx-bootstrap/tabs/tab.directive'"`

3.0.1 didn't have this issue, but 3.1.1 does

I've tried both of these

`import { TabDirective } from "ngx-bootstrap/tabs/public_api";`
`import { TabDirective } from "ngx-bootstrap/tabs/tab.directive";`

### Plunker/StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-exefje

If you comment out the `import { TabDirective } from "ngx-bootstrap/tabs/tab.directive";` line, it will build successfully.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.1.1

Angular: 7.0.1

Bootstrap: 4.1.1

### Build system: Angular CLI, System.js, webpack, starter seed: 

Angular CLI

**Comment by Domainv** [comment]
@clabough
`import { TabDirective } from "ngx-bootstrap/tabs`
