### ISSUE TITLE
 locales.js:84 Khronos locale error: please load locale "zhcn" before using it

### ISSUE THREAD

**Issue by YuZaiShui** [valor-software/ng2-bootstrap#4761]
why locales.js throw the fault when i use ngx-bootstrap@2.0.0.
In my project, i import znCnlocale && defineLocale().

**Comment by Domainv** [comment]
@YuZaiShui 
There's no need to open an issue here if you want to ask a general question.
Use <a href="https://stackoverflow.com/questions/tagged/ngx-bootstrap">StackOverflow</a> or <a href="https://ngx-slack.herokuapp.com/">Slack</a> instead

Also, recommend using last version 3.1.1
