### ISSUE TITLE
Datepicker cursor is showing on disabled dates

### ISSUE THREAD

**Issue by Nysosis** [valor-software/ng2-bootstrap#4781]
https://github.com/valor-software/ngx-bootstrap/blob/1d2ff35375716dfbbd2bce9bc6dd45376c2ff46b/src/datepicker/bs-datepicker.scss#L157

Within the component, the `.disabled` class gets applied to the `span`, but not the `td`, which means this rule is applying, when I wouldn't expect it to be for a disabled date.

**Comment by Domainv** [comment]
Fixed in #4905

**Comment by Nysosis** [comment]
Thanks! 
(Also, I think you meant #4905, that's the PR :) )
