### ISSUE TITLE
v3.1.1 removes component-loader from dist folder

### ISSUE THREAD

**Issue by StarpTech** [valor-software/ng2-bootstrap#4784]
As titled try `npm i ngx-bootstrap@3.1.1` there is no `component-loader` but in version `3.0.1` its still there.

**Comment by Domainv** [comment]
@StarpTech 
it still there. (3.1.1)
import { ComponentLoader } from 'ngx-bootstrap/loader';
or
import { ComponentLoader } from 'ngx-bootstrap';

Or give me please reproduction of your problem
https://stackblitz.com/edit/ngx-bootstrap-hs952f?file=app/app.component.ts

**Comment by StarpTech** [comment]
Try
```
npm i ngx-bootstrap@3.1.1 --registry=https://registry.npmjs.org/
```
result
![image](https://user-images.githubusercontent.com/1764424/48211349-9bd86c00-e379-11e8-8165-394a50338f0d.png)

**Comment by Domainv** [comment]
@StarpTech Ok will be fixed soon

**Comment by StarpTech** [comment]
@domainv thank you!
