### ISSUE TITLE
feat(datepicker) Disable onBlur autocomplete

### ISSUE THREAD

**Issue by ecancino** [valor-software/ng2-bootstrap#4786]
### Help modifying a feature 

I don't want the onBlur autocomplete feature and I haven't found a way to remove the onBlur method because is inside the DatepickerInputComponent. I have tried overriding it with a provider, creating a lower level "input" directive but to no avail.  

Any help would be appreciated and maybe I can create a PR after with configuration to skip it.

Thank you.

### StackBlitz that reproduces the issue:
https://ngx-datepicker-autocomplete.stackblitz.io

Just type 99 and tab out.

### Versions
ngx-bootstrap: 3.0.1
Angular: 6.1.10
Bootstrap: bootstrap

### Build system: 
Angular CLI

**Comment by ecancino** [comment]
@valorkin Any help would be appreciated.

**Comment by daniloff200** [comment]
looks like, your stackblitz link is broken @ecancino 
Could you fix it, and together we try to find out the solution?
