### ISSUE TITLE
Order results when using typeahead from ngx-bootstrap?

### ISSUE THREAD

**Issue by i1990jain** [valor-software/ng2-bootstrap#4808]
I am using customTemplate for my typeahead which has three fields

`({{model.number}}-{{model.city}}-{{model.state}})`

using the number as the typeaheadOptionField, I see there is typeaheadGroupField available which I use on the number field .... I would like to know is there anyway in which I can order the result based on the city field?

```
<ng-template #customCapTemplate let-model="item" let-index="index">
   <h5>{{model.code}}-{{model.city}}-{{model.prov}}</h5>
</ng-template>
<input name="colCap" [typeahead]="capList" typeaheadGroupField="code" 
    typeaheadOptionField="code" [typeaheadItemTemplate]="customCapTemplate" class="form-control">
```
<img width="445" alt="screen shot 2018-11-15 at 12 43 20" src="https://user-images.githubusercontent.com/805570/48551913-27e91700-e8d7-11e8-8368-238e8996769d.png">

**Comment by KenrySanchez** [comment]
Hello @i1990jain, I have the same problem with my development. Can you tell me how did you solve the problem?

**Comment by IraErshova** [comment]
@i1990jain Hi! Do you mean you want to search by number and by the city at the same time?

**Comment by IraErshova** [comment]
I created a stackblitz example for this case. @i1990jain you can use it
https://stackblitz.com/edit/angular-gzssfc

**Comment by i1990jain** [comment]
> @i1990jain Hi! Do you mean you want to search by number and by the city at the same time?

search just by the number but then the results must be order by the name of the city

**Comment by IraErshova** [comment]
> > @i1990jain Hi! Do you mean you want to search by number and by the city at the same time?
> 
> search just by the number but then the results must be order by the name of the city

Oh, I got it! Thanks for clarification
