### ISSUE TITLE
Popover is closing on inside click when it shouldn't.

### ISSUE THREAD

**Issue by pwinstead** [valor-software/ng2-bootstrap#4810]
### Bug description or feature request:
Popover with custom template and outsideClick=true will close when user clicks inside popover if click results in *ngFor bound data within the popover being changed.

If outsideClick=false then the popover does not close.

### Plunker/StackBlitz that reproduces the issue:
Stackblitz example:
https://stackblitz.com/edit/ngx-bootstrap-8aqjmh

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.1.1

Angular: 6.1.10

Bootstrap: 4.1.3

**Comment by llysenko** [comment]
This issue is easy to solve by adding `event.stopPropagation();` in your method:
`removeLineOfData(line: string) {
     this.dataLines.splice(this.dataLines.indexOf(line), 1);
     event.stopPropagation();
 }`
