### ISSUE TITLE
Issue with Datepicker when using optimized Builds

### ISSUE THREAD

**Issue by egandro** [valor-software/ng2-bootstrap#4821]
### Bug description or feature request:

Compiling an application with "ng build --progress=false --prod"

This causes issues on the datepicker and BsDatePicker. All days / month / years are replaced with
"DD", "MM", "YYYY".

--prod enables the "buildOptimizer" flag.

I guess this will will cause some issues in the dependency injection.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.1.1

-> It worked with "ngx-bootstrap": "^3.0.1",

Angular: 6.x

Bootstrap: 4.x

### Build system: Angular CLI, System.js, webpack, starter seed:

6.x

**Comment by neilime** [comment]
Same issue for me.

**Comment by fchiumeo** [comment]
xref #4752, #4754

**Comment by egandro** [comment]
Thank you. Any release date scheduled for 3.1.2?

**Comment by jopicornell** [comment]
Same issue here. I've downgraded to 3.0.1 until this is fixed. There's something important between 3.0.1 and 3.1.1?

**Comment by Domainv** [comment]
@egandro 3.1.2 with the fix released, please try

**Comment by neilime** [comment]
It's working for me. Thanks

**Comment by egandro** [comment]
Thank you.

**Comment by sebastian-zarzycki-apzumi** [comment]
It seems like this returned in 3.2.0, even for a build that is not optimized (Bootstrap 4.2, NG CLI 7.2.2, Angular 7.2.1).

**Comment by Domainv** [comment]
@sebastian-zarzycki-es 
Does not reproduced on 3.2.0
(Angular: 7.2.1, Bootstrap 4.2, CLI 6.1.5)

**Comment by sebastian-zarzycki-apzumi** [comment]
```
Angular CLI: 7.2.2
Node: 10.6.0
OS: darwin x64
Angular: 7.2.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.2
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              7.2.2
@angular-devkit/schematics        7.2.2
@angular/cli                      7.2.2
@ngtools/webpack                  7.2.2
@schematics/angular               7.2.2
@schematics/update                0.12.2
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.28.4
```
```
  "bootstrap": "^4.2.1",
   (...)
   "ngx-bootstrap": "^3.2.0",
```
![screenshot 2019-01-22 at 15 27 28](https://user-images.githubusercontent.com/11352013/51541965-6f9d9900-1e5a-11e9-9e07-b394c6e34eac.png)

This is standard ng serve, not a prod build with optimizations turned on.

**Comment by sebastian-zarzycki-apzumi** [comment]
Any information regarding this? Datepicker is currently unusable.

**Comment by sebastian-zarzycki-apzumi** [comment]
Also tested with CLI 7.3.0. Same issue.

**Comment by Hoakie** [comment]
@sebastian-zarzycki-es check your tsconfig.json file.  under compiler options see if your "target" is set to "es6".  I found that bs datepicker did not load locales' properly for me unless it was set to "es5"

**Comment by sebastian-zarzycki-apzumi** [comment]
Yes. it's on "es5". I've tested this on a fresh angular project.

**Comment by Domainv** [comment]
@sebastian-zarzycki-es 
Sorry, I was loaded with the higher priority task.
Please create a repo with reproduction, I'll take a look

**Comment by sebastian-zarzycki-apzumi** [comment]
I've found the culprit in the meantime.

I've been using:
```
    defineLocale('en', locale);
    this.localeService.use('en');
```
What seems to yield correct results is:
```
    defineLocale('en-gb', locale);
    this.localeService.use('en-gb');
```

Your locale documentation seems to suggest that using 'en' this way is ok, too. It isn't (there's no "en" locale file in chronos).
