### ISSUE TITLE
Future plans for ngModel and Timepicker

### ISSUE THREAD

**Issue by daviddassau** [valor-software/ng2-bootstrap#4824]
As of right now, I'm only able to populate times (in edit view) with the Timepicker using [(ngModel)], but ngModel is in the process of being deprecated. I was wondering what your plans were going forward with ngModel, specifically in regards to the Timepicker.

**Comment by valorkin** [comment]
Are you referring to https://next.angular.io/api/forms/FormControlName#use-with-ngmodel

If not please drop more info, thanks in advance

One way or another we are always trying to support n-1 angular version (v6 and v7 as of now)
So if it will be deprecated we will release new major version with new way to provide model values

**Comment by daviddassau** [comment]
@valorkin Yes, that's what I was referring to. I work with Angular/NGX Bootstrap on practically a daily basis, so thanks for your amazing product, and commitment to keep it up-to-date!

**Comment by valorkin** [comment]
Thanks! Kudos to @domainv ;)
