### ISSUE TITLE
Injector.create BsModalService

### ISSUE THREAD

**Issue by Dovernh** [valor-software/ng2-bootstrap#4834]
I'm trying to use a modal in a angular class using Injector.create. I'm trying to resolve what are the dependancies. So far I have

const injector = Injector.create({
      providers: [
        {
          provide: BsModalService,
          useClass: BsModalService,
          deps: [BsModalRef]
        },
        {
          provide: BsModalRef,
          useClass: BsModalRef
        }
      ]
    });

At runtime it's complaining about the deps for BsModalRef.

**Comment by valorkin** [comment]
What kind of complain?

**Comment by ihsanberahim** [comment]
i also looking for solutions for these.
