### ISSUE TITLE
bsdaterangepicker month selector issue

### ISSUE THREAD

**Issue by abhijeetsap21** [valor-software/ng2-bootstrap#4835]
### Issue description
Selecting Future Date of Future year using the month selector does not selects the correct month.
Instead it selects month of previous year

This issue can be replicated on the examples section of `https://valor-software.com/ngx-bootstrap/#/datepicker`

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.1

Angular:6.0.7

Bootstrap: 4.1.3

**Comment by johnsmathew** [comment]
In the daterangepicker, 2 picker panels are displayed at the same time. Does this occur only when selecting the month from the second panel? If so, it is same as #4500 and it is fixed in the latest version (v3.1.3).
