### ISSUE TITLE
Error in pagination typescript description when strictNullChecks set to true

### ISSUE THREAD

**Issue by sherlock1982** [valor-software/ng2-bootstrap#4848]
### Bug description or feature request:

3.1.2 can not be compiled.

```
ERROR in node_modules/ngx-bootstrap/pagination/models/index.d.ts(2,5): error TS2411: Property 'align' of type 'boolean | undefined' is not assignable to string index type 'string | number
| boolean'.

```
align? should be boolean or index should allow boolean?

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.1.2

Angular: 7.0.4
Bootstrap: 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed:

AngularClass

**Comment by jmwierzbicki** [comment]
how this could even pass tests?

**Comment by Domainv** [comment]
@sherlock1982 Please provide some small repo of reproduction

**Comment by sherlock1982** [comment]
Sorry, for now I don't have enough time to make a repo. I will do a bit later but here are the contents of `node_modules/ngx-bootstrap/pagination/models/index.d.ts` right after I install 3.1.2:

```
export interface ConfigModel {
    align?: boolean;
    boundaryLinks: boolean;
    directionLinks: boolean;
    firstText: string;
    itemsPerPage: number;
    lastText: string;
    maxSize: number;
    nextText: string;
    pageBtnClass: string;
    previousText: string;
    rotate: boolean;
    [key: string]: string | number | boolean;
}

```

`align?` can't be used together with  `[key: string]: string | number | boolean;`. This is quite clear to typescript compiler 3.1.6

**Comment by sherlock1982** [comment]
Ok here it is:

https://github.com/sherlock1982/ngx-bootstrap-ts

Fails when `strictNullChecks` set to true

**Comment by Domainv** [comment]
@sherlock1982 Thanks a lot, will be updated to support the option.

**Comment by sherlock1982** [comment]
I suggest to simply do everything with `strict: true` if it's possible.

**Comment by Domainv** [comment]
@sherlock1982 I agree

**Comment by valorkin** [comment]
I thought I enabled this flag when Angular added support for it, hm
