### ISSUE TITLE
Date Picker doesn't open when the locale is el

### ISSUE THREAD

**Issue by meshubh** [valor-software/ng2-bootstrap#4851]
### Bug description or feature request:
When you use the el locale and try to open the date-picker you see an console error stating "momentToFormat.month is not a function" and the date picker popover doesn't open. On investigating further it seemed like the months function in el locale expects a moment date object as the first parameter and not a simple date object. Can you please address this issue.

### Versions
ngx-bootstrap:  3.0.1

Angular: 7.0.1

Bootstrap: 3.3.7

**Comment by llysenko** [comment]
Please provide a reproduction via stackblitz

Starter templates:
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts
