### ISSUE TITLE
Problem with build Can't resolve 'ngx-bootstrap/loader'

### ISSUE THREAD

**Issue by jarekkowol** [valor-software/ng2-bootstrap#4852]
During command ng build --prod
Have You any solution?
```
ERROR in ./node_modules/ngx-bootstrap/datepicker/fesm5/ngx-bootstrap-datepicker.js
Module not found: Error: Can't resolve 'ngx-bootstrap/loader' in '/Users/jaroslawkowol/PhpstormProjects/project-sendflow-frontend/node_modules/ngx-bootstrap/datepicker/fesm5'
ERROR in ./node_modules/ngx-bootstrap/dropdown/fesm5/ngx-bootstrap-dropdown.js
Module not found: Error: Can't resolve 'ngx-bootstrap/loader' in '/Users/jaroslawkowol/PhpstormProjects/project-sendflow-frontend/node_modules/ngx-bootstrap/dropdown/fesm5'
ERROR in ./node_modules/ngx-bootstrap/esm5/public_api.js
```

### Versions of ngx-bootstrap, Angular:

ngx-bootstrap: ^3.1.2

Angular CLI: 7.1.0
Node: 9.6.1
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.1.0
@angular/cdk                      6.4.7
@angular/cli                      7.1.0
@angular/material                 6.4.7
@ngtools/webpack                  6.0.8
@schematics/angular               7.1.0
@schematics/update                0.11.0
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.8.3

**Comment by Domainv** [comment]
@jarekkowol Please change used link to 'ngx-bootstrap/component-loader'

**Comment by denis-souzaa** [comment]
solution not working for me.

**Comment by Domainv** [comment]
@SistemasSouza Could you provide some small repo of reproduction?

**Comment by denis-souzaa** [comment]
my problem is project path, problem resolved. thanks @Domainv

**Comment by Domainv** [comment]
ok)

**Comment by RomainAtEverdyn** [comment]
Hello @SistemasSouza,
I have the very same issue, could you please explain the steps you get to solve ? 
Thanks

**Comment by denis-souzaa** [comment]
Hi @RomainAtEverdyn my problem it was space in path directory, only remove space and it work

**Comment by RomainAtEverdyn** [comment]
@SistemasSouza Thanks for replying,
I do not have any space in my folders tree, investigating further...

**Comment by haseel2004** [comment]
I do have a similar issue. No folders or files with spaces.

ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve 'ngx-bootstrap/loader' in '/src/app'

**Comment by NoumanMukhtar** [comment]
I was also facing this problem with angular version 7. I did'nt find a proper solution but currently, i just downgrade my ngx-bootstrap version to 3.0.1 and it just fix the issue.

**Comment by francovp** [comment]
Hi, I have the same Issue as @haseel2004 but I din't even have ngx-bootstrap installed.
