### ISSUE TITLE
update version of npm-run-all to lastest avoid malicious code

### ISSUE THREAD

**Issue by 901F** [valor-software/ng2-bootstrap#4854]
please update your library `npm-run-all` from version 4.1.3 to version 4.1.5

follow this issue
[Issue with dependency on flatmap-stream via ps-tree#155](https://github.com/mysticatea/npm-run-all/issues/155)

about event-stream issue
[I don't know what to say#116](https://github.com/dominictarr/event-stream/issues/116)

**Comment by NewEraCracker** [comment]
Hi,

I am trying to get flatmap-stream published with npm. Hopefully they allow me to publish 0.1.3 (same as 0.1.0) without the backdoor.

This will possibly unbreak any projects still using this.

**Comment by ludmilanesvitiy** [comment]
Solved in https://github.com/valor-software/ngx-bootstrap/pull/4882
