### ISSUE TITLE
rating is automatically submitting form while using reactive forms

### ISSUE THREAD

**Issue by santhoshraju621** [valor-software/ng2-bootstrap#4858]
Hi i have used bootstrap rating in my reactive form while clicking on the rating it is automatically calling the form submit function .

here is the html code i have used for reactive forms.

`<div class="overall-rating" [tooltip]="validationerrors.checktouchedvaliddirty(compform,'overAllRating')">

                        <p class="gradfontbold">Overall Rating</p>

                        <ng-template #overAllTemplate let-i="index" let-v="value">

                          <button class="btn btn-{{i < v ? 'success' : 'default'}}">
                            <i class="fa fa-{{i < v ? 'star' : 'star-o'}}"></i>
                          </button>
                        </ng-template>
                        <rating [max]="5"  formControlName="overAllRating"  name='rating' [customTemplate]="overAllTemplate" ></rating>
                      </div>`

Here is my type script function to submit a form

`companyReview() {
    console.log("fom submittion");
    if (this.compform.valid) {
      let authenticateddata = JSON.parse(localStorage.getItem('userState'));
      if(authenticateddata.authenticated == true){
       // let data = sessionStorage.getItem('reviewdata');
       // this.senddata((data === null || data === undefined)?this.compform.value:data);
       this.senddata(this.compform.value);
        sessionStorage.removeItem('reviewtype');
        sessionStorage.removeItem('reviewdata');
      } else {
        sessionStorage.setItem('reviewdata',JSON.stringify(this.compform.value));
        sessionStorage.setItem('reviewtype','NOT_LOGGED_IN');
        this.router.navigate(['jslogin'],{ queryParams:{link:'/give-company-review'}});
      } 
      console.log('form submitted');
    } else {
      console.log('form not submitted');
      this.validateAllFormFields(this.compform); //{7}
    }
  }`

Please help me to resolve the issue.

Thanks in Advance.

**Comment by llysenko** [comment]
Please provide a reproduction via stackblitz

Starter templates:
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts
