### ISSUE TITLE
Adding "modals" will add bs-datepicker.css

### ISSUE THREAD

**Issue by FrancescoBorzi** [valor-software/ng2-bootstrap#4888]
### Bug description or feature request:

Running `ng add ngx-bootstrap  --component modals` also adds `"./node_modules/ngx-bootstrap/datepicker/bs-datepicker.css"` to the `styles` array in `angular.json`.

Since it looks like weird to me (what does that file have to do with modals?), I was wondering if it's a bug or the expected behaviour

ngx-bootstrap: `3.1.2`

Angular: `7.1.1`

Bootstrap: `4.1.3`

### Build system: Angular CLI, System.js, webpack, starter seed:

> Angular CLI: 7.1.1
> Node: 10.13.0
> OS: linux x64
> Angular: 7.1.1
> ... animations, cli, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.11.1
> @angular-devkit/build-angular     0.11.1
> @angular-devkit/build-optimizer   0.11.1
> @angular-devkit/build-webpack     0.11.1
> @angular-devkit/core              7.1.1
> @angular-devkit/schematics        7.1.1
> @ngtools/webpack                  7.1.1
> @schematics/angular               7.1.1
> @schematics/update                0.11.1
> rxjs                              6.3.3
> typescript                        3.1.6
> webpack                           4.23.1
>

**Comment by Domainv** [comment]
@FrancescoBorzi Will be fixed

**Comment by FrancescoBorzi** [comment]
JFYI: I think it happens also with other features, for example I've just tried with Accordion and there is the same issue.

**Comment by Domainv** [comment]
@FrancescoBorzi Thanx, I now
