### ISSUE TITLE
Pagination component: Dynamic items per page is not reflecting on pagination

### ISSUE THREAD

**Issue by akvaliya** [valor-software/ng2-bootstrap#4897]
I have select in which i have ` [(ngModel)]="itemsPerPage"`

And pagination is like this

```
  <pagination [totalItems]="totalItems" [itemsPerPage]="itemsPerPage" boundaryLinks="true"
                      [(ngModel)]="currentPage" (pageChanged)="pageChanged($event)" [maxSize]="10" [disabled]="inProgress"></pagination>
```

When i change select of items per page it is not reflecting on pagination.

For example, with 20 total items at 10 items per page the pagination component should show two pages, and does. However, if I set the itemsPerPage to 5 it still only shows 2 pages instead of 4. It appears the calculation for the number of pages is not recalculated when itemsPerPage is changed.

Can anyone tell me what am i missing here?

**Comment by llysenko** [comment]
Please provide a reproduction via stackblitz

Starter templates:
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by akvaliya** [comment]
I have tried to reproduce & found out then it's not working when i call http call on select change of itemsPerPage dropdown.

I don't know why but i had to put setTimeOut on that http call & pagination component started working fine.

Strange behavior. Thanks for the assist by the way.
