### ISSUE TITLE
suspicious umd bundle size 3.1.2

### ISSUE THREAD

**Issue by timbell** [valor-software/ng2-bootstrap#4899]
Is the `ngx-bootstrap.umd.js` file built ok in 3.1.2? It looks suspiciously small (~11KB) whereas in 3.0.1 it's ~900KB and in 2.0.5 it's 1MB

I'm trying to move from 2.0.5 to 3.1.2 and getting load errors in my systemjs environment with 3.1.2 which point to a problem with the bundle.

**Comment by valorkin** [comment]
In versions 3.1+ we switched to ng-packagr builds, but why systemjs?

**Comment by timbell** [comment]
Why not? So long as UMD is included in the Angular Package Format I think it makes sense to support it. I could be wrong but the ngx-bootstrap UMD file looks broken to me.
