### ISSUE TITLE
Issues enter keypress

### ISSUE THREAD

**Issue by vietdq1291** [valor-software/ng2-bootstrap#4907]
I have problem when hit enter key ,my page redirect to previous link (Datepicker inside reactive form)

**Comment by ludmilanesvitiy** [comment]
@vietdq1291 Please provide a reproduction via stackblitz

Starter templates:
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by vietdq1291** [comment]
> @vietdq1291 Please provide a reproduction via stackblitz
> 
> Starter templates:
> StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

thank you !
I have solve problem, this case only occurs when using control inside form with out submit form event
