### ISSUE TITLE
BsDatepickerModule under development warning issue

### ISSUE THREAD

**Issue by dhanashree26p** [valor-software/ng2-bootstrap#4909]
Hello,

I am using BsDatepicker to select dates on my HTML template. I have imported BsDatepickerModule  from 'ngx-bootstrap'. Environment is - Angular 6. Datepicker works fine on chrome browser but when I see console - it says a warning that "BsDatepickerModule is under development, BREAKING CHANGES are possible, PLEASE, read changelog". Can anybody please help to resolve this issue or suggest what will be alternate & easy way or datepicker to use in NgxBootstrap?

**Comment by valorkin** [comment]
You can ignore this warning, Datepicker is stable.
But more features will be added

**Comment by thetric** [comment]
> You can ignore this warning, Datepicker is stable.

So is this warning obsolete and can be removed?

**Comment by valorkin** [comment]
Yep
