### ISSUE TITLE
tooltipEnable property value inconsistent behavior

### ISSUE THREAD

**Issue by benj0c** [valor-software/ng2-bootstrap#4910]
### Bug description or feature request:

Bug: For tooltip when set tooltipEnable on true, tooltip is disabled and vice-versa.

### Plunker/StackBlitz that reproduces the issue:

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-fq9c2x?embed=1&file=app/app.component.html

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: v3.0.1

Angular: v7.0.3

Bootstrap: v3.x

**Comment by benj0c** [comment]
Here is PR #4911

**Comment by valorkin** [comment]
Gould catch, thanks for PR.
Use isDisabled, cuz tooltipEnabled will be removed
