### ISSUE TITLE
feature(datepicker): Add some way to select a week

### ISSUE THREAD

**Issue by Lolmewn** [valor-software/ng2-bootstrap#4921]
### Feature request:
I'm looking for the ability to select a week number, but I can't seem to find a way to do this right now. The week numbers are displayed, but are not clickable. When clicked, I'd suggest to select the first day of the week as output.

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 3.1.3
Angular: 7.1.2
Bootstrap: 3.3.7

**Comment by daniloff200** [comment]
I think, I can help with this. 
But, I have two questions
What about the case, when, for example, first day of the week is disabled? 
And also, how this functionality should work if first day of the week in previous month (like 29th November for the December case) 
@Lolmewn do you have any ideas or suggestions?

**Comment by Lolmewn** [comment]
@daniloff200 I'd suggest to select the first non-disabled day, then. If all days in a week are disabled, disable the week entirely. 
If the first day of the week is in a different month (or a different year for that matter) I don't see any issues with that. The main use-case is to have some starting point from which you can go forward one week (e.g. with momentjs, use `startMoment.startOf('isoWeek').add(1, 'week')`)

**Comment by daniloff200** [comment]
@Lolmewn  Great to hear that, we're on the same page, I also thought about such implementations. So, I hope to create a PR with this feature soon
