### ISSUE TITLE
how to set z-index for datepicker

### ISSUE THREAD

**Issue by YuZaiShui** [valor-software/ng2-bootstrap#4923]
In my codes, input element has to be seted z-index > 1, how to set config for my datepicker?

**Comment by llysenko** [comment]
Could you clarify please, do you want to add z-index through bsConfig?

**Comment by YuZaiShui** [comment]
@MilaLys yes, i want to set z-index for my datepicker through [bsConfig] input,or can i set other attribute/[input] ?

**Comment by llysenko** [comment]
@YuZaiShui sorry for delay of a response. You can't set styles through bsConfig, but you can try to override z-index in your custom styles, something like this:
```
body {
  .bs-datepicker {
    z-index: 0;
  }
}
```

**Comment by YuZaiShui** [comment]
@MilaLys thanks for your answer, it work for me! Thanks.
