### ISSUE TITLE
how to implement model class method in parent class 

### ISSUE THREAD

**Issue by GeethGamage** [valor-software/ng2-bootstrap#4926]
hii
export class PagemanagementComponent implements OnInit { 
viewAuthAdd(code:string,record :string){
      const modalRef = this.modalService.open(AddviewComponent);
      modalRef.componentInstance.cord = code;
      modalRef.componentInstance.record = record;
      modalRef.componentInstance.service = record;
  }
}

export class AddviewComponent Implements OnInit{
  @Input() code: string;
  @Input() record: string;

  submitted = false;
  actionMessage :String;
  addError :String;
  testObject:{ [key: string]: any };
  addmodel = new Authentication("","");

  constructor(public activeModal: NgbActiveModal,
              public http: HttpClient,
              ) { }

  ngOnInit() {
   console.log(JSON.parse(this.record));
   this.testObject=JSON.parse(this.record);
  }

  callParent() {
 
  }
  closeModal() {
    this.activeModal.close('Modal Closed');
  }

}

hi i want AddviewComponent.callParent() common method call in parent class or implement in parent class( PagemanagementComponent )

**Comment by ludmilanesvitiy** [comment]
@GeethGamage There's no need to open an issue here if you want to ask a general question, use [StackOverflow]( https://stackoverflow.com/questions/tagged/ngx-bootstrap) or Slack instead
