### ISSUE TITLE
ngx pagination with fast clicking on sever side call

### ISSUE THREAD

**Issue by AlexandriaDeveloper** [valor-software/ng2-bootstrap#4937]
notice to me if i clicked very fast on  pagination bar there is some lags if i paginate from server side any option to debounce clicking on pagination till response back ?!

**Comment by ludmilanesvitiy** [comment]
@AlexandriaDeveloper There's no need to open an issue here if you want to ask a general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or Slack instead.
