### ISSUE TITLE
Date Range Picker | Highlight todays date

### ISSUE THREAD

**Issue by naveendb92** [valor-software/ng2-bootstrap#4938]
- Can anyone help me to highlight the current date in a **DateRangePicker**.

- Or provide a way to add **class** to current date so that the user can customize according to his needs
in a **DateRangePicker**.

**Comment by valorkin** [comment]
PR already merged will be released as v3.1.4 this week, watch in slack for a note

**Comment by naveendb92** [comment]
Thank you @valorkin

**Comment by naveendb92** [comment]
Not able to find this in **3.1.4** release. Has this went through?
