### ISSUE TITLE
Can btnCheckbox be disabled?

### ISSUE THREAD

**Issue by emilynielson** [valor-software/ng2-bootstrap#4942]
Can a btnCheckbox be disabled? I am able to disable a btnRadio, but not a btnCheckbox.

I've tried disabled, [disabled], [disabled] = true, [attr.disabled]="true".

Thanks!

**Comment by ghost** [comment]
@emilynielson besides [disabled]=true , you can add styles like in bootstrap 3 
`.btn[disabled],
fieldset[disabled] .btn {
  cursor: not-allowed;
  filter: alpha(opacity=65);
  -webkit-box-shadow: none;
          box-shadow: none;
  opacity: .65;
}`
and everything will be ok
