### ISSUE TITLE
Disable any day of month

### ISSUE THREAD

**Issue by psalkowski** [valor-software/ng2-bootstrap#4945]
### Feature request:

It would be great to have possibility to disable any date in calendar. Currently, we can disable day of week, but often, we would like to disable just few days in month, i.e. Christmass or other bank holidays. 

It would be even greater if we will have ability to provide tooltip for any of these days :)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.1.3

Angular: 6.1.8

Bootstrap: 4.1.3

**Comment by ludmilanesvitiy** [comment]
The feature is already implemented, demo example here: https://valor-software.com/ngx-bootstrap/#/datepicker#dates-disabled
