### ISSUE TITLE
display error

### ISSUE THREAD

**Issue by tkezyo** [valor-software/ng2-bootstrap#4948]
display error after publish.

![image](https://user-images.githubusercontent.com/11564410/50127659-0a7be400-02ad-11e9-9c6f-91f4ec733c1a.png)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:3.1.3

Angular:7.1.1

Bootstrap:

**Comment by daniloff200** [comment]
hi @tkezyo 
Please provide a reproduction of this issue.
You can use one of these templates:
Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-hkm8pi?file=app/app.module.ts

**Comment by zernolo** [comment]
I get the same error in production using Angular 6.1.8 and ngx-bootstrap 3.1.1

**Comment by zernolo** [comment]
with the option of production -> "buildOptimizer": false in file angular.json the problem disappear
[may be this issue it's involved?](https://github.com/angular/angular-cli/issues/10655)

**Comment by tkezyo** [comment]
thanks for your help.
