### ISSUE TITLE
Nested dropdowns (experimental)   show Bug

### ISSUE THREAD

**Issue by li10217** [valor-software/ng2-bootstrap#4955]
## Three menu displays overlap, one of which does not disappear

![qq 20181219161203](https://user-images.githubusercontent.com/23067397/50207321-16e56700-03a9-11e9-907e-a921632cf3c4.png)

**Comment by ghost** [comment]
Duplicate of #3703

**Comment by ludmilanesvitiy** [comment]
Actual issue #4739
