### ISSUE TITLE
Dropdown autoClose not working with manual triggering

### ISSUE THREAD

**Issue by fynnfeldpausch** [valor-software/ng2-bootstrap#4956]
### Bug description or feature request:
The manual triggering of the `BsDropdownDirective` is not working when the `autoClose` option is set. Calling `toggle`, `show` or `hide` shows no effect. I'd expect these methods to work as usual and the `autoClose` option to apply. Both features should work independently and in combination.

### Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/ngx-bootstrap-yigrz6

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.1.2

Angular: 7.1.0

Bootstrap: 3

**Comment by ghost** [comment]
@fynnfeldpausch you are absolutely right because if you set autoClose equal true you said to the app: "Please close a dropdown when I make click on any element if this element isn't a dropdown menu."

**Comment by fynnfeldpausch** [comment]
@svetoldo4444ka I don't see the contradiction here. Why can't I manually show a dropdown and - once it is visible - have it close on click if the clicked element isn't a dropdown menu?

**Comment by ghost** [comment]
@fynnfeldpausch you can do something like this:
![joxi_screenshot_1545310300904](https://user-images.githubusercontent.com/21618857/50286182-43f84f00-0467-11e9-8db7-2ec85e49f700.png)
![joxi_screenshot_1545310452946](https://user-images.githubusercontent.com/21618857/50286185-49559980-0467-11e9-88c4-e3ed4690a82b.png)

**Comment by fynnfeldpausch** [comment]
Agreed, this is the sort of workaround I am using now. However, I do think that the behavior is inconsistent and should be fixed. But this is a matter of perspective...

**Comment by valorkin** [comment]
It's rather a hack in user code, or hack in ngx component, which will stop propogation if autoclose true, which should be optional cuz not obvious

**Comment by paolomangiadev** [comment]
why is this closed if still isn't working?

**Comment by tanishkab** [comment]
did you find any solution?
