### ISSUE TITLE
Add language translation for Catalan

### ISSUE THREAD

**Issue by arbatxavier** [valor-software/ng2-bootstrap#4959]
Hello, I would like to add Catalan translations.

I have a local branch with translations and all related tests to this.
I just need to make a pull request but I need permission to set remote branch.

Thank you in advance.

**Comment by ludmilanesvitiy** [comment]
@XavisaurusRex Please, make a fork of ngx-bootstrap and from there you'll be able to create a PR: https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md#-submitting-a-pull-request-pr
