### ISSUE TITLE
Datepicker extensibility

### ISSUE THREAD

**Issue by li10217** [valor-software/ng2-bootstrap#4968]
###  I want a date picker similar to the one below. What should I do?Do you have extension properties?
![qq 20181221104656](https://user-images.githubusercontent.com/23067397/50321844-c3d8f480-050d-11e9-9dc1-b2e02dc421d1.png)

**Comment by ludmilanesvitiy** [comment]
Closed as a duplicate of https://github.com/valor-software/ngx-bootstrap/issues/551
