### ISSUE TITLE
feat(demo): update landing page

### ISSUE THREAD

**Issue by valorkin** [valor-software/ng2-bootstrap#4970]
Replace `github button` with `documentation` button on landing page
Could lead to the same route for now

slack badge replace with a constant icon of slack and set link to https://join.slack.com/t/ngx-home/shared_invite/enQtNTExMTY5MzcwMTM0LWQ5M2Y4OWM0OGJjNmZiOGYyNjFlZTdlOGI1YjcxYWQ2ODhiOTY4NzhiODgwMTIzNDczODIyNWNmM2RlYWRhNTg

this link should be updated in readme.md and header and on getting-started page

**Comment by valorkin** [comment]
cc @svetoldo4444ka

**Comment by ludmilanesvitiy** [comment]
And need to update Credits:
Crossbrowser testing sponsored by Browser Stack  => Crossbrowser testing sponsored by Saucelab
And need to add appropriate icon, link (https://saucelabs.com/)
