### ISSUE TITLE
typeahead async is not showing all results

### ISSUE THREAD

**Issue by t-zander** [valor-software/ng2-bootstrap#4983]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://join.slack.com/t/ngx-home/shared_invite/enQtNTExMTY5MzcwMTM0LWQ5M2Y4OWM0OGJjNmZiOGYyNjFlZTdlOGI1YjcxYWQ2ODhiOTY4NzhiODgwMTIzNDczODIyNWNmM2RlYWRhNTg) instead

### Bug description or feature request:
When using async calls, and get, for example 50+ options back, typeahead windows will show only first 20.
However, in the API I haven't found that 
typeaheadOptionsLimit has any default value.
Here is the code
```
       <input 
        [(ngModel)]="inputValue"
        [typeahead]="dataSource"
        (typeaheadOnSelect)="addressSelected($event.item)"
        [typeaheadAsync]="true"
        [typeaheadScrollable]="true"
        [typeaheadItemTemplate]="schemeTemplate"
        [typeaheadOptionsInScrollableView]="10"
        typeaheadWaitMs="400"
        type="text" 
        class="form-control input-lg" 
        autocorrect="off" 
        autocapitalize="off" 
        placeholder="Search by"
        >

      <ng-template #schemeTemplate let-model="item" let-index="index">
        {{model.address}} 
      </ng-template>
```
Here is what I got
[http://prntscr.com/m0hntj](url)
[http://prntscr.com/m0hmyh](url)

Just as a temporary solution I just set **typeaheadOptionsLimit** to a big number like 10000, but I gues it is not the best solution.

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:
^2.0.5
Angular:
^6.0.0
Bootstrap:

**Comment by ghost** [comment]
@t-zander hanks for your comment. `typeaheadOptionsLimit` value equals 20 by default. We will add it in our docs.
