### ISSUE TITLE
how to use Manual selection of tabs in modals

### ISSUE THREAD

**Issue by hellodpk** [valor-software/ng2-bootstrap#4987]
I am trying to use [Manual selection of tabs](https://valor-software.com/ngx-bootstrap/#/tabs#tabs-manual-select). It works in template.
### Bug description or feature request:
Manual selection of tabs does not works when we use it inside  [Modals](https://valor-software.com/ngx-bootstrap/#/modals).

I want manual selection of tabs to work in modals

### Plunker/StackBlitz that reproduces the issue:
[StackBlitz ](https://stackblitz.com/edit/ngx-bootstrap-ra7akc?embed=1&file=app/app.component.html)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:3.1.3

Angular:6.1.10

Bootstrap:4

**Comment by llysenko** [comment]
@hellodpk try this:
1. add template reference variable to those methods `(click)="selectTab(staticTabs, 1)`
1. in component remove @ViewChild and change a bit this method:
```
selectTab(staticTabs: TabsetComponent, tabId: number) {
    staticTabs.tabs[tabId].active = true;
}
```
It works for me. I hope does for you too.

**Comment by hellodpk** [comment]
@MilaLys, above fix worked. Thanks
