### ISSUE TITLE
auto placement for daterange picker

### ISSUE THREAD

**Issue by amitsadafule** [valor-software/ng2-bootstrap#4990]
Hi all,

As I can see, bsDaterangepicker supports only top, right, left, bottom placements. It should support an "auto" placement as well. If configured, it will, based on UI, will show calendar(s) on left/right/top/bottom if there is space to show it. Bydefault it can be bottom.

Is there any way to achieve this with current configuration?

**Comment by daniloff200** [comment]
Looks like a duplicate of https://github.com/valor-software/ngx-bootstrap/issues/4540

**Comment by amitsadafule** [comment]
yes.. Thanks.. But there is no reply on that as well. Closing this issue
