### ISSUE TITLE
feat(datepicker): add possibility of keeping special dates always highlighted regardless of the selected date

### ISSUE THREAD

**Issue by riede** [valor-software/ng2-bootstrap#4993]
The title already describes the feature. You've got a list of special dates that should be highlighted in the datepicker. This feature might be quite similar to #3192. I think the feature can be realized via the `BsDatepickerConfig`. Add here two attributes (something like that):

1.  `customSpecialDatesClass: string` - it expects a css class for highlighting the special dates
2. `specialDates: Date[]` it expects a list of dates that represents the dates that should be highlighted

**Comment by pgeyman** [comment]
I have just had a client ask if this functionality is possible to highlight Public Holidays. It would be great to see it added
