### ISSUE TITLE
Daterange input field - formatting selected value not in documentation

### ISSUE THREAD

**Issue by hajdun** [valor-software/ng2-bootstrap#5014]
### Bug description or feature request:
Daterange : I would like to add formatting to the field AFTER I have selected a date range

I have a 
```
2019-01-01 - 2019-02-05
```
selected, shown in my input field (it is ok, functionally).

and I thought about adding a greater distance between these values to make it more readable, so  

```
2019-01-01            -                2019-02-05
```
but I find no way to do so :( 
Can this be done somehow? Is there a config option to replace the  "-" with something with more whitespace?

**Comment by Joklogh** [comment]
Hi @hajdun 
You can use `word-spacing` property in html. Just add this CSS property to the input field and assign how many px should be added between words.
Let me know if it solves your issue
