### ISSUE TITLE
Buttons highlight of month switch in the Datepicker component, are not centered

### ISSUE THREAD

**Issue by dmitry-zhemchugov** [valor-software/ng2-bootstrap#5015]
### Bug description:
Buttons highlight of month switch in the Datepicker component, are not centered

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.1.4

Angular: 6

Bootstrap: 4

### Build system: Angular CLI

![bootstrap_issue](https://user-images.githubusercontent.com/44227371/51395487-ab2c2080-1b45-11e9-8800-955597ef4ef1.jpg)

**Comment by edchai** [comment]
@SvetlanaMuravlova this issue is still actual
![Screenshot 2021-05-31 at 15.21.29.png](https://images.zenhubusercontent.com/608a8147a3a918726c2b7d7d/ebfe5e72-bfe8-48d4-bb83-813f13ee2495)
