### ISSUE TITLE
Can't bind to 'insideClick' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by majorsaaam** [valor-software/ng2-bootstrap#5016]
### Bug description or feature request:
> Can't bind to 'insideClick' since it isn't a known property of 'div'.

I need to make a dropdown clickable since it will be a login form. Checking the docs, I used `[insideClick]="true"` on my `<div class="btn-group">`, but the template couldn't parse it as a known property of div. 
`[autoClose]="false"` could solve my issue, but the experience is rather harsh since I have another dropdown just by its side, and I would have to toggle the auto-closing dropdown every time I clicked it.

I have already tried using the common `<button>` tag instead of `<a role="button">` in case this was the issue, to no avail.

### Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/ngx-bootstrap-ryrc4c?embed=1&file=app/app.component.html

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 3.1.4

Angular: 6.1.1

Bootstrap: 4.2.1

### Build system: Angular CLI, System.js, webpack, starter seed:
@angular/cli - 6.1.1
@ngtools/webpack - 6.1.1
rxjs - 6.2.2
typescript - 2.7.2
webpack - 4.9.2

**Comment by Joklogh** [comment]
Hi @majorsaaam, the issue, in the StackBlitz that you provided, is that `BsDropdownModule` is not imported in AppModule. Also use the current version of ngx-bootstrap, in StackBlitz the old version was used. 
Hope it helps :)
If it won't solve your issue, please let me know.

**Comment by majorsaaam** [comment]
Sorry for taking so long, I had to work in another project.

My AppModule had `BsDropdownModule`, but updating it to 3.2.0 solved the issue. Thanks a lot.

By the way, is it too much asking to have minimum versions specified in most functions? I'm new to versioning and publishing - I wouldn't know how much work it would be, but considering I had an older version and **most** worked but not **some**, my instant line of thought was that the package was bugged.

**Comment by ludmilanesvitiy** [comment]
Looks like issue solved. Thank you @Joklogh
