### ISSUE TITLE
ERROR TypeError: h.ngOnInit is not a function

### ISSUE THREAD

**Issue by prayagkr** [valor-software/ng2-bootstrap#5017]
### Bug description or feature request:

When a Button is clicked to Show the Date range picker or date picker. It gives an error as mentioned below and date is populated slowly one by one. Date picker doesn't disappear when we click outside. Current version of ngx-bootstrap is 3.0.1, I also tried using 3.1.4, but problem exists. In local development it works fine, but when we deploy it to dev environment. Error is observed. 

ERROR TypeError: h.ngOnInit is not a function
    at main.e1698cdb2dfe7eda1fce.js:1
    at main.e1698cdb2dfe7eda1fce.js:1
    at db (main.e1698cdb2dfe7eda1fce.js:1)
    at Zb (main.e1698cdb2dfe7eda1fce.js:1)
    at main.e1698cdb2dfe7eda1fce.js:1
    at Object.updateDirectives (main.e1698cdb2dfe7eda1fce.js:1)
    at Object.Wb [as updateDirectives] (main.e1698cdb2dfe7eda1fce.js:1)
    at lb (main.e1698cdb2dfe7eda1fce.js:1)
    at bb (main.e1698cdb2dfe7eda1fce.js:1)
    at fb (main.e1698cdb2dfe7eda1fce.js:1)

code used : 

`
<button type="button" (click)="dp.show()">Date picker</button>
<input type="button" placeholder="Custom" id="calendar_f" class="btn-cal-hid"   
                        bsDaterangepicker #dp="bsDaterangepicker"   
                        [bsConfig]="DATE_RANGE_PICKER_CONFIG"
                        [isDisabled]="datePickerIsDisabled"  
                        [outsideClick]="true"  placement="bottom"
                        (bsValueChange)="selectedDate($event)"/>
`
### Image of error
<img width="1090" alt="calendar issue" src="https://user-images.githubusercontent.com/18230934/51440181-537aea00-1cea-11e9-9f81-a21cb6b49eb8.png">

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.1 / 3.1.4

Angular:  7.0.5

Bootstrap: 3.3.7

**Comment by ludmilanesvitiy** [comment]
@prayagkr  Hello! Please provide a reproduction via StackBlitz.
Starter template:
https://stackblitz.com/edit/ngx-bootstrap

**Comment by Domainv** [comment]
Closes as outdated
