### ISSUE TITLE
Time display abnormality

### ISSUE THREAD

**Issue by jocklei** [valor-software/ng2-bootstrap#5018]
The local development environment shows normal, but after compilation, it shows abnormal in the production environment. See the attached picture:
![tim 20190121160544](https://user-images.githubusercontent.com/19809782/51461462-1883bf80-1d99-11e9-8b59-9fcea7ca8361.png)

**Comment by Domainv** [comment]
@leihg More info please.
Which version of angular, ngx-bootsrap?

**Comment by sebastian-zarzycki-apzumi** [comment]
I've provided some information in #4821 . Basically, it now happens even in non-optimized builds.

**Comment by jocklei** [comment]
The problem has been solved. Thank you very much.

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=jocklei&uid=jocklei%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22jocklei%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
jocklei

jocklei@outlook.com

签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
On 1/25/2019 19:18，Sebastian Zarzycki<notifications@github.com><mailto:notifications@github.com> wrote：

I've provided some information in #4821<https://github.com/valor-software/ngx-bootstrap/issues/4821> . Basically, it now happens even in non-optimized builds.

**Comment by Domainv** [comment]
@leihg Great!
What was the reason?

**Comment by jocklei** [comment]
I don't know why. I upgraded the'ngx-bootstrap'version to'3.2.0', and that's all.

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?ftlId=1&name=jocklei&uid=jocklei%40outlook.com&iconUrl=https%3A%2F%2Fmail-online.nosdn.127.net%2Fqiyelogo%2FdefaultAvatar.png&items=%5B%22jocklei%40outlook.com%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
jocklei

jocklei@outlook.com

签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail81> 定制
On 1/25/2019 22:58，Vitaliy Makogon<notifications@github.com><mailto:notifications@github.com> wrote：

@leihg<https://github.com/leihg> Great!
What was the reason?
