### ISSUE TITLE
issue is created with a fix

### ISSUE THREAD

**Issue by dolphinsd** [valor-software/ng2-bootstrap#5021]
This fix
https://github.com/valor-software/ngx-bootstrap/commit/6e04b33e88c454eebbf21b32e3bada71bb121deb#diff-16979e36a5a13aafd2342c798d64e85b

created issue when used with metronic in aspnetzero

Now dropdown does not appear, as it overrides metronic stylying.

it should be reversed.

**Comment by ludmilanesvitiy** [comment]
@dolphinsd  Hello! Please provide a reproduction via StackBlitz.
Starter template:
https://stackblitz.com/edit/ngx-bootstrap

**Comment by Domainv** [comment]
Closes as outdated
