### ISSUE TITLE
How to add directive to the modal creates via modalService?

### ISSUE THREAD

**Issue by rzych** [valor-software/ng2-bootstrap#5025]
### Bug description or feature request:
I want to add angular2-draggable to the ngx-modals. But I don't know how to do this via modalService. Is there any option to do this?

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.1.4

Angular: 7.2.2

Bootstrap:4.2.1

**Comment by ludmilanesvitiy** [comment]
@rzych There's no need to open an issue here if you want to ask a general question, use StackOverflow or Slack instead
https://stackoverflow.com/questions/tagged/ngx-bootstrap
https://ngx-home.slack.com/
