### ISSUE TITLE
Can I select days without hiding them?

### ISSUE THREAD

**Issue by li10217** [valor-software/ng2-bootstrap#5032]
### I need to make a datetimepicker selector.But when I choose the day it is hidden.

**Comment by ludmilanesvitiy** [comment]
@li10217 There's no need to open an issue here if you want to ask a general question, use StackOverflow or Slack instead
https://stackoverflow.com/questions/tagged/ngx-bootstrap
https://ngx-home.slack.com/

**Comment by ludmilanesvitiy** [comment]
@li10217 Did you try inline datepicker for your goal?
