### ISSUE TITLE
I dont add i just change any language source

### ISSUE THREAD

**Issue by ghost** [valor-software/ng2-bootstrap#5038]
Hi.I want change any language Month days for my language(Azerbaijan). I dont add a just change any language source(idLocale).But I cannot find which file contain month strings for datepicker. I search all id(Indonesian month(Agustus) and find and change all. But my datepicker dont change language. Thans

**Comment by ludmilanesvitiy** [comment]
@emilalsgndr There's no need to open an issue here if you want to ask a general question, use StackOverflow or Slack instead
https://stackoverflow.com/questions/tagged/ngx-bootstrap
https://ngx-home.slack.com/
