### ISSUE TITLE
BsDatepickerInline - isDisabled input not functioning properly

### ISSUE THREAD

**Issue by mihaivarga** [valor-software/ng2-bootstrap#5040]
http://recordit.co/GsnuvRq6My

1. When you disable dynamically you can still click year and months.
2. When you enable dynamically you cannot select days only after clicking year and month.
3. No disabled class added to main container, had to use HostBinding in my custom input to make this work.

ngx-bootstrap: 3.2.0

Angular: 7.2.0

Bootstrap: 4.2.1

**Comment by ludmilanesvitiy** [comment]
@mihaivarga Hello! Thank you for the image, but could you, please provide a reproduction via StackBlitz.
Starter template:
https://stackblitz.com/edit/ngx-bootstrap

**Comment by Domainv** [comment]
Closes as outdated
