### ISSUE TITLE
bsDatepicker not working on Internet Explorer

### ISSUE THREAD

**Issue by itsSandeepNandey** [valor-software/ng2-bootstrap#5049]
### Bug description :
Date Picker is not working on Internet Explorer  and its working fine on Chrome.

Do i need to configure something for Internet Explorer ?

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:
  -->   "ngx-bootstrap": "^3.0.1",

Angular:
  -->   "@angular/cli": "~6.2.4",

Bootstrap:
--> "bootstrap": "^4.1.3",

**Comment by ludmilanesvitiy** [comment]
@itsSandeepNandey Hello! Please provide a reproduction via StackBlitz.
Starter template:
https://stackblitz.com/edit/ngx-bootstrap

**Comment by Domainv** [comment]
Closes as outdated

**Comment by nehamattani** [comment]
I was facing the same issue with angular 8.  Please downgrade and restrict your ngx-bootstrap version to 3.0.0

**Comment by daniloff200** [comment]
I don't recommend that. 3.0.0 is a very old one, and it's better to update to latest version
If you facing any issues with that, open a new github issue, and provide some code / steps to reproduce, and we will try to help you with a fix for it
