### ISSUE TITLE
[timepicker] when user types a valid hours manually, component marks it as invalid

### ISSUE THREAD

**Issue by treeskar** [valor-software/ng2-bootstrap#5053]
### Bug description:

When user types valid hour in "timepicker" hour's field, the component displays this field as invalid.
It returns null in valueChanges stream, but formControl has still a valid status.
BTW formControl status doesn't change to invalid at all, even when I type invalid time.

### StackBlitz that reproduces the issue:
Step to reproduce:
* Go to https://stackblitz.com/edit/angular-tbce7x
* Type "06" in hour's field and click outside the field. 

I succeed to reproduce this issue on the official [site](https://valor-software.com/ngx-bootstrap/?gclid=Cj0KCQiAsdHhBRCwARIsAAhRhskwCuKj5vtznkYfhzUNwowvotCezahklsSbwmMT9Q2F6I9OAaCm7O8aAsPUEALw_wcB#/timepicker#min-max) also, [min-max section]

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.2.0

Angular: 7.2.4

Bootstrap: 4.2.1

**Comment by treeskar** [comment]
Hi @ludmilanesvitiy, 
The Problem is, that  [this.isValidLimit](https://github.com/valor-software/ngx-bootstrap/blob/development/src/timepicker/timepicker.component.ts#L283) method returns false instead true.

There you call to util function [isInputLimitValid](https://github.com/valor-software/ngx-bootstrap/blob/development/src/timepicker/timepicker.utils.ts#L180) and pass diff object that contains actual time: hour, minutes, isPM... and min/max date. The root of the issue happens here

export function isInputLimitValid(diff: Time, max: Date, min: Date): boolean {
  const newDate = changeTime(new Date(), diff);

  if (max && newDate > max) {
    return false;
  }
....
}
https://github.com/valor-software/ngx-bootstrap/blob/development/src/timepicker/timepicker.utils.ts#L181

[changeTime](https://github.com/valor-software/ngx-bootstrap/blob/development/src/timepicker/timepicker.utils.ts#L91) **adds** to current time the diff,
so if my current time is 13:10 and diff is { hours: 09, minutes: 20 } the result would be 22:30.
Then the result [isInputLimitValid](https://github.com/valor-software/ngx-bootstrap/blob/development/src/timepicker/timepicker.utils.ts#L180) compares with maxDate, that for example 18:00 and less then 22:30. Instead to compare maxDate with actual input that is 09:20.

I am working now on date range picker, that based on yours time/date pickers components, and this bug causes problems in integration layer, because I can't relay on valueChanges stream. It returns null even though the date is actually valid.
It is much easier and correctly to fix the issue where it happens, so I like to create a pull request, if you agree, instead looking for some workaround in my component.

**Comment by ludmilanesvitiy** [comment]
@treeskar If you could create PR with a fix, it'll be super awesome. Thank you!

**Comment by ludmilanesvitiy** [comment]
@treeskar I'm working with e2e tests for timepicker now and looks like this issue easy to fix. So, I'm planning to fix it soon by myself.

**Comment by treeskar** [comment]
@ludmilanesvitiy yes, this is exactly what needs to be done.

**Comment by ludmilanesvitiy** [comment]
@treeskar Not exactly) Yesterday I've faced issue with 12:05 PM. Every day whole 12'th hour of PM will also send 
isInputLimitValid=false with this solution. I've found how to solve it, but need a bit of testing.

**Comment by treeskar** [comment]
@ludmilanesvitiy I found another issue and it looks relative to issue that you are describing.
12:00 AM is 00:00 in 24h format. But you don't take it in account in parseHours function.

## Reproduces the issue:

I succeed to reproduce the issue in your demo [site -> timepicker -> basic example](https://valor-software.com/ngx-bootstrap/?gclid=CjwKCAiA0uLgBRABEiwAecFnk4QlKk-0Yz8rOOBT5YpfrmzqA1nCOnBbn5Fny258Sseji4NKX5Ty4xoC4O8QAvD_BwE#/timepicker#basic
) 
- set Hours to 12 h
- then **type** valid minutes number, for example 03

meridian would change to PM, even though I've not changed it. If I type another valid number to minute's field, meridian would change once again to AM.

I've not opened a new issue, because as I said it looks relative to this one and the fix itself is very simple. I can create a pull request from my branch, or you can just copy the changes to you branch.

**Comment by aleksander351** [comment]
Still a problem in ngx-bootstrap 18 and angular 18:

            ```
              <timepicker 
                        [(ngModel)]="time"
                        [showMeridian]="showMeridian"
                        [showSpinners]="false"
                        [min]="minDate"
                        [max]="maxDate">
            </timepicker>
            ```

If the maxDate is the current datetime (new Date()) and the selected time is yesterday's date at a specific hour, it still doesn't let me change the hours above the current time, even though the Date object is clearly in the past. Mouse scroll is working, but manual input is not.

time: Tue Dec 10 2024 12:56:03 GMT+0100 (Central European Standard Time)
maxDate (current time): Wed Dec 11 2024 13:00:00 GMT+0100 (Central European Standard Time)

mouse wheel: I can scroll to 14:00
manual input: I can not type in 14
