### ISSUE TITLE
TemplateRef context completely discarded.

### ISSUE THREAD

**Issue by cosminadrianpopescu** [valor-software/ng2-bootstrap#5059]
### Bug description or feature request:
The `ComponentLoader::show` function accepts to have an `opts.context` parameter, to set the `TemplateRef` parameters, which is very cool. But first of all, we can see that the `BsModalConfig` does not have an option for context. 

And then, if I look into `BsModalService::_showModal`, which is calling the `ComponentLoader::show`, I can see that the context is completely discarded:

```
  _showModal(content: any): BsModalRef {
    const modalLoader = this.loaders[this.loaders.length - 1];
    const bsModalRef = new BsModalRef();
    const modalContainerRef = modalLoader
      .provide({ provide: ModalOptions, useValue: this.config })
      .provide({ provide: BsModalRef, useValue: bsModalRef })
      .attach(ModalContainerComponent)
      .to('body')
==>      .show({content, isAnimated: this.config.animated, initialState: this.config.initialState, bsModalService: this}); // NO CONTEXT HERE
    modalContainerRef.instance.level = this.getModalsCount();
    bsModalRef.hide = () => {
      modalContainerRef.instance.hide();
    };
    bsModalRef.content = modalLoader.getInnerComponent() || null;
    bsModalRef.setClass = (newClass: string) => {
      modalContainerRef.instance.config.class = newClass;
    };

    return bsModalRef;
  }
```

Ideally, I should be able to do something like this:

```
<ng-template let-context #tpl>
{{context.name}}
</ng-template>
```

and then 

```
this._bsModalService.show(tpl, { ... context: {$implicit: {name: 'MyName'}});
```
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: latest

Angular: 5

Bootstrap: latest

### Build system: Angular CLI, System.js, webpack, starter seed:

webpack

**Comment by Domainv** [comment]
@cosminadrianpopescu ngx-bootstrap 3 should be used with angular 6,7

for angular 5 use ngx-bootstrap 2 please
