### ISSUE TITLE
Support Angular 8 beta

### ISSUE THREAD

**Issue by siimveskilt** [valor-software/ng2-bootstrap#5064]
### Feature request:

Make ngx-bootstrap compile with Angular 8 beta. Currently, timepicker's import causes an error:

ERROR in node_modules/ngx-bootstrap/timepicker/models/index.d.ts(3,22): error TS2307: Cannot find module '@angular/core/src/type'.

Should import from @angular/core, and not @angular/core/src/type.

### Versions of ngx-bootstrap, Angular:

ngx-bootstrap: 3.3.0

Angular: 8.0.0-beta.3

**Comment by iamjoshuabcxvii** [comment]
I have the same issue, has this been fixed already?.

**Comment by Domainv** [comment]
@iamjoshuabcxvii Yes, current issue was fixed.
Did you try 4.2.0 version?

**Comment by nitinjs** [comment]
I am facing the same issue,

how did you get rid of this issue??
