### ISSUE TITLE
Version 3.3.0 Is Breaking Angular Universal

### ISSUE THREAD

**Issue by omahjoub** [valor-software/ng2-bootstrap#5071]
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.3.0

Angular: 7.2.5

Bootstrap: 3.3.7

### Error:
Hi All,

I had this error on my server when i upgraded ngx-bootstrap from 3.2.0 to 3.3.0 an it's breaking all the SSR on Angular.

ERROR ReferenceError: window is not defined
    at new PositioningService

Every Thing Is Ok with version 3.2.0.

**Comment by Domainv** [comment]
@omahjoub checking

**Comment by SelimBhs** [comment]
check your lib ngx-bootstrap

**Comment by vibhor-vp** [comment]
Hi,

This issue is not fixed in version 3.3.0 rather it is fixed in version 4 and above. And using version 4 of ngx-bootstrap will require change in typescript versions and so on.
Can you help me with the solution?
I am using
Angular: 6.1.7,
Typescript: 2.7.2
