### ISSUE TITLE
The tooltip doesn`t work when the button is disabled

### ISSUE THREAD

**Issue by mcvova** [valor-software/ng2-bootstrap#5074]
The tooltip doesn`t work when the button is disabled:
https://stackblitz.com/edit/ngx-bootstrap-tooltip

But it works in the original Bootstrap:
https://getbootstrap.com/docs/4.3/components/tooltips/#disabled-elements

ngx-bootstrap: 3.3.0
Angular: 6.0.3
Bootstrap: 4.1.1

**Comment by ludmilanesvitiy** [comment]
@mcvova ![Peek 2019-03-19 17-352](https://user-images.githubusercontent.com/18209841/54620082-54bc5f00-4a6e-11e9-995a-b0a1dc2f73d7.gif)
Just added a disabled button to our demo, it works properly.

**Comment by CzechsMix** [comment]
Here's a stackblitz link where I'm not seeing it work

https://angular-iffl92.stackblitz.io/

Browser: Chrome Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by orkisz** [comment]
@ludmilanesvitiy 
Please read this article: https://jakearchibald.com/2017/events-and-disabled-form-fields/

Probably Chrome and many other browsers stop emitting **all** mouse events on disabled form fields, including buttons.
Unfortunately there is nothing you can do about it.

@CzechsMix, @mcvova 
Workaround:
`triggers="pointerenter:pointerout"`
Depending on content used inside button it may require to add `pointer-events: none;` in CSS for them.
Confirmed to work on:
* Chrome 73.0.3683.86 
* FF 66.0.2
* IE 11.285.17134.0
* Edge 42.17134.1.0

**Comment by orkisz** [comment]
Other way is to use class "disabled" of bootstrap and not to disable button at all. Check whether to invoke action or not can be done inside handler method

**Comment by marceloloureiro** [comment]
Workaround
- Wrap your button in a span tag.
- Put the tooltip in that span.

**Comment by IraErshova** [comment]
I'm closing the issue. Please use workarounds from messages above if you want to see tooltip for disabled buttons.

**Comment by a30001735** [comment]
> * 
> * Put the tooltip in that span.

This didnt work for me...   Is this what you meant?

`<span tooltip="some tip">
<button
              [disabled]="true"
              class="btn form-control btn-confirmation"
              type="submit"
              (click)="someclickevent()"
            >
              My Button
            </button>
</span>`

**Comment by Petya-Naumova-MM** [comment]
Not a good practice to use workaround for something so obviously needed as a tooltip for a disabled button.

**Comment by DmytrievA** [comment]
having same issue with pagination component: if previous/next button is disabled tolltip is not shown

**Comment by victor-0x29a** [comment]
Nothing worked for me
