### ISSUE TITLE
bug(rating): Rating component adds an extra star on mouse leave for decimal values

### ISSUE THREAD

**Issue by custompro12** [valor-software/ng2-bootstrap#5076]
### Bug description:
Binding a decimal value to the ngModel of a rating component will cause a star to be added to the component when the mouse leaves the component.

### Plunker/StackBlitz that reproduces the issue:
1) Load stackblitz
2) Observe component correctly shows 2 stars for input value 2.1
3) Mouse over the component
4) Stop mouse over the component
5) Observe component now incorrectly shows 3 stars

https://stackblitz.com/edit/angular-hj4tnx

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: "^3.3.0",

Angular: "^7.2.5"

Bootstrap: "^4.2.1"

### Build system: Angular CLI, System.js, webpack, starter seed:

Angular CLI

**Comment by daniloff200** [comment]
Yeah, that looks like, if you used a 2.1, it will round up to 3, or, if it's 1.9, then, to 2

We need to **Math.round(value)** here

**Comment by daniloff200** [comment]
so, for 2.1 it will be 2, but, for 2.5 -> 3
