### ISSUE TITLE
Tab is not a known element

### ISSUE THREAD

**Issue by ghost** [valor-software/ng2-bootstrap#5079]
### Bug description:

Tabs do not work when imported to shared module

### Plunker/StackBlitz that reproduces the issue:

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-goh43d

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.2.0

Angular: 7.2.0

Bootstrap: 3

**Comment by Provson** [comment]
Hi, add this in the sharedModule :

`exports: [TabsModule]`

**Comment by ludmilanesvitiy** [comment]
The solution from @Provson works properly, thanks.

**Comment by Arruls8** [comment]
> exports: [TabsModule]

Where to add this code!

**Comment by AruljothySundaramoorthy** [comment]
Still facing error even I added under the shared module.
