### ISSUE TITLE
Khronos locale error: please load locale: "target": "es6"

### ISSUE THREAD

**Issue by Domainv** [valor-software/ng2-bootstrap#5086]
![screen shot 2019-03-01 at 2 00 49 pm](https://user-images.githubusercontent.com/14885427/53636943-77efad80-3c2a-11e9-960d-672935b50be5.png)
![screen shot 2019-03-01 at 2 01 16 pm](https://user-images.githubusercontent.com/14885427/53636952-8211ac00-3c2a-11e9-9e3d-35c861c8ca37.png)

**Comment by Domainv** [comment]
@here @FrancescoBorzi @abhilashsandi @antonsimola @Hoakie

Please try the fix.
npm i ngx-bootstrap-ci@b38be856d9003bdb767cadbe778011d69791b2b6
mv node_modules/ngx-bootstrap-ci node_modules/ngx-bootstrap
tsconfig.json >> target = es6

**Comment by FrancescoBorzi** [comment]
@Domainv Thank you. Looks like it's working for me, at least I can confirm that I no longer get the compilation error reported in https://github.com/valor-software/ngx-bootstrap/issues/5068

I don't know about khronos locale error.

**Comment by roymilder** [comment]
@Domainv, I've encountered the same error. Followed your instructions above and can confirm it is working as expected. Thank you.

**Comment by jacques-hoventer** [comment]
> @here @FrancescoBorzi @abhilashsandi @antonsimola @Hoakie
> 
> Please try the fix.
> npm i ngx-bootstrap-ci@b38be856d9003bdb767cadbe778011d69791b2b6
> mv node_modules/ngx-bootstrap-ci node_modules/ngx-bootstrap
> tsconfig.json >> target = es6

Is targeting es6 a requirement for this fix?

**Comment by r-sw-eet** [comment]
didnt work for me :/

"target": "es2015", (also es6 with recompile did not work)
"ngx-bootstrap": "^5.3.2",
"@angular/common": "~8.1.0",

_edit:_ 
that worked though:
https://github.com/valor-software/ngx-bootstrap/issues/4752#issuecomment-466619227
