### ISSUE TITLE
Modal Module Default Configurations

### ISSUE THREAD

**Issue by cuneytbetik** [valor-software/ng2-bootstrap#5090]
Is there any option for default configurations. For example, igronebackdropclick always false, but i want to set it just one time to true. Otherway i must configurate all the modal show actions one by one.

**Comment by Totati** [comment]
I import the ModalModule in the SharedModule, and export it too.
In the constructor I configured the modal. Not as beautiful as using Injection token, but it works.
```javascript
export class SharedModule {
  constructor(private modalService: BsModalService) {
    this.modalService.config.class = 'modal-lg';
    this.modalService.config.ignoreBackdropClick = true;
  }
}
```

**Comment by mrjohnr** [comment]
your code is great,I done that inside AppComponent: 
```
export class AppComponent {
  constructor(private modalService: BsModalService) {

    this.modalService.config.ignoreBackdropClick = true;
....
  }
```

**Comment by dafi-dnv** [comment]
There is injection token.
```
import { MODAL_CONFIG_DEFAULT_OVERRIDE } from 'ngx-bootstrap/modal';
...
{
  provide: MODAL_CONFIG_DEFAULT_OVERRIDE,
  useValue: {
    backdrop: true,
    ignoreBackdropClick: true,
    keyboard: false
  }
}
```
