### ISSUE TITLE
我在你们的datepicker基础上改一个时间选择器

### ISSUE THREAD

**Issue by li10217** [valor-software/ng2-bootstrap#5093]
![image](https://user-images.githubusercontent.com/23067397/53947608-11becb00-4101-11e9-8892-f5289fcce863.png)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

**Comment by ludmilanesvitiy** [comment]
@li10217 There's no need to open an issue here if you want to ask a general question, use StackOverflow or Slack instead
To be clear, ask questions there in English, please.
https://stackoverflow.com/questions/tagged/ngx-bootstrap
https://ngx-home.slack.com/
