### ISSUE TITLE
Dynamic tabs: click in remove icon immediately delete tab.

### ISSUE THREAD

**Issue by jarekkowol** [valor-software/ng2-bootstrap#5096]
My goal is show confirm modal before remove tab.

I have handler:

```
  removeTabHandler(tab: any): void {
   // here is place when i need to fire confirmation modal.. 
    console.log('Remove Tab handler');
  }
```

But click in remove icon immediately delete tab. Any solution?

I try to use TabDirective as second parameter of this handler but unfortunately.

**Comment by ludmilanesvitiy** [comment]
@jarekkowol  There's no need to open an issue here if you want to ask a general question, use StackOverflow or Slack instead
https://stackoverflow.com/questions/tagged/ngx-bootstrap
https://ngx-home.slack.com/
