### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: Cannot find module './km-kh.js'

### ISSUE THREAD

**Issue by sokhomhuy** [valor-software/ng2-bootstrap#5103]
Hi I got this error when i try to use khmer language in my app. can any one help me
![image](https://user-images.githubusercontent.com/21234988/54252543-dba89d80-457d-11e9-9b75-892c6083952e.png)

**Comment by ludmilanesvitiy** [comment]
@sokhomhuy  There's no need to open an issue here if you want to ask a general question, use StackOverflow or Slack instead
https://stackoverflow.com/questions/tagged/ngx-bootstrap
https://ngx-home.slack.com/
