### ISSUE TITLE
Typeahead blocks the input if there isn't enough space for it

### ISSUE THREAD

**Issue by user753** [valor-software/ng2-bootstrap#5104]
https://valor-software.com/ngx-bootstrap/#/typeahead
You need to set 
```
.prettyprint {
  display: none
} 
```
so page would be shorter.
![typeahead](https://user-images.githubusercontent.com/35331542/54291879-50033100-45be-11e9-9c71-18facc752559.png)

**Comment by ludmilanesvitiy** [comment]
@user753 Could you be more specific? What version of ngx-bootstrap was used? what browser? what resolution? I can't reproduce this behaviour on latest development anymore.

**Comment by user753** [comment]
@ludmilanesvitiy Did you add `display: none` to `.prettyprint` class?
Open dev tool in any browser, select first code block in it add `display: none` to `.prettyprint` class, close dev tool and press `a` in first input.

**Comment by ludmilanesvitiy** [comment]
![Screenshot from 2019-03-19 15-53-44](https://user-images.githubusercontent.com/18209841/54611313-5fbbc300-4a5f-11e9-81ba-e08a36c67c81.png)
@user753 Looks like this behaviour fixed in the latest development

**Comment by ludmilanesvitiy** [comment]
//TODO Need to recheck issue after 4.0.0 release

**Comment by user753** [comment]
@ludmilanesvitiy Can you reproduce this bug on https://valor-software.com/ngx-bootstrap/#/typeahead
?

**Comment by ludmilanesvitiy** [comment]
![Screenshot from 2019-03-19 16-56-16](https://user-images.githubusercontent.com/18209841/54616134-ec6a7f00-4a67-11e9-94a5-ef87c31e6070.png)
Yes, I can. But behaviour of typeahead position was changed in the current milestone. That's why on local development it's not reproducible anymore.

**Comment by user753** [comment]
@ludmilanesvitiy Could you check in your version what happens if there isn't enough space below input? Would it still block the input?

**Comment by ludmilanesvitiy** [comment]
![Peek 2019-03-19 17-35](https://user-images.githubusercontent.com/18209841/54619595-897be680-4a6d-11e9-97da-15e20a472c8e.gif)

**Comment by ludmilanesvitiy** [comment]
@user753 WE've released 4.0.0. COuld you approve, that this issue had gone?

**Comment by user753** [comment]
@ludmilanesvitiy yes, thanks.

**Comment by oznu** [comment]
Strangely I encountered this issue when updating from 3.2.0 to 4.0.0 (also tried 4.0.1 from the `next` tag). I wasn't able to reproduce it in stackblitz so it might just be isolated to my environment.
