### ISSUE TITLE
Popover trigger open close functionality 

### ISSUE THREAD

**Issue by hellodpk** [valor-software/ng2-bootstrap#5107]
Hi,
I want the functionality like [outside-click](https://valor-software.com/ngx-bootstrap/#/popover#outside-click) . So that the popover opens and we can press button inside it. 

Now when using [Custom triggers](https://valor-software.com/ngx-bootstrap/#/popover#triggers-custom), popover opens as mouse enters the target element, but popover closes when I try to put cursor inside it for pressing button. 

So I want functionality like when I hover (only hover no click) on any button the popover opens and we can press button inside the popover.And when cursor is out of the popover or the button, popover should be closed.

Thanks for your support

Demo:

https://stackblitz.com/edit/angular-rw7ha8

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.3.0

Angular:6.10

Bootstrap:4

**Comment by hellodpk** [comment]
Hi any updates in this issue

**Comment by hellodpk** [comment]
HI,
I got some ideas for this solution in [stackoverflow](https://stackoverflow.com/a/48946394/3898339)

It helped me
Thanks

**Comment by ludmilanesvitiy** [comment]
Closed as a solved question.
