### ISSUE TITLE
datesDisabled not working

### ISSUE THREAD

**Issue by platzhersh** [valor-software/ng2-bootstrap#5118]
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.2.0

Angular: 7.2.9

Bootstrap: 3.3.7

### Build system: Angular CLI

The datesDisabled property of the bsConfig does not seem to work. No dates are getting disabled when I use it with a Date[] Array.

https://stackblitz.com/edit/ngx-bootstrap-wvmjcz

**Comment by ludmilanesvitiy** [comment]
@platzhersh Could you try this way, please: https://stackblitz.com/edit/angular-ngx-bootstrap-datepicker-datesdisabled ? It works.
In your stackblitz example I see old ngx-bootstrap version, but datesDisabled available only from 3.3.0 version, see changelog: https://github.com/valor-software/ngx-bootstrap/blob/development/CHANGELOG.md

**Comment by platzhersh** [comment]
Thank you! I wasn't aware that 3.3.0 is out! On npmjs it is still on 3.2.0.
Thanks a lot for pointing that out!

With 3.3.0 it is working fine!
