### ISSUE TITLE
Feature Request: Datepicker enabledDates

### ISSUE THREAD

**Issue by platzhersh** [valor-software/ng2-bootstrap#5121]
##Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.3.0

Angular: 7.2.9

Bootstrap: 3.3.7

Build system: Angular CLI

----------------------------------------------------------------------

I have some cases where I would like to use the opposite of `disabledDates`, namely `enabledDates`.

i.e. with a property like

    datesEnabled = [ new Date('2019-03-21'), new Date('2018-03-21') ]

The only dates that should still be enabled in the datepicker like this, should then be `2019-03-21` and `2018-03-21`.

An example for this use case is a date picker that lets you only select dates for which you have any documents (i.e. online banking).

https://stackoverflow.com/questions/55276897/allowing-only-specific-dates-in-datepicker/55279232?noredirect=1#comment97324592_55279232

**Comment by daniloff200** [comment]
Well
I used to work with disabledDates, let's see, what I can do with enabledDates :man_astronaut:
