### ISSUE TITLE
Change class to modal-xl

### ISSUE THREAD

**Issue by wilfriednhw** [valor-software/ng2-bootstrap#5136]
Hi, 
please is it possible to set class modal-xl for modal?

**Comment by fchiumeo** [comment]
[Optional sizes](https://valor-software.com/ngx-bootstrap/#/modals#directive-sizes)
[Сustom css class](https://valor-software.com/ngx-bootstrap/#/modals#service-custom-css-class)

**Comment by ludmilanesvitiy** [comment]
@wilfriednhw  There's no need to open an issue here if you want to ask a general question, use StackOverflow or Slack instead
https://stackoverflow.com/questions/tagged/ngx-bootstrap
https://ngx-home.slack.com/
