### ISSUE TITLE
Rating onMouseLeave not working with font-awesome stars

### ISSUE THREAD

**Issue by SnakeB** [valor-software/ng2-bootstrap#5141]
### Bug description:
I am using the rating component with the fontawesome stars as custom star layout. In Chrome when hovering over the stars and quickly pull the mouse off the component the hovered value is not cleared and it looks like all stars are selected. As far as i know this problem only appers with the Chrome browser. If i don´t use the fontawesome stars the bug does not occur. 
### Plunker/StackBlitz that reproduces the issue:
In the provided example you will find two rating elements the first one uses the fontawesome stars (this is the element where the bug occurs) and the second one uses the default implementation.
https://stackblitz.com/edit/chrome-hover-bug

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 4.0.1
Angular: 7.2.5
@fortawesome/angular-fontawesome: 0.3.0
@fortawesome/fontawesome-svg-core: 1.2.17
@fortawesome/free-regular-svg-icons": 5.8.1
@fortawesome/free-solid-svg-icons: 5.8.1

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLI

**Comment by valorkin** [comment]
thank for reporting this issues, just checked again your sample in chrome
can't reproduce so I assume it was fixed
