### ISSUE TITLE
Dropdown in modal issue

### ISSUE THREAD

**Issue by SERGEES** [valor-software/ng2-bootstrap#5144]
### Bug description
I have a dropdown with container="body" inside modal 
With the update to ngx-bootstrap@3.3.0 my dropdown opens behind modal

https://stackblitz.com/edit/angular-kvs2c3?file=src%2Fapp%2Fapp.component.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.3.0

Angular: ^6

Bootstrap: 3

**Comment by xaamin** [comment]
Fix it using css styles on your main saas file
```
bs-dropdown-container {
  z-index: 1060;;
}
```
