### ISSUE TITLE
Problem with datepicker after upgrade to 4.0.1

### ISSUE THREAD

**Issue by jarekkowol** [valor-software/ng2-bootstrap#5150]
### Bug description or feature request:

After upgrade ngx-bootstrap to 4.0.1 i getting error when serve or build:
I try to delete node_modules/. The same warning on local and CI server/

```
WARNING in ./node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.ngfactory.js
119:257-262 "export 'ɵt' (imported as 'i1') was not found in 'ngx-bootstrap/datepicker'

WARNING in ./node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.ngfactory.js
165:267-272 "export 'ɵt' (imported as 'i1') was not found in 'ngx-bootstrap/datepicker'

WARNING in ./src/app/app.module.ngfactory.js
194:6491-6519 "export 'BsDatepickerInlineConfig' (imported as 'i74') was not found in 'ngx-bootstrap/datepicker'

WARNING in ./src/app/app.module.ngfactory.js
194:6521-6549 "export 'BsDatepickerInlineConfig' (imported as 'i74') was not found in 'ngx-bootstrap/datepicker'

WARNING in ./node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.ngfactory.js
211:262-267 "export 'ɵt' (imported as 'i1') was not found in 'ngx-bootstrap/datepicker'

WARNING in ./node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.ngfactory.js
38:1184-1189 "export 'ɵt' (imported as 'i1') was not found in 'ngx-bootstrap/datepicker'

WARNING in ./node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.ngfactory.js
38:1412-1417 "export 'ɵt' (imported as 'i1') was not found in 'ngx-bootstrap/datepicker'

WARNING in ./node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.ngfactory.js
38:1636-1641 "export 'ɵt' (imported as 'i1') was not found in 'ngx-bootstrap/datepicker'

WARNING in ./node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.ngfactory.js
38:71-76 "export 'ɵt' (imported as 'i1') was not found in 'ngx-bootstrap/datepicker'

WARNING in ./node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.ngfactory.js
731:192-197 "export 'ɵt' (imported as 'i1') was not found in 'ngx-bootstrap/datepicker'

WARNING in ./node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.ngfactory.js
732:74-79 "export 'ɵt' (imported as 'i1') was not found in 'ngx-bootstrap/datepicker'
```

### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 4.0.1
Bootstrap: 4.3.1

Angular CLI: 7.3.8
Node: 9.6.1
OS: darwin x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      6.4.7
@angular/cli                      7.3.8
@angular/material                 6.4.7
@ngtools/webpack                  6.0.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.8.3

**Comment by Domainv** [comment]
@jarekkowol Provide repo of reproduction, please

**Comment by ludmilanesvitiy** [comment]
Closed due to the inability to reproduce issue.
