### ISSUE TITLE
Inline Datepicker strange behavior with minMode='year'

### ISSUE THREAD

**Issue by livthomas** [valor-software/ng2-bootstrap#5154]
### Bug description:

If you try to use Inline Datepicker with view mode (`minMode` property) set to `year`, it has really strange behavior. When you click on a year, the whole list of years is suddenly reordered and none of the years is selected.

I would expect at least to have the selected year highlighted. It would also be nice if the list of years was not reordered because it confuses users and they can accidentally click on a wrong year if they do not spot this reordering and are about to change their selection.

### StackBlitz that reproduces the issue:
https://stackblitz.com/edit/ngx-bootstrap-inline-datepicker-year

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 4.0.1
Angular: 7.2.5
Bootstrap: 4.3.1

**Comment by livthomas** [comment]
@ludmilanesvitiy Are there any plans to fix this bug?

**Comment by ludmilanesvitiy** [comment]
@livthomas I agree, that this is an important fix, but now we're working on adding animations to the components. If you have ideas about how to fix it - don't hesitate to contribute - it'll be super awesome)

**Comment by daniloff200** [comment]
closed via #5346
