### ISSUE TITLE
Prefix for typeahead !

### ISSUE THREAD

**Issue by piernik** [valor-software/ng2-bootstrap#5155]
For me it's a bug.
You are not using prefixes in whole project so I have directive conflict.
In `typeahead` component You are using `<input [(ngModel)]="selected"
       [typeahead]="states"
       adaptivePosition="true"
       class="form-control">` without any prefix.

Problem is that other library `ng-select` also uses `typeahead` directive: https://ng-select.github.io/ng-select#/filter. So I have conflict.

How can I solve it?

Edit: I did it creating my own module which not imports `ng-Select`.
But I do think that using prefixes is good practice.

**Comment by g3344** [comment]
@piernik  Any chance you would mind showing how you did your workaround?  Thanks!

**Comment by IraErshova** [comment]
@piernik Hi! Thanks for your comment. We are sorry that you have such type of problem, but we are not planning to add prefixes at this stage. The lack of prefixes was an omission at the stage of creating the library. And because many people use it we can't do such change.

**Comment by Juliete** [comment]
I solved it by declaring the ng-select as ViewChild in the component and setting its typeahead property there
