### ISSUE TITLE
Timepicker: With min it doesn't validate when typing in minutes or hours by keyboard

### ISSUE THREAD

**Issue by probfacile** [valor-software/ng2-bootstrap#5158]
### Bug description or feature request:
Setting a minimun date for timepicker, you get wrong validation when typing in hour or minute by keyboard instead using arrows.
To reproduce:

- open the example, it will have current date.
- arrow keys down will be disabled
- arrow keys up will get forward in time
- in any valid time adjust minutes to a valid minute by selecting and typing in minutes by keyboard
- It will not validate

### StackBlitz that reproduces the issue:
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-mbh4jd?file=app%2Fapp.component.html

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: ^3.3.0

Angular: ^6.1.10

Bootstrap: ^4.3.1

### Build system: Angular CLI, System.js, webpack, starter seed:
Stackblitz

**Comment by ludmilanesvitiy** [comment]
@probfacile Could you update the version of ngx-bootstrap to the latest? 4.0.0 as a minimum? This issue is fixed already.
![Peek 2019-04-10 15-07](https://user-images.githubusercontent.com/18209841/55877350-7a86e080-5ba2-11e9-9844-6f40e8d604b3.gif)

**Comment by probfacile** [comment]
The problem is that 4.0.0 requires to upgrade to angular 7.0.0 i was not planning this update for now and move to 8.0.0 next month... 
Why you didn't mantain and backport to version 3.3 ?

**Comment by ludmilanesvitiy** [comment]
As a temporary solution, you can fork ngx-bootstrap, change this line: https://github.com/valor-software/ngx-bootstrap/commit/8a4456b#diff-077e5c1aa694c8b9aead5432afafa3caR181 and reuse fork. After updating your app to the higher angular, you'll just back to ngx-bootstrap origin repo.
