### ISSUE TITLE
Spam - No Unsubcribe

### ISSUE THREAD

**Issue by cphillips83** [valor-software/ng2-bootstrap#5159]
Why am I constantly receiving spam from your marketing team with no way of unsubscribing. 

- I never heard of you
- Never signed up to receive any emails
- We don't even use this tech stack

```
Hi Chris,
I’m writing to follow up on my email. I didn’t hear back from anyone on the team. If it makes sense to talk, let me know how your calendar looks.

If not, who is the appropriate person for me to talk to?

Thanks for your help.

Kind regards,
Vadym Bondar

  | Vadym BondarVP Salesmail: vadym.bondar@valor-software.comskype: vadym.bondvalor-software.com | Vadym BondarVP Sales |   |   |   |  
-- | -- | -- | -- | -- | -- | --
Vadym BondarVP Sales |  
  |   |  



```

Dump of the email https://gist.github.com/cphillips83/f26ebafabb85aa8c2a66dba479f4287e

**Comment by ludmilanesvitiy** [comment]
Please, contact a person directly. This is not related to the ngx-bootstrap library. Thanks.

**Comment by valorkin** [comment]
Sorry about it, reported to sales team
