### ISSUE TITLE
Problems with opening modal

### ISSUE THREAD

**Issue by dejooo13** [valor-software/ng2-bootstrap#5162]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://join.slack.com/t/ngx-home/shared_invite/enQtNTExMTY5MzcwMTM0LWQ5M2Y4OWM0OGJjNmZiOGYyNjFlZTdlOGI1YjcxYWQ2ODhiOTY4NzhiODgwMTIzNDczODIyNWNmM2RlYWRhNTg) instead

### Bug description or feature request:

I have modal for reseting password, after ajax success i want to close that modal and open next in which you should type new password. This is the part of doing that functionality:

    this.firstModalSubsc = this.modRefEfe.closeFirstModal.subscribe(val => {
      this.modalRef.hide();
      this.modalRef = null;

// it breaks here when i try to opet new one
      this.modalRef2 = this.modalService.show(val, {
        class: 'second customModal'
      });
  });

and i get two errors: 
- ERROR TypeError: Cannot read property 'createText' of null
    at ComponentLoader.push../node_modules/ngx-bootstrap/component-loader/fesm5/ngx-bootstrap-component-loader.js.ComponentLoader._getContentRef
- ERROR TypeError: Cannot set property 'level' of undefined

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:
3.2
Angular:
7
Bootstrap:
4.3

**Comment by ludmilanesvitiy** [comment]
@dejooo13 Hi! Please, create a reproduction on StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by ludmilanesvitiy** [comment]
CLosed due to not enough information for reproduce.

**Comment by mgoodnight** [comment]
Ran into this issue and was following a similar pattern as OP (trying to invoke visibility of modal via modal ref and modal service). Fixed by wrapping my markup in `ng-template` (modal expects TemplateRefs).
