### ISSUE TITLE
Modal-open class is not removed on clicking browser back button 

### ISSUE THREAD

**Issue by babupca** [valor-software/ng2-bootstrap#5164]
Dear Valor Team,

**Versions of ngx-bootstrap, Angular, and Bootstrap:**
ngx-bootstrap: 4.1.1
Angular: 7.0.2
Bootstrap: 4

**Issue Description**
I have requirement to close the modal on clicking the browser back button. I could able to close the modal, but it is not working properly

I have provided an example in that (linka, linkb, linkc) and logout will be available. 
**Steps to reproduce the issue**
1. Open the stackblitz url
2. You are currently at 'linkb' page
3. click on the 'logout' link, logout modal is opened
4. Now without closing the logout modal, click the browser back button
5. Now the Modal is closed
6. Now press the F12 and see the chrome developer tool bar under element tab, 'modal-open' class still available at the body tag

The class 'modal-open' added to the body tag is not removed properly and because of this scroll bar in the page is hidden. 

**Stackblitz Link**
https://angular-ngx-bootrap-modal-example-babu.stackblitz.io/ 

![image](https://user-images.githubusercontent.com/2504343/56088029-938adc80-5e95-11e9-9e53-3fc8dcb196ce.png)

Currently I had added a below solution, where i manually remove the class from the app.component for now. But would you please suggest a proper solution to resolve this error please.

```
>  constructor (
>     private bsModalService:BsModalService,
>     private location: PlatformLocation,
>     @Inject(DOCUMENT) private document: Document,
>     private renderer: Renderer2) {    
>     location.onPopState(() => {
>     console.log("called");   
>     this.bsModalService.hide(1);
>     this.renderer.removeClass(this.document.body, 'modal-open');
>   }
> 
```

Thank You

**Comment by IraErshova** [comment]
@babupca Hi! Unfortunately, I can't open your example. Could you please fix this? I created my own one using angular Tour of heroes, just added modal to dashboard component. But if you try to switch between routes, then open the modal and click back, you see that the modal will be always opened. (**important**: use stackblitz example by opening it via app url)

Here is my example:

https://stackblitz.com/edit/angular-gq6zyf-dgedrn

**Comment by IraErshova** [comment]
Close issue because of inactivity

**Comment by jibranahsan** [comment]
In you submit button or which ever button/selection that moves you to another page, just have data-dismiss="modal" and that should take care of the back drop. It is just telling to dismiss the modal when you have made your selection.
