### ISSUE TITLE
hmr error: Uncaught TypeError: Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by MaoScut** [valor-software/ng2-bootstrap#5165]
### Bug description:
when open a modal and emit hmr, this error appears: 
`zone.js:199 Uncaught TypeError: Cannot read property 'removeChild' of null
    at ComponentLoader.push../node_modules/ngx-bootstrap/component-loader/fesm5/ngx-bootstrap-component-loader.js.ComponentLoader.hide (ngx-bootstrap-component-loader.js:219)
    at BsModalService.push../node_modules/ngx-bootstrap/modal/fesm5/ngx-bootstrap-modal.js.BsModalService.removeBackdrop (ngx-bootstrap-modal.js:1087)
    at ngx-bootstrap-modal.js:1009
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:498)
    at ZoneTask.invoke (zone.js:487)
    at timer (zone.js:2281)`

### step to reproduces the issue:
Here is my simple app. It is generated by angular-cli and the  the hmr is configed accroding this wiki: [https://github.com/angular/angular-cli/wiki/stories-configure-hmr](url)
1. git clone https://github.com/MaoScut/ngx-bootstrap-hmr-error.git
1. cd ngx-bootstrap-hmr-error
1. npm i
1. npm run start:hmr
1. open the browser with localhost:4200
1. click the button on page, it will show a modal
1. change code in src\app\modal-content.component.ts and save to emit hmr
1. open the browser console, you will see the error

I also notice the comment in file src\environments\environment.ts. it says importing 'zone.js/dist/zone-error' will ignore zone error. I add this import statement to src\environments\environment.hmr.ts, but the error still appears.

What am I getting wrong? How to solve this error?
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 4.0.1

Angular: 7.2.0

Bootstrap: 4.2.1

**Comment by babupca** [comment]
@MaoScut , The only difference which i see in your code is the entry level addition. As per my understanding it is not required, angular will do it as per this link below. Just try remove this and see please.
please refer -> https://angular.io/guide/entry-components

**Comment by MaoScut** [comment]
> @MaoScut , The only difference which i see in your code is the entry level addition. As per my understanding it is not required, angular will do it as per this link below. Just try remove this and see please.
> please refer -> https://angular.io/guide/entry-components

Thank you for your replay. Unfortunately, it doesn't work. 
Removing the pop component from the entryComponents in app.module.ts case error 'No component factory found for ModalContentComponent.'. ModalContentComponent is added to view dynamically, so it must be added to the entryComponent array.

**Comment by MaoScut** [comment]
This error occur frequently while developing component with module 'ngx-bootstrap/modal', I am confused that why is there no related discussion.

**Comment by loutocky** [comment]
+1

**Comment by IraErshova** [comment]
@MaoScut Hi! I couldn't start your repo locally, but I could do this in stackblitz. Could you check it, please?

Here is your app - https://stackblitz.com/edit/github-xm6ozh

I didn't understand the **step 7**. Could you explain it to me, please? And is it possible to reproduce this issue in stackblitz?

**Comment by IraErshova** [comment]
@MaoScut Also I want to add information about **entryComponents** error. It happens not because of 'ngx-bootstrap/modal' but because of Angular works in this way. Do you know why we have to add a component to **entryComponents** when we want to use it for modal? See how it's explained in Angular Doc:

`If a component isn't found in a template, the tree shaker will throw it away`

So if you don't add this component to **entryComponents**, during the compilation it will be thrown away. 

For more information you can check official documentation:
https://angular.io/guide/entry-components

**Comment by IraErshova** [comment]
Close issue because of inactivity
