### ISSUE TITLE
Can't highlight selected month in min-mode

### ISSUE THREAD

**Issue by arjunkgit** [valor-software/ng2-bootstrap#5166]
I'm trying to highlight selected month using ngx-bootstrap with min-mode.
In datepicker we can highlight like [this](https://i.stack.imgur.com/jd8kM.jpg).

In a same manner I want to highlight in ngx-bootstrap like [this](https://i.stack.imgur.com/oR8kq.jpg)

stackblits example : https://stackblitz.com/edit/angular-jcbl4o

I have tried a lot to highlight selected month but nothing seems working. 
I feel it's something fairly simple with config.

**Comment by ludmilanesvitiy** [comment]
Related to https://github.com/valor-software/ngx-bootstrap/issues/5154
Same issue, but with min-mode: month

**Comment by arjunkgit** [comment]
For those who looking for temporary solution to highlight the selected month :

`    setTimeout(function () {
      $('.months > tbody  > tr > td > span').each(function () {
        if (this.innerText == tempMonth) {
          this.style.backgroundColor = "#008ECF";
          this.style.border = "1px solid #008ECF";
        } else {
          this.style.backgroundColor = "transparent";
        }
      });
    }, 0);`

But I'm still looking for the permanent fix for this issue.

**Comment by daniloff200** [comment]
looks like, was fixed long time ago, and available  from 5.4.0
