### ISSUE TITLE
angular error in latest release 4.1.1

### ISSUE THREAD

**Issue by dolphinsd** [valor-software/ng2-bootstrap#5175]
Upgraded to latest release 4.1.1 and now get this errors. See image.

Going back to 4.0.1 and error goes away.

![06691d9a3c939b268b67cdf28330a310](https://user-images.githubusercontent.com/3460517/56537224-da6f7680-6514-11e9-94b1-61f7190c8e41.png)

**Comment by Domainv** [comment]
@dolphinsd Could you provide repo of reproduction?

**Comment by arthurfrancioni** [comment]
Hello,

I have the same error.

Repo of reproduction: https://stackblitz.com/edit/angular-nynxlp

**Comment by johaven** [comment]
Same error reported above and since 4.1.1

**Comment by jurt** [comment]
Same issue, happening only when menu item of dropdown contains routerLink to another view.
