### ISSUE TITLE
popover(Positioning) - computeAutoPlacement with flip being called when I have placement=bottom for popover

### ISSUE THREAD

**Issue by bharatn** [valor-software/ng2-bootstrap#5181]
Using ver 3.3.0 or 4.0.1

Looking at positioning code - for popover in this case 

function (hostElement, targetElement, position, appendToBody) {
        var /** @type {?} */ chainOfModifiers = [flip, shift, preventOverflow, arrow];
        return chainOfModifiers.reduce(function (modifiedData, modifier) { return modifier(modifiedData); }, initData(targetElement, hostElement, position));
    };

I see flip being called when I have placement='bottom'

Shouldnt it just not call the flip for this setting?

Also I see the popover flipping up and down as I click on rows in my grid depending on space available - so Its not expected behavior.

I got the latest version 4.0.1 and same issue. Webpack is picking up 

function (hostElement, targetElement, position, appendToBody, options) {
        /** @type {?} */
        var chainOfModifiers = [flip, shift, preventOverflow, arrow];
        return chainOfModifiers.reduce(function (modifiedData, modifier) { return modifier(modifiedData); }, initData(targetElement, hostElement, position, options));
    };

**Comment by Domainv** [comment]
It's expected behavior. Works as in a bootstrap
Some position by default but if don't have enough space switched to auto.
soon be added option for disabling of adaptive position for popover
