### ISSUE TITLE
Where can I find unit tests for some of the components?

### ISSUE THREAD

**Issue by codeepic** [valor-software/ng2-bootstrap#5186]
As in the title, I am most interested in finding unit tests for the popover functionality.

**Comment by ludmilanesvitiy** [comment]
@codeepic Hi! For such questions, use [slack channel](https://join.slack.com/t/ngx-home/shared_invite/enQtNTExMTY5MzcwMTM0LWQ5M2Y4OWM0OGJjNmZiOGYyNjFlZTdlOGI1YjcxYWQ2ODhiOTY4NzhiODgwMTIzNDczODIyNWNmM2RlYWRhNTg), pls.
https://github.com/valor-software/ngx-bootstrap/blob/development/src/spec/ng-bootstrap/popover.spec.ts - this is unit test for popover
