### ISSUE TITLE
accordion Error: Can't bind to 'isAnimated' since it isn't a known property of 'accordion'

### ISSUE THREAD

**Issue by germangc125** [valor-software/ng2-bootstrap#5188]
### ERROR ACCORDION

I have installed 

   "ngx-bootstrap": "^4.1.1",

and when implementing the accordion i get an error:

Uncaught Error: Template parse errors:
Can't bind to 'isAnimated' since it isn't a known property of 'accordion'. 

AppModule:

import { AccordionModule } from 'ngx-bootstrap/accordion';

 imports: [
   AccordionModule.forRoot()
  ],

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 4.1

Angular: 7.2

Bootstrap: 4.3

### Build system: Angular CLI, System.js, webpack, starter seed:

ClI: 7.2

**Comment by germangc125** [comment]
Lo solucione instalando la version "ngx-bootstrap": "^4.2.0" que no se instala con el npm (el npm solo instala la 4.1), para forzar la instalacion borre la carpeta node_modules , cambie la version en el package.json a la 4.2.0 e hice el npm install, y solucionado, 
La version 4.1 no tiene el atributo isAnimated .

**Comment by klevismino** [comment]
Or just run 
`npm i ngx-bootstrap@4.2.0`

**Comment by germangc125** [comment]
Es verdad gracias!

**Comment by germangc125** [comment]
> Or just run
> `npm i ngx-bootstrap@4.2.0`

Es verdad gracias!
