### ISSUE TITLE
[question] snyk detect XSS

### ISSUE THREAD

**Issue by xk4r00t** [valor-software/ng2-bootstrap#5190]
```
Medium severity vulnerability found in ngx-bootstrap
  Description: Cross-site Scripting (XSS)
  Info: https://snyk.io/vuln/SNYK-JS-NGXBOOTSTRAP-174319
  Introduced through: ngx-bootstrap@4.1.1
  From: ngx-bootstrap@4.1.1
```
https://snyk.io/vuln/SNYK-JS-NGXBOOTSTRAP-174319

Hello,

I upgraded from 2.x to 4.x version today but the snyk vulnerability checker do not stop to show this vulnerability.

All my data are sanitized from back-end responses but could you add some global fix about this issue in the next release ?

May be this is related : 
https://github.com/valor-software/ngx-bootstrap/pull/4827

Regards,

Thomas

**Comment by rits-development** [comment]
Is this issue on any roadmap to get fixed?

**Comment by valorkin** [comment]
yes related, closing as sublicate. just in case, UI lib is worst place to enforce XSS. this is should be a responsibility of data providers
