### ISSUE TITLE
Date time picker - Close the main popper content on date selection

### ISSUE THREAD

**Issue by ayush1329** [valor-software/ng2-bootstrap#5192]
We have use the ngx datetime picker inside the popper container. Once we select the date from datetimepicker its close the main popper container.

<popper-content #settingPopupContent>
<div class="form-group">
            <div class="input-group">
              <input id="txt-from-date" name="fromDate" class="form-control" [(ngModel)]="fromDate"
                bsDatepicker #val="bsDatepicker" (bsValueChange)="onDateChanged($event)"
                [bsConfig]="bsConfig">
             </div>
</div>
</popper-content>

**Comment by Domainv** [comment]
There's no need to open an issue here if you want to ask a general question.
Use <a href="https://stackoverflow.com/questions/tagged/ngx-bootstrap">StackOverflow</a> instead

**Comment by ludmilanesvitiy** [comment]
Closed due to not enough information
