### ISSUE TITLE
Convert an input in format 'DD-MM-YYYY' to 'DD-MMM-YYYY'

### ISSUE THREAD

**Issue by ngocngoan** [valor-software/ng2-bootstrap#5197]
My input needs to accept 2 formats 'DD-MM-YYYY' and 'DD-MMM-YYYY'. While I want bs-bootstrap to accept the format 'DD-MMM-YYYY' by setting. So, how do I convert the input in format 'DD-MM-YYYY' to 'DD-MMM-YYYY'?

**Comment by ludmilanesvitiy** [comment]
@ngocngoan https://valor-software.com/ngx-bootstrap/#/datepicker#format - this is an example
There's no need to open an issue here if you want to ask a general question.
Use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) instead or [Slack](https://join.slack.com/t/ngx-home/shared_invite/enQtNTExMTY5MzcwMTM0LWQ5M2Y4OWM0OGJjNmZiOGYyNjFlZTdlOGI1YjcxYWQ2ODhiOTY4NzhiODgwMTIzNDczODIyNWNmM2RlYWRhNTg)
