### ISSUE TITLE
Tooltip placement right position failure

### ISSUE THREAD

**Issue by jredd** [valor-software/ng2-bootstrap#5200]
`###` Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 3.3+
Angular: 7.2
Bootstrap:4.3.1
### Build system: Angular CLI
I wasn't able to figure out how to get links to share properly but this should be simple enough. since version 3.3+ of ngx tooltips seem to not be able to break out of their parent container when using the ng-template or I guess when there is more complicated nesting going on. This has been driving me crazy the last few days, I finally just downgraded to 3.2.0, which works fine and wanted to let you guys know this is an issue with the tooltips.

```
<div style="width: 220px;background:lightblue; height: 100px; overflow-y: scroll;">
  <div style="background:violet;">
    <div style="width: 200px; background:orange;height:200px;">
      <div>
        <div id='segments'>
          <div>
            <div
          [tooltip]="panelNavToolTip"
                placement="right"
                container="body"
          >Hello!</div>
        </div>
          </div>
      </div>
    </div>
  </div>
</div>

<ng-template #panelNavToolTip>
  Here is some content information
</ng-template>
```

**Comment by Domainv** [comment]
@jredd In next release will be added adaptivePosition option to tooltip.
[adaptivePosition]="false" will help you
