### ISSUE TITLE
Carousel: Reset time-out when clicking on arrow or the bottom indicators

### ISSUE THREAD

**Issue by brechtb86** [valor-software/ng2-bootstrap#5201]
I noticed that if you click one of the arrows of indicators, the timout for the next slide isn't reset. The problem with this is that if there is a time-out of 10 seconds, and you click the arrow after 9 seconds, you only see the this slide for 1 second and then it immediatly goes to the next slide.

Can you provide a fix for it?

**Comment by ludmilanesvitiy** [comment]
Duplicate of #4853

**Comment by gioboa** [comment]
Hi @ludmilanesvitiy I have the same problem.
Can I send a PR for it? :+1:

**Comment by ludmilanesvitiy** [comment]
@gioboa Hi! Sure, please do!

**Comment by Domainv** [comment]
Closes as duplicate of #4853
