### ISSUE TITLE
Animated accordion doesn't resize group height if content height changes

### ISSUE THREAD

**Issue by greg73** [valor-software/ng2-bootstrap#5202]
### Bug description or feature request:

When `isAnimated` is set to true, after opening an accordion group, the height does not change if the content height changes. With `isAnimated` set to false, this works as expected

### Plunker/StackBlitz that reproduces the issue:
[https://stackblitz.com/edit/angular-wc8qhb](https://stackblitz.com/edit/angular-wc8qhb)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 4.2.0

Angular: 7.2.15

Bootstrap: 4.0.0

### Build system: Angular CLI, System.js, webpack, starter seed:

Angular CLI

**Comment by pzontrop** [comment]
same happens with the collapse component when isAnimated is true.

**Comment by taimursaeed** [comment]
has anyone found any fix for this?

**Comment by psalkowski** [comment]
Same here on collapse component. In my case there is a bit more complex problem.

I have a page with list of categories. It's collapse component on mobile. On dekstop is always expanded (I change [collapse] to false during window resize). When user collapse component on mobile, then resize window, the component expands and have correct height. But when I update list of categories (i.e via route to another page based on the same layout), the component has previous height, doesn't matter if there is more or less items. The bigger problem is - I didn't see any special CSS'es attached to it.

**Comment by vuhi** [comment]
I have the same issue when [isAnimate]=true. Accordion body is no responsive with the content inside. Update to 5.1.1 fix the problem. Thanks. However, I still wonder why the component does not show any css? Is it an intended purpose?

**Comment by Domainv** [comment]
@vuhi try 5.1.1 version

**Comment by carrillocarlosce** [comment]
I was using the 4.2.0 version of ngx-bootstrap and I was having this issue, I just updated it to 5.5.0 and its working as expected with isAnimated set to true

**Comment by paulinak-dev** [comment]
Not working on [IE], checked on demo page.
After shrinking, the text is wrapped but the height is not adjusted. When wrapped to 3 lines, the last one completely disappears under next groups heading.
Toggling the group fixes the problem, but then again, when expanded, the height is not recalculated and empty space appears under the text.
