### ISSUE TITLE
Popover not working when added through innerHtml 

### ISSUE THREAD

**Issue by akvaliya** [valor-software/ng2-bootstrap#5203]
### Bug description or feature request:
I have a dynamic grid component in which i add html dynamically based on some conditions.

I create html from component side & add to html through `innerHtml`. When i add popover `div` through `innerHtml`, popover is not working. What am i missing here?

### Plunker/StackBlitz that reproduces the issue:
[https://stackblitz.com/edit/angular-cq9cp9](https://stackblitz.com/edit/angular-cq9cp9)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 4.1.1

Angular: 7.2.5

Bootstrap: 4.0.0

**Comment by ludmilanesvitiy** [comment]
@akvaliya Hi. Take a look at this example: https://valor-software.com/ngx-bootstrap/#/popover#dynamic-html
There's no need to open an issue here if you want to ask a general question.
Use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) instead or [Slack](https://join.slack.com/t/ngx-home/shared_invite/enQtNTExMTY5MzcwMTM0LWQ5M2Y4OWM0OGJjNmZiOGYyNjFlZTdlOGI1YjcxYWQ2ODhiOTY4NzhiODgwMTIzNDczODIyNWNmM2RlYWRhNTg)

**Comment by glukki** [comment]
@ludmilanesvitiy unfortunately, this example doesn't solve the issue, but thank you for pointing to SO and Slack

**Comment by agiagoulas** [comment]
@glukki Did you solve your issue? I have the same problem.
