### ISSUE TITLE
DatePicker display 'value' not updated when same date is selected again

### ISSUE THREAD

**Issue by masoomar** [valor-software/ng2-bootstrap#5209]
### Bug description or feature request:
I want to display 'Today' string instead of the date, when current date is selected.
I am using value property to display either 'Today' if current date is selected or display date if any other date is selected other than current date.

When you select current date the first time, the value in the input box updates to 'Today' which is expected. However if you re-select current date again, it doesn't display 'Today' but instead just displays the date.  Please see the StackBlitz example below to reproduce the issue.

Expected: 
Datepicker input should update value when same date is selected again.

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-datepicker-mbae2d?file=app%2Fapp.component.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular: 5

Bootstrap: 3.3.7

**Comment by sbvkrishna** [comment]
I would like to take on this issue. It will be my first contribution here.

**Comment by max-arias** [comment]
@ludmilanesvitiy  Hey, is this up for grabs? I can look into this
