### ISSUE TITLE
Datepicker - day and calendar custom class example

### ISSUE THREAD

**Issue by jbacalo** [valor-software/ng2-bootstrap#5213]
Hi,
Is there a way to fully template the days in the datepicker? 
Also is there a way to customize the template of the header of the date picker?

I can't an example for those(The links in the website are not working or leading to non working stackblitz/plunker).

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 4.1.1

Angular: 6

Bootstrap: 4

Build system: Angular CLI

**Comment by Domainv** [comment]
@jbacalo Already merged possibility to add a custom class to each day #5036
Soon be released. Also, you can globally style datepicker

**Comment by ludmilanesvitiy** [comment]
@jbacalo Take a look at official example: https://valor-software.com/ngx-bootstrap/#/datepicker#date-custom-classes
