### ISSUE TITLE
 ngx-carousel multilist don't work

### ISSUE THREAD

**Issue by giovannidias1** [valor-software/ng2-bootstrap#5215]
### Bug description or feature request:

I'm trying to use the carousel multilist exactly as in the example it raises the following error
```
Error in /turbo_modules/@angular/compiler@7.2.5/bundles/compiler.umd.js (2496:21)
Template parse errors:
Can't bind to 'itemsPerSlide' since it isn't a known property of 'carousel'. ("<carousel [ERROR ->][itemsPerSlide]="itemsPerSlide"
[singleSlideOffset]="singleSlideOffset"
[noWrap"): ng:///AppModule/DemoCarouselMultilistComponent.html@0:10
Can't bind to 'singleSlideOffset' since it isn't a known property of 'carousel'. ("<carousel [itemsPerSlide]="itemsPerSlide"
[ERROR ->][singleSlideOffset]="singleSlideOffset"
[noWrap]="!noWrap"
[interval]="false"
"): ng:///AppModule/DemoCarouselMultilistComponent.html@1:10
Can't bind to 'startFromIndex' since it isn't a known property of 'carousel'. ("
[noWrap]="!noWrap"
[interval]="false"
[ERROR ->][startFromIndex]="5"
(slideRangeChange)="onSlideRangeChange($event)">
<slide *ngFor="le"): ng:///AppModule/DemoCarouselMultilistComponent.html@4:10
```

### Plunker/StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-45bxzs

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 4.1.1

Angular: 7.2.9

Bootstrap: 4.2.1

### Build system: Angular CLI, System.js, webpack, starter seed:
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              7.3.6
@angular-devkit/schematics        7.3.6
@angular/cli                      7.3.6
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

**Comment by giovannidias1** [comment]
The problem is that `npm` was installing version 4.1.1 I put the command determining the version and it worked.

the command:

`npm ngx-bootstrap@4.2.0 --save`

**Comment by vikasprashar99** [comment]
> The problem is that `npm` was installing version 4.1.1 I put the command determining the version and it worked.
> 
> the command:
> 
> `npm ngx-bootstrap@4.2.0 --save`

It's not working in my case

**Comment by aniruddhadas9** [comment]
I am using `"ngx-bootstrap": "5.6.1",` and its not working, its only showing the first image in the slide and rest are blank
