### ISSUE TITLE
Tooltip stay on the left top corner when spam click

### ISSUE THREAD

**Issue by batgos** [valor-software/ng2-bootstrap#5217]
### Bug description or feature request:
Hello,
I have the same problem as this issue but it's closed so i don't know if i should do a new post https://github.com/valor-software/ngx-bootstrap/issues/4300#issuecomment-424731958
When trigger elements is clicked within the delay time and destroy the tooltip appears and stay at the top left corner.
If no delay and we spam click the toolip will appears quickly at the corner but disappear directly after.
Do someone have a solution or fix ?

Here is the exemple : https://stackblitz.com/edit/angular-fbpddy
Edit : Sorry for bad quality expemple
You just have to open the dropdown and spam click the info icon of the top, you will see the tooltip element stay in the body

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.2.0
Angular: 6

**Comment by batgos** [comment]
Here is the exemple : https://stackblitz.com/edit/angular-fbpddy
Sorry for the bad quality of it, I will improve it if necessary
Just spam click on the info icone and you will see the duplication of the tooltip

**Comment by batgos** [comment]
Do someone have an idea pls ?

**Comment by reimavronicolas** [comment]
Here's a workaround for the use case where clicking on the element (with the tooltip) hides it, and the tooltip still appears in the top left corner of the window (after the delay). 

You can utilise the `triggers` attribute to dismiss the tooltip on click: `triggers="mouseenter:click mouseenter:mouseleave"`

Example:
https://stackblitz.com/edit/angular-tirenu?file=src%2Fapp%2Fapp.component.html

**Comment by kambbado** [comment]
Has anyone been able to resolve this issue? I tried adding the triggers suggested above, but all it does is display all tool-tips within the page as I hover.  I'm using the 5.3.2 version.  If I change the triggers to just `mouseenter:mouseleave`, it returns to the randomly placing the tool-tip on the top left, on some occasions I have multiple tool-tips.  I have been thinking of creating some function to remove the any `<bs-tooltip-container>` from the page on every module load, I'm sure if it;s even possible.  Would lazy load cause this issue?

Using the above example with a few more buttons: https://angular-78lcrx.stackblitz.io
