### ISSUE TITLE
Initializers are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by vixson** [valor-software/ng2-bootstrap#5220]
I understand that this is a [typescript error](https://github.com/angular/angular-cli/issues/5693).
And the possible solution is to use [typescript 3.1 or above](https://github.com/awslabs/aws-cdk/issues/1075#issuecomment-436225383).

But this would require upgrading to angular 7 to use typescript 3.

And technically that's stressful and impossible. (Because my project is bulky and I'm avoiding any break changes)

### Feature request:
So please is there any stable ngx-bootstrap version to use with angular 6.

### Bug description:
(TS1039) Initializers are not allowed in ambient contexts, On typescript 2.9.2

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 4.1.1

Angular: 6.1.0

Bootstrap: 4.0

Typescript: 2.9.2

**Comment by ludmilanesvitiy** [comment]
@ciriarte https://valor-software.com/ngx-bootstrap/old/3.3.0/#/documentation#getting-started - this is the latest stable version, which you can use with app on ng6

**Comment by ludmilanesvitiy** [comment]
There's no need to open an issue here if you want to ask a general question.
Use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://join.slack.com/t/ngx-home/shared_invite/enQtNTExMTY5MzcwMTM0LWQ5M2Y4OWM0OGJjNmZiOGYyNjFlZTdlOGI1YjcxYWQ2ODhiOTY4NzhiODgwMTIzNDczODIyNWNmM2RlYWRhNTg) instead

**Comment by vixson** [comment]
Thanks. But I had to put the issue here because a lot of people might encounter the same issue
