### ISSUE TITLE
Dropdown not automatically close when click outside

### ISSUE THREAD

**Issue by silencieuxle** [valor-software/ng2-bootstrap#5222]
### Bug description or feature request:

Dropdown not automatically close when click outside

### Versions of ngx-bootstrap, Angular, and Bootstrap: latest on npm
```
    "@angular/animations": "7.2.15",
    "@angular/common": "^7.2.15",
    "@angular/compiler": "7.2.15",
    "@angular/core": "7.2.15",
    "@angular/forms": "7.2.15",
    "@angular/http": "7.2.15",
    "@angular/platform-browser": "7.2.15",
    "@angular/platform-browser-dynamic": "7.2.15",
    "@angular/platform-server": "7.2.15",
    "@angular/router": "7.2.15",
    "@fortawesome/fontawesome-free": "^5.8.2",
    "@nguniversal/module-map-ngfactory-loader": "7.1.1",
    "@nicky-lenaers/ngx-scroll-to": "^2.0.0",
    "aspnet-prerendering": "^3.0.1",
    "bootstrap": "^4.3.1",
    "core-js": "^2.5.7",
    "jquery": "^3.4.1",
    "ngx-bootstrap": "^4.1.1",
    "ngx-loading": "^3.0.1",
    "popper.js": "^1.15.0",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
```

```
<nav class="navbar navbar-expand-lg navbar-light bg-transparent">
  <button class="btn ml-auto btn-outline-success" type="button" (click)="dropdown.isOpen = !dropdown.isOpen">
    <i class="fas fa-bars"></i>
  </button>
  <div class="btn-group" dropdown #dropdown="bs-dropdown" [autoClose]="true" [insideClick]="true">
    <ul *dropdownMenu class="dropdown-menu" role="menu">
      <li role="menuitem"><a class="dropdown-item" routerLink="/sign-in">Sign In</a></li>
      <li role="menuitem"><a class="dropdown-item" routerLink="/sign-up">Sign Up</a></li>
      <li role="menuitem"><a class="dropdown-item" routerLink="/manage">Sign Out</a> </li>
      <li class="divider dropdown-divider"></li>
      <li role="menuitem"><a class="dropdown-item" routerLink="/manage">Manage</a> </li>
      <li role="menuitem"><a class="dropdown-item" routerLink="/admin">Administration</a> </li>
    </ul>
  </div>
</nav>
```

**Comment by ludmilanesvitiy** [comment]
@silencieuxle Hello! Could you, please, create a reproduction on StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts ?

**Comment by anapper** [comment]
@silencieuxle Hey! I created a StackBlitz to resolve your issue. I don't think there was a bug with ngx-bootstrap but rather in how it was dealing with the isOpen property on click. I based my solution on the ngx-bootstrap documentation found here: https://valor-software.com/ngx-bootstrap/#/dropdowns#autoclose

Here is the StackBlitz link: https://stackblitz.com/edit/ngx-bootstrap-xwzpvc?embed=1&file=app/app.component.html

My apologies if this is incorrect or not the right way to deal with issues. This is my first issue comment

**Comment by ludmilanesvitiy** [comment]
@anapper Hi! Thank you!
@silencieuxle Hi! So, take a look one more time at the official docs https://valor-software.com/ngx-bootstrap/#/dropdowns#autoclose
And take a look at Stackblitz example above, created by @anapper 
If you still observe issue with autoclose - just let me know. Otherwise, I'll close this issue.
![Peek 2019-05-30 11-54](https://user-images.githubusercontent.com/18209841/58621446-147d2680-82d2-11e9-8d84-3bf39ac1e960.gif)

**Comment by silencieuxle** [comment]
Hello, thanks for your helps @anapper @ludmilanesvitiy

**Comment by tanishkab** [comment]
Hi, I am kind of facing the same issue , Here I am using isOpen property of dropdown to open the dropdown, but I want the dropdown to autoClose and it is not happening. I am using BsDropdownModule from ngx-bootstrap for this.

`<div class="btn-group" dropdown #dropdown="bs-dropdown" [autoClose]="true" [insideClick]='true'>`
`<button type="button" class="btn btn-primary">`
`  Button dropdown <span class="caret"></span>`
`</button>`
`<ul id="dropdown-triggers-manual" *dropdownMenu class="dropdown-menu"  role="menu" aria-labelledby="button-triggers-manual">`
`  <li role="menuitem"><a class="dropdown-item" href="#">Action</a></li>`
`  <li class="divider dropdown-divider"></li>`
`</ul>`
`</div>`
`<button type="button" class="btn btn-primary" (click)="dropdown.isOpen=true">Show</button>`
   
   I am using #newdropdown template ref to use isOpen property in my .ts file.

Here is a similar stackblitz representation of it:  https://stackblitz.com/edit/angular-ngx-dropdown-msaj1m?file=src/app/app.component.ts
