### ISSUE TITLE
Datepicker will not show up in full screen mode

### ISSUE THREAD

**Issue by itsvse** [valor-software/ng2-bootstrap#5227]
Datepicker will not show up in full screen mode

The date selection box will be obscured and cannot be displayed in full screen mode

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:^4.3.0

Angular:~7.2.0

Bootstrap:^4.3.1

**Comment by itsvse** [comment]
A full div of a div, the dynamically generated control will not be included in the div, resulting in the display

**Comment by Domainv** [comment]
Needs more info screenshots or repo with reproduction.
Also, you can use the link for reproduction
https://stackblitz.com/edit/angular-njxtkm

**Comment by itsvse** [comment]
> Needs more info screenshots or repo with reproduction.
> Also, you can use the link for reproduction
> https://stackblitz.com/edit/angular-njxtkm

https://angular-njxtkm-yphdvw.stackblitz.io/
https://stackblitz.com/edit/angular-njxtkm-yphdvw

recurrent

**Comment by Domainv** [comment]
Thank you, I'll check

**Comment by IraErshova** [comment]
@itsvse Hi! Your stackblitz example doesn't work cause of `TypeError: fullscreen error`. Could you please provide a working example?

**Comment by IraErshova** [comment]
Close issue because of inactivity
