### ISSUE TITLE
ngOnDestroy is not always called

### ISSUE THREAD

**Issue by t-zander** [valor-software/ng2-bootstrap#5228]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://join.slack.com/t/ngx-home/shared_invite/enQtNTExMTY5MzcwMTM0LWQ5M2Y4OWM0OGJjNmZiOGYyNjFlZTdlOGI1YjcxYWQ2ODhiOTY4NzhiODgwMTIzNDczODIyNWNmM2RlYWRhNTg) instead

### Bug description or feature request:
Bug

In my app, I open modal dynamically depending on the query params.

When I navigate from another page and open a modal it cannot be closed. Although backdrop is removed;

Sometimes backdrop click removes only backdrop, but not modal istelf. 

E.g. 
I am on the page A with the modal A open.
I navigate to page B
I close modal A
On the page B I open modal B
When I try to close it, backdrop disappears but modal itself is still there. 
ngOnDestroy() is not called

```
console.log(this.bsModalService.getModalsCount()); // gives 1
this.bsModalService.hide(1);
console.log(this.bsModalService.getModalsCount()); // gives 0 although modal may be still there and ngOnDestroy may not be called
```
It leads to cases like this(please watch the screen below):
http://prntscr.com/nrs761

I just checked it once more. I seems like if you open the modal, then close it, then open it again, the second time you won't be able to close it. (ngOnDestroy is not called)

Any ideas what might go wrong?
Any help would be much appreciated, because it is my main roadblock for now. Thanks.

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:
"^2.0.5",
Angular:
6.0.0
Bootstrap:

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLI

**Comment by ludmilanesvitiy** [comment]
@t-zander Hello! Could you, please, create a reproduction on StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts ?

**Comment by t-zander** [comment]
@ludmilanesvitiy 
I am afraid there is a lot of code there, but I can provide the parts connected to the modal itself. Is it okay?

**Comment by ludmilanesvitiy** [comment]
@t-zander To be sure, that described issue really exists and it's related to library implementation and not to your other code implementation, need to create reproduction on StackBlitz. It'll help not only to reproduce but also to test fixes, which will be developed.

**Comment by t-zander** [comment]
@ludmilanesvitiy WIll git hub repo be okay?

**Comment by ludmilanesvitiy** [comment]
@t-zander yes)

**Comment by t-zander** [comment]
@ludmilanesvitiy Sorry that was my problem. I had unsubsscribe in onDestroy and called it on undefined.
For some reason I didn't see the error, but I guess it blocked modal from closing.
Thank you and sorry for your time.
