### ISSUE TITLE
BsDatePicker - highlight todays date

### ISSUE THREAD

**Issue by vaidd4** [valor-software/ng2-bootstrap#5229]
It seems that there is no higlighting (or special class) for todays date in the new datepicker.
And the parameter `customTodayClass` from `bsConfig` doesn't seems to work either.

I tried to reproduce but the plunkr and stackblitz provided are way to old so here is one up to date (css doesn't seems to work well):
https://stackblitz.com/edit/angular-vwtsvp

The issue for the old component : https://github.com/valor-software/ngx-bootstrap/issues/4938

**Versions**:

ngx-bootstrap: 4.3.0  
Angular: 7.x  
Bootstrap: 3.x or 4.x

**Comment by Domainv** [comment]
@vaidd4 https://stackblitz.com/edit/angular-amgo4f
![Screenshot from 2019-05-22 12-32-13](https://user-images.githubusercontent.com/14885427/58164026-b6c35b80-7c8d-11e9-966f-d55f7446eb36.png)
As I can see, customTodayClass works correctly

**Comment by vaidd4** [comment]
Thanks ! I understand what was my problem, so there was two things :
- by default there is no class nor style to differentiate the current date.
- the component datepicker is created at the root of the HTML (just before `</body>`) so I needed to add my custom class to the main style.css of my application.

This might need some clarification in the doc.

**Comment by uiswarup** [comment]
Just add [bsValue]="bsInlineValue" on your input 
and add "bsInlineValue = new Date();" on your export class
