### ISSUE TITLE
Infinite loop if using tooltip inside dropdown

### ISSUE THREAD

**Issue by tony-bondarenko** [valor-software/ng2-bootstrap#5231]
### Bug description:
Using tooltip inside dropdown may lead to an infinite loop.
Steps to reproduce:
1. Place element with a tooltip inside a dropdown menu.
2. Open dropdown menu and hover the mouse over an element with the tooltip to see it.
3. Close dropdown menu with Esc button. There're other ways to close dropdown and leave tooltip open, but a scenario with the Esc button is more easy to reproduce.
4. The browser will hang with 100% CPU usage.

The cause of this issue is the following piece of code:
https://github.com/valor-software/ngx-bootstrap/blob/aaa291394692d1acd96971e0f0877dcc348b1fb3/src/positioning/utils/getOffsetParent.ts#L18-L23
Element here - is an element from the 1st step, element.nextElementSibling - bs-tooltip-container. Both of them has offsetParent = null as they are placed inside a hidden dropdown menu. Loop condition is always true.
### Plunker/StackBlitz that reproduces the issue:
Unfortunately, don't have time to create plunker for this, reproduction is pretty straightforward.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 4.2.0

Angular: 7.2.15

Bootstrap: 4.3.2

**Comment by amiram** [comment]
Happened to me too. CPU was 100%. Now I understand why. I had to downgrade to 3.2.0.
