### ISSUE TITLE
BsDatepickerModule style not showing 

### ISSUE THREAD

**Issue by harmnot** [valor-software/ng2-bootstrap#5232]
I have follow the instruction correctly but the style of border and colour is not showing, am I wrong or something missing ?? 

this is the pic of the date picker not showing  the style : 

<img width="451" alt="Screen Shot 2019-05-22 at 22 17 26" src="https://user-images.githubusercontent.com/42674439/58186928-00d52d00-7ce0-11e9-8538-95ea10df2236.png">

my NgModule import is using this 
`import { DatepickerModule, BsDatepickerModule } from "ngx-bootstrap/datepicker";`

and in my html : 

  ```
<div class="content">
  <h4>datepicker should display current date:</h4>
  <div class="row">
    <div class="col-xs-12 col-12 col-md-4 form-group">
      <input type="text"
            class="form-control"
            [minDate]="minDate"
            [maxDate]="maxDate"
            #dp="bsDatepicker"
            bsDatepicker [(bsValue)]="myDateValue">
    </div>
  </div>
```

and my component.ts 

```
myDateValue: Date;

  onDateChange(newDate: Date) {
    console.log(newDate);
  }
ngOnInit() {
    this.myDateValue = new Date();
  }
```

**Comment by ludmilanesvitiy** [comment]
Note: If you installed ngx-bootstrap not via ng add command, you will need to perform a several actions

Notable change is additional css for it "/datepicker/bs-datepicker.css" 

There are two ways of adding css:

Load it from CDN. Add <link rel="stylesheet" href="https://unpkg.com/ngx-bootstrap/datepicker/bs-datepicker.css"> to your index.html
Load it from node_modules/ngx-bootstrap/datepicker/bs-datepicker.css via package bundler like Angular CLI, if you're using one.

**Comment by ludmilanesvitiy** [comment]
@harmnot Hi! See details: https://valor-software.com/ngx-bootstrap/#/datepicker
There's no need to open an issue here if you want to ask a general question.
Use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) instead or [Slack](https://join.slack.com/t/ngx-home/shared_invite/enQtNTExMTY5MzcwMTM0LWQ5M2Y4OWM0OGJjNmZiOGYyNjFlZTdlOGI1YjcxYWQ2ODhiOTY4NzhiODgwMTIzNDczODIyNWNmM2RlYWRhNTg)
