### ISSUE TITLE
How to use other animation styles ?

### ISSUE THREAD

**Issue by syedyawar** [valor-software/ng2-bootstrap#5238]
how to use other animation styles in ngx modules other than 'fadeindown' and 'fadeoutup' 
like provided in this link: https://codepen.io/nhembram/pen/PzyYLL

**Comment by Domainv** [comment]
@syedyawar The link is broken

**Comment by syedyawar** [comment]
> @syedyawar The link is broken

@Domainv 
sorry, kindly check again

**Comment by Domainv** [comment]
For general question please use https://stackoverflow.com/questions/tagged/ngx-bootstrap
