### ISSUE TITLE
bsDaterangepicker incorrect mobile position?

### ISSUE THREAD

**Issue by Cobr3n** [valor-software/ng2-bootstrap#5239]
Hello i use "ngx-bootstrap": "4.3.0", set config adaptivePosition: true
`<input class="form-control"
               placeholder="DD/MM/YYYY"
               [bsConfig]="{ rangeInputFormat: 'DD/MM/YYYY', containerClass: 'theme-blue', adaptivePosition: true }"
               bsDaterangepicker
               placement="bottom"
               [maxDate]="maxDate"
               [(ngModel)]="bsRangeValue">`
but position in mobile, calculate incorrect, why ?
![image](https://user-images.githubusercontent.com/25749976/58413519-2a58d480-80a3-11e9-8c36-f0bf348e832f.png)

**Comment by Cobr3n** [comment]
web version work correct ...

**Comment by Domainv** [comment]
@Cobr3n 
![Screenshot from 2019-05-27 18-09-13](https://user-images.githubusercontent.com/14885427/58428273-a1de3200-80aa-11e9-867e-e7197928fb7a.png)

As I can see all works correctly on mobile
https://stackblitz.com/edit/angular-stzgvk?file=main.ts

**Comment by Cobr3n** [comment]
sory, the problem was because of the left styles  in the root of the project ^(
