### ISSUE TITLE
When version 4.3.0 will  be released on npm?

### ISSUE THREAD

**Issue by notarnet** [valor-software/ng2-bootstrap#5243]

**Comment by Domainv** [comment]
@notarnet Already released with tag next.
Will be added as latest after releasing next version with tag next

**Comment by livthomas** [comment]
@Domainv Why do you do it this way? Projects are then by default always getting the previous version of your library instead of the latest one because NPM uses `latest` tag when you don't specify any version. Shouldn't `next` tag be used for unstable beta versions of an upcoming release?
