### ISSUE TITLE
IOS Safari: After modal opened still i am able to scroll my background table

### ISSUE THREAD

**Issue by sri-ir** [valor-software/ng2-bootstrap#5247]
In my application i have a table of data contains more rows with scrollbar, after opened any modal still i can able to scroll my table in IOS safari.

How to prevent this this scroll when ever modal is opened, or else is there any solution for this.

**Comment by ludmilanesvitiy** [comment]
@sri-ir  Hello! Could you, please, create a reproduction on StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts ?
If you want to ask a general question, use StackOverflow or Slack instead
https://stackoverflow.com/questions/tagged/ngx-bootstrap
https://ngx-home.slack.com/

**Comment by sri-ir** [comment]
Hello @ludmilanesvitiy, check this stackblitz url  https://stackblitz.com/edit/ag-grid-template-renderer-example-pu8epa

I observed grid scrollbar still working when i am opened modal.

Is there any solution or suggestions to prevent that background grid scroll.

**Comment by sri-ir** [comment]
Hello Guys,

Is there any update regarding this bug fix, still I am waiting for suggestions to fix this one.

**Comment by belinef** [comment]
Hello @sri-ir, looks like issue is not reproducible, if i understand it correct
[Screen Recording 2020-02-21 at 4.11.26 PM.zip](https://github.com/valor-software/ngx-bootstrap/files/4236437/Screen.Recording.2020-02-21.at.4.11.26.PM.zip)
