### ISSUE TITLE
Typeahead does not react to model changes correctly

### ISSUE THREAD

**Issue by meta72** [valor-software/ng2-bootstrap#5251]
### Bug description 

Typeahead is not immediately updating its options list when the model of the input changes.

I am using typeahead for a dropdown with search functionallity. The input should show the text of the selected item. When the input is clicked, it should be empty, so all options can be seen. I do this by resetting its model to `""` on focus. 
This is only working after the input is clicked and the mouse button released. While pressing the mouse button, the input is empty, but the options only show the previously selected item. When using tab to cycle through form controls, the options will also only show this one entry.

Funnily enough, when I log the `TypeaheadDirective` to the console on focus, press tab to focus the input, showing only the selected item as options and an empty input, the input will change to the selected item when the `TypeaheadDirective` is evaluated in the DevTools by clicking on/expanding it in the console.

### StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-pw8s4g

### Versions of ngx-bootstrap, Angular, and Bootstrap:

* ngx-bootstrap: **4.2.0**
* Angular: **7.2.15**
* Bootstrap: **3.4.1**

### Build system
Angular CLI: **7.3.9**

**Comment by meta72** [comment]
With ngx-bootstrap@5.0.0 the bug even exists with nothing preselected.
Both typeahead option lists in the StackBlitz demo are completely empty. With version 4.2.0 the first one showed all options, the second one showed Alabama.

**Comment by Sirius-A** [comment]
I can repoduce this in Angular 8. The typeahead is not filled correctly in versions` >4.2.0`.
