### ISSUE TITLE
Hiding a typeahead input while options are shown causes freeze

### ISSUE THREAD

**Issue by meta72** [valor-software/ng2-bootstrap#5254]
### Bug description or feature request:

When a component that contains a typeahead with an opened options list becomes hidden it causes the page to freeze. 

### StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-bsnuzr
The issue can be triggered by XHR or other async events. It can be reproduced with a timeout.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

* ngx-bootstrap: **4.2.0**
*  Angular: **7.2.15**
*  Bootstrap: **3.4.1**

### Build system: 

Angular CLI: **7.3.9**

**Comment by meta72** [comment]
#### Workaround:
Before hiding the component containing the typeahead element, call `typeaheadDirective.hide()`.

**Comment by meta72** [comment]
This is possibly the same issue as in #5194

**Comment by meta72** [comment]
This is indeed fixed in 5.0.0

**Comment by themaxhero** [comment]
> 
> 
> This is indeed fixed in 5.0.0

I'm having the same issue. I'm using 5.6.1.
