### ISSUE TITLE
"Quick select" date ranges for date range picker

### ISSUE THREAD

**Issue by wwarby** [valor-software/ng2-bootstrap#5262]
### Bug description or feature request:

Feature Request.

I'd really like to be able to achieve a similar effect to http://www.daterangepicker.com/ and https://www.npmjs.com/package/ngx-daterangepicker-material where you can set custom "quick select" ranges for the date when the picker is in range mode. If that functionality could be added to ngx-bootstrap's date range picker that would be awesome, however, my fallback plan would have been to use an inline date range picker nested within a Popover. That would have worked, except there's no inline date range picker, only an inline date picker, if the "quick select" ranges don't happen, second on my wish list would be the ability to inline a date range picker.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 4.2.0

Angular: 8.0.0

Bootstrap: 4.3.1

**Comment by arvindm95** [comment]
#5580

**Comment by gr8white** [comment]
Any idea when the updates from #5580 will be in use for the public?

**Comment by daniloff200** [comment]
hey @gr8white , that will be a next version (5.6.0)
I suppose, that will be after Friday's release, or, in the worst case, next week
