### ISSUE TITLE
Ability to add services to modal injector

### ISSUE THREAD

**Issue by rseanhall** [valor-software/ng2-bootstrap#5275]
Currently, `BsModalService` does not give the ability to provide services through injection. It is hardcoded to provide the `ModalOptions` and `BsModalRef` service in `_showModal`. I have a service that needs to be injected deep into the component tree where it is impractical to pass it through using `initialState` and `Input`s. `ModalOptions` should expose a `providers?: StaticProvider[]` property so that the caller can add more providers to the injector.

**Comment by eLeontev** [comment]
this feature works only if providers has no other DI or providers are registered as part of `root` module. The issue is the injector used in the modal is rootInjector and all DI registered in different modules does not exists in it.

Example:
```typescript

@Component()
export class RootModalComponent {
  constructor(rootComponentModalService: RootComponentModalService) {}
}

@Component()
export class FeatureModalComponent {
  constructor(featureComponentModalService: FeatureComponentModalService) {}
}

@Component()
export class FeatureWithDIModalComponent {
  constructor(featureWithOtherDIService: FeatureWithOtherDIService) {}
}

@Injectable()
export class FeatureComponentModalService {}

@Injectable()
export class FeatureWithOtherDIService {
  constructor(featureWithoutDIService: FeatureWithoutDIService) {}
}

@Injectable()
export class FeatureWithoutDIService {}

@NgModule({
   imports: [FeatureModule],
   declarations: [RootModalComponent],
   providers: [RootComponentModalService]
})
export class RootModule {}

@NgModule({
   declarations: [FeatureModalComponent, FeatureWithDIModalComponent],
   providers: [FeatureComponentModalService, FeatureWithOtherDIService, FeatureWithoutDIService]
})
export class FeatureModule {}

platform.bootstrapModule(RootModule)

// usage
bsModalService.show(RootModalComponent) // works as expected

// dependecy is not provided for RootModule and cannot be found
bsModalService.show(FeatureModalComponent) //  injection error
bsModalService.show(FeatureModalComponent, {providers: [FeatureComponentModalService]}) //  works as expected

// first dependency is provided but cannot be injected since its dependency (FeatureWithoutDIService) is not found
bsModalService.show(FeatureModalComponent, {providers: [FeatureComponentModalService]}) //  injection error
bsModalService.show(FeatureModalComponent, {providers: [FeatureComponentModalService, FeatureWithoutDIService]}) //  works as expected
```

I hope the examples are readable :)


Hacks:
1. register all services to rootModule (bad solution leads to increase of main bundle size)
2. use only services without other dependencies (if it make sense for your logic)
3. pass all dependent services to `providers` options (can be weird with a lot of dependencies)


If it will be fixed (proposal):
add additional field for options to define the injector from which the modal will be created.

for now it works: 
``` typescript
let modalInjector({
  providers: options.providers,
  parent: rootInjector //  this._injector in the code
})
```

to next view:
```typescript
let modalInjector({
  providers: options.providers,
  parent: options.parentInjector || rootInjector
})
```

**Comment by rseanhall** [comment]
My use case was:

> 2. use only services without other dependencies (if it make sense for your logic)

It was the responsibility of the code calling `bsModalService.show` to resolve dependencies. It sounds like you want a new feature. You probably should create a separate issue for that.

**Comment by d0r0sh** [comment]
> My use case was:
> 
> > 2. use only services without other dependencies (if it make sense for your logic)
> 
> It was the responsibility of the code calling `bsModalService.show` to resolve dependencies. It sounds like you want a new feature. You probably should create a separate issue for that.

@rseanhall  Is it planned to add such an option to define a modal injector in the future?

**Comment by d0r0sh** [comment]
![image](https://user-images.githubusercontent.com/46892003/195591002-ea063675-0dd1-4eaa-8395-f89c5cf7ef5f.png)
