### ISSUE TITLE
how to increase the input field when  use ngx-datetime-picker.

### ISSUE THREAD

**Issue by VikrantGohane** [valor-software/ng2-bootstrap#5288]
<ngx-datetime-picker [(selectedDateTime)]="dateTimeExample"  placeholder="Enter your date and time"    [disableButton]="true" 
 [disableInput]="false"  [disablePicker]="false" 
 [doNotCloseOnDateSet]="false" ></ngx-datetime-picker>

**Comment by vixson** [comment]
> Increase the input field?

Like how? Please explain better.

**Comment by VikrantGohane** [comment]
which is best date and time picker example in angular if any model are available please give best link on that.

**Comment by ludmilanesvitiy** [comment]
If you want to ask a general question about ngx-bootstrap library, use StackOverflow or Slack instead
https://stackoverflow.com/questions/tagged/ngx-bootstrap
https://ngx-home.slack.com/
