### ISSUE TITLE
event work with tooltip

### ISSUE THREAD

**Issue by zhukof** [valor-software/ng2-bootstrap#5289]
### When specifying several variants of events, only one works

code example:
`<label [tooltip]="test" triggers="focusin:focusout mouseover:mouseout mouseover:dblclick focusin:dblclick" [delay]="1000">test label</label>`

This sample code will not work with a set of events. Since now the binding only goes to the first event.
` this._tooltipCancelShowFn = this._renderer.listen(this._elementRef.nativeElement, triggers[0].close, () => {
            timer.unsubscribe();
            cancelDelayedTooltipShowing();
          });`

in the tooltip.directive.ts file you need to go through all the events

`for (let i=0; i<triggers.length; i++) {
                    this._tooltipCancelShowFn = this._renderer.listen(this._elementRef.nativeElement, triggers[i].close, function () {
                        timer.unsubscribe();
                        cancelDelayedTooltipShowing();
                    });
                }`

**Comment by ludmilanesvitiy** [comment]
Fix available from 5.2.0 version.
