### ISSUE TITLE
Typeahead question: is possible to open dropdown on input focus?

### ISSUE THREAD

**Issue by kolisko** [valor-software/ng2-bootstrap#5292]
I would like to show all results in dropdown list when input is empty and user focus the input.

`````
@ViewChild(TypeaheadDirective) td:TypeaheadDirective;
private selectedSector: string;

///

private onSectorFocus(): void {
        if (this.isSectorEmpty())
            setTimeout(() => { this.td.show(); }, 200);
}

    private isSectorEmpty(): boolean {
        if (this.selectedSector == null || this.selectedSector == '')
            return true;

        return false;
    }

///

<input 
                       class="form-control"
                                     id="sectionCombobox"
                                     (typeaheadOnSelect)="onSectorSelect($event?.item)"
                                     [(ngModel)]="selectedSector"
                       typeaheadOptionField="value"
                                     [typeahead]="codebook.cb('XXXX')"
                                     formControlName="sectorInput"
                       (click)="onSectorFocus()"
                >


`````

I am trying to manually call show() method on TypeaheadDirective in input click handler but it goes to exception. 

     EXCEPTION: Cannot read property 'length' of undefined {"exception":"EXCEPTION: Cannot read property 'length' of undefined","originalStack":"TypeError: Cannot read property 'length' of undefined\n    at TypeaheadContainerComponent.set [as matches] (webpack-internal:///449:49:31)\n    at TypeaheadDirective.show (webpack-internal:///928:231:33)\n    at eval (webpack-internal:///1308:236:32)\n    at ZoneDelegate.invokeTask (webpack-internal:///1540:425:31)\n    at Object.onInvokeTask (webpack-internal:///0:4085:33)\n    at ZoneDelegate.invokeTask (webpack-internal:///1540:424:36)\n

**Comment by ludmilanesvitiy** [comment]
@kolisko Hi! Try to use [typeaheadMinLength]="0" param for the typeahead:
 https://valor-software.com/ngx-bootstrap/#/typeahead#min-length

**Comment by kolisko** [comment]
It works well. Thank you!
