### ISSUE TITLE
In angular 7 which is the best date and time picker on bootstrap suggest me any example or link

### ISSUE THREAD

**Issue by VikrantGohane** [valor-software/ng2-bootstrap#5294]

**Comment by ludmilanesvitiy** [comment]
The issue name is not descriptive. A description is empty. Looks like a just mistake. Closing.
If you want to ask a general question, use StackOverflow or Slack instead
https://stackoverflow.com/questions/tagged/ngx-bootstrap
https://ngx-home.slack.com/
