### ISSUE TITLE
Advanced daterange picker

### ISSUE THREAD

**Issue by hoangleitvn** [valor-software/ng2-bootstrap#5297]
I would be nice if we can support a few options for daterange picker that allows user easy to select a relative date range
![image](https://user-images.githubusercontent.com/43955692/59986664-edf8a400-9661-11e9-90ec-2280d63d0a80.png)

**Comment by ludmilanesvitiy** [comment]
Closed as a duplicate of https://github.com/valor-software/ngx-bootstrap/issues/5262
