### ISSUE TITLE
Getting compilation error when installed ngx-bootstrap 4.3.0

### ISSUE THREAD

**Issue by arnab46** [valor-software/ng2-bootstrap#5298]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://join.slack.com/t/ngx-home/shared_invite/enQtNTExMTY5MzcwMTM0LWQ5M2Y4OWM0OGJjNmZiOGYyNjFlZTdlOGI1YjcxYWQ2ODhiOTY4NzhiODgwMTIzNDczODIyNWNmM2RlYWRhNTg) instead

### Bug description or feature request:
installed ngx bootstrap V4.3. from earlier version V3.3.0
After which command 'ng build' gives below compilation error:

ERROR in node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(5,33): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(6,30): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(7,28): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(8,30): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(9,39): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(10,35): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(11,35): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(12,29): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(13,39): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(14,36): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(15,36): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(16,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(17,41): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(18,39): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(19,47): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(20,34): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(21,36): error TS1039: Initializers are not allowed in ambient contexts.

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

Angular CLI: 6.2.2
Node: 10.6.0
OS: darwin x64
Angular: 6.1.8
... common, core, forms, http, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.2
@angular-devkit/build-angular     0.8.2
@angular-devkit/build-optimizer   0.8.2
@angular-devkit/build-webpack     0.8.2
@angular-devkit/core              0.8.2
@angular-devkit/schematics        0.8.2
@angular/animations               6.1.10
@angular/cdk                      6.4.7
@angular/cli                      6.2.2
@angular/compiler                 6.1.10
@angular/compiler-cli             6.1.10
@angular/language-service         6.1.10
@angular/material                 6.4.7
@ngtools/webpack                  6.2.2
@schematics/angular               0.8.2
@schematics/update                0.8.2
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.24.0

**Comment by ludmilanesvitiy** [comment]
@arnab46 Hello! Could you, please, create a reproduction on StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts ?

**Comment by arnab46** [comment]
@ludmilanesvitiy 
Not sure how to share project in stackblitz. 
I'm trying to add below import statement:

`import { DatepickerDateCustomClasses } from 'ngx-bootstrap/datepicker';`

in app.component.ts file and it's giving "red error" saying /ngx-bootstrap/datepicker has no export class DatepickerDateCustomClasses. This seems reasonable as I see in stackblitz ngx-bootstrap has version 1.9.3 whereas as per https://valor-software.com/ngx-bootstrap/#/datepicker this feature is available for ngx-boostrap V4.X.X. 

However, the issue I'm facing is, in my local I've installed ngx-bootstrap V4.3.0 and the import statement for DatepickerDateCustomClasses is  no more throwing red alert/error which is fine. But When I try to build or start serve using the command `ng build` or `ng serve`, I get compilation error as mentioned in 'Bug description' section of the issue.

**Comment by ludmilanesvitiy** [comment]
@arnab46 If you want to add datepicker with custom classes, just add similar template and component, as shown in https://valor-software.com/ngx-bootstrap/#/datepicker#date-custom-classes
Example on stackblitz: https://stackblitz.com/edit/angular-dafgtl?embed=1&file=app/ngx-bootstrap-demo.component.ts

**Comment by arnab46** [comment]
@lanocturne  Thanks for replying.
I have the code you have shared. 
From the stackblitz code you shared I see that it's using ng-bootstrap 5.1.0 from the dependency.
Currently my ng-bootstrap version is 3.3.0. In my current version (V3.3.0) the feature `DatepickerDateCustomClasses` is not available.

That's why I installed ng-bootstrap 5.1.0 using command:

`npm install ngx-bootstrap@5.1.0`

which  was installed successfully.

But after this if I try to build my project using `ng build` I 'm getting error

ERROR in node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(5,33): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(6,30): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(7,28): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(8,30): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(9,39): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(10,35): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(11,35): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(12,29): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(13,39): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(14,36): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(15,36): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(16,40): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(17,41): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(18,39): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(19,47): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(20,34): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ngx-bootstrap/datepicker/reducer/bs-datepicker.actions.d.ts(21,36): error TS1039: Initializers are not allowed in ambient contexts.

So, my basic issue is to upgrade ng-bootstap to version5.1.0 and get it work properly. It seems I'm facing some dependency related issue. Could you please help me with this.

**Comment by ludmilanesvitiy** [comment]
Need to update all related ng packages to v8. Compatibility table: https://valor-software.com/ngx-bootstrap/#/documentation#compatibility

**Comment by Moulde** [comment]
Per the compatibility chart, version 4.3.0 should work for angular 6-7, which is the version (6.1.10) I'm using as well, but when updating ngx-bootstrap to version 4.3.0, I get the above errors.
