### ISSUE TITLE
How to Apply css to <modal-container> element if I am using 'BsModalService' in Angular ?

### ISSUE THREAD

**Issue by RanjeetEppa18** [valor-software/ng2-bootstrap#5302]
I am not allowed to use bootstrap class 'modal'.
Question is asked because i don't have to let modal close if User clicks outside the modal.

I tried  ->
    keyboard: false,
    backdrop: false,
    class: "custom-class"

but these are applied to 'model-content' and that's not effective.
Please tell me any solution.

**Comment by ludmilanesvitiy** [comment]
@RanjeetEppa18 Did you try this example: https://valor-software.com/ngx-bootstrap/#/modals#service-disable-backdrop
In this case, if you disable backdrop click (click outside modal), then modal will not close by outside click.

**Comment by RanjeetEppa18** [comment]
@ludmilanesvitiy Thanks for your help , That really worked.
