### ISSUE TITLE
Change isAnimated dynamically in accordion component doesn't work

### ISSUE THREAD

**Issue by psalkowski** [valor-software/ng2-bootstrap#5311]
### Bug description or feature request:
I can not update `[isAnimated]` property in `accordion` component. In the demo, if you click on button, it change flag `isAnimated` to `false`, when you click on accordion you will see that it doesn't work.

### Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-qrhmpv

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.1.0

Angular: 8.1.0

Bootstrap: 4.3.1

**Comment by Domainv** [comment]
As designed
