### ISSUE TITLE
Hide days from other month in datepicker and daterangepicker

### ISSUE THREAD

**Issue by Mikiawm** [valor-software/ng2-bootstrap#5313]
Feature request:
Hide days from other month in datepicker and daterangepicker

**Comment by daniloff200** [comment]
RIght now, by default you can't select these dates, and they are disabled (unless, you don't use https://valor-software.com/ngx-bootstrap/#/datepicker#select-dates-from-other-month in config)

Then, you need to add `display: none` to  `.bs-datepicker-body table td span.is-other-month `
