### ISSUE TITLE
bug(timepicker): Error when writing 12 in the text box reserved for hours, but when using the mousewheel Bug disappears. 

### ISSUE THREAD

**Issue by stephanetcheua** [valor-software/ng2-bootstrap#5319]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://join.slack.com/t/ngx-home/shared_invite/enQtNTExMTY5MzcwMTM0LWQ5M2Y4OWM0OGJjNmZiOGYyNjFlZTdlOGI1YjcxYWQ2ODhiOTY4NzhiODgwMTIzNDczODIyNWNmM2RlYWRhNTg) instead

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

**Comment by stephanetcheua** [comment]
1- Error when writing 12 in the text box reserved for hours

![image](https://user-images.githubusercontent.com/34269858/60980498-de9d7a00-a334-11e9-9aa6-6ea9560d03b1.png)

**Comment by stephanetcheua** [comment]
2-but when using the mousewheel Bug disappears.

![image](https://user-images.githubusercontent.com/34269858/60980586-07257400-a335-11e9-94ff-feb81e7ff030.png)

**Comment by ludmilanesvitiy** [comment]
Duplicate of https://github.com/valor-software/ngx-bootstrap/issues/5125
