### ISSUE TITLE
Date picker issue:- if we put year as two digit ex 68 it will take 2068 by default how to stop that

### ISSUE THREAD

**Issue by ckrandhir** [valor-software/ng2-bootstrap#5322]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://join.slack.com/t/ngx-home/shared_invite/enQtNTExMTY5MzcwMTM0LWQ5M2Y4OWM0OGJjNmZiOGYyNjFlZTdlOGI1YjcxYWQ2ODhiOTY4NzhiODgwMTIzNDczODIyNWNmM2RlYWRhNTg) instead

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:

Angular:

Bootstrap:

**Comment by ckrandhir** [comment]
Date picker issue:- if we put year as two digit ex 68 it will take 2068 by default how to stop that

**Comment by ludmilanesvitiy** [comment]
@ckrandhir You need to specify the format of your date, like shown in this example:
https://valor-software.com/ngx-bootstrap/#/datepicker#format
In your case, looks like you need format DD-MM-YY or similar.
It'll look like this:
![Screen Shot 2019-07-11 at 13 06 49](https://user-images.githubusercontent.com/18209841/61042670-558e4d80-a3dd-11e9-8d8e-7da2682a468e.png)
