### ISSUE TITLE
Pagination component buttons lose focus on Enter press

### ISSUE THREAD

**Issue by LKU4** [valor-software/ng2-bootstrap#5323]
### Bug description or feature request:
Pagination component loses focus upon selecting a page and restores it on different buttons, which makes a keyboard navigation somewhat wonky.

Steps to reproduce:
1. Use Tab to set focus on numbered page button.
2. Press Enter to select focused page. The button will now lose focus.
3. Press Tab again. The focus will be restored on "Next" button.
4. If Enter is pressed when non-numbered page buttons are focused, then focus will later be restored on the next element of the page.

This behaviour can be observed for all pagination controls on demo page.

### Plunker/StackBlitz that reproduces the issue:
Demo: https://valor-software.com/ngx-bootstrap/#/pagination
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-2quamx

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.x

Angular: 8.x

Bootstrap: 3.x

**Comment by LKU4** [comment]
The selectPage() method, which is probably the place where this could be changed, looks like this:
```
selectPage(page: number, event?: Event): void {
    if (event) {
      event.preventDefault();
    }

    if (!this.disabled) {
      if (event && event.target) {
        // tslint:disable-next-line:no-any
        const target: any = event.target;
        target.blur();
      }
      this.writeValue(page);
      this.onChange(this.page);
    }
  }
```

So first, there is a target.blur() call here which seems to sit there since always, thus it is possible there is some use case that I'm missing and this behaviour is intentional. Even removing this call doesn't resolve the problem though. It looks like the page buttons are re-rendered and swapped upon page selection, so naturally they do not preserve focus.

I fixed it locally with a piece of code that after single tick finds the new element corresponding to the one that was clicked and focuses it:
```
const text = target.innerText;
setTimeout(() => { 
    const elList = this.elementRef.nativeElement.querySelectorAll("a.page-link");
    const el = [...elList].filter(el => el.innerText === text)[0]
    el.focus();
}, 0);
```
This actually seems to work really well for my use case, but looks pretty hacky and I'm not sure if I'm missing anything else.

**Comment by apotapcukv** [comment]
Dear LKU4! 
As per our check this issue is fixed in the latest version, so we’re closing the issue.
Please don’t hesitate to let us know if you face further issues.
