### ISSUE TITLE
ngx-modal with ngx-datepicker with @ngrx/effect throw an error: "Cannot read property 'map' of undefined"

### ISSUE THREAD

**Issue by DmitriyIvanko** [valor-software/ng2-bootstrap#5324]
### Bug description:
I have simple @ngrx/effect. This effect should open ngx-modal with component contained ngx-datepicker (http://prntscr.com/odo4z5):
```
  @Effect({ dispatch: false })
  public openModal$ = this.actions$.pipe(
      ofType(SignInActionTypes.OPEN_MODAL),
      map((action) => {
        return this.modalService.show(DatetimepickerComponent);
      }),
  );
```
But if i wrap it by setTimeout everything works well:
```
    setTimeout(() => {
      this.modalService.show(DatetimepickerComponent);
    }, 10);
```
Error:
core.js:9110 ERROR TypeError: Cannot read property 'map' of undefined
    at flagReducer (ngx-bootstrap-datepicker.js:1604)
    at bsDatepickerReducer (ngx-bootstrap-datepicker.js:1376)
    at ScanSubscriber.accumulator (ngx-bootstrap-mini-ngrx.js:31)
    at ScanSubscriber._tryNext (scan.js:49)
    at ScanSubscriber._next (scan.js:42)
    at ScanSubscriber.next (Subscriber.js:49)
    at Notification.observe (Notification.js:20)
    at QueueAction.dispatch (observeOn.js:25)
    at QueueAction._execute (AsyncAction.js:51)
    at QueueAction.execute (QueueAction.js:20)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:
"ngx-bootstrap": "^5.0.0"
Angular:
 "@angular/core": "^8.1.0",
Bootstrap:
"bootstrap": "^4.3.1",
### Build system: Angular CLI, System.js, webpack, starter seed:

Angular CLI: 8.1.0
Node: 10.16.0
OS: win32 x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.0.0
@ngtools/webpack                  8.1.0
@schematics/angular               8.0.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2

**Comment by ludmilanesvitiy** [comment]
@DmitriyIvanko Could you, please, create a reproduction on StackBlitz?

**Comment by IraErshova** [comment]
@DmitriyIvanko Hi! What's the status of this issue? Did you have a chance to handle this case? Also, I think it's better to use tap operator instead of map:
```
tap(() => {
  this.modalService.show(DatetimepickerComponent);
}),
```
