### ISSUE TITLE
Active date and Bs4

### ISSUE THREAD

**Issue by korinovsky** [valor-software/ng2-bootstrap#5325]
Where are no any class for active date and Bs4:
https://github.com/valor-software/ngx-bootstrap/blob/efa5229ce7306d00966d1d9d41b95a71549499cc/src/datepicker/daypicker.component.ts#L64

can`t specify style for it.

**Comment by IraErshova** [comment]
@korinovsky Hi! Could you please provide a bit more information about your issue? It would be better if you use our [guideline for submitting issues ](https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md#-submitting-an-issue).

Do you want to add your custom class to datepicker or what?

**Comment by IraErshova** [comment]
Close because of inactivity
