### ISSUE TITLE
Popover not loading

### ISSUE THREAD

**Issue by SSheoran84** [valor-software/ng2-bootstrap#5328]
I'm using a Single-SPA architecture where I've 5 angular applications. In one of the applications, I'm using the popover module, but popover is not visible after rendering.

Below is the HTML code:
<div triggers="mouseenter:mouseleave" [popover]="popTemplate" class="abc">
      <ng-template #popTemplate>
        <span>
           DEMO
        </span>
      </ng-template>
    </div>

CSS:
:host /deep/ .popoverStyle,
:host /deep/ .popover {
    background-color: #ebdd1a;
    color: var(--color0) !important;
    box-shadow: rgba(0, 0, 0, .8) 0 10px 10px;
    width: 100%;
    &.top{
        margin-top: 6px;
        margin-right: 100px;
    }
    .popover-body{
        font-size: 13px;
    }
    .arrow{
        border-style:none;
        border-left: 10px solid transparent;
        border-right: 10px solid transparent;
        border-top: 10px solid #ebdd1a;
        bottom: -8px;
    }
    &>.arrow:after {
        border-style:none !important;
    }
    div {
        span {
            ul {
                li {
                    color: var(--color16);
                    font-size: 1.125em;
                    font-weight: 600;
                    label {
                        font-size: .85em;
                        font-weight: 300;
                    }
                }
            }
        }
    }
}

app.Module file:
import { PopoverModule } from 'ngx-bootstrap/popover';
import {
PopoverModule.forRoot()
}

Below is the DOM snippet for the same:

![Popover Issue](https://user-images.githubusercontent.com/52840416/61161041-a2e6e980-a4c7-11e9-8b9f-448d1cd178a2.JPG)

Could you please suggest why this is happening?

**Comment by ludmilanesvitiy** [comment]
@SSheoran84 Could you please create a reproduction on Stackblitz for this issue? https://stackblitz.com

**Comment by SSheoran84** [comment]
The issue is resolved now. Thank you for the quick response!
