### ISSUE TITLE
this._datePicker is undefined

### ISSUE THREAD

**Issue by Gillardo** [valor-software/ng2-bootstrap#5330]
### Bug description or feature request:
Upon putting a datepicker into a dropdown, an error is now displayed upon first trying to open the dropdown list `this._datePicker is undefined`.  This didnt happen in v4.3.0 but only when i upgraded to v5.1.0.  If you change the example below to use v4.3.0, the problem doesnt appear.

The problem appears at line 162 of the datepicker.component.ts file, the function looks like so.

```
writeValue(value: any): void {
	if (this._datePicker.compare(value, this._activeDate) === 0) {
		return;
	}
	if (value && value instanceof Date) {
		this.activeDate = value;
		this._datePicker.select(value, false);

		return;
	}

	this.activeDate = value ? new Date(value) : void 0;
}
```

However, if you change it to the following, this seems to fix the problem, but not sure if have a knock on affect?

```
writeValue(value: any): void {
        if (!this._datePicker) {
            return;
        }
	if (this._datePicker.compare(value, this._activeDate) === 0) {
		return;
	}
	if (value && value instanceof Date) {
		this.activeDate = value;
		this._datePicker.select(value, false);

		return;
	}

	this.activeDate = value ? new Date(value) : void 0;
}
```

### Plunker/StackBlitz that reproduces the issue:
Here is a stackblitz that reproduces the problem https://stackblitz.com/edit/ngx-bootstrap-unxusi

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.1.0

Angular: 8.1.0

Bootstrap: latest on master branch

### Build system: Angular CLI, System.js, webpack, starter seed:
Angular CLi

**Comment by pernillah** [comment]
We are experiencing the same issues when migrating to Angular 8.

**Comment by fireappsAdmin** [comment]
I'g getting an extremely similar error for the dropdown toggle while upgrading to angular 8. `TypeError: _this._documentClickListener is not a function at... `. It seems as though it could be related to this.

**Comment by lizlux** [comment]
I had this same problem and was also using `<datepicker>` instead of `<bs-datepicker-inline>`. Switching to the latter fixed my issue.

**Comment by lolismatic** [comment]
It seems to be a issue related to `ViewChild` [static change in Angular 8](https://angular.io/guide/static-query-migration).

In my case updating `datepicker.component.ts`:
```typescript
  @ViewChild(DatePickerInnerComponent, { static: false })
  _datePicker: DatePickerInnerComponent;
```
to
```typescript
  @ViewChild(DatePickerInnerComponent, { static: true })
  _datePicker: DatePickerInnerComponent;
```
fixed the issue.
