### ISSUE TITLE
Tooltip with delay on element with routerlink crashes browser tab

### ISSUE THREAD

**Issue by segersrobbertKlarrio** [valor-software/ng2-bootstrap#5333]
Crashes browser:
`<button routerLink="/url" tooltip="tooltip" delay="500"</button>`

Works fine:
`<button routerLink="/url" tooltip="tooltip"</button>`

ngx-bootstrap: 4.3.0
Angular: 7.2

**Comment by ludmilanesvitiy** [comment]
@segersrobbertKlarrio Could you, please, try the latest version of ngx-bootstrap - 5.1.1 for this issue?

**Comment by Domainv** [comment]
@segersrobbertKlarrio In 5.1.1 version works correctly
https://stackblitz.com/edit/angular-gtkjbc?file=app/delay.html
