### ISSUE TITLE
Modal performance (rerender on scroll)

### ISSUE THREAD

**Issue by NekitCorp** [valor-software/ng2-bootstrap#5335]
### Bug description or feature request:
When injecting a BsModalService into the constructor, a rerender occurs with each scroll.
### Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-g61vpl
### Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: ^5.1.0
Angular: 7.0.3
Bootstrap: 4.1.3

**Comment by sod** [comment]
related https://github.com/valor-software/ngx-bootstrap/issues/5291
