### ISSUE TITLE
Animate progressbar with static values

### ISSUE THREAD

**Issue by g3344** [valor-software/ng2-bootstrap#5336]
The dynamic value progressbar example has an animation where the colored bar value fills up.

Is it possible to have that animation effect (filling up the bar), with a static value?

The progressbar seems to load at the value.

https://valor-software.com/ngx-bootstrap/#/progressbar#bs3-dynamic

**Comment by valorkin** [comment]
@SvetlanaMuravlova please set default `value` for progress and bar to `0`

**Comment by valorkin** [comment]
will be a part of v7 release
