### ISSUE TITLE
Multiple dropdown but close only one 

### ISSUE THREAD

**Issue by batgos** [valor-software/ng2-bootstrap#5339]
### Bug description or feature request:

Hello,
I have 2 dropdown opened in same time but i want to close only one
I've distinct my dropdown by changing id : #dropdown="bs-dropdown" and #dropdown2="bs-dropdown" but seems it's doesn't effect each time i call dropdown2.hide() the both close
Do there is another solution ?
Thanks

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 3.0.1

Angular: 6.0.3

Bootstrap: 4

**Comment by IraErshova** [comment]
@batgos Hi! Is this issue still relevant? I created a stackblitz demo, could you please check it? 
https://stackblitz.com/edit/angular-eynjxm

**Comment by IraErshova** [comment]
Close because of inactivity
