### ISSUE TITLE
Datepicker placement "bottom left" not at all working. Always opens in middle of the field.

### ISSUE THREAD

**Issue by cdmhari** [valor-software/ng2-bootstrap#5340]
Here is a live example to demonstrate the issue
StackBlitz: https://angular-9yzpyn.stackblitz.io

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.1.1

Angular: 8.2.0-next.1

Bootstrap: 4

**Comment by Victor716** [comment]
I met the same issue

**Comment by vijayhardaha** [comment]
Any Update on this issue? I am also looking for bottom left Or top left position.

**Comment by KasperSommer** [comment]
I really need this too. Please have a look at it...!

**Comment by vz28bh** [comment]
Same here. When using the date range picker it is so wide as to be off screen.

**Comment by daniloff200** [comment]
hey, @cdmhari !
Your example looks broken, I can't even open a datepicker and get a console error 

Could you please fix it?

**Comment by vijayhardaha** [comment]
Just checked, @cdmhari example page is working fine.

**Comment by daniloff200** [comment]
strange
I've opened it, pressed  on the DatePicker button, and got this
![Selection_276](https://user-images.githubusercontent.com/13692220/73464674-f4819380-4387-11ea-976a-933c5ac71737.png)

**Comment by vijayhardaha** [comment]
Ok, Toggle Button has Problem and throwing error, But if you focus on input. Datepicker works.

**Comment by daniloff200** [comment]
Ah, now I get it

ngx-bootstrap doesn't support mixed placement, like **top left** **bottom right** etc
We have only top, bottom, left, and right, and bottom is an initial value, so, in this case, bottom lleft does not working, and bottom is selected as default one

**Comment by cyberbobjr** [comment]
Hi,
i've made a trick with ng-deep selector :
```
::ng-deep {
    bs-datepicker-container {
        transform: translate3d(0px, 34px, 0px) !important;
    }
}
```

and i wrapped my control inside a span with container selector :
```
 <span class="control-body" id="datestart">
            <input type="text"
                   placeholder="Choissisez une date de début pour l'export"
                   formControlName="datestart"
                   [container]="'#datestart'"
                   class="form-control"
                   bsDatepicker/>
        </span>
```

with this trick i can left-align the datepicker container to the input.

**Comment by vijayhardaha** [comment]
@cyberbobjr so it's CSS based solutions? Right?

And it will affect every instance of datepicker?

**Comment by cyberbobjr** [comment]
> @cyberbobjr so it's CSS based solutions? Right?
> 
> And it will affect every instance of datepicker?

Yes it’s pure CSS, but you can prevent spreading the modified style with a ng-deep selector to be more precise.

**Comment by vijayhardaha** [comment]
@cyberbobjr Ok I'll test the code.

**Comment by Polantaris** [comment]
> Ah, now I get it
> 
> ngx-bootstrap doesn't support mixed placement, like **top left** **bottom right** etc
> We have only top, bottom, left, and right, and bottom is an initial value, so, in this case, bottom lleft does not working, and bottom is selected as default one

Why was this changed when this was previously supported?

https://github.com/valor-software/ngx-bootstrap/issues/3721

I'm in the middle of an upgrade cycle, mixed placement was completely supported in a previous version and has been removed. I don't understand why this would not be supported anymore, handling this kind of thing through CSS is extremely wasteful and tricky to implement due to various screen sizes and similar issues. 

Additionally, as far as I can tell, there's no way to add a custom class to the datepicker as a whole (unless I'm blind and am missing it in the documentation) which means you need to override the base datepicker classes to implement the placement you want, which is unrealistic when you have multiple datepickers on one screen.

**Comment by Superhands89** [comment]
Strange that this functionality was dropped. Would really like to see it return. Positioning the datepicker in the bottom left of the input field seems like a pretty normal thing to me

**Comment by bastianremo** [comment]
any updates of this? I really need positioning two datepickers when the windows is resized

**Comment by mjunaidqasim7** [comment]
any updates of this? I really need positioning two datepickers when the windows is resized
