### ISSUE TITLE
the document of using ngx-bootstrap is not work well

### ISSUE THREAD

**Issue by shingle2302** [valor-software/ng2-bootstrap#5341]
Before opening an issue, please search for duplicates (opened and closed)
https://github.com/valor-software/ngx-bootstrap/issues
There's no need to open an issue here if you want to ask general question, use [StackOverflow](https://stackoverflow.com/questions/tagged/ngx-bootstrap) or [Slack](https://join.slack.com/t/ngx-home/shared_invite/enQtNTExMTY5MzcwMTM0LWQ5M2Y4OWM0OGJjNmZiOGYyNjFlZTdlOGI1YjcxYWQ2ODhiOTY4NzhiODgwMTIzNDczODIyNWNmM2RlYWRhNTg) instead

### Plunker/StackBlitz that reproduces the issue:
Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.1.1

Angular: 8.0.1

Bootstrap: 4.3.1

### Build system: Angular CLI, System.js, webpack, starter seed:

when i add the bootstrap.min.css to angular.json, It cannot work,but when i add this below, it works well.
![image](https://user-images.githubusercontent.com/20883097/61877704-2837b880-af22-11e9-856b-7da0dbaca9a3.png)

Here is the example project link: https://github.com/jang675953/angular8-demo

**Comment by ludmilanesvitiy** [comment]
You need to follow these instructions: https://valor-software.com/ngx-bootstrap/#/documentation#installation-instructions
