### ISSUE TITLE
Small documentation mistake

### ISSUE THREAD

**Issue by JamesHobday21** [valor-software/ng2-bootstrap#5344]
Hi,
in the docs its gives the wrong event for listening for when a tab is selected. It says '(selectTab)' whilst the correct event is just '(select)'. Took me a little while to figure it out.

https://valor-software.com/ngx-bootstrap/old/4.0.0/#/tabs#select-event

**Comment by ludmilanesvitiy** [comment]
@JamesHobday21 You're looking into the old documentation, newest one: https://valor-software.com/ngx-bootstrap/#/tabs#select-event
