### ISSUE TITLE
Increase the Size of the Modal

### ISSUE THREAD

**Issue by jt4000** [valor-software/ng2-bootstrap#5345]
Goal:
Make modal as a large modal by using class "modal-lg"

Problem:
Don't know how to solve it when I tried using the syntax code "modal-lg" in different places.

Info:
*I'm new in angular
*Using VS code and ngx-bootstrap

Thank you!

https://stackblitz.com/edit/angular-nested-component-modal-ngx-bootstrap-not-working-ap7wnp

**Comment by ludmilanesvitiy** [comment]
There's no need to open an issue here if you want to ask general question, use StackOverflow or Slack instead
https://stackoverflow.com/questions/tagged/ngx-bootstrap
https://ngx-slack.herokuapp.com/
