### ISSUE TITLE
Why ukLocale was removed from chronos?

### ISSUE THREAD

**Issue by pbaukov** [valor-software/ng2-bootstrap#5351]
Hello there, I'm developer from Ukraine and I'm wondering why Ukrainian locale was removed? I see it was there like 1-1.5 years ago and now it's gone. How can I add my own locale to datepicker then?

**Comment by pbaukov** [comment]
Actually I see uk.ts localization file here, for example:
https://github.com/valor-software/ngx-bootstrap/blob/v5.1.0/src/chronos/i18n/uk.ts

But I don't see any "uk" files when I install latest ngx-bootstrap version

**Comment by pbaukov** [comment]
OK, as I see, it's just not added here
https://github.com/valor-software/ngx-bootstrap/blob/development/src/locale.ts

Is there any reason for that?

**Comment by ludmilanesvitiy** [comment]
@pbaukov If you need a new locale - you can create a PR with that change.
