### ISSUE TITLE
Dynamic containerClass in Tooltip not working Properly 

### ISSUE THREAD

**Issue by KrishnaRathore** [valor-software/ng2-bootstrap#5352]
Hi Team ,
When I click the button the tooltip class does not change.Until we move the cursor and move it back again on the button.

Stackbliz Demo - https://stackblitz.com/edit/angular-ngx-bootstrap-tooltip-containerclass-issue?file=app/class.html

**Comment by ludmilanesvitiy** [comment]
@KrishnaRathore You need to make this change in your template:
```<button type="button" class="btn btn-primary"
        tooltip="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." (click)="clicked=true;" containerClass="customClass">
  Demo with custom class
</button>
```
As shown in this example: https://valor-software.com/ngx-bootstrap/#/tooltip#custom-class

**Comment by ludmilanesvitiy** [comment]
quest
