### ISSUE TITLE
position datepicker dialog middle of screen or page

### ISSUE THREAD

**Issue by srijib** [valor-software/ng2-bootstrap#5359]
position datepicker calander middle of screen not working.  tried with renderer, jquery nothing works.
can not set these style properties
`top: 50%
  left: 50%
  transform: translate3d(50%, 50%)
`
I want the datepicker to open in the middle of screen like the way modal popup does
see below screen where the datpicker is appearing
![datepicker](https://user-images.githubusercontent.com/7030187/62831617-0dfb1b80-bc40-11e9-8d80-99c94e53e5b9.PNG)

`<input id="dashdate" type="text" disabled class='datepickerinput'          
             #dpr="bsDatepicker"
             bsDatepicker
             [bsValue]="bsValue"
             (onShown)="handler('onShown')"
             (onHidden)="handler('onHidden')">

        <ons-icon icon="ion-calendar" (click)="dpr.toggle()" [attr.aria-expanded]="dpr.isOpen"></ons-icon>
        <ons-icon icon="ion-calendar" (click)="dpr.toggle()" [attr.aria-expanded]="dpr.isOpen"></ons-icon>
 in my ts file
---------------
 handler(value: string): void {
    if('onShown' === value) {

      setTimeout(function(){
        $("bs-datepicker-container").removeAttr("style");ddstyle(); console.log('done')},1200)
      function ddstyle(){
        $("bs-datepicker-container").css('position', 'absolute')
        $("bs-datepicker-container").css('display', 'block')
        $("bs-datepicker-container").css('zoom', 1.6)
        $("bs-datepicker-container").css('top', "3px")

        /*const li = this.renderer.selectRootElement('bs-datepicker-container', true);
        this.renderer.setStyle(li, 'position', 'absolute')
        this.renderer.setStyle(li, 'top', '50%')
        this.renderer.setStyle(li, 'zoom', 1.6)
        this.renderer.setStyle(li, 'left', '50%')
        this.renderer.setStyle(li, 'transform', 'translate3d(50%,50%)')
        */
      }
      
   // }
  }`

**Comment by ludmilanesvitiy** [comment]
@srijib Could you, please create a reproduction for this issue on Stackblitz?

**Comment by srijib** [comment]
https://stackblitz.com/edit/angular-4xp3ex
https://angular-4xp3ex.stackblitz.io

In the example I am showing the selected date on the left of the screen ,green button which opens the calendar dialog, I want the dialog to appear at the middle of screen like modal dialog popup with black backdrop (similar to blue button)

**Comment by IraErshova** [comment]
@srijib Hi! Unfortunately, we don't have the option to set up the position for datepicker's container according to document. Also, you couldn't use renderer for this purpose because our renderer overwrites your styles.

Currently, we are not planning to add this feature to ngx-bootstrap. But if you have desire you can create a PR with functionality, which allows doing this.

The only way to overwrite these css properties for datepicker's container is to use ViewEncapsulation.None and important in your styles.
