### ISSUE TITLE
Blur event inconsistent on typeahead

### ISSUE THREAD

**Issue by kameelyan** [valor-software/ng2-bootstrap#5360]
### Bug description or feature request:
Typeahead blur event seems very inconsistent.

### Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-7spriy

With developer console open:

- In the typeahead, enter 'il' to get the results Illinois. Without selecting Illinois, click outside the box. --> **Blur Event works properly**
- Clear the entry and in the typeahead, enter 'il' again. With the results open, hit tab to exit the box. --> **Blur event does not fire.**
- In the typeahead box, with 'il' already entered, enter 'z' (to give 'ilz' in the box). No results are found, and exit the box via click or tab. --> **Blur event does not fire.**

I would expect all these events to fire a blur event.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: ^5.1.1

Angular: ~8.0.1

Bootstrap: 4

**Comment by daniloff200** [comment]
hello, @kameelyan , I've checked the scenario, you've described, and yes, case 2 and 3 are not handled for now

Just want to be clear, how you can see the result of blur event in this cases

For 
`Clear the entry and in the typeahead, enter 'il' again. With the results open, hit tab to exit the box. --> Blur event does not fire.
`
it should return  **Illinois** too , right?

For 

`In the typeahead box, with 'il' already entered, enter 'z' (to give 'ilz' in the box). No results are found, and exit the box via click or tab. --> Blur event does not fire.`

it should return the typeahead value, like **ilz** in this case, or, it's better to return just **null** value / empty object?? 

Thanks again for finding that, hope to fix that soon with your comments ! 


**UPD: no response for 3 weeks, so, gonna implement that in the way, mentioned above, and for the last case I will return user typed value, not null or some empty value**
