### ISSUE TITLE
Hello, i see http://ngx-bootstrap.com/#/modals cannot access

### ISSUE THREAD

**Issue by bestbelief** [valor-software/ng2-bootstrap#5361]
Hello
![image](https://user-images.githubusercontent.com/34058047/63071153-ab13c800-bf50-11e9-9b74-b83f7d789362.png)
This page(http://ngx-bootstrap.com/#/modals) cannot be opened, other pages can be opened normally.
Please have a look. Thank you.

**Comment by Domainv** [comment]
@bestbelief It's the wrong link.
Correct link to ngx-bootstrap is here https://valor-software.com/ngx-bootstrap/#/modals

**Comment by bestbelief** [comment]
@Domainv Ok，i get. Thank you very much
