### ISSUE TITLE
type ahead drop down width with template 

### ISSUE THREAD

**Issue by as-ghub** [valor-software/ng2-bootstrap#5363]
I am using type ahead from ngx-bootstrap 2.0 version with bootstrap 3. I have a template for drop down results inside which I have a custom component for showing the drop down result set. The width of the drop down is very less. The drop down shows a horizontal scroll because of size of my custom component element inside the template. I want to adjust the width of the drop down's container to match my custom component width but there seems to be no such option exposed. Also I had to embed a custom component inside the template because my component is a complex html with image and multiple text lines. Any suggestions on how to change the drop down width? Below is the sample code for my case: 
``` 
<input
    #input
    [(ngModel)]="value"
    [typeahead]="options"
    [typeaheadItemTemplate]="itemTemplate"
    class="form-control">

<ng-template #itemTemplate let-model="item" let-index="index">
<myCustom-Component [myInput]="item"> </myCustom-Component>
</ng-template>

```

**Comment by ludmilanesvitiy** [comment]
@anirudhsamudrala Hi! Please, take a look at similar questions and suggestions to resolving:
https://github.com/valor-software/ngx-bootstrap/issues/190
https://github.com/valor-software/ngx-bootstrap/issues/1519
If you still will have a problem - create a reproduction via Stackblitz, please. Thanks.
