### ISSUE TITLE
Date Range Picker: empty input field when editing date from input field

### ISSUE THREAD

**Issue by mentadev** [valor-software/ng2-bootstrap#5368]
### Bug description or feature request:
When editing the date right **from the input field** instead of using the picker on a Range Date Picker **with custom date format**, the input field is cleared/set to an empty string after pressing the enter key (i.e. when the focus is lost).

### Plunker/StackBlitz that reproduces the issue:
1. No need to use Plunkr or, StackBlitz, just go to the "Custom date format" section of the demo [web site](https://valor-software.com/ngx-bootstrap/#/datepicker#format)
2. Edit the Range Date Picker right from the input field instead of opening the picker and press the enter key. For instance just change the _"August 26th 2019, 11:16:31 am - August 26th 2019, 11:16:31 am"_ from 26 to 25 and press enter.
3. you will notice that the input field is now blank/empty

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.1.1

Angular: 8.0.2

Bootstrap: 4.3.1

**Comment by RizkyRajitha** [comment]
hi i am a new bee , 
how can i get  started with this issue

**Comment by Domainv** [comment]
https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md @RizkyRajitha

**Comment by lkreimann** [comment]
Can't really reproduce this. When I edit the date in the input field and hit enter, the date picker opens itself automatically. Which browser (& version) are you using? 
I used Firefox v69 to test this.

**Comment by vrchavez** [comment]
So should I make change in demo? Is that enough?

**Comment by GabriFedi** [comment]
I'll get it

**Comment by GabriFedi** [comment]
Here you go https://github.com/valor-software/ngx-bootstrap/pull/5423

**Comment by mentadev** [comment]
Sorry for this very late answer, I'm using Chrome. Versión 77.0.3865.120 (Build oficial) (64 bits)
