### ISSUE TITLE
Animated collapse: Remove overflow:hidden after animation

### ISSUE THREAD

**Issue by tinogo** [valor-software/ng2-bootstrap#5369]
# Bug description or feature request:

When using an animated collapse, the inline style `overflow: hidden` is being added. While the animation is running this is fine, but when the animation is finished this inline style should be removed again, as this causes elements which need to overflow (like custom autocomplete components) to be cutoff.

### Steps to repeat:
1. https://valor-software.com/ngx-bootstrap/#/collapse#animated
2. Hide the animated collapse
3. Show the animated collapse
4. Inspect the HTML-markup using the Browser developer tools

### Actual result:
`overflow: hidden` stays, even after the animation has finished.

### Expected result:
`overflow: hidden` gets removed after the animation has finished.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.1.1

Angular: 7.2.15

Bootstrap: 4.3.1

**Comment by ludmilanesvitiy** [comment]
@Domainv While investigating this issue, need to take care of Accordion, typeahead also. Behavior there the same as described above.

**Comment by varun2508** [comment]
Was this problem fixed? Cause i still can reproduce it
