### ISSUE TITLE
4.3 & 5 fail due to missing dependency error

### ISSUE THREAD

**Issue by mdentremont** [valor-software/ng2-bootstrap#5375]
Newer versions fail for me - does the README need "@angular/animations" to be added as a required dependency (or better yet, via the package.json so we don't need to explicitly install it)?

```
ERROR in ./node_modules/ngx-bootstrap/collapse/fesm5/ngx-bootstrap-collapse.js
Module not found: Error: Can't resolve '@angular/animations' in '<redacted>/node_modules/ngx-bootstrap/collapse/fesm5'
```

The error goes away after installing `@angular/animations`

**Comment by ludmilanesvitiy** [comment]
@mdentremont Only 4 components, for now, require animations module installed: Accordion, Collapse, Datepicker and Typehead. We added info about that in documentation, "Usage" block, like here: https://valor-software.com/ngx-bootstrap/#/typeahead 
But this info could be added to readme also, could it @Domainv ?

**Comment by daniloff200** [comment]
is it still an issue with 5.4.0???
