### ISSUE TITLE
[bug] tooltip with delay doesn't disappear

### ISSUE THREAD

**Issue by Darkein** [valor-software/ng2-bootstrap#5377]
### Bug description or feature request:
small bug with delayed tootips: If I set a delay of 1s then mouse over and mouse leave the element with tooltip fast, the tooltip appear after 1s but I can't hide it, except if I mouse over the element again.

If I mouse leave the element before the delay, the tooltip shouldn't appear.

You can reproduce it on the tooltip with delay exemple:
https://valor-software.com/ngx-bootstrap/#/tooltip#tooltip-delay

![peekJ67Z6Z](https://user-images.githubusercontent.com/4948463/64126671-f4687200-cdae-11e9-9d9d-7f89c552a3ec.gif)

it's maybe related to #5217 

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.1.1

Angular: 8

Bootstrap: 4.3

**Comment by ludmilanesvitiy** [comment]
@Darkein Hello! I can't reproduce the described issue in our Demo site.
![Peek 2019-09-16 10-16](https://user-images.githubusercontent.com/18209841/64939948-4c04e400-d86b-11e9-93e4-c599a0928128.gif)
Could you, please, specify your browser, version, OS, etc.?

**Comment by Darkein** [comment]
Hello @ludmilanesvitiy, you have to leave the button before the end of the delay.

I can reproduce it on Firefox and Chrome, under Linux, Mac OS and windows 10 ^^

**Comment by Darkein** [comment]
@ludmilanesvitiy have you been able to reproduce it ?

**Comment by ludmilanesvitiy** [comment]
Sorry, but I can't reproduce it @Darkein . @Domainv could you try, please?

**Comment by apotapcukv** [comment]
Dear Darkein! 
As per our check this issue is fixed in the latest version, so we’re closing the issue.
Please don’t hesitate to let us know if you face further issues.

**Comment by Darkein** [comment]
I can confirm it's fixed. Thanks a lot !
