### ISSUE TITLE
angular 8 property alert does not exist on type AlertComponent

### ISSUE THREAD

**Issue by radici** [valor-software/ng2-bootstrap#5388]
Hi whe deploy an application on angular 8 i give back the error message:
property alert does not exist on type AlertComponent.
I configured the app.module like the documentation and i created a component to use it by name AlertComponent.
When i run the app with angular-cli it work fine.
Thanks

**Comment by ludmilanesvitiy** [comment]
@radici Hello. Could you, please, add reproduction somewhere? On stackblitz, for example. And all related info needed: stacktraces, screenshots, versions, etc.
