### ISSUE TITLE
Popover delay option?

### ISSUE THREAD

**Issue by jziggas** [valor-software/ng2-bootstrap#5389]
Tooltips have a `[delay]="500"` input but I was surprised to see that popovers don't have the same feature?

**Comment by daniloff200** [comment]
closed in #5582

**Comment by amiram** [comment]
Well, after my pull request was merged, I discovered it didn't help me. The thing I wanted is to not open the popover if the user just moved the mouse over the element for a very short time. This delay just delayed the opening of the popover but eventually the popover showed up after some time, even though the mouse was already far from the element.
If you want to not show the popover if the mouse was over the element just for a short time, you can use the following code:

```
<a #pop="bs-popover"
    [popover]="popTemplate"
    [outsideClick]="true"
    (click)="false"
    (mouseenter)="showPop()"
    (mouseleave)="onPopMouseLeave()"
    triggers=""
    href="#">
    <i class="fas fa-some-icon"></i>
</a>
<ng-template #popTemplate>
    <div>some template</div>
</ng-template>
```

In component:

```
popMouseLeft: boolean;
@ViewChild('pop', {static: false}) pop: PopoverDirective;

showPop() {
    this.popMouseLeft = false;

    setTimeout(() => {
        if (!this.popMouseLeft && this.pop) {
            this.pop.show();
        }
    }, 500);
}

onPopMouseLeave() {
    this.popMouseLeft = true;
}
```

**Comment by daniloff200** [comment]
Thanks for that, @amiram !
