### ISSUE TITLE
Datepicker doesn't auto hide in modal

### ISSUE THREAD

**Issue by vdumbrav** [valor-software/ng2-bootstrap#5390]
### Bug description:
If datepicker is in modal, it will not automatically close when scrolling

### StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-b9dgrt
https://media.giphy.com/media/Tg6ggvlMjz9NQTX0MM/giphy.gif

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.1.2

Angular: 8.2.6

Bootstrap: 4.3.1

**Comment by gagandeepp** [comment]
Assign this to me

**Comment by vdumbrav** [comment]
@ludmilanesvitiy

**Comment by ludmilanesvitiy** [comment]
I can't add assignee, but @Domainv should have this possibility.

**Comment by gagandeepp** [comment]
In progress

**Comment by Hrtkk** [comment]
Hey, can I work on it??

**Comment by vdumbrav** [comment]
@gagandeepp @daniloff200 in progress?

**Comment by daniloff200** [comment]
@vdumbrav he removed his assignment,  you can pick it, if you want 😀

**Comment by IraErshova** [comment]
@vdumbrav Hi! The issue why your datepicker doesn't hide on a scroll is caused your HostListener is listening to **window:scroll**. Window scroll is hidden when you open the modal.
```
.modal-open {
    overflow: hidden;
}
```
I think you can use rxjs operator **fromEvent** to listen to the modal's scroll.

**Comment by OwenLin-lwc** [comment]
@vdumbrav Do you solve your issue? If yes, could you kindly share how you do it?
I tried another way to open modal by component and have the same situation.
https://stackblitz.com/edit/angular-ivy-2swahw

@IraErshova Can you reopen this issue, I still don't know how to fix it
