### ISSUE TITLE
Datepiker & Modal

### ISSUE THREAD

**Issue by CN-Tower** [valor-software/ng2-bootstrap#5398]
runtime.23000ea1cc0ae59dbc67.js:1 GET http://ngx-bootstrap.com/components-datepicker-demo-datepicker-module-ngfactory~components-tabs-demo-tabs-module-ngfactory~co~83964347.70e893fc289904f9ed86.js net::ERR_ABORTED 403 (Forbidden)

vendor.66a2ea0be208de0e7b59.js:1 ERROR Error: Uncaught (in promise): Error: Loading chunk 1 failed.
(error: http://ngx-bootstrap.com/components-datepicker-demo-datepicker-module-ngfactory~components-tabs-demo-tabs-module-ngfactory~co~83964347.70e893fc289904f9ed86.js)
Error: Loading chunk 1 failed.
(error: http://ngx-bootstrap.com/components-datepicker-demo-datepicker-module-ngfactory~components-tabs-demo-tabs-module-ngfactory~co~83964347.70e893fc289904f9ed86.js)

**Comment by ludmilanesvitiy** [comment]
@CN-Tower Hi! What is your issue? How to reproduce it? Create a reproduction via Stackblitz, please.

**Comment by CN-Tower** [comment]
> @CN-Tower Hi! What is your issue? How to reproduce it? Create a reproduction via Stackblitz, please.

It seems something wrong with the document webset. I can't open the `Datepiker` & `Modal` page.
