### ISSUE TITLE
Update Slack Link in or website and docs or delete completely

### ISSUE THREAD

**Issue by olierxleben** [valor-software/ng2-bootstrap#5416]
### Bug description or feature request:

Clicking on the Slack-Link either in the Docs or on the Website (upper right corner) you will get a new tab where slack shows it is not an active invitation anymore. 

Same behavior in README file. Potentially, on all links to slack community

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.2.0

**Comment by olierxleben** [comment]
Is there a slack community available?

I would like to handle it if one can say which way to go (deleting or updating)

**Comment by daniloff200** [comment]
Oh yeah, that looks outdated. I'm gonna ask for a new link
