### ISSUE TITLE
DataPicker Error Context

### ISSUE THREAD

**Issue by Master-Antonio** [valor-software/ng2-bootstrap#5417]
Hello, im using your datapicker for my form, load the graphic, but i cant scroll the month, the month is blocked in October. Looking the console of Chrome, i see a Error Context.

![Error3](https://user-images.githubusercontent.com/9674957/66107989-d49cb780-e5c1-11e9-9ac3-662b57a1de70.png)

![Error](https://user-images.githubusercontent.com/9674957/66107866-97382a00-e5c1-11e9-80f8-3b4403c0d5e3.png)

![Error2](https://user-images.githubusercontent.com/9674957/66107892-9dc6a180-e5c1-11e9-8fa4-4e63a6a8eb81.png)

 ```
<input type="text" placeholder="Data" class="form-control" bsDatepicker
                 [bsConfig]="{isAnimated: true, adaptivePosition: true, dateInputFormat: 'DD/MM/YYYY', containerClass: 'theme-dark-blue'}"
                 [bsValue]="bsValue">
```
### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.1.2
 
Angular: 8.2.8

Bootstrap: 4.3.1

Thanks so much for your help.

**Comment by daniloff200** [comment]
hello, @Master-Antonio , can you please share Plunkr or Stackblitz with reproduction? 
also, what do you mean by **scroll the month** ?

**Comment by Master-Antonio** [comment]
There was a error with other components of angular, isn't a your error, sorry so much, you can close the issue.  Thanks for your support.
