### ISSUE TITLE
Error  Argument of type in Modal

### ISSUE THREAD

**Issue by oveshparasara** [valor-software/ng2-bootstrap#5430]
i have set configuration modal
const  config = {
      keyboard: false,
      backdrop: 'static',
      class: 'paymentModal'
    };
    this.bsModalRef = this.modalService.show(PaymentPopupComponent , config);

then error:
 error TS2345: Argument of type '{ keyboard: boolean; backdrop: string; class: string; }' is not assignable to parameter of type 'ModalOptions'.
  Types of property 'backdrop' are incompatible.
    Type 'string' is not assignable to type 'boolean | "static"'.

**Comment by gsoares85** [comment]
How i fix this?

**Comment by dmaf87** [comment]
Hi @oveshparasara.
How you solved this issue?
