### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by anandprabhakar0507** [valor-software/ng2-bootstrap#5434]

**Comment by anandprabhakar0507** [comment]
How to add a label Hacktoberfest in a issue..? help..

**Comment by daniloff200** [comment]
@anandprabhakar0507 you can't do that, because you don't have access for it.

What's the reason of that issue?

**Comment by daniloff200** [comment]
@anandprabhakar0507 
hello?

**Comment by daniloff200** [comment]
closed for inactivity and empty description
