### ISSUE TITLE
Updating type of progressbar dynamically removes striped and animate configuration

### ISSUE THREAD

**Issue by rits-development** [valor-software/ng2-bootstrap#5437]
### Bug description or feature request:
Dynamically changing the type (info/success/warning/error) of a progressbar removes the striped and animate configuration. 

### Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-zsvgbv?file=app%2Fngx-bootstrap-demo.component.ts

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.2.0

Angular: 8.0.0

Bootstrap: 4.0.0

### Build system: Angular CLI, System.js, webpack, starter seed:
Forked from this stackblitz example: https://valor-software.com/ngx-bootstrap/#/progressbar#bs3-dynamic

**Comment by vitaliy-bobrov** [comment]
I'd like to take this one ;)

**Comment by daniloff200** [comment]
@vitaliy-bobrov  wow wow wow ! :D 
Nice to meet ya here :100:
