### ISSUE TITLE
Correct grammatical mistake in readme

### ISSUE THREAD

**Issue by parammittal16** [valor-software/ng2-bootstrap#5438]
### Bug description or feature request:

There are some grammatical issues in Readme file.
I want to correct them and work on this issue as of Hackoberfest.

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.2.0

Angular: 8.0.0

Bootstrap: 4.0.0

**Comment by parammittal16** [comment]
@Domainv plz review. Can we add hacktoberfest label here

**Comment by parammittal16** [comment]
@daniloff200 plz let me know an changes to the PR (#5439 ) so it can be merged

**Comment by preethi900** [comment]
I would like to work on this issue.Is it still available ??

**Comment by NeelPrime** [comment]
I am also working on this. #5459 #5459 #5462

**Comment by NeelPrime** [comment]
> I am also working on this. #5459

#5434
