### ISSUE TITLE
Constant expression should not be used in the conditional statements

### ISSUE THREAD

**Issue by chawdamrunal** [valor-software/ng2-bootstrap#5447]
''passada la ' +(m.hours() !== 1)' is always true because it evaluates to a non-empty string.

src/chronos/test/locale/ca.spec.ts (line : 208)

('passada la ' +(m.hours() !== 1)

This rule applies when a condition check has always the same result.

For example, it occurs when constant-valued variables are used or the condition is redundant with previously checked one. This rule also applies when only one case is executed due to the result of switch condition check being always the same.

It could be a debugging code, but at worst it is a programmer's mistake that completely misses block of code intended to be executed.

**Comment by danmana** [comment]
I think this is a false positive.
The full line is:
```
assertEq(m.calendar(), m.format('[el] dddd [' + ('passada la ' +(m.hours() !== 1) ? 'passades les' : '') + '] LT'), 'Today - ' + i + ' days end of day');
```

Which compares:
`m.calendar()` to `m.format('[el] dddd [' + ('passada la ' +(m.hours() !== 1) ? 'passades les' : '')`

Even if the second part is always the same, the `m.calendar()` is dynamic.

More so, the second part is not always fixed: in the first comparisson (line 204) hours is unset and defaults to the current hour, which might be 1 or not depending on when the test is ran. Only on lines 206 and 208 hours is fixed and !== 1


I think this is ok as it is

**Comment by daniloff200** [comment]
I also think, that this is not needed right now. We've got a lot more work to do
