### ISSUE TITLE
Adding a better and more descriptive slack button.

### ISSUE THREAD

**Issue by sakkshm** [valor-software/ng2-bootstrap#5453]
### Bug description or feature request:
Adding a better and more descriptive slack button.

I would like to do this!

Can we add the hacktoberfest label to it?

**Comment by Innovator007** [comment]
Hi @daniloff200 Is this issue done or i can work on it?

**Comment by sakkshm** [comment]
@innovator007 I have already made the PR but they have not reviewed it till now.
