### ISSUE TITLE
wrong file name

### ISSUE THREAD

**Issue by sameshl** [valor-software/ng2-bootstrap#5456]
### Bug description or feature request:
wrong file name `doc/spec/tooltip/tooltip.examles.placement.use-case.md`

need to change it to `tooltip.examples.placement.use-case.md`

is it possible to add `hacktoberfest` label to it?

**Comment by hasalassh** [comment]
@sameshl Let me work on this...!

**Comment by hasalassh** [comment]
@sameshl I have created a pull request for this...!
https://github.com/valor-software/ngx-bootstrap/pull/5472

**Comment by sameshl** [comment]
@hasalassh I had already created a PR for this here https://github.com/valor-software/ngx-bootstrap/pull/5457. It is already been approved. Nice work but next time just check if there are any existing PRs for the issue you are taking up.

**Comment by ahdyt** [comment]
Lol, why the issue still open????
