### ISSUE TITLE
Improve the readability of the README file.

### ISSUE THREAD

**Issue by srivastavaayu** [valor-software/ng2-bootstrap#5478]
I want to improve the readability of the README file.
Can I work on this? And can the Hacktoberfest label be added to this issue?

**Comment by daniloff200** [comment]
A lot of people want to do that, if you open pull requests :rofl: 

Can you give more info about your improvements?

**Comment by srivastavaayu** [comment]
Improve and elaborate sentences defining the product, elaborate license details(which right now are close to non-existent) and of course, improve grammatical mistakes. 🤣

**Comment by srivastavaayu** [comment]
Should I start working on this? @daniloff200
