### ISSUE TITLE
.toggle() doesn't work

### ISSUE THREAD

**Issue by AlMorton** [valor-software/ng2-bootstrap#5497]
Here is my html mark up.
`<div class="agent-details-text" [popover]="detailsTemplate" #detailPop="bs-popover" [outsideClick]="true"
        placement="right" adaptivePosition="true" (click)="detailPop.toggle()">
        <div class="agent-details-name">
            <span>{{agent.surname}}, {{agent.forename}}</span>
        </div>
        
        <ng-template #detailsTemplate>
            <div class="popover-content">
                <ul>
                    <li><label>Team: </label>{{agent.team}}</li>
                    <li><label>Campaign: </label>{{agent.campaign}}</li>
                    <li><label>Agent Id: </label>{{agent.sourceAgentId}}</li>
                </ul>
                <button mat-raised-button type="button" (click)="detailPop.toggle()">Close</button>
            </div>
        </ng-template>
    </div>`

However toggle refuses to work.
If I change both to, "detailPop.hide()", it works!?
This completely flies in the face of the documentation.

**Comment by apotapcukv** [comment]
Hi, @AlMorton! We can’t reproduce the issue now in the latest version to check if it has been fixed or not. If you still can, please do it at https://stackblitz.com/edit/angular-ivy-de1elj?file=tsconfig.json/ and share with us,  looking at toggle functionality in docs https://valor-software.com/ngx-bootstrap/#/popover#triggers-manual. 
Please don’t hesitate to let us know if you face further issues. Thank you for using our library).
