### ISSUE TITLE
Inline DateRange Picker double click on same date

### ISSUE THREAD

**Issue by jdpapa** [valor-software/ng2-bootstrap#5502]
Hi, 

I am having an issue on user experience because if the date range is on the same date, the user needed to click it twice. The problem is if the user click once, bsValueChange will not emit and the new date range will not reflect.

Is there a workaround on it? Or can i request for an event emitter when click once or the user make new action? (Any other alternatives that solves my issue.)

What I really want is to disable the apply button on the screenshot if the user only click once.

![image](https://user-images.githubusercontent.com/33341391/66916275-79e96e00-f04d-11e9-9dee-174b9d11e05f.png)

**Comment by latusdenis** [comment]
@jdpapa Hey! Did you manage do find a solution?

**Comment by valorkin** [comment]
this was an iOS related issue, fixed and merged
