### ISSUE TITLE
Use float: right for datepicker's arrows

### ISSUE THREAD

**Issue by Dommar92** [valor-software/ng2-bootstrap#5511]
**Description:**
Issue: When clicking the "next month" arrow on the right, the length of month's name changes, causing the year and "next month" button to jump around. Not possible to quickly zap through the months.

Solve by: 
```
.bs-datepicker-head button.next{
    border-radius: 50%;
    width: 30px;
    height: 30px;
    float: right;
}
```

respective the `button.previous` needs to be isolated.

Thanks.

**Comment by daniloff200** [comment]
Strange one , @Dommar92 
Can you share a small video, or, demo, when it's happening? I can't see that on our demo, and can quickly zap through the months 
Check this video, please : https://www.loom.com/share/8e7b0da7d23b4fa5a29227ac985b053d

**Comment by Dommar92** [comment]
Hi @daniloff200 
I did not manage to reproduce it outside of my project, so I believe it's some side effect in conflict with bad naming in the project, none of your business ;) Issue can be closed.

[https://streamable.com/d76lm](https://streamable.com/d76lm)
