### ISSUE TITLE
Albanian Language needed

### ISSUE THREAD

**Issue by ghost** [valor-software/ng2-bootstrap#5541]
Please add the Albanian Language (sq) to this project!

**Comment by daniloff200** [comment]
Hey @EctabyteSrl .
Unfortunately,  nobody from our core team know Albanian 
 Do you know Albanian ? You can create a PR with a localization, we will be happy to merge it
I also can share some Pea with localizations as example for you

**Comment by ghost** [comment]
Thanks a lot, yes I know Albanian, but I don't know how can I contribute here..
Please give me the steps to start working on it!

**Comment by daniloff200** [comment]
@EctabyteSrl well, our README.md should help you to setup the project locally, and https://github.com/valor-software/ngx-bootstrap/blob/development/CONTRIBUTING.md should help to understand how  to contribute 

Also, check https://github.com/valor-software/ngx-bootstrap/pull/5432 or https://github.com/valor-software/ngx-bootstrap/pull/5387 to  check, how to add locale properly:)

**Comment by ghost** [comment]
@daniloff200 thank you!

**Comment by daniloff200** [comment]
hey, @EctabyteSrl  I saw, that @agoncecelia make a PR with Albanian locale, but, that has broken unit test. Could you help with that?
