### ISSUE TITLE
Nested modal with scrollbar makes second modal not centered

### ISSUE THREAD

**Issue by bacmanni** [valor-software/ng2-bootstrap#5552]
Bug description:
When opening first modal with so big content that it uses scrollbar and opening nested dialog over that one the nested dialog is not centered. 

Took a screenshot from ngx-bootstrap documentation page with added text
![image](https://user-images.githubusercontent.com/2714736/69216917-053aaf80-0b76-11ea-9d42-4e182a593814.png)

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.3.2

Angular: The one used on ngx-bootstrap documentation page

Bootstrap: 4.0.0

**Expected behavior**
Should be centered :)

**Comment by IraErshova** [comment]
@bacmanni Hi! Unfortunately, this issue happens because of bootstrap's styles, which we use in our library not because of our functionality. I can advise you to overwrite bootstrap's styles to fix this problem:
```
.modal-open .modal {
    overflow-y: scroll;
}
```
If you add these styles, your problem is gone.

**Comment by khaukheng** [comment]
> @bacmanni Hi! Unfortunately, this issue happens because of bootstrap's styles, which we use in our library not because of our functionality. I can advise you to overwrite bootstrap's styles to fix this problem:
> 
> ```
> .modal-open .modal {
>     overflow-y: scroll;
> }
> ```
> 
> If you add these styles, your problem is gone.

This doesn't look like a real fix. The scrollbar will be visible for every modal even though those modal only have a short content.
