### ISSUE TITLE
Delayed tooltips not removed

### ISSUE THREAD

**Issue by mikaelagr** [valor-software/ng2-bootstrap#5554]
Bug description:

Plunker/StackBlitz that reproduces the issue. Hover over the box and notice how the tooltip count (in positioningservice) increases.
https://stackblitz.com/edit/ngx-bootstrap-hanging-tooltip

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.3.2

Angular: 8

Bootstrap: 3

Build system: Angular CLI, System.js, webpack, starter seed:
webpack

We had a performance issue which we narrowed down to the tooltips. We noticed that PositioningService.calcPosition was being called, calculating the position of a lot of tooltips. We could however not see any visible tooltips.

After some investigation it seemed like some of our delayed tooltips were not being properly removed. It occured where the target element was removed before the tooltip was displayed.

The only way we could see it was through the calls to calcPosition which caused performance degradation which was quite noticeable with 20-30 tooltips which should have been destroyed.

**Comment by RobertasM** [comment]
Same here, any solution how to fix it?

**Comment by RobertasM** [comment]
Found temporary fix for it if someone else will have same problem:

```
 ngOnDestroy(): void {
        setTimeout(() => {
            if (this.tooltipDirective.isOpen) {
                this.tooltipDirective.ngOnDestroy();
            }
        }, this.delay);
    }
```

**Comment by valorkin** [comment]
hello, closing as duplicate, there are an issue with linked PR https://github.com/valor-software/ngx-bootstrap/issues/5572

**Comment by PapaNappa** [comment]
@valorkin  is this really a duplicate? #5572 is about a new feature (hide tooltip even when mouse is not moved), while this is about a bug in a different feature (delay showing of tooltip leads to memory leak).
The other issue also does not mention any related bug.

Please re-open, as this is technically not a duplicate at all.

**Comment by valorkin** [comment]
@PapaNappa it's literally the same function responsible for this
