### ISSUE TITLE
Accessibility attributes when creating modal with Component?

### ISSUE THREAD

**Issue by esoyke** [valor-software/ng2-bootstrap#5557]
**How can you specify aria-labelledby when passing component to modal service?**

The Accessibility documentation states:

> Be sure to add role="dialog" and aria-labelledby="...", referencing the modal title, to .modal, and role="document" to the .modal-dialog itself. Additionally, you may give a description of your modal dialog with aria-describedby on .modal.

I am creating my modals by passing Components to the modal service. How is it possible to set values on .modal or .modal-dialog when the component is nested under .modal > .modal-dialog > .modal-content > my-component ?

**Comment by IraErshova** [comment]
@esoyke Thanks for your question! I've added the functionality. It will be available in the next release.
