### ISSUE TITLE
User is allowed to type Alphabets in DatePicker.

### ISSUE THREAD

**Issue by sijusamson** [valor-software/ng2-bootstrap#5558]
Bug description:  If you go to datePicker and start typing characters in it, it accepts it and then you select any date, its reflected as Invalid Date. 

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.2.0

Angular: 8

Bootstrap: 4.3.1

Build system: Angular CLI, System.js, webpack, starter seed:

**Expected behavior**

User can type numerical values but he should be restricted to type alphabets.

**Comment by daniloff200** [comment]
related to #5576

maybe, will be fixed via #5577
