### ISSUE TITLE
No space possible for `<input>` element in tab heading

### ISSUE THREAD

**Issue by stefanmeschke** [valor-software/ng2-bootstrap#5559]
## Bug description

For a custom tab heading with an input element. It is not possible to insert a space in this input.
It seems that the space is not possible because of this code block:

https://github.com/valor-software/ngx-bootstrap/blob/161f419c67daed188ad7a936aad4875f2cbc4dd5/src/tabs/tabset.component.ts#L101-L107

### Plunker/StackBlitz that reproduces the issue
https://stackblitz.com/edit/angular-kkt91e

### Versions
ngx-bootstrap: 5.2.0
Angular: 8.2.13

## Expected behavior

Input with space should be possible or it would be very nice to disable the whole key navigation.

**Comment by stefanmeschke** [comment]
I fixed it with:

**Template**
`<input (keydown)=keydown($event) … />`

**Component**
```
import { includes } from 'lodash';

…

public keydown(event: KeyboardEvent) {
  if (includes(['Space', 'ArrowLeft', 'ArrowRight'], event.code)) {
    event.stopPropagation();
  }
}
```

But I think an option to disable the keyboard events would be very very nice. ;)


Cheers
SM

**Comment by fhuschle** [comment]
I started reviewing/reproducing this issue. I think it can be closed as it can be fixed with the TabsetConfig.isKeysAllowed property or did i miss something?
