### ISSUE TITLE
Does ngx-bootstrap has an option to use it in rtl languages ?

### ISSUE THREAD

**Issue by samhoseinkhani** [valor-software/ng2-bootstrap#5560]
i'm using it in Angular 8 
i expect it to has a config like this :

@NgModule({
  imports: [
    NbThemeModule.forRoot(nbThemeOptions, nbJSThemes, nbMediaBreakpoints, 'rtl')
  ]
})

which i can tell it whether it should be rtl or ltr and it handles the rest  ...
does it have sth similar ?

**Comment by ddawsari** [comment]
Did you get your answer on this?

**Comment by valorkin** [comment]
it depends on css (bootstrap) we use
but we don't have any particular switch for it
