### ISSUE TITLE
Daterangepicker: Max date range feature

### ISSUE THREAD

**Issue by JelleVisser** [valor-software/ng2-bootstrap#5562]
**Is your feature request related to a problem? Please describe.**
We would like to be able to enforce that a selected date range is not larger then for example "6 months". 

**Describe the solution you'd like**
Setting this value would allow you to select any date between the existing `minDate`/`maxDate`, after selecting the first date the dates that don't fall within the `maximumDateRange` would be disabled

**Describe alternatives you've considered**
I tried to modify the `minDate`/`maxDate` after selecting the first date of the dateRange. But I didn't see any callback or method that responds to selecting the first date

**Comment by daniloff200** [comment]
There's look like https://github.com/valor-software/ngx-bootstrap/issues/5636, but, we don't have such functionality yet :(

**Comment by arvindm95** [comment]
@daniloff200 If this feature is approved, Can I work on this?

**Comment by daniloff200** [comment]
@arvindm95  yeah, that will be very cool!!!
Feel free to pick it, I very appreciate it!

**Comment by cwilsn** [comment]
@arvindm95 - the opposite of this would be super helpful for us.  We need a way to enforce a minimum date range (eg user must pick at least a week).  Is that something that could be easily worked in while you are on it?
