### ISSUE TITLE
Wrong date with custom date formats with DateRangePicker

### ISSUE THREAD

**Issue by ChrisCherryfarmer** [valor-software/ng2-bootstrap#5564]
Hi,

I found **a severe issue** with custom date formats.

When you set a custom dateRangeFormat and change the value of the yeah in the input field, the Datepicker gets confused and changes month and day.

**Steps to reproduce**

1. Go to https://valor-software.com/ngx-bootstrap/#/datepicker
2. Got to section Custom date format
3. Select Date range on custom format field: e.g. 2019-12-01 to 2019-12-05. Value in input field is "December 1st 2019, 8:17:52 am - December 5th 2019, 8:17:52 am"
4. change the year to 2020 in input field with keyboard and click outside
5. Input field value is: "January 20th 2019, 12:00:00 am - May 20th 2020, 12:00:00 am"

The date range picker confuses month and day.
This happens also with other custom date-formats. (e.g: DD-MM-YYYY)

**Comment by daniloff200** [comment]
Woah
That's actually happened, even if you just copypaste any date over there
I've tried just to paste **February 1st 2019, 8:17:52 am - February 5th 2019, 8:17:52 am** in input, and got the same result

**Comment by daniloff200** [comment]
well, that was fixed in #5423, but, not released right now
I hope, new version with this fix will be available next week.
