### ISSUE TITLE
Can't access NgbDatePicker ViewChild in modal template [Angular 8]

### ISSUE THREAD

**Issue by jenswet** [valor-software/ng2-bootstrap#5565]
Hey folks,

I am trying to migrate to Angular 8 and experiencing the following issue:

I use a slightly modified version of this https://stackblitz.com/edit/angular-datetimepicker?file=src%2Fapp%2Fdate-time-picker%2Fdate-time-picker.component.ts date-timepicker combination.

It worked fine with Angular 7. With Angular 8 the
`@ViewChild(NgbDatepicker)
private dp: NgbDatepicker;`
does not work anymore. It's always undefined no matter in which context. I tried it with `{static: false}` and `{static: true}`, but it never works.
Does anyone has a hint how to fix this?

Thanks!

**Comment by fabio984** [comment]
Same problem. Any solution?

**Comment by cgasis** [comment]
having the same problem, anyone?

**Comment by cgasis** [comment]
> Hey folks,
> 
> I am trying to migrate to Angular 8 and experiencing the following issue:
> 
> I use a slightly modified version of this https://stackblitz.com/edit/angular-datetimepicker?file=src%2Fapp%2Fdate-time-picker%2Fdate-time-picker.component.ts date-timepicker combination.
> 
> It worked fine with Angular 7. With Angular 8 the
> `@ViewChild(NgbDatepicker) private dp: NgbDatepicker;`
> does not work anymore. It's always undefined no matter in which context. I tried it with `{static: false}` and `{static: true}`, but it never works.
> Does anyone has a hint how to fix this?
> 
> Thanks!

have you resolved this?

**Comment by jenswet** [comment]
No sorry. Could not resolve it yet.

**Comment by cgasis** [comment]
> No sorry. Could not resolve it yet.

i tried removing this line and it works. 

this.dp.navigateTo({ year: this.datetime.year, month: this.datetime.month });

**Comment by jenswet** [comment]
> > No sorry. Could not resolve it yet.
> 
> i tried removing this line and it works.
> 
> this.dp.navigateTo({ year: this.datetime.year, month: this.datetime.month });

Yes, I did the same to get the code running again. But it does not resolve the issue. We just don't use the possibility to work on the datepicker in code anymore with this workaround.
The metioned navigateTo would navigate the datepicker to the newly typed date in the textfield, which would still be nice. But I don't know how to get access to the datepicker in code, when the ViewChild is not working.

**Comment by IraErshova** [comment]
Hi @jenswet! You used **ng-bootstrap** instead of **ngx-bootstrap** in your stackblitz example. It's totally different libraries. 

But **ngx-bootstrap** could have the same issue. If you try to get access via **ViewChild** to any element inside the modal you get undefined. It happens because the modal is appended to body element. It's outside the component when you open it. You can fix this issue by using [static modal](https://valor-software.com/ngx-bootstrap/#/modals#directive-static). Or you can find the element by using renderer2

I've created an example with datepicker inside the modal. Could you check it, please?
https://stackblitz.com/edit/angular-xxrqdg

**Comment by jenswet** [comment]
Hi @IraErshova, sorry for the late reply. I worked on other projects. I could fix it now. Thanks!

Is there a major difference between the frameworks / a good reason for me to switch?

**Comment by DerZyklop** [comment]
@jenswet Congrats that you could fix it. For me and other people, that will probably stumble upon this issue… how did you solve it?

**Comment by DerZyklop** [comment]
I solved it, too. 

I don’t use Bs Modal, so @IraErshova’s solution was not fitting to/possible for me. 

I had something like this:

```typescript
…
@ViewChild('datepickerRef') datepickerRef;

onSetToSuggestedDate() {
  this.date = this.suggestedDate;
  this.datepickerRef.navigateTo(this.date);
}
…
```

and 

```html
…
<ng-template #modalContent let-c="close" let-d="dismiss">
  <button (click)="onSetToSuggestedDate()">Set to suggested date</button>
  …
  <ngb-datepicker
    #datepickerRef
    formControlName="date"
  ></ngb-datepicker>
  …
</ng-template>
…
```

It crashed because it is not possible to get the reference via ViewChild while it’s inside a ng-template. 

But this worked for me:

```typescript
…
onSetToSuggestedDate() {
  this.date = this.suggestedDate;
}
…
```

and

```html
…
<ng-template #modalContent let-c="close" let-d="dismiss">
  <button (click)="onSetToSuggestedDate();datepickerRef.navTo()">Set to suggested date</button>
  …
  <ngb-datepicker
    #datepickerRef
    formControlName="date"
  ></ngb-datepicker>
  …
</ng-template>
…
```

**Comment by jenswet** [comment]
> @jenswet Congrats that you could fix it. For me and other people, that will probably stumble upon this issue… how did you solve it?

Well, I both tried ngx-bootstrap and ng-bootstrap in my project and had less problems in my use case with ng-bootstrap. That's probably not the kind of fix that helps you... Sorry!
