### ISSUE TITLE
Retrieve user input value on Datepicker prior to autocorrecting the value to "Invalid Date".

### ISSUE THREAD

**Issue by lydiacodesdaily** [valor-software/ng2-bootstrap#5567]
I have reviewed the documentation and the datepicker itself, but couldn't find anything where I could retrieve user input value prior to autocorrect. 

I do not want to disable the autocorrect, but would like to retrieve the user input value on datepicker prior to the autocorrect, so that the user input can be displayed on a custom validation message and show the user input data instead of "Invalid date".

**Comment by valorkin** [comment]
hello, in existing implementation there are no such option
