### ISSUE TITLE
Typeahead performance regression > 100 items

### ISSUE THREAD

**Issue by Marcisbee** [valor-software/ng2-bootstrap#5569]
## Bug description:
The problem is that typeahead components performance got worse since v5. With more than 100 items in the list it loads very slow.

### v4.3.0
![4 3](https://user-images.githubusercontent.com/16621507/70706737-2eff7600-1cdf-11ea-91a7-002045c97f5f.gif)

### v5.x.x
![5 3](https://user-images.githubusercontent.com/16621507/70706750-3b83ce80-1cdf-11ea-945a-e833beca84c9.gif)

**Note**: Gif speed was not altered!

## Plunker/StackBlitz that reproduces the issue:
- 5.2.0 (latest) - https://stackblitz.com/edit/angular-13mykh | _slow_
- 5.3.2 (next) - https://stackblitz.com/edit/angular-13mykh-whhjen | _slow_
- 4.3.0 - https://stackblitz.com/edit/angular-13mykh-h2qfxe | _fast_

In all 3 examples codebase is exactly the same, only version of `ngx-bootstrap` package is changing.

Click on "input" field to see how slow the list opens.

## Versions of ngx-bootstrap, Angular, and Bootstrap:
- ngx-bootstrap: 5.x.x
- Angular: 8.0.0

**Comment by Harmades** [comment]
The typeahead seems slow because of the interaction between `TypeaheadContainerComponent` and its dependency `PositioningService`, introduced in #5240.

Here's a working workaround (insert in your module file), which empties the positioning service :
```typescript
import { TypeaheadModule, TypeaheadConfig } from 'ngx-bootstrap/typeahead';
import { ComponentLoaderFactory } from 'ngx-bootstrap/component-loader';
import { PositioningService } from 'ngx-bootstrap/positioning';
import { Observable, empty } from 'rxjs';

const emptyPositioningService = {
  setOptions(i: any) {},
  position(o: any) {},
  addPositionElement(o: any) {},
  get event$(): Observable<number|Event> { return empty(); },
  calcPosition() {},
  deletePositionElement(e: any) {},
  enable() {},
  disable() {}
};

const typeaheadModule = {
  ngModule: TypeaheadModule,
  providers: [ ComponentLoaderFactory, { provide: PositioningService, useValue: emptyPositioningService }, TypeaheadConfig ]
};

@NgModule({
  ...
  imports: [
    ....
    typeaheadModule
  ]
  ....
})
```

**Comment by Marcisbee** [comment]
Is there a plan to fix this in library without using a workaround?

**Comment by Harmades** [comment]
#5589 fixes this issue 👍

**Comment by daniloff200** [comment]
Yeah, I suppose, that in ver 5.5.0 that issue should be resolved, or, at least, performance should be better
