### ISSUE TITLE
Incompatibility tooltip and modal

### ISSUE THREAD

**Issue by harikasin** [valor-software/ng2-bootstrap#5573]
**Bug description:**

I have a modal with a confirm button and the button has a tooltip. When I press the button to confirm,  and the loop in the method _getOffsetParent()_ from **ngx-bootstrap-positioning.js** it gets crazy because the modal is hidden and don't find the parent of the tooltip.
The code of the infinite loop is:

`while (offsetParent === noOffsetParent && element.nextElementSibling) {
        sibling = element.nextElementSibling;
        offsetParent = sibling.offsetParent;
    }`

It works with old versions but with the current version which you can see in the StackBlitz below it doesn't.

**StackBlitz that reproduces the issue:**

https://ngx-bootstrap-issue-tooltip-with-modal.stackblitz.io

**Versions of ngx-bootstrap, Angular, and Bootstrap:**
ngx-bootstrap: "^3.3.0"
Angular: "7.3.9"
Bootstrap: "^4.3.1"
Build system: Angular CLI: "@angular/cli": "7.3.9"

**Expected behavior**
Use at the same time a button for closing with a tooltip inside a modal.

**Comment by harikasin** [comment]
Sorry, with the last version it doesn't fail: "ngx-bootstrap": "5.2.0".

**Comment by harikasin** [comment]
The error persist with the updated versions. 

**Versions of ngx-bootstrap, Angular, and Bootstrap:**
- "@angular/cli": "8.3.20"
- "bootstrap": "^4.3.1"
- "ngx-bootstrap": "^3.3.0"

**Comment by IraErshova** [comment]
@harikasin Hi! Your StackBlitz link doesn't work, unfortunately. Do you have the same use case as in this demo? Could you check it, please?
https://valor-software.com/ngx-bootstrap/#/modals#modal-with-popups

**Comment by IraErshova** [comment]
Close issue because of inactivity
