### ISSUE TITLE
dropdown is not animating when opening

### ISSUE THREAD

**Issue by marcelvarela** [valor-software/ng2-bootstrap#5581]
**Versions of ngx-bootstrap, Angular, and Bootstrap**

- ngx-bootstrap: 5.2.0
- bootstrap: 4.2.0
- Angular: 8.2.14

**Comment by MVDeveloper1** [comment]
> **Versions of ngx-bootstrap, Angular, and Bootstrap**
> 
> * ngx-bootstrap: 5.2.0
> * bootstrap: 4.2.0
> * Angular: 8.2.14

**Comment by marcelvarela** [comment]
I found that Animation in the dropdown is only available from version 5.3.0 but I was at version 5.2.0 and npm did not show any updates.
