### ISSUE TITLE
Error when importing BsDatepickerModule.forRoot() on angular9.rc

### ISSUE THREAD

**Issue by tiaroque** [valor-software/ng2-bootstrap#5585]
I' am getting the following error when using the Date Picker module in the new version of angular

Symbol BsDaterangepickerInlineContainerComponent declared in /node_modules/ngx-bootstrap/datepicker/themes/bs/bs-daterangepicker-inline-container.component.d.ts is not exported from ngx-bootstrap

**Comment by MaGnaL** [comment]
I could work around this by importing `BsDatepickerModule` from `ngx-bootstrap/datepicker` instead of `ngx-bootstrap`.

```
import {BsDatepickerModule} from 'ngx-bootstrap/datepicker';
```

For me that worked, but should be fixed in the library anyway.

**Comment by petebacondarwin** [comment]
Looks like this file needs to be updated with more exports - https://github.com/valor-software/ngx-bootstrap/blob/5846bf2934c7f3ecbdf3e9a2edc48adbfe4f016f/src/index.ts#L49-L66

**Comment by malkaviano** [comment]
> I could work around this by importing `BsDatepickerModule` from `ngx-bootstrap/datepicker` instead of `ngx-bootstrap`.
> 
> ```
> import {BsDatepickerModule} from 'ngx-bootstrap/datepicker';
> ```
> 
> For me that worked, but should be fixed in the library anyway.

At least fix the documentation, only one import works.

**Comment by daniloff200** [comment]
I think, that was updated in https://github.com/valor-software/ngx-bootstrap/pull/5663 and in next release docs will contain information, about not using old kind of imports with NG9
