### ISSUE TITLE
feat(datepicker): selectWeek returns whole week

### ISSUE THREAD

**Issue by An-MS** [valor-software/ng2-bootstrap#5588]
Is it possible for the selectWeek functionality to return the whole week instead of the first day of the week in the **daterangepicker**?

Currently selectWeek uses the same event as normal selections, so there is no way do differentiate if a week was selected or a day/range.

**Comment by daniloff200** [comment]
That's interesting, @An-MS 
selectWeek returns not exactly first day of the week, but, first available (perhaps, first, or first & second days were disabled).

I supposed, you talking about DateRangePicker, because, I don't completely get, how we should return the whole week in DatePicker. Please, correct me, if I wrong 

But, how do you see it? Array of dates, or, just a range, like 01/20/2020 - 01/27/2020 ?

**Comment by daniloff200** [comment]
looks like can be related to https://github.com/valor-software/ngx-bootstrap/issues/5539

**Comment by gassmannT** [comment]
Interesting @An-MS We had a similar requirement. 

@daniloff200 
I think a minimal solution could be an array with two dates (range like 01/20/2020 - 01/27/2020) starting at the first available day. Like you select a range of dates.

**Comment by gassmannT** [comment]
> looks like can be related to #5539
I think the feature request doesn't correspond to this one. #5539 wants to highlight the whole week of every selected date. 

@An-MS wants to click on the week number and get the corresponding week selected.

**Comment by daniloff200** [comment]
Well, looks like that's actually two different features then, and both related to week selection

**Comment by An-MS** [comment]
@daniloff200 
Yes, @gassmannT is right. 

What I'd want to achieve is to select for example week 5 and I would get an array from bsValue with this content [01/27/2020, 02/02/2020].

Right now bsValue would return an array with two times the same date and because the same event is used for date selection/week selection you have no way to differentiate.

**Comment by daniloff200** [comment]
Well, let's try to implement it :)

**Comment by daniloff200** [comment]
will be available in next version (I suppose it wiil be 5.6.0) next week, or later

**Comment by An-MS** [comment]
@daniloff200 
Thanks for the update!

**Comment by Vinoth-deva** [comment]
Hi can you share How implement this?
@daniloff200

**Comment by daniloff200** [comment]
@Vinoth-deva  I think, if I answer, that, with your brain, and your hands, that will be not 100% correct answer. :smile: 
What do you want to know? 

You can check the implementation in PR, related to this issue.
