### ISSUE TITLE
Modal closing releasing mouse outside the modal

### ISSUE THREAD

**Issue by marcotuliocnd** [valor-software/ng2-bootstrap#5595]
Really annoying error, because that made me disable the backdrop on all modals in my application, there's any fix to this issue?

**Comment by daniloff200** [comment]
I think, that can be related to https://github.com/valor-software/ngx-bootstrap/issues/5264. 
If so, it's already merged to dev, and will be available very soon, in next release

**Comment by marcotuliocnd** [comment]
thank you

**Comment by daniloff200** [comment]
today we're gonna release a 5.5.0 version, and this fix will be there @marcotuliocnd

**Comment by DanBoSlice** [comment]
Thanks for the fix. When will version 5.5.0 be avaiable on NPM?

**Comment by daniloff200** [comment]
@DanBoSlice 5.5.0 already available with `latest ` tag
