### ISSUE TITLE
dropdown not displaying items added with ngIf

### ISSUE THREAD

**Issue by CueToDo** [valor-software/ng2-bootstrap#5602]
Items conditionally added to dropdown with *ngIf are not displayed

https://stackblitz.com/edit/angular-ngx-bootstrap-dropdown-conditional-items
https://angular-ngx-bootstrap-dropdown-conditional-items.stackblitz.io/

Updated to add *ngIf="true" on li element - still doesn't work

ngx-bootstrap: 5.4.0
Angular: 8.2.14
Bootstrap: 4.4.1

![Dropdown](https://user-images.githubusercontent.com/1644901/72686996-cb444600-3af1-11ea-93fe-ff8698db5222.JPG)

![missing item](https://user-images.githubusercontent.com/1644901/72687055-59b8c780-3af2-11ea-825a-e2752ca62a5f.JPG)

**Comment by evilstiefel** [comment]
This has to do with the recently added animation-feature with the dropdown list. If you set `isAnimated` to false, then the item shows up. There must be an error with either appending the items during the animation or calculating the height of the container for the animation.

**Comment by CueToDo** [comment]
Ah OK, that works fine without the animation, thanks.

**Comment by sonicpro** [comment]
I am going to investigate this.

**Comment by daniloff200** [comment]
Yes, @Dassderdie , I checked, this issue was fixed too
