### ISSUE TITLE
"Collapse" component breaks "Dropdown" component

### ISSUE THREAD

**Issue by ghost** [valor-software/ng2-bootstrap#5625]
Bug description:
When using the "Dropdown" component in the "Collapse" component, a bug occurs with the "Dropdown" display.

StackBlitz that reproduces the issue:
https://stackblitz.com/edit/ngx-dropdown-bug

**Bug Playback:**
1. On StackBlitz there is a window for viewing the example web page. In this window, find the "Example navbar" element.
2. The navbar element should have a button that allows you to collapse / expand the navbar. If this button is not present, then reduce the window for viewing the web page in the StackBlitz example so that this button appears.
3. Click on "Dropdown" button. A list with two links should open. Dropdown should work now.
4. Сollapse "Example navbar" using the button on the right, and then expand it back.
5. Click on "Dropdown" again. Now the list shouldn't show.

ngx-bootstrap: 5.5.0

Angular: 8.2.14

Bootstrap: 4.4.1

**Expected behavior**
The "Collapse" component shouldn't break the "Dropdown" component.

**Comment by masdevid** [comment]
Is there work around for it?

**Comment by ghost** [comment]
> Is there work around for it?

I've already done pull request
