### ISSUE TITLE
Display single calendar with date range picker

### ISSUE THREAD

**Issue by arun-maddheshia** [valor-software/ng2-bootstrap#5631]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add an option for a single calendar with date range functionality? It would be great for mobile visibility and usability. 

**Describe the solution you'd like**
Look like something
<img width="298" alt="Screenshot 2020-01-31 at 10 33 08 AM" src="https://user-images.githubusercontent.com/5073214/73513828-2e4cab80-4415-11ea-8bb2-d4da685caf95.png">

**Comment by daniloff200** [comment]
hi, @arun-maddheshia , but how about the case, when you want to select a range from Jan 17, to, Feb 17, for example?

**Comment by arun-maddheshia** [comment]
hi @daniloff200 the arrow keys are there to move next/prev month

**Comment by daniloff200** [comment]
Well, gonna see next week, what can be done to make it work

**Comment by daniloff200** [comment]
@arun-maddheshia  I've suddenly found, that this logic was already implemented. That was not so clear in docs, but, we have **displayMonths** which by default for daterRangePicker is 2, but, you can change it with bsConfig

just pass the property `displayMonths : 1` there

https://valor-software.com/ngx-bootstrap/#/datepicker#bs-datepicker-config

**Comment by arun-maddheshia** [comment]
@daniloff200 thanx :) perfect what i am looking for.

**Comment by daniloff200** [comment]
good:) gonna close it then
