### ISSUE TITLE
Error with datepicker of ngx-bootstrap@latest After upgrading to version 9.0.0-rc.8

### ISSUE THREAD

**Issue by shivaji33** [valor-software/ng2-bootstrap#5653]
ERROR in Symbol BsDaterangepickerInlineContainerComponent declared in X/node_modules/ngx-bootstrap/datepicker/themes/bs/bs-daterangepicker-inline-container.component.d.ts is not exported from ngx-bootstrap (import into X)

**Comment by pgarzina** [comment]
experiencing the same issue

**Comment by adventmedia** [comment]
similar problem with final release of 9.0.0

**Comment by IraErshova** [comment]
Hi @shivaji33 ! Could you please provide a minimal reproduction example in Stackblitz? You can use my template
https://stackblitz.com/edit/github-5cak2w

**Comment by shivaji33** [comment]
it's working fine in new angular application but not working in the existing application. plz find the below image.
![Screenshot from 2020-02-10 17-54-41](https://user-images.githubusercontent.com/52051484/74149892-df7ded80-4c2e-11ea-9618-b722353e2abe.png)

**Comment by dgsqrs** [comment]
same problem with a working Angular 8 app. Upgrade to Angular 9 initiate this issue.

**Comment by RuneSP** [comment]
It works for me with Ivy after changing this 
`import { BsDatepickerModule } from 'ngx-bootstrap'` to 
`import { BsDatepickerModule } from 'ngx-bootstrap/datepicker'`

https://github.com/valor-software/ngx-bootstrap/pull/5268#issuecomment-502142482

**Comment by shivaji33** [comment]
Hey it's working thanks 😀

**Comment by Polantaris** [comment]
This resolved the issue for me as well, it looks like the top level 'ngx-bootstrap' import is no longer working as expected. Although, importing at that level doesn't allow proper tree-shaking from what I understand so it's probably not a good idea to use it anyway.

**Comment by IraErshova** [comment]
Angular 9 **doesn't support** such imports:
`import { ... } from 'ngx-bootstrap'`
We are going to update the documentation to mention this case. Thanks, everyone!

**Comment by ofeliperr** [comment]
Thank you! importing BsDatepickerModule this way worked here!
