### ISSUE TITLE
Tabset with Flexbox

### ISSUE THREAD

**Issue by StefanKoenigMUC** [valor-software/ng2-bootstrap#5654]
Hi all,

I've got a problem during use of tabset with a flexbox layout:

```  <div class="display: flex; flex-direction: column; flex: 1; height: 100%;">
                 <div style="flex: 1"></div>
                 <div class="box-bottom" style="flex: 1; height: 100%;">
                                   <tabset>
                                        <tab heading="Summary" id="summaryTab"></tab>
                                        <tab heading="Summary2" id="summaryTab2"></tab>
                                   </tabset>
                  </div>
     </div>
```
Size of those tabs (in special "div.tab-content") is always 0.

Do you have any suggestions how i can improve that, so that tab-content uses all available space for its content?

Thanks in advance,

**Comment by StefanKoenigMUC** [comment]
a little help brought this to me:

` <tab heading="Summary" id="summaryTab" style="height: 100%; min-height: 100%;">`

with this (global) CSS:

```
/*** workaround for ngx-tabset **/
.tab-content {
  min-height: 95%;
  height: 95%;
}
```

but i don't this solution as it seems very hacky (and i cant use 100% for height, as 100% will cause an overflow).

Do you have any advice? :/

**Comment by IraErshova** [comment]
@StefanKoenigMUC Hi! Could you please provide a minimal reproduction example in stackblitz? Because I can't understand the issue you have. You can change my example:
https://stackblitz.com/edit/angular-sjd5a7

**Comment by StefanKoenigMUC** [comment]
Thanks a lot for your reply. Indeed the issue is a bit different and i'm not sure now if its a problem with ngx-bootstraps component or ag-grid.

Unfortunately i cannot save/fork the given stackblitz (temporarily problems?), but i made the following changes to reproduce the behavior:

1) Install ag-grid
2) Change styles.sccs to
```
@import "~ag-grid-community/dist/styles/ag-grid.css";
@import "~ag-grid-community/dist/styles/ag-theme-balham.css";

body {padding: 30px; position: relative}
```

3) change DemoTabsBasicComponent to
 ```
   columnDefs = [
        {field: 'make' },
        {field: 'model' },
        {field: 'price'}
    ];

    rowData = [
        { make: 'Toyota', model: 'Celica', price: 35000 },
        { make: 'Ford', model: 'Mondeo', price: 32000 },
        { make: 'Porsche', model: 'Boxter', price: 72000 }
    ];

```
  change markup to
```
<div style="flex: 1">
  <div class="box-bottom" style="flex: 1; height: 100%;">
    <tabset>
      <tab heading="Summary" id="summaryTab">
          <ag-grid-angular
              style="width: 100%; height: 100%;"
              class="ag-theme-balham"
              [rowData]="rowData"
              [columnDefs]="columnDefs">
          </ag-grid-angular>
      </tab>
      <tab heading="Summary2" id="summaryTab2">Content 2</tab>
    </tabset>
  </div>
</div>
```

thanks so much for your help!

if i enforce tab content so a specific hight, it's working again, but without that ag-grid resolves 100% to 0 pixels.

Do you have any idea about that?

**Comment by IraErshova** [comment]
@StefanKoenigMUC Thanks for your reply! I check your code and the problem not in ngx-bootstrap but in `ag-grid-angular` component. Could you please check my example?
https://stackblitz.com/edit/angular-sjd5a7

If you don't use height 100% then you see the table otherwise there is nothing
