### ISSUE TITLE
production build failure because missing hidden property on TypeaheadContainerComponent

### ISSUE THREAD

**Issue by vindemasi** [valor-software/ng2-bootstrap#5662]
Bug description: Compiling my app with 'ng build --prod' fails with error:
  
**ERROR in (1,1): Directive TypeaheadContainerComponent, Property 'hidden' does not exist on type 'TypeaheadContainerComponent'.**

The issue appears using AOT compilation. Simply adding an 'hidden' property to TypeaheadContainerComponent solve the issue.

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.4.0

Angular: 8.2.14

Bootstrap: 4.3.1

Build system: Angular CLI

**Expected behavior**

'ng build --prod' should complete without error.

**Comment by daniloff200** [comment]
Hi @vindemasi ! 
That issue was fixed in https://github.com/valor-software/ngx-bootstrap/pull/5616, and already available in 5.5.0

**Comment by vindemasi** [comment]
Hello @daniloff200 sorry for the noise, bad search on issues using 'TypeaheadContainer' instead 'typeahead'. I'll close the issue.
