### ISSUE TITLE
Selected Input There Is No Datepicker

### ISSUE THREAD

**Issue by tahsincagrizorkol** [valor-software/ng2-bootstrap#5669]
Hello,

I added datepicker module in app.module.ts 

After that added this code my ts file: 
`public bsInlineValue = new Date();`
`public bsInlineRangeValue: Date[];`
`public maxDate = new Date();`

`constructor() {`
`super()`
`this.maxDate.setDate(this.maxDate.getDate() + 7);`
`this.bsInlineRangeValue = [this.bsInlineValue, this.maxDate];`
`}`

After that added this code my html file: 
`<input type="text" placeholder="Daterangepicker" class="form-control" bsDaterangepicker>`

When i run coded with `ng serve` in my local, there is a only input area. I clicked this input, but there is no datepicker. Only there is a blue border style. How can i resolve this problem?
![Screenshot_1](https://user-images.githubusercontent.com/1385157/74614915-166f6a00-512d-11ea-8ce5-4f252e6b706e.png)

**Comment by daniloff200** [comment]
hey, @tombultaho 

Could you please create a reproduction via Stackblitz? 
https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

Also, are there any errors in your console?

**Comment by tahsincagrizorkol** [comment]
> hey, @tombultaho
> 
> Could you please create a reproduction via Stackblitz?
> https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts
> 
> Also, are there any errors in your console?

Hi @daniloff200 

If I create new project, there is no problem. I tried to create new angular project and installed ngx-bootstrap and datepicker. 

Also I used material ui in my project. Could this be the cause of the problem? As you can see that there aren't any error in my console:

![Screenshot_1](https://user-images.githubusercontent.com/1385157/74649209-2ff5cd80-5190-11ea-930e-ac7ca72f1938.png)

**Comment by ABugajska** [comment]
@tombultaho does your browser freeze after clicking datepicker input?

**Comment by tahsincagrizorkol** [comment]
> @tombultaho does your browser freeze after clicking datepicker input?

i resolved this problem thank you so much for your message

**Comment by daniloff200** [comment]
can I close this Issue then @tombultaho ?

**Comment by tahsincagrizorkol** [comment]
> can I close this Issue then @tombultaho ?

of course.. thank you for everything
