### ISSUE TITLE
Datepicker Standard/Summer time offset handling issue

### ISSUE THREAD

**Issue by anton-horbachov** [valor-software/ng2-bootstrap#5672]
We use ngx-bootstrap(5.5.0) in our angular app(8.2.14) generated with angular-cli(8.3.21). (windows 10/x64. Chrome v80, Edge)
There is a problem with datepicker module: it miss Standard/Summer time offset...

According to business logic, user restricted to select date with interval:
min date equals current date - 6 month, 
max = current date + 2 month

We receive UTC date from API in [ISO 8601 format][1] ```yyyy-MM-dd'T'HH:mm:ss.SSS'Z'```, and saves in the  same format.

For example: Default date value is  ```2020-01-01T00:00:00.000Z``` (timezone offset equals +02:00)

The problem starts, when user change 
**Satndard time ('2020-01-01.000Z' +02:00)** to 
**Summer time ('2019-08-18.000Z' +03:00)**

UTC date displayed in [] brackets (whent date would be serialized it call ```Date.toJson() => Date.toISOString()```).

*minDate:* ```["2019-08-18T00:00:00.000Z"] Sun Aug 18 2019 03:00:00 GMT+0300 (Eastern European Summer Time)```

*maxDate:* ```["2020-04-18T23:59:59.000Z"] Sat Apr 18 2020 03:00:00 GMT+0300 (Eastern European Summer Time)```

*Date value:*

    ["2020-01-01T00:00:00.000Z"] Wed Jan 01 2020 02:00:00 GMT+0200 (Eastern European Standard Time)
					             ^^ correct time shift by default

*After change:*

    ["2019-08-17T23:00:00.000Z"] Sun Aug 18 2019 02:00:00 GMT+0300 (Eastern European Summer Time)
	          ^^ switch day(should be 18.08.2019)^^ - incorrect timeshift, should be 03:00:00 (equals to GMT+0300)

**Result:** ```2019-08-17T23:00:00.000Z``` is less than ```2019-08-18T00:00:00.000Z``` (minDate)

PS: in this case, datepicker used as part of reactive form (formControl), but when it used as templateDriven form control - results the same

Is it a bug ?

  [1]: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString

**Comment by anton-horbachov** [comment]
I apologize - the issue is inappropriate, the case is invalid.
The problem that I encountered is different (the date picker resets the time to zero in some cases).

**Comment by daniloff200** [comment]
@Anton-Gorbachev  no worries :)
