### ISSUE TITLE
Daterangepicker : Missing exports in public_api.d.ts

### ISSUE THREAD

**Issue by dgsqrs** [valor-software/ng2-bootstrap#5677]
Hi there

I'm trying to upgrade my app from Angular8 to Angular9 and I get an error. It seems there are two missing exports in the public_api.d.ts : BsDaterangepickerInlineContainerComponent, BsDaterangepickerInlineDirective.

I already update all my 'ngx-boostrap' imports with 'ngx-bootstrap/MODULE'

> ERROR in Symbol BsDaterangepickerInlineContainerComponent declared in /Users/xxx/front/node_modules/ngx-bootstrap/datepicker/themes/bs/bs-daterangepicker-inline-container.component.d.ts is not exported from ngx-bootstrap (import into /Users/xxx/front/src/app/plugin-booking/message-sender/message-sender.component.ts)

**Comment by IraErshova** [comment]
Hi @dgsqrs ! These classes are exported from [public_api.ts](https://github.com/valor-software/ngx-bootstrap/blob/development/src/datepicker/public_api.ts). You can check it in our repo.

Could you please provide a stackblitz example with a minimal reproduction?

**Comment by dgsqrs** [comment]
Well I tried to extract part of my application to reproduce the problem but it is too complicated.

When I try to start the angular app using the cli I get this message. 

ERROR in Symbol BsDaterangepickerInlineContainerComponent declared in /Users/XXXfront/node_modules/ngx-bootstrap/datepicker/themes/bs/bs-daterangepicker-inline-container.component.d.ts is not exported from ngx-bootstrap (import into /Users/XXX/front/src/app/plugin-booking/message-sender/message-sender.component.ts)
/Users/XXX/front/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:452
                finally { if (e_7) throw e_7.error; }

It seems that "something", inside ngx-boostrap, is using the 'ngx-bootstrap' import instead of a 'ngx-bootstrap/MODULE'. In fact, it is using the root public_api.d.ts where the 2 export are missing.

**Comment by dgsqrs** [comment]
The template is using a bsDaterangepicker directive
 `<input type="text"
           readonly="readonly"
           (bsValueChange)="copyToTimeslot($event)"
           class="form-control"
           #drp="bsDaterangepicker"
           bsDaterangepicker [(ngModel)]="bsRangeValue">`

but I don't know how Angular "import" the directive when it is used in a template

**Comment by IraErshova** [comment]
@dgsqrs Did you add datepicker component according to [Usage rule](https://valor-software.com/ngx-bootstrap/#/datepicker#usage) in our documentation?

Could you please check my example, I'm using your input from the message above:
https://stackblitz.com/edit/angular-c118ci-fqqrds
It works as expected. It would be easy to understand your problem if you provide a minimal reproduction

UPD: changed demo link

**Comment by IraErshova** [comment]
What version of ngx-bootstrap are you using?

**Comment by IraErshova** [comment]
> It seems that "something", inside ngx-boostrap, is using the 'ngx-bootstrap' import instead of a 'ngx-bootstrap/MODULE'.

There is no place in the code where we use such way of import.

**Comment by dgsqrs** [comment]
Thank you for your help. The problem was on my side. I check about wrong imports using ctrl+f of ngx-boostrap' and I forgot ngx-boostrap" where I had some results there. It seems it fixes my problem. Sorry for the noise.
