### ISSUE TITLE
BsInlineDatepicker datesDisabled doesn't update

### ISSUE THREAD

**Issue by lizlux** [valor-software/ng2-bootstrap#5678]
Bug description:
Updating `datesDisabled` after initialising the inline date picker doesn't have any affect on the UI. 

Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/angular-inline-datepicker-disabled-dates

ngx-bootstrap:
5.5.0
Angular:
8
Bootstrap:
3

**Expected behavior**
If I update the `datesDisabled` property I would expect the calendar to display the newly updated array of disabled dates. Instead, nothing happens. 

This PR https://github.com/valor-software/ngx-bootstrap/pull/5436 claims to fix the issue but I'm still seeing the bug in 5.5.0.

**Comment by sonicpro** [comment]
looking into this.

**Comment by daniloff200** [comment]
@lizlux  hey!
unfortunately, I can't open your stackblitz link, can you update it?

**Comment by lizlux** [comment]
@daniloff200 sorry about that. I've updated the link. Thanks!

**Comment by daniloff200** [comment]
@lizlux  yeah, I see
Well, gonna investigate what went wrong today. Thank you for reporting that!

**Comment by daniloff200** [comment]
hey, @lizlux !
Thanks again for finding this. I'm not sure what went wrong with #5436 , that worked before, but, right now it's not
The same thing also happening not only for [datesDisabled] property, but also for others, and also not only for datepicker, but, for daterangepicker too. 
I'm gonna create a PR with fixes, hope, it will be available in 5.6.0 version
