### ISSUE TITLE
Thai Buddish calendar on Datepicker show wrong on leap year

### ISSUE THREAD

**Issue by cityhunter44** [valor-software/ng2-bootstrap#5679]
Thai Buddish calendar show wrong on leap year in 2020.

![image](https://user-images.githubusercontent.com/7777538/74849727-a7cc1f80-536b-11ea-9298-bd2b013849f2.png)

**Comment by daniloff200** [comment]
Well, that looks weird :(

Unfortunately, we're not really have expertise with this kind of localisation, so, not sure, when it will be fixed. Perhaps, somebody from community can help with that

**Comment by daniloff200** [comment]
I'm actually had found a place, where it happened, gonna try to fix it started from Tuesday

**Comment by jonathansoong15** [comment]
I'm experiencing this problem as well. Thanks a lot in fixing the issue @daniloff200. May I know how long it takes for the fix to be available in the coming release?

**Comment by daniloff200** [comment]
not sure exactly, @jonathansoong15 ,  the work is still in progress on that issue.
Also, I don't know exactly where will be the next release, and will I able to finish this issue before the release

**Comment by tumit** [comment]
Hi @cityhunter44  @daniloff200 

I am the person who PR this feature and after analyze this problem I think I found solution for this issue at https://github.com/valor-software/ngx-bootstrap/pull/5715

if this look good enough please use this code.

Thanks

**Comment by daniloff200** [comment]
Released in 5.6.0
