### ISSUE TITLE
Today Date Button 

### ISSUE THREAD

**Issue by fawadtayyab123** [valor-software/ng2-bootstrap#5680]
How can i add today date button to bsDatePicke that user can easily select today date.
Thanks

**Comment by daniloff200** [comment]
hey!

We don't have such functionality right now
But!

We have a PR for it (which right now kind a broken https://github.com/valor-software/ngx-bootstrap/pull/5024) and also, we gonna have in next version  https://github.com/valor-software/ngx-bootstrap/pull/5580 this functionality, which actually can be used, but, it's only for daterangepicker...

**Comment by daniloff200** [comment]
Could be closed by https://github.com/valor-software/ngx-bootstrap/pull/5786
