### ISSUE TITLE
Inline datepicker on touch takes two taps to choose date

### ISSUE THREAD

**Issue by lizlux** [valor-software/ng2-bootstrap#5683]
Bug description:
On an iOS touch device you have to tap twice to select a date. Ideally you'd only have to touch once. 

Plunker/StackBlitz that reproduces the issue:
This is reproducible by running the documentation site on an iOS device, i.e: https://valor-software.com/ngx-bootstrap/#/datepicker#inline-datepicker

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:
5.5

Angular:
8

Bootstrap:
3

**Expected behavior**
One tap would select a date in the inline datepicker

Note there's a similar ticket regarding the regular date picker here https://github.com/valor-software/ngx-bootstrap/issues/2810. Unfortunately it's been open for 3 years. Hoping someone can fix this issue for both!

**Comment by keybong** [comment]
```
private onShowPicker() {
        let _this = this;
        function clickListener(e: any) {
            if(window.document.querySelector('bs-datepicker-inline bs-month-calendar-view')
            ||window.document.querySelector('bs-datepicker-inline bs-years-calendar-view')) return;

            if(e.srcElement.parentElement.tagName != 'TD') return;//Only TD > SPAN
            if(e.srcElement.tagName != 'SPAN') return;//Only SPAN
            if(e.srcElement.getAttribute('class')&&e.srcElement.getAttribute('class').indexOf('disabled')>-1)return;//Only Active Tag
            if(isNaN(e.srcElement.innerText)) return;//Only Number
            
            let headerText: string =window.document.querySelector('bs-datepicker-inline bs-datepicker-navigation-view')['innerText'];
            headerText=headerText.replace(/\n/gi,'');
            headerText=headerText.replace(/\s+/, '');
            headerText=headerText.replace(/\s+$/g, '');
            headerText=headerText.replace(/[^\d]/g, '');
    
            let year: any=headerText.substr(headerText.length-4);
            let month: any=headerText.split(year)[0];
            let day: any=e.srcElement.innerText;
    
            year=parseInt(year);
            month=parseInt(month)-1;
            day=parseInt(day);
    
            _this.bsValue=new Date(year, month, day);
        }
        window.removeEventListener('touchstart',clickListener);
        window.addEventListener('touchstart', clickListener);
    }
```

I know.. this is not answer it
I was in a hurry...

Somebody fix it!!!!!!!!!!!!

**Comment by trigonometric-act** [comment]
still waiting for solution

**Comment by trigonometric-act** [comment]
Aproach: 
ngAfterViewInit() {
 
    const iOS = /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream;
    if ( iOS === true  ) {
       // gets all days on calendar
      const allDays = this.elRef.nativeElement.querySelectorAll('.bs-datepicker-body table td');
      for (let i = 0; i < allDays.length; i++) { 
        // how do I handle the touchstart to be a click?
        allDays[i].addEventListener('touchstart', (e) => {

        });
      }

    }
  }

**Comment by daniloff200** [comment]
The issue is related to known problem, like, iOS double-tapping (for example, a lot about that can be found  [here ](https://stackoverflow.com/questions/17710893/why-when-do-i-have-to-tap-twice-to-trigger-click-on-ios))

I've to fix that in various ways, but, still no success, but, at least, I've found a bottle-neck in the logic 

Gonna continue to work on that next week

**Comment by trigonometric-act** [comment]
A possible workaround for angular while you fix It could be a hostlistener
for the class before the span tag of the day and try process the tap as
click?
