### ISSUE TITLE
error NG6002: Appears in the NgModule.imports of AdminModule, but itself has errors

### ISSUE THREAD

**Issue by ghost** [valor-software/ng2-bootstrap#5692]
**Description:**

importing datepicker module gives error NG6002:

error NG6002: Appears in the NgModule.imports of AdminModule, but itself has errors

**Comment by daniloff200** [comment]
hey @kevinkhagan 

Can you share some repro of this issue? 
Or, at least, some code, that you used, wanna check the imports, etc.

**Comment by daniloff200** [comment]
User was deleted... :crying_cat_face: 
So, looks like, I should close that
