### ISSUE TITLE
Display tooltip on selected date in datepicker

### ISSUE THREAD

**Issue by arun-maddheshia** [valor-software/ng2-bootstrap#5693]
**Is your feature request related to a problem? Please describe.**
I need to display tooltip on custom dates. Is there any existing method exist in https://valor-software.com/ngx-bootstrap/#/datepicker#date-custom-classes

**Describe the solution you'd like**
Good to have option like Content Template so we can replace the content of the datepicker.

```
  <ng-template #customDay
    let-date="date"
    let-currentMonth="currentMonth"
    let-currentYear="currentYear"
    let-selected="selected">
    <span class="custom-class"
      placement="top"
      tooltip="Vivamus sagittis">
      {{ date.day }}
    </span>
  </ng-template>
```

**Or** 

more config options to pass tooltip `tooltip="Vivamus sagittis"`
```
this.dateCustomClasses = [
      {
        date: twoDaysAhead,
        classes: ['bg-warning'],
        tooltip: 'Vivamus sagittis'
      },
      {
        date: fourDaysAhead,
        classes: ['bg-danger', 'text-warning'],
        tooltip: 'Vivamus sagittis'
      }
    ];
```

**Additional context**

<img width="553" alt="Screenshot 2020-02-27 at 1 17 05 PM" src="https://user-images.githubusercontent.com/5073214/75422843-781ca900-5963-11ea-99d7-c0e1cafa8dc0.png">

**Comment by sonicpro** [comment]
I am going to look at this.

**Comment by arun-maddheshia** [comment]
hi @sonicpro are you working on it sorry to ask but i have some requirement of this utility.

**Comment by imben1109** [comment]
could we do by existing datepicker component?

**Comment by arun-maddheshia** [comment]
@sonicpro any progress ?

**Comment by daniloff200** [comment]
Unfortunately, @sonicpro  will not able to work on that anymore.
Hope to pick that soon, but, not sure, when it will be finished, and released.

cc @arun-maddheshia

**Comment by arun-maddheshia** [comment]
@sonicpro any luck with this :blush:

**Comment by daniloff200** [comment]
Well, it's a tough one, and, unfortunately, @sonicpro  is no longer a library contributor.

I'm gonna try to look at this, and try to implement this, but, not sure when.

**Comment by daniloff200** [comment]
Okay,  so, I've finished that
Here's how it looks like right now.
![Peek 2020-08-06 22-48](https://user-images.githubusercontent.com/13692220/89585479-9528a280-d846-11ea-8a59-9b0111d9897d.gif)

Gonna be in next release, 6.1.0, which, hopefully, will be in next two weeks, or, in the worst scenario, this month

**Comment by uvojjala** [comment]
is this feature for **"Display tooltip on selected date in datepicker"** available now? if not when its going to be available? Please let me know as we need to use this feature in our application's datepicker asap in our current sprint. Please let me know. Thanks in advance!

**Comment by daniloff200** [comment]
@uvojjala  6.1.0 was released today, and available now

**Comment by uvojjala** [comment]
@daniloff200 - Thanks Dan FYI...

**Comment by uvojjala** [comment]
I have tried this new tooltip feature for specific date is working as intended
thanks so much for this. 

I have few things to clarify: 
1. nstead of tooltip can we display text on the specific date under the date?
2. is ngx-bootstrap/Calendar supports ADA Compliant and/or WCAG (https://www.w3.org/WAI/standards-guidelines/wcag/)  ?



thanks in advance!

**Comment by rhlkumar234** [comment]
is there a way to render html content inside the tooltip? The fix deployed seems to be working only for texts @daniloff200
