### ISSUE TITLE
[BUG] - Tooltip position itself incorrectly when element to have tooltip is inside of a 'scrollable div'.

### ISSUE THREAD

**Issue by classicmike** [valor-software/ng2-bootstrap#5707]
### Bug description:
We are using ngx-bootstrap to replicate Bootstrap's tooltips and we are experiencing bugs where the calculated postioning of the tooltip is incorrect, resulting in it being rendered at the wrong place. This only happens inside divs that have scrollable overflows such as ```overflow: auto```.

Here's the bug in action:
<img width="462" alt="Screen Shot 2020-03-06 at 8 08 48 pm" src="https://user-images.githubusercontent.com/1841040/76069020-56b46080-5fe6-11ea-8462-aaaca0edb1ef.png">

- [Link to the above screenshot's Stackblitz](https://stackblitz.com/edit/tooltip-in-overflow-div-bug-ngx-bootstrap-5-5-with-overflow)

Now if I take ```overflow: auto``` off the scrollable div, the tooltip renders correctly where the positions are perfect. See screenshot below:
<img width="464" alt="Screen Shot 2020-03-06 at 8 11 42 pm" src="https://user-images.githubusercontent.com/1841040/76069273-bad72480-5fe6-11ea-8147-1219e0315a00.png">
- [Link to the above screenshot's Stackblitz](https://stackblitz.com/edit/tooltip-in-overflow-div-bug-ngx-bootstrap-5-5-without-overflow)

After some initial investigations the bug seems to be caused by change introduced as part of some the positioning components of ngx-bootstrap used to power the positioining of tooltips. Please see this link here to the commit with the changes: [here](https://github.com/valor-software/ngx-bootstrap/commit/66ae92d804779b0244e97bff6032632165000932#diff-9fe3ac9a2449669aefa49cc4e91038ad). These changes were released as part of version 3.3.0. The previous release 3.2.0 does not show signs of the bug.

Below is version ```3.3.0``` showing the bug with ```overflow: auto```. Same as the latest version:
<img width="466" alt="Screen Shot 2020-03-06 at 8 15 35 pm" src="https://user-images.githubusercontent.com/1841040/76069641-4d77c380-5fe7-11ea-8051-9f8b9a96d712.png">
- [Link to the above screenshot's Stackblitz](https://stackblitz.com/edit/tooltip-in-overflow-div-bug-ngx-bootstrap-3-3-with-overflow)

Below is version ```3.2.0``` with no bug when ```overflow: auto``` applied to the scrollable div. This version does not have the positioning refactoring changes.
<img width="460" alt="Screen Shot 2020-03-06 at 8 24 16 pm" src="https://user-images.githubusercontent.com/1841040/76070366-82384a80-5fe8-11ea-8378-d3c30b076f83.png">
-[Link to the above screenshot's Stackblitz](https://stackblitz.com/edit/tooltip-in-overflow-div-bug-ngx-bootstrap-3-2-with-overflow)

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: Version 3.3.0 onwards

Angular: Stackblitzes were demoed using angular 8.2.14. However it's been replicated on earlier versions of Angular our installed version where bug was happening was 7.2.2

Bootstrap: 4.x

### A clear and concise description of what you expected to happen.
As with the above screenshots showing the correct behavior, tooltips with ```placement="right"``` and ```container="body"``` on elements placed inside of a scrollable div should be positioned directly to the right of the element, like as below:
<img width="464" alt="Screen Shot 2020-03-06 at 8 11 42 pm" src="https://user-images.githubusercontent.com/1841040/76069273-bad72480-5fe6-11ea-8147-1219e0315a00.png">

Hopefully this is enough information and test cases to start debugging this issue.

Thanks.

**Comment by dr-itz** [comment]
I can confirm this with popover, even when configured to attach the container to the `body`. What I noticed is that it also depends on the size of the containers, at a certain point things are done correctly.

**Comment by classicmike** [comment]
I've encountered a similar issue but through co-indicdence, I think I may have narrowed down the problem to some thing more easily explained.

So please be mindful that I've just only discovered it, but you guys might be somewhat aware of it already. Please feel free to point it out if so but I'm writing this comment with the assumption that nothing has been discovered behind the scenes.

So part of the problem is that **the width of the of the scrollable element is less than the width of the tooltip plus the visible content inside the scrollable div combined**.

Below is a link to a test where I gave the tooltip a width and gave the scrollable div (Sidebar) a width (194px) that can fit both the tooltip trigger element (Buttons) and  the tooltip itself (150px). The result is that the tooltip will position itself properly on the right, to the right of the tooltip trigger. 

See screenshot below:

<img width="825" alt="Screen Shot 2021-10-20 at 1 51 27 pm" src="https://user-images.githubusercontent.com/1841040/138021136-b13647bc-c8f0-43f4-b511-d45fbf29d1b0.png">

Stackblitz here:
https://stackblitz.com/edit/tooltip-in-overflow-div-bug-ngx-bootstrap-5-5-with-overf-nrgjxl?file=src/app/hello.component.css

The original replication of the problem had the scrollable div widths narrower than the room required for the tooltip, and the visible content of the scrollable div.

Screenshot and Stack Blitz here for comparison of both scenarios
<img width="462" alt="76069020-56b46080-5fe6-11ea-8462-aaaca0edb1ef" src="https://user-images.githubusercontent.com/1841040/138022145-84840b07-2663-432c-b6dc-48043d58bcad.png">

https://stackblitz.com/edit/tooltip-in-overflow-div-bug-ngx-bootstrap-5-5-with-overflow


I think a fix would have to be done in the PositioningService (I'm assuming that is the piece of code that controls the positioning right?) in the way how the position of the tooltips are calculated.

Hope this finds you well. Thanks

**Comment by UdayAppam** [comment]
Any update on this? @apotapcukv

**Comment by SvetlanaMuravlova** [comment]
@classicmike , hi) thank you for your issue. Try to add property "boundariesElement" for each tooltip element
example is here https://stackblitz.com/edit/angular-ivy-ipu3ds?file=src%2Fapp%2Fapp.component.html
But it should work from 8 version of the ngx-bootstrap
 
if it doesn't resolve your problem, let us know, please)

**Comment by niklas-dahl** [comment]
I am having the same problem but for some reason the `boundariesElement` option does not seem to be present in the 8.0.0 release. Speaking of the popover directive, this directive seems to be missing the option.
