### ISSUE TITLE
BsDatepicker position is not fixed IE

### ISSUE THREAD

**Issue by SelmaAhmetovic** [valor-software/ng2-bootstrap#5708]
BsDatepicker position is not fixed IE

Bug description:
When you click on input datepicker is showed not directly above input, but it's position is changing when you scroll the page
https://drive.google.com/drive/folders/12G39GpIQpan7QKnt5Vl3Zo7i3Rug3yP-?usp=sharing

ngx bootrsrap ~5.5.0
ngx-malihu-scrollbar ^9.0.0
angular ~8.2.10
boostrap ^4.4.1
angular cli ~8.3.9
node 10.15.1
os win10 64bit

expected behavior:
when you click on input datepicker shows directly above the input and it's position is fixed

**Comment by spahicharis** [comment]
I am facing same issue.

**Comment by apotapcukv** [comment]
Dear SelmaAhmetovic! 
As per our check this issue is fixed in the latest version, so we’re closing the issue.
Please don’t hesitate to let us know if you face further issues.
