### ISSUE TITLE
Inline datepicker fails to update some props (minMode, daysDisabled)

### ISSUE THREAD

**Issue by Pingolus** [valor-software/ng2-bootstrap#5714]
I'd like to update minMode at runtime with inline datepicker but it seems this is not working.

Demo  : https://stackblitz.com/edit/angular-7rl1ry 

I tried to guess where's the problem, I saw that inline directive doest not have input for minMode ; whereas standard directive has ; I don't know why ? 

EDIT : Same behavior for daysDisabled prop. So inline datepicker has not the same update behavior than standard one ?

**Comment by daniloff200** [comment]
I think, that it can be related to issues, fixed in https://github.com/valor-software/ngx-bootstrap/pull/5681 , but, this fix was not released yet.

I hope that new version will be this or next week

**Comment by daniloff200** [comment]
Should be good for now, please, check the latest version

In case this issue still exists, feel free to write about it here
