### ISSUE TITLE
Datepicker: Min-mode year alignment not in center

### ISSUE THREAD

**Issue by augustovandyk** [valor-software/ng2-bootstrap#5717]
I did look for duplicates but couldn't find anything that is still open, so please forgive me if there is anything.

Bug description:

This can be found on your website: 
https://valor-software.com/ngx-bootstrap/#/datepicker

Click on "Date Picker" under the Min-mode header an look at the year at the top of the datepicker.

ngx-bootstrap: 5.3.2 -> 5.5.0, 

Angular: 9.0.1

Bootstrap: 4.4.1

Build system: Angular CLI: 9.0.1

**Expected behavior**

It would be great if the year was centered :)

**Comment by Pingolus** [comment]
Waiting for a fix, I just added in my CSS : 

```
.theme-[name-of-your-theme] .bs-datepicker-head {
  text-align: center;
}
```
Nav buttons are centered too but it's better.

**Comment by apotapcukv** [comment]
Dear augustovandyk! As per our check this issue is fixed in the latest version, so we’re closing the issue.
Please don’t hesitate to let us know if you face further issues.
