### ISSUE TITLE
Setting default options for Modal?

### ISSUE THREAD

**Issue by ghost** [valor-software/ng2-bootstrap#5719]
**Description:**

How could I set modal default options, in other words, override `modalConfigDefaults`?

There is a [way](https://valor-software.com/ngx-bootstrap/#/tooltip#config-defaults) to do it for Tooltip component. Could we achieve a such with Modal?
Thanks.

**Comment by reinaldorauch** [comment]
I came here for the same thing as you but it seems there is an open PR implementing this: #4222 
Let's wait them to merge the pr

**Comment by eduardoluizm** [comment]
We have a problem with angular 10+

https://github.com/valor-software/ngx-bootstrap/pull/4222#issuecomment-701654195

**Comment by eduardoluizm** [comment]
@dkosasih Could you help me? the issue above..

**Comment by dkosasih** [comment]
Hi @eduardoluizm 
That is because the code is merged but I don't think that it's released yet. 
Latest ngx-bootstrap was released in Aug and the code was merged in Sept.

**Comment by eduardoluizm** [comment]
Thanks @dkosasih 

I tried to update my package to 6.2.0, released 5 days ago but still got problem.

ERROR in ./src/app/shared/shared.module.ts
Module not found: Error: Can't resolve 'ngx-bootstrap/modal/modal-options.class' in '/home/eduardo/p/src/app/shared'

cc @daniloff200

**Comment by dkosasih** [comment]
Hey @eduardoluizm 
It works when I test it. 
Angular ^10
Ngx-bootstrap 6.2.0
Maybe try to nuke your `node_modules` and try again. 
![image](https://user-images.githubusercontent.com/8027235/99145826-f671d480-26c5-11eb-845e-517ad3a16983.png)
![image](https://user-images.githubusercontent.com/8027235/99145832-04275a00-26c6-11eb-93ce-15df362ff60d.png)

**Comment by eduardoluizm** [comment]
> Hey @eduardoluizm
> It works when I test it.
> Angular ^10
> Ngx-bootstrap 6.2.0
> Maybe try to nuke your `node_modules` and try again.
> ![image](https://user-images.githubusercontent.com/8027235/99145826-f671d480-26c5-11eb-845e-517ad3a16983.png)
> ![image](https://user-images.githubusercontent.com/8027235/99145832-04275a00-26c6-11eb-93ce-15df362ff60d.png)

Thank you!

After restart my environment it worked (i dont know way, maybe some cache on 6.1.0).

Currently MODAL_CONFIG.. is imported from 'ngx-bootstrap/modal' instead 'ngx-bootstrap/modal/modal-options.class'

tks again!

**Comment by dkosasih** [comment]
> Currently MODAL_CONFIG.. is imported from 'ngx-bootstrap/modal' instead 'ngx-bootstrap/modal/modal-options.class'

That is intended I believe, because as of Angular 9, you are not encourage to do deep import.
