### ISSUE TITLE
Datepicker- Wrong week numbers in 2021

### ISSUE THREAD

**Issue by Layera1** [valor-software/ng2-bootstrap#5724]
Datepicker is showing wrong week numbers in 2021. 

![image](https://user-images.githubusercontent.com/62538488/77294250-3540bd80-6ce4-11ea-8797-f5ce89e2702a.png)

2020 is missing week 53 therefor all weeks in 2021 are off by one.

**Comment by daniloff200** [comment]
woah, thanks for finding this!

Gonna try to fix it in the nearest time

**Comment by Layera1** [comment]
Hi, is there any update on this?

**Comment by Layera1** [comment]
Work by changing Locale. Must have been using wrong, sorry!
