### ISSUE TITLE
Npm latest version 5.5.0 instead of 5.6.0

### ISSUE THREAD

**Issue by pmelisko** [valor-software/ng2-bootstrap#5734]
**Description:**
Hello, thanks for great work. There is some problem with npm publish, it still shows latest version 5.5.0, last deploy 8 days ago, version 5.6.0 tag created 8 days ago
<img width="927" alt="Screenshot 2020-03-27 at 23 34 31" src="https://user-images.githubusercontent.com/10432801/77805986-adf89e80-7083-11ea-83c2-ab0a54818d25.png">

**Comment by daniloff200** [comment]
It shows latest version, but, 5.6.0 was with a next tag
Right now we have 5.6.1 as a next with some important build fixes , if you're using Angular 9
