### ISSUE TITLE
Problem with import BsDaterangepickerInlineConfig in 5.6 version

### ISSUE THREAD

**Issue by jarekkowol** [valor-software/ng2-bootstrap#5735]
Bug description:
After upgrading to ngx-bootstrap to 5.6, I can't build the application. Problem with import BsDaterangepickerInlineConfig. Detailed description below:

That's how I import the package. (I think that's good)
<pre><code>
import {BsDatepickerModule} from 'ngx-bootstrap/datepicker';

imports: [
    BsDatepickerModule.forRoot(),
    ...
],

</code></pre>

<pre><code>
$ ng build --prod --aot=true --build-optimizer=true

 Date: 2020-03-29T18:04:55.412Z
 Hash: 0728670ed13e0d4c9221
 Time: 195701ms
 chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
 chunk {1} styles.16bcdbd3a9de669a78d7.css (styles) 71.4 kB [initial] [rendered]
 chunk {2} polyfills.0d15062993f573c5c1f8.js (polyfills) 67.9 kB [initial] [rendered]
 chunk {3} main.fb30bb3da70cdb671c5b.js (main) 3.63 MB [initial] [rendered]
 WARNING in ./src/app/app.module.ngfactory.js
 234:7211-7244 "export 'BsDaterangepickerInlineConfig' (imported as 'i87') was not found in 'ngx-bootstrap/datepicker'
 WARNING in ./src/app/app.module.ngfactory.js
 234:7246-7279 "export 'BsDaterangepickerInlineConfig' (imported as 'i87') was not found in 'ngx-bootstrap/datepicker'
 WARNING in ./node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.ngfactory.js
 359:246-290 "export 'BsDaterangepickerInlineContainerComponent' (imported as 'i1') was not found in 'ngx-bootstrap/datepicker'
 WARNING in ./node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.ngfactory.js
 361:132-176 "export 'BsDaterangepickerInlineContainerComponent' (imported as 'i1') was not found in 'ngx-bootstrap/datepicker
</code></pre>

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:
<pre><code>
5.6.0
</code></pre>

Angular:
<pre><code>
Angular CLI: 7.3.8
Node: 10.16.2
OS: darwin x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.0.0
@angular/cli                      7.3.8
@angular/material                 6.4.7
@angular/pwa                      0.12.4
@angular/service-worker           7.2.15
@ngtools/webpack                  6.0.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.8.3

</code></pre>

Bootstrap:
<pre><code>
^4.3.1
</code></pre>

**Comment by daniloff200** [comment]
I don't think, that, it's an issue, just a warning.
Anyway, it's with Angular 7, so maybe, this issue was already resolved in new Angular and in new ngx-bootstrap version. 
Could you, please, try to update? 

Also, will be very very cool, if you share with me some small repository with a reproduction, and I'll try to help you with that

**Comment by apotapcukv** [comment]
Dear jarekkowol! As per our check this issue is fixed in the latest version, so we’re closing the issue.
Please don’t hesitate to let us know if you face further issues.
