### ISSUE TITLE
5.6.1 Error compiling with "fullTemplateTypeCheck": true

### ISSUE THREAD

**Issue by cantacell** [valor-software/ng2-bootstrap#5740]
Angular CLI: 8.3.25
Node: 10.15.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.25
@angular-devkit/build-angular              0.803.25
@angular-devkit/build-optimizer            0.803.25
@angular-devkit/build-webpack              0.803.25
@angular-devkit/core                       8.3.25
@angular-devkit/schematics                 8.3.25
@angular/cli                               8.3.25
@angular/pwa                               0.803.25
@ngtools/webpack                           8.3.25
@nguniversal/express-engine                8.2.6
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        8.3.25
@schematics/update                         0.803.25
rxjs                                       6.5.2
typescript                                 3.5.3
webpack                                    4.39.2

Compiling using version 5.6.1 and with "fullTemplateTypeCheck": true in tsconfig.json it shows the following errors:

`ERROR in node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.d.ts.BsDatepickerContainerComponent.html(60,7): Property 'chosenRange' does not exist on type 'BsDatepickerCont
ainerComponent'.
node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.d.ts.BsDatepickerContainerComponent.html(62,7): Property 'setRangeOnCalendar' does not exist on type 'BsDatepickerContai
nerComponent'.
node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.d.ts.BsDatepickerInlineContainerComponent.html(60,7): Property 'chosenRange' does not exist on type 'BsDatepickerInlineC
ontainerComponent'.
node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.d.ts.BsDatepickerInlineContainerComponent.html(62,7): Property 'setRangeOnCalendar' does not exist on type 'BsDatepicker
InlineContainerComponent'.
`

**Comment by devailtonmereo** [comment]
Related:
#5730

**Comment by adros** [comment]
Can you publish new version (5.6.2) with this fix?
