### ISSUE TITLE
Angular 9 Support

### ISSUE THREAD

**Issue by ersimont** [valor-software/ng2-bootstrap#5744]
This feature request is not any kind of new idea, just an official request to support Angular 9.

On to the issue template!

**Is your feature request related to a problem? Please describe.**

My team would like to upgrade, but first we need our dependencies to support it. This library is the last one.

**Describe the solution you'd like**

I would like ngx-bootstrap to officially support Angular 9.

**Describe alternatives you've considered**

At this point I think we just wait. Eventually I suppose we'd have to consider migrating to another library that stays up to date ... but let's not get ahead of ourselves. :)

**Additional context**

I think we've more than covered it!

**Comment by daniloff200** [comment]
We have a PR, related to migration : https://github.com/valor-software/ngx-bootstrap/pull/5665 , but, it will be not merged for now, because, it will break the compatibility with 8 version, and all apps, which use Angular 8 will be not able to use ngx-bootstrap

**Comment by eric-simonton-sama** [comment]
I mean ... they would certainly still be able to use ngx-bootstrap - they just wouldn't be able to upgrade it (unless you release updates for both ngx-bootstrap 5 _and_ 6, but that may be overkill). Do you think there are many apps out there that would want to upgrade ngx-bootstrap but would not also want to upgrade Angular?

**Comment by daniloff200** [comment]
I'm not sure, why do you need full support of Angular 9 right now
As far, as I know, right now current version of ngx-bootstrap works with NG9 too. I worked on providing compatibility, and I see bunch of issues , when people mentioned, that they use library with Angular 9

Have you tried to add current version to your project? @ersimont @eric-simonton-sama

**Comment by eric-simonton-sama** [comment]
Your docs say this is for Angular 7-8, which is why I opened the ticket. If it works for 9 as well, I could change my request to be a simple doc update.

My team works on a large app. We're not in a good position to manually look through each widget on our site to see if any of them broke. From our side, we wait for libraries to give the official OK first.

**Comment by daniloff200** [comment]
Ah, yeah, docs right now are mess, and needs update :(

I've got your point and it's understandable. I hope that next week we finally make a decision, will this PR with official support merged, or not, and that will be  ngx-bootstrap 6.0.0 or not

**Comment by eric-simonton-sama** [comment]
Great - thank you for giving it the attention!

**Comment by douasin** [comment]
I got this error while following the document with angular 9

>  error NG8001: 'tabset' is not a known element:
> 1. If 'tabset' is an Angular component, then verify that it is part of this module.
> 2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
> 
> error NG8001: 'tab' is not a known element:
> 1. If 'tab' is an Angular component, then verify that it is part of this module.
> 2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.


angular version:

> Angular CLI: 9.1.1
> Node: 10.16.0
> OS: linux x64
> 
> Angular: 9.1.1
> ... animations, cli, common, compiler, compiler-cli, core, forms
> ... language-service, platform-browser, platform-browser-dynamic
> ... router
> Ivy Workspace: Yes
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.901.1
> @angular-devkit/build-angular     0.901.1
> @angular-devkit/build-optimizer   0.901.1
> @angular-devkit/build-webpack     0.901.1
> @angular-devkit/core              9.1.1
> @angular-devkit/schematics        9.1.1
> @ngtools/webpack                  9.1.1
> @schematics/angular               9.1.1
> @schematics/update                0.901.1
> rxjs                              6.5.5
> typescript                        3.8.3
> webpack                           4.42.0
>

**Comment by trt-joshh** [comment]
Do we have any updated on what @douasin posted?
I'm getting exactly the say issue implementing Tabs

**Comment by douasin** [comment]
Hi, @trt-joshh sorry that I forget to update. There's a missing import component bug in my project.
Although don't know why the error message like that.
The problem solved! Works fine in angular 9.1.1

**Comment by ewwwgiddings** [comment]
I think being compatible with Ivy is a default now. I can't update Angular because the file upload component does not seem to be compatible with it.

**Comment by lisandroprada** [comment]
I added .forRoot() and worked. (like recomends documentation. 
***************************************************************
// RECOMMENDED
import { TabsModule } from 'ngx-bootstrap/tabs';
// NOT RECOMMENDED (Angular 9 doesn't support this kind of import)
import { TabsModule } from 'ngx-bootstrap';

@NgModule({
  imports: [TabsModule.forRoot(),...]
})
export class AppModule(){}
****************************************************************

**TabsModule.forRoot() (Version 5.6.1 ngx-bootstrap) Angular 9/10**
