### ISSUE TITLE
Carousel isAnimated MIA

### ISSUE THREAD

**Issue by adventmedia** [valor-software/ng2-bootstrap#5750]
As described in the docs (https://valor-software.com/ngx-bootstrap/#/carousel#animated)
`<carousel [isAnimated]="true">`
should animate the carousel transition.
However this option is rejected by TypeScript, and does not appear in the types file

ngx-bootstrap v 5.6.1
angular v 9.0.5

**Comment by daniloff200** [comment]
I'm not 100% sure what you mean in this issue.

I see the animation, which works well in docs page.

Could you create reproduction via stackblitz?
StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

**Comment by adventmedia** [comment]
stackblitz is a minimal environment, it does not enforce typescript errors. As implemented in an Angular CLI generated project:
```<carousel [isAnimated]="true">
  <slide *ngFor="let slide of slides" class="animated fadeIn">
    <img [src]="slide.pic" />
    <div class="carousel-caption d-none d-md-block">
      <span>{{slide.title}}</span>
    </div>
  </slide>
</carousel>
```
on build, fails:
```

ERROR in src/app/components/carousel/carousel.component.html:1:11 - error NG8002: Can't bind to 'isAnimated' since it isn't a known property of 'carousel'.

1 <carousel [isAnimated]="true">
            ~~~~~~~~~~~~~~~~~~~

  src/app/components/carousel/carousel.component.ts:8:16
    8   templateUrl: './carousel.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component CarouselComponent.

```
This is (at least) because the parameter 'isAnimated' is not defined in node_modules/ngx-bootstrap/carousel/carousel.component.d.ts'

**Comment by daniloff200** [comment]
Strange one.
I've just tried to add small carousel component to one of my project with Angular 9.1.0, and it works
Also, I see **isAnimated** in **carousel.component.d.ts
![Selection_056](https://user-images.githubusercontent.com/13692220/78568926-80ea7f80-782b-11ea-91bd-dc9d7446dec9.png)
**

Could you please create a small repo with reproduction and drop a link here? @adventmedia

**Comment by adventmedia** [comment]
which is exactly what is missing from my file. So I checked the version in package.json, it's 5.5.0.
One would expect `npm install ngx-bootstrap` to install the current versions… or definitely `npm install ngx-bootstrap@latest` but both times got 5.5.0.
Had to explicitly install 5.6.1 to get it, then had to fix a few imports… now animating.

**Comment by daniloff200** [comment]
@next version was 5.6.1, but, latest, yes, was 5.5.0 :(
Sad, that it's happened, but, happy, that we've found the reason for the issue and fixed it!
