### ISSUE TITLE
Datepicker html properties

### ISSUE THREAD

**Issue by hugoj-goncalves** [valor-software/ng2-bootstrap#5752]
![image](https://user-images.githubusercontent.com/10927715/78686313-4505f780-78c9-11ea-925c-fb47b884530f.png)

`ERROR in node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.d.ts.BsDatepickerContainerComponent.html(60,7): Property 'chosenRange' does not exist on type 'BsDatepickerContainerComponent'.
node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.d.ts.BsDatepickerContainerComponent.html(62,7): Property 'setRangeOnCalendar' does not exist on type 'BsDatepickerContainerComponent'.
node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.d.ts.BsDatepickerInlineContainerComponent.html(60,7): Property 'chosenRange' does not exist on type 
'BsDatepickerInlineContainerComponent'.
node_modules/ngx-bootstrap/datepicker/ngx-bootstrap-datepicker.d.ts.BsDatepickerInlineContainerComponent.html(62,7): Property 'setRangeOnCalendar' does not exist on type 'BsDatepickerInlineContainerComponent'`

Looks like there are some properties that does not exist anymore inside the lib template.

**Comment by ghost** [comment]
we are having the same issue in our gitlab pipelines!

**Comment by daniloff200** [comment]
that's related to #5730 
Duplicated
