### ISSUE TITLE
In 5.5.0 ng build is getting failed

### ISSUE THREAD

**Issue by ghost** [valor-software/ng2-bootstrap#5754]
Before opening an issue, please search for duplicates (opened and closed) https://github.com/valor-software/ngx-bootstrap/issues There's no need to open an issue here if you want to ask general question, use StackOverflow or Slack instead

Bug description:

Plunker/StackBlitz that reproduces the issue:
![Screenshot from 2020-04-08 00-39-11](https://user-images.githubusercontent.com/54355997/78709714-bda09e80-7931-11ea-8a23-975eccb2b81c.png)

Using Plunkr, StackBlitz is the best way to show your issue. Issues without link to an example of reproduction might be closed.

You can use one of starter templates:

Plunkr: https://plnkr.co/edit/0NipkZrnckZZROAcnjzB?p=preview

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap?file=app%2Fapp.module.ts

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.5.0

Angular: 8

Bootstrap: 4.3.1

Build system: Angular CLI, System.js, webpack, starter seed:

**Expected behavior**

**Comment by daniloff200** [comment]
that's known issue, we already have a PR for it 
https://github.com/valor-software/ngx-bootstrap/pull/5751

Let's wait for a new version, with a fix

**Comment by ghost** [comment]
Thank you for the quick response
