### ISSUE TITLE
Build error with 5.6.1 version

### ISSUE THREAD

**Issue by PrashantVasava** [valor-software/ng2-bootstrap#5767]
I have installed ngx-bootstrap version in my project version "^5.4.0". My colleague took repository and executed npm install. The ngx-bootstrap package with 5.6.1 version downloaded. When he build project he got error "Cannot find module 'ngx-bootstrap' ".

**Comment by uifortdev** [comment]
You need to import modules as
`import { BsDatepickerModule } from 'ngx-bootstrap/datepicker';
`
and not

`import { BsDatepickerModule } from 'ngx-bootstrap';`

**Comment by scssyworks** [comment]
You have a breaking change associated with a minor version. This should be fixed.

**Comment by daniloff200** [comment]
Yeah, I assume, that was fixed, and 5.6.2 should be without that.

**Comment by dmenne** [comment]
This will break MANY packages. There should be really good reasons for it.

**Comment by valorkin** [comment]
fixed in v6
