### ISSUE TITLE
BsDropdownModule.forRoot returns a ModuleWithProviders type without a generic type argument. 

### ISSUE THREAD

**Issue by zakeerms** [valor-software/ng2-bootstrap#5770]
ERROR in node_modules/ngx-bootstrap/dropdown/bs-dropdown.module.d.ts:3:35 - error NG6005: BsDropdownModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.

Bug description: 
![node1](https://user-images.githubusercontent.com/16174872/79952969-ccfb0e00-8440-11ea-9104-d9a52da6c08c.PNG)
![app module ts_code](https://user-images.githubusercontent.com/16174872/79952970-cd93a480-8440-11ea-9c11-e1e87dba5ac5.PNG)
![cmponent_html](https://user-images.githubusercontent.com/16174872/79952972-ce2c3b00-8440-11ea-99c9-9ed0abfda3eb.PNG)

-----------------------
ERROR in node_modules/ngx-bootstrap/dropdown/bs-dropdown.module.d.ts:3:35 - error NG6005: BsDropdownModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.
    
    3     static forRoot(config?: any): ModuleWithProviders;
                                        ~~~~~~~~~~~~~~~~~~~
    src/app/app.component.html:1:3 - error NG8001: 'app-nav' is not a known element:
    1. If 'app-nav' is an Angular component, then verify that it is part of this module.
    2. If 'app-nav' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    
    1   <app-nav></app-nav>
        ~~~~~~~~~~~~~~~~~~~
    
      src/app/app.component.ts:7:16
        7   templateUrl: './app.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component AppComponent.
    src/app/app.component.html:2:3 - error NG8001: 'app-home' is not a known element:
    1. If 'app-home' is an Angular component, then verify that it is part of this module.
    2. If 'app-home' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    
    2   <app-home></app-home>
        ~~~~~~~~~~~~~~~~~~~~~
    
      src/app/app.component.ts:7:16
        7   templateUrl: './app.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component AppComponent.
    src/app/nav/nav.component.html:30:32 - error NG8002: Can't bind to 'ngModel' since it isn't a known property of 'input'.
    
    30       name="username" required [(ngModel)]="model.username">
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
      src/app/nav/nav.component.ts:7:16
        7   templateUrl: './nav.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component NavComponent.
    src/app/nav/nav.component.html:32:33 - error NG8002: Can't bind to 'ngModel' since it isn't a known property of 'input'.
    
    32        name="password" required [(ngModel)]="model.password">
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
      src/app/nav/nav.component.ts:7:16
        7   templateUrl: './nav.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component NavComponent.
    src/app/home/home.component.html:13:9 - error NG8001: 'app-register' is not a known element:
    1. If 'app-register' is an Angular component, then verify that it is part of this module.
    2. If 'app-register' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
    
    13         <app-register (cancelRegister)="cancelRegisterMode($event)"></app-register>
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
      src/app/home/home.component.ts:6:16
        6   templateUrl: './home.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component HomeComponent.
    src/app/register/register.component.html:5:93 - error NG8002: Can't bind to 'ngModel' since it isn't a known property of 'input'.
    
    5     <input type="text" class="form-control" placeholder="Username" name="username" required [(ngModel)]="model.username" />
                                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
      src/app/register/register.component.ts:8:16
        8   templateUrl: './register.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component RegisterComponent.
    src/app/register/register.component.html:8:97 - error NG8002: Can't bind to 'ngModel' since it isn't a known property of 'input'.
    
    8     <input type="password" class="form-control" placeholder="Password" name="password" required [(ngModel)]="model.password" />
                                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
      src/app/register/register.component.ts:8:16
        8   templateUrl: './register.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component RegisterComponent.
    src/app/nav/nav.component.html:28:43 - error NG8003: No directive found with exportAs 'ngForm'.
    
    28     <form *ngIf="!loggedIn()" #loginForm="ngForm" class="form-inline my-2 my-lg-0" (ngSubmit)="login()">
                                                 ~~~~~~
    
      src/app/nav/nav.component.ts:7:160m
        7   templateUrl: './nav.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component NavComponent.
    src/app/register/register.component.html:1:23 - error NG8003: No directive found with exportAs 'ngForm'.

    1 <form  #registerForm="ngForm"  (ngSubmit)="register()">
                            ~~~~~~

      src/app/register/register.component.ts:8:16
        8   templateUrl: './register.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component RegisterComponent.

**Comment by daniloff200** [comment]
hey, @zakeerms 

Could you, please, add a little more info about your environment? First of all, I need to know, what versions of Angular and ngx-bootstrap you used?

Also, will be helpful to get some demo via Stackblitz, or,  a github repo with issue reproduction. 
Unfortunately, I'm just a man, not a compiler, and can't compile your code in my head :(

**Comment by zakeerms** [comment]
Hey @daniloff200, I am using Angular 8 and  latest version of ngx-bootstrap. Now i close my application and recompile again and I can see that the error gone. I don't know what happened suddenly. 
Thanks
