### ISSUE TITLE
destroy modal when route change

### ISSUE THREAD

**Issue by CoskunCakir** [valor-software/ng2-bootstrap#5779]
hi guys,

i searched but didn't find. is there a global way or option to destroy open modals when route change or component destroy?

I am doing this like below but need to do this every parent component which is using modal.

```javascript
ngOnDestroy() {
    const modalCount = this.bsModalService.getModalsCount();
    if (modalCount > 0) {
      this.bsModalService._hideModal(modalCount);
    }
  }
```

cheers..

**Comment by DoanVanThuong** [comment]
You can using Abstract class have ngOnDestroy method and every component extends that Abstract Class

**Comment by CoskunCakir** [comment]
Hi @DoanVanThuong,
using an abstract class seems like a good idea.
i prepared an abstract class like below and extend my components with this.
```javascript
import { OnDestroy } from '@angular/core';
import { BsModalService, BsModalRef } from 'ngx-bootstrap/modal';

export abstract class BaseComponent implements OnDestroy {
  bsModalService: BsModalService;
  bsModalRef: BsModalRef;

  ngOnDestroy() {
    const modalCount = this.bsModalService.getModalsCount();
    if (modalCount > 0) {
      this.bsModalService._hideModal(modalCount);
    }
  }
}
```

thanks 👍
