### ISSUE TITLE
Using Picture tag with carousel

### ISSUE THREAD

**Issue by ShadabFaiz** [valor-software/ng2-bootstrap#5788]
**Description:**
How can i use picture tag in carousel? It seems like it is not supported right now
``` html

    <slide>
      <picture>
        <source
          srcset="/assets/images/carousels/background_1.webp"
          type="image/webp"
        />
        <source
          srcset="/assets/images/carousels/background_1.png"
          type="image/png"
        />
      </picture>
    </slide>
```
The above code does not work when using picture tag but works with img tag. The problem is I want to use Webp image and provide the fallback to png if browser if not supported. Another way to do so is to checks for feature detection either by own your own or using other libraries like modernizer but since there is already fallback support for in the html5, I would like to use it.

**Comment by valorkin** [comment]
hello. carousel has nothing to do about it, picture always should have an image tag
https://www.w3schools.com/tags/tag_picture.asp
