### ISSUE TITLE
Mat-Table sort and pagination not working on ngx-bootstrap Modal

### ISSUE THREAD

**Issue by pavankjadda** [valor-software/ng2-bootstrap#5789]
Bug description:
Mat-Table sort and pagination not working on ngx-bootstrap Modal

Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/github/pavankjadda/ngx-bootstrap-modal-bug?file=src%2Fstyles.css

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.6.1

Angular: 9.1.8

Bootstrap: 4.5.0

Build system: Angular CLI

**Expected behavior**
Bootstrap Modal should load data and allow sort and pagination

**Comment by pavankjadda** [comment]
And Ma-Table sort and pagination are working fine on Native Bootstrap Modal and Angular Material Dialog

**Comment by jasonreid0873** [comment]
Am seeing the same issue too, any updates or workarounds?

**Comment by pavankjadda** [comment]
I switched to Angular Material [Dialog](https://material.angular.io/components/dialog/overview)

**Comment by pavankjadda** [comment]
Not sure why the issue was closed without addressing it

**Comment by valorkin** [comment]
how can we fix mat-table here?

**Comment by pavankjadda** [comment]
Not sure if you read the whole issue. I only see this problem when using ngx bootstrap modal and works fine in angular material dialog.

**Comment by vanshikawo** [comment]
Facing same issue. Any solution for this?

**Comment by pavankjadda** [comment]
> Facing same issue. Any solution for this?

Don't know. I switched to `mat-table`

**Comment by jasonreid0873** [comment]
I switched to primeNG tables which work fine
