### ISSUE TITLE
Datepicker th-be locale automatic convert year when manual input

### ISSUE THREAD

**Issue by cityhunter44** [valor-software/ng2-bootstrap#5790]
Bug description:
I use datepicker on th-be locale. When I input date manual the Buddhist year will be changed (add 543).

Example:
Input: 21/5/2563
Output: 21/5/3106
![BugDatepicker](https://user-images.githubusercontent.com/7777538/82531229-21d99380-9b69-11ea-9f87-389cb620ae70.gif)

**Comment by daniloff200** [comment]
hey, @tumit, I see, that you made some changes in your fork, which can be related to this issue

Could you submit a PR with a fix, please ?

**Comment by tumit** [comment]
@daniloff200 Yes I'm working on it. Sorry for slow responding 🙇‍♂️

**Comment by daniloff200** [comment]
No worries!
Thanks for your help, I will review these fixes ASAP
