### ISSUE TITLE
datepicker: Thai Buddish calendar Input Data show wrong on year

### ISSUE THREAD

**Issue by AekGie** [valor-software/ng2-bootstrap#5793]
When I set local to 'th-Be'. I input data to text box 01/01/2563 before input data complete. data in text box change to 01/01/3106. How I can fix it ?

**Comment by tumit** [comment]
@AekGie I'm working on it. Sorry for slow responding 🙇‍♂️

**Comment by tumit** [comment]
@AekGie Can we able to close this issue ?
