### ISSUE TITLE
Done/Close button in datepicker

### ISSUE THREAD

**Issue by UdayAppam** [valor-software/ng2-bootstrap#5795]
How can we Done/Close button inside calendar panel for datepicker control.
Could you please help me.

`BsDatepickerContainerComponent` need  datepicker  ref to hide the datepicker panel.
How we would get the reference? Could you please share the inputs

**Comment by daniloff200** [comment]
hello, @KernelLora 
is this a duplicate of #5835 ?

**Comment by UdayAppam** [comment]
Yeah Somehow missed Closed the issue
