### ISSUE TITLE
Send Data from Component to another Component

### ISSUE THREAD

**Issue by jt4000** [valor-software/ng2-bootstrap#5797]
Goal:
Send data of a variable from app component to SomeComponent. The value of the variable should be displayed inside of the modal body.

Problem:
I don't know how to solve it. Any idea?

Info:
https://stackblitz.com/edit/ngx-modal-m9sctv

Thank you!

**Comment by daniloff200** [comment]
That's easy to do
I see you have `data` in your `initialState` object.

Just make it like, 

`initialState: {
        title: 'Modal titles',
        data: DATA_YOU_WANT_TO_PASS  //  (let's imagine it will be string)
      }`

And then use it in SomeComponent

```
<div class="modal-body">
	This is a modal.
    <br>

  <span>{{data}}</span>
```
