### ISSUE TITLE
ngcc failed to run on ngx-bootstrap@5.6.2.

### ISSUE THREAD

**Issue by fzs1994** [valor-software/ng2-bootstrap#5801]
**Not able to install latest in Stackblitz**
https://stackblitz.com/edit/angular-ivy-ym49z2?file=package.json

![image](https://user-images.githubusercontent.com/10684213/83257111-4f5db700-a1d1-11ea-8f87-10656f739a9d.png)

**Comment by axell9641** [comment]
Same here

**Comment by vvolodin** [comment]
Same here. Tried 5.6.2, 5.6.1 and 5.5.0

**Comment by daniloff200** [comment]
5.6.2 was broken at all, and not even published to npm
Try 6.0.0 or 6.1.0 , and, please, share your results here

**Comment by fzs1994** [comment]
@daniloff200 6.0.0 is working, 6.1.0 fails
