### ISSUE TITLE
Wrong version in npm and documentation 

### ISSUE THREAD

**Issue by Fredx87** [valor-software/ng2-bootstrap#5802]
There are several issue related to version numbers:

- The latest released version is 5.6.2, but the latest tag on npm is for version 5.6.1
- Here on github the [release](https://github.com/valor-software/ngx-bootstrap/releases) tagged as latest is 5.5.0
- In the homepage of the documentation there is a "4.0.1", I think it should point to the latest release version
- I think that some time ago there was a version selector in the documentation, or am I wrong? It is very useful to see the documentation relative to the version that you are currently using

**Comment by valorkin** [comment]
Thanks for pointing this out, https://travis-ci.org/github/valor-software/ngx-bootstrap/jobs/673347174
deploy job finished without error, while was deployed wrong folder

**Comment by valorkin** [comment]
as for release notes https://travis-ci.org/github/valor-software/ngx-bootstrap/jobs/673347179
GitHubError: Bad credentials (401)
will have to update credentials and version of releaser, because Github API has changed

**Comment by meta72** [comment]
Is there any update on this? I'm really waiting on a bug fix in 5.6.2

**Comment by daniloff200** [comment]
@meta72 https://www.npmjs.com/package/ngx-bootstrap/v/6.0.0 already available, but yes, the version number is still broken

**Comment by daniloff200** [comment]
I've   updated Github Releases info in the repo, so, 6.0.0 is now marked as the latest version here
![Selection_063](https://user-images.githubusercontent.com/13692220/89901454-c52cc880-dbed-11ea-97c7-005ea92ce249.png)

**Comment by daniloff200** [comment]
Version on documentation was also fixed
