### ISSUE TITLE
Ngx Bootstrap Typeahead OnBlur Errors when clicked outside after clicking the unfilled input

### ISSUE THREAD

**Issue by KShewengger** [valor-software/ng2-bootstrap#5804]
Even when no Stackblitz to demo, this also happens on **[Ngx Bootstrap Typeahead Documentation](https://valor-software.com/ngx-bootstrap/#/typeahead)** examples.

To reproduce the problem:

```
1.) Go to the Ngx Bootstrap Typeahead link above
2.) Open your console
3.) Click on any input element (unfilled) from the samples
4.) Then click outside of the element, you can see that the error shows somehow like this (attached photo below)
```

Would like to know if there are any steps to counter this issue? Would like to be guided.

**Demo:**
![demo](https://user-images.githubusercontent.com/7908747/83704336-6d4d7080-a644-11ea-956e-d5b3dfe235f4.gif)

**Error Encountered:**
![image](https://user-images.githubusercontent.com/7908747/83704012-8e619180-a643-11ea-92fe-039034755b29.png)

**Comment by Theyssen** [comment]
Same as issue #5736

**Comment by mcicco** [comment]
I've the same issue

**Comment by KShewengger** [comment]
Closed this issue as it is related to https://github.com/valor-software/ngx-bootstrap/issues/5736
Will stay up to date on that thread instead.

**Comment by calldeludo** [comment]
are there any of these links open? i didnt find any solution
