### ISSUE TITLE
Tooltip onHover

### ISSUE THREAD

**Issue by jhonmacaraig** [valor-software/ng2-bootstrap#5806]
Hello Guys,
    Question, is there a way the tooltip will not go away if i lost focus on the current element
I have a custom tooltip template. I added a button , the issue is when i try to click the button
the tooltip hides.

![image](https://user-images.githubusercontent.com/1201350/83841241-0e1a5980-a733-11ea-86ce-002ba9d6c3c2.png)

thank you
jhon

**Comment by apotapcukv** [comment]
Hi, @jhonmacaraig! We can’t reproduce the issue. If you still can, please do it at https://stackblitz.com/edit/angular-ivy-de1elj?file=tsconfig.json/ and share with us, or please add a recorded video.

**Comment by SvetlanaMuravlova** [comment]
@jhonmacaraig , hi) thank you for your question, if it is still actual i think you can look for the answer in our documentation, especially there http://localhost:4200/ngx-bootstrap/#/components/tooltip?tab=overview#triggers-custom or http://localhost:4200/ngx-bootstrap/#/components/tooltip?tab=overview#triggers-manual

if you aren't able to resolve your problem with such information, you can prepare an example on https://stackblitz.com/  for quick help
