### ISSUE TITLE
https://valor-software.com/ngx-bootstrap/ webpage is not working

### ISSUE THREAD

**Issue by amit-ahire** [valor-software/ng2-bootstrap#5809]
I tried opening the [ngx-bootstrap](https://valor-software.com/ngx-bootstrap/) link, but giving some error.

![image](https://user-images.githubusercontent.com/11144520/84027218-41b3e880-a9ac-11ea-907d-9329efeb2dbb.png)

**Comment by daniloff200** [comment]
Really strange, I can open it
https://downforeveryoneorjustme.com/valor-software.com says the same

**Comment by amit-ahire** [comment]
> Really strange, I can open it
> https://downforeveryoneorjustme.com/valor-software.com says the same

Yeah, it's working now
Yesterday it wasn't working for more than an hour.
There closing the issue
