### ISSUE TITLE
[Feature] [Datepicker] Open on Year or Month view

### ISSUE THREAD

**Issue by c00** [valor-software/ng2-bootstrap#5816]
**Is your feature request related to a problem? Please describe.**

Use cases: Selecting Date of Birth, Date of document issuance, date of entry, or any other date that is likely not to be this year/month (and where year/month aren't predictable). 

Let's go with DOB for the rest of this FR.

Currently a user will open the dialog, and either click the back button a lot, or click the year (if they realize they can) and find the required year, month and day.

**Describe the solution you'd like**

Add an option in the config like `openView` with possible values `year`, `month`, `day`. It would default to day, as that is the current behavior.

When the datepicker dialog opens, the initial view should go to the configured view (`year` in the example) as a starting point, rather than always defaulting to day.

The new flow would be: 

1. User opens dialog
2. Selects year
3. Selects month
4. Selects day.

**Describe alternatives you've considered**

I've looked at the current DatePicker directive to see if this could be achieved relatively easy through some manual triggering, but it can't. 

Alternatives would be to take a `view` argument in `toggle` and `open` and respond with the needed starting view.

**Additional context**

Note that this is different form `minDate`. `minDate` limits the view. This feature would only provide a starting point, but still have the months, years and day selection available.

**Comment by fhuschle** [comment]
I would like to do that
