### ISSUE TITLE
Datepicker AdaptivePosition doesn't work for left/right 

### ISSUE THREAD

**Issue by axell9641** [valor-software/ng2-bootstrap#5825]
I need to build a interface (for mobile) where two datepickers should be displayed in the same row
Something like this image.
![image](https://user-images.githubusercontent.com/637311/85062461-24caa280-b16e-11ea-8503-bffd9092e72d.png)

The problem is that even if I apply **adaptive-position** , the calendar doesn't fit into the screen 
I want to know if I can reduce the control to the minimum or make it appear to the right or left depending where there's more room

[Here's a very simple demo of my case ](https://stackblitz.com/edit/angular-7rxmuq-8qgxp1)

**Comment by keyboardbreaker** [comment]
im facing the same problem but with the date range picker

**Comment by axell9641** [comment]
> im facing the same problem but with the date range picker

I ended up using the calendar from Angular Material. It works great for my particular use case.

**Comment by NenadJovicic** [comment]
I have the same problem
![Screenshot from 2020-12-28 22-43-41](https://user-images.githubusercontent.com/2767416/103244790-62e72100-495e-11eb-96d1-c922cbda16ad.png)

**Comment by apotapcukv** [comment]
Dear axell9641! As per our check this issue is fixed in the latest version, so we’re closing the issue.
Please don’t hesitate to let us know if you face further issues.
