### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rlassche** [valor-software/ng2-bootstrap#5826]
Typeahead with ng-select and ngx-typeahead differ, and I want to use both of them in angular formly and bootstrap..

Error message below occured when I combined ng-select and ngx-typeahead.
```
core.js:6228 ERROR TypeError: Cannot read property 'length' of undefined
    at TypeaheadDirective.onBlur (ngx-bootstrap-typeahead.js:2010)
    at TypeaheadDirective_blur_HostBindingHandler (ngx-bootstrap-typeahead.js:2394)
    at executeListenerWithErrorHandling (core.js:21806)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:21848)
    at SafeSubscriber.schedulerFn [as _next] (core.js:37171)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at EventEmitter.next (Subject.js:39)
```
**SOLUTION:**

In my case, I solved the error by editing file `node_modules/ngx-bootstrap/__ivy_ngcc__/typeahead/fesm2015/ngx-bootstrap-typeahead.js`.
The onBlur method is modfied:
```
onBlur() {
        this.isFocused = false;
        if (this._container && !this._container.isFocused) {
            this.typeaheadOnBlur.emit(this._container.active);
        }
        if (!this.container && this._matches && this._matches.length === 0) {
            this.typeaheadOnBlur.emit(new TypeaheadMatch(this.element.nativeElement.value, this.element.nativeElement.value, false));
        }
    }
```
NOTE: I added **&& this._matches** in the second if.

**Comment by Trottero** [comment]
Currently having the same issue, wondering whether there's a way to solve this problem without resorting to editing `node_modules`

**Comment by rlassche** [comment]
Hi,
I did not found an other solution.I hope that my suggestion will be updated in the source.
Greetings,Rob Lassche

Verzonden via Yahoo Mail op Android 
 
  Op di, jul. 7, 2020 om 12:14 schreef Niels Witte<notifications@github.com>:   


Currently having the same issue, wondering whether there's a way to solve this problem without resorting to editing node_modules

**Comment by tirro-s** [comment]
I add this two options and problem gones!

[typeaheadOptionsLimit]="7"
[typeaheadMinLength]="0"

**Comment by rlassche** [comment]
Hello Tirro-s,

that's a much better solution!

I will implement it this week.

Thanks,


Greetings,


Rob Lassche

**Comment by boloboloda** [comment]
> I add this two options and problem gones!
> 
> [typeaheadOptionsLimit]="7"
> [typeaheadMinLength]="0"

same issues,but this is not work for me.

angular version: "~8.2.14"
ng-select version: "^3.7.3"

**Comment by uttahb** [comment]
Hi @tirro-s ,

I am using ngx-bootstrap 5.6.1 and it seems like the fix you mentioned not working. I couldn't find an alternate solution as well.

**Comment by szh** [comment]
Seems to be solved in https://github.com/valor-software/ngx-bootstrap/issues/5736, thought it's not released to npm

**Comment by daniloff200** [comment]
fix was released in 6.0.0

**Comment by eugene-b360** [comment]
6.0.0 - is for Angular 9, 10.
I've got 8. Is there any possible fix or work around for it in 5.6.2 ?

**Comment by bryantlikes** [comment]
> [typeaheadMinLength]="0"

Just adding this seems to get rid of it. I'm assuming this is because it causes the control to build the _matches array.

**Comment by DerZyklop** [comment]
@bryantlikes’s workaround works. 

And since updating my ngx-bootstrap to 6 ist blocked in my project for other reasons i can also confirm that his workaround works on 
`Angular@9.1.12` with `ngx-bootstrap@5.6.1`.

**Comment by harrymaynard-maximus** [comment]
Hi, will this be fixed in a future 5.x release of the library?
