### ISSUE TITLE
Angular 10 Support

### ISSUE THREAD

**Issue by pavankjadda** [valor-software/ng2-bootstrap#5831]
**Is your feature request related to a problem? Please describe.**
No, just a request to support Angular 10

**Describe the solution you'd like**
Please update the ngx-bootstrap to support Angular 10

**Comment by eric-simonton-sama** [comment]
This request can replace mine in https://github.com/valor-software/ngx-bootstrap/issues/5744

**Comment by CemAltel** [comment]
https://github.com/valor-software/ngx-bootstrap/pull/5812

**Comment by gmaggiodev** [comment]
As workaround, like suggested by agGrid (https://www.ag-grid.com/angular-grid/), that has the same problem, you could set 
```"skipLibCheck": true``` in `tsconfig.app.json`.

For example:

```json
{
  "extends": "./tsconfig.base.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": [],
    "skipLibCheck": true
    },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ],
  "angularCompilerOptions": {
    "enableIvy": true,
  }
}
```

**Comment by daniloff200** [comment]
PR with support for NG 10 was merged to dev, and support for NG 10 will be in 6.0.0 version, hopefully, next week

**Comment by jziggas** [comment]
Terrific news, thanks for the update. Just out of curiosity, why close the issue before the version has been released?

**Comment by JohnnyTMD** [comment]
> As workaround, like suggested by agGrid (https://www.ag-grid.com/angular-grid/), that has the same problem, you could set
> `"skipLibCheck": true` in `tsconfig.app.json`.
> 
> For example:
> 
> ```json
> {
>   "extends": "./tsconfig.base.json",
>   "compilerOptions": {
>     "outDir": "./out-tsc/app",
>     "types": [],
>     "skipLibCheck": true
>     },
>   "files": [
>     "src/main.ts",
>     "src/polyfills.ts"
>   ],
>   "include": [
>     "src/**/*.d.ts"
>   ],
>   "angularCompilerOptions": {
>     "enableIvy": true,
>   }
> }
> ```
skipLibCheck worked for me but in the template I still have the error ` ERROR in There is no directive with "exportAs" set to "bs-tooltip" `

**Comment by roopeshchinnakampalli** [comment]
Yes, I'm facing the same issue with Angular v10.x & v6.0.0

> There is no directive with "exportAs" set to "bs-popover" ("-popover" placement="bottom" [adaptivePosition]="false" container="body" [outsideClick]="true"
>     [ERROR ->]#pop3="bs-popover" (onShown)="popUser=true; popSettings=false" (onHidden)="popUser=false">
>     <div ")

**Comment by Gillardo** [comment]
Any idea when v6.0.0 is going to be out?

**Comment by daniloff200** [comment]
![Selection_062](https://user-images.githubusercontent.com/13692220/89886239-f8169280-dbd4-11ea-9c5b-ac5d83e8561b.png)
it's already live for almost a month :)  @Gillardo

**Comment by Gillardo** [comment]
Sorry realised that once i clicked on the releases tab, but via the home screen is just showed this

![image](https://user-images.githubusercontent.com/7406381/89893073-9e5f9980-dbcf-11ea-883c-9d6eb90a105a.png)

**Comment by daniloff200** [comment]
Yeah, I don't know, why it works like that here. If you open releases tab, you will see that we had 5 more new releases

**Comment by daniloff200** [comment]
@Gillardo  I've updated github releases info, now, it shows 6.0.0 :)

**Comment by Gillardo** [comment]
Confirmed, thank you!

**Comment by CemAltel** [comment]
Will it be updated to work with Angular 10? It's still causing an error.
