### ISSUE TITLE
Compatiblity with Angular 10

### ISSUE THREAD

**Issue by HakamFostok** [valor-software/ng2-bootstrap#5838]
ngx-bootstrap does not work with angular 10
here is an error if I update my project to angular 10 with ngx-bootstrap version 5.6.1 (the latest version of ngx-bootstrap at the time of opening this issue)

````
ERROR in node_modules/ngx-bootstrap/collapse/collapse.module.d.ts:3:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

3     static forRoot(): ModuleWithProviders;
````
this is very normal and understandable, my question is the following

when will be new version of the ngx-bootstrap which support angular 10?

thanks in advanced

**Comment by Dassderdie** [comment]
See #5831

**Comment by daniloff200** [comment]
PR with support for NG 10 was merged to dev, and support for NG 10 will be in 6.0.0 version, hopefully, next week
