### ISSUE TITLE
Progressbar animate inconsistency

### ISSUE THREAD

**Issue by meta72** [valor-software/ng2-bootstrap#5848]
_Bug description:_

1. the stripes of a progressbar animate when setting `[animate]="true"`
2. transitions between value changes are smooth when setting `[animate]="false"`

_Plunker/StackBlitz that reproduces the issue:_

https://stackblitz.com/edit/ngx-bootstrap-fwtt39?file=app%2Fapp.component.html

_Versions of ngx-bootstrap, Angular, and Bootstrap:_

ngx-bootstrap: 5.6.1

Angular: 8.2.14

Bootstrap: 3.4.1

Angular CLI: 8.3.26

**Expected behavior**

1. As far as I understand the [documentation](https://valor-software.com/ngx-bootstrap/#/progressbar#progressbar-component), `[animate]` does only concern transitions between different _values_ of the progressbar and `.active` makes the stripes animate. So having `[animate]="true"` and not having `.active` should not animate the stripes.

2. For the same reason, having `[animate]="false"` should not have smooth transitions between different values of the progressbar.

I think this behaviour may come from a change in bootstrap itself: Bootstrap 3 uses `.active` for animated stripes, whereas bootstrap 4 uses `.progress-bar-animated`. Either the documentation for the `[animate]` property in ngx-bootstrap should be updated or it should not affect animation of the stripes, at least when using bootstrap 3.

**Comment by valorkin** [comment]
thank you for your time and effort, but next major version we are gonna drop support for bootstrap css v3
