### ISSUE TITLE
ModuleWithProviders Issue in Angular v10

### ISSUE THREAD

**Issue by roopeshchinnakampalli** [valor-software/ng2-bootstrap#5851]
Bug description:
Looks like the library is not updated the code to support the Angular v9.x or Angular v10.x upgrade compability checker - [https://angular.io/guide/migration-module-with-providers#what-does-this-mean-for-libraries](https://angular.io/guide/migration-module-with-providers#what-does-this-mean-for-libraries)

Steps to reproduce the Issue:

1. Add ngx-boostrap as peer dependency to any library which has Angular v10.x, now you should see the error for all the modules - 

> node_modules/ngx-bootstrap/collapse/collapse.module.d.ts:3:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

>    static forRoot(): ModuleWithProviders;

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.6.x

Angular: Angular v10.x

Bootstrap: 4.x

Build system: Angular CLI,

**Expected behavior**

Build should work without any errors

**Comment by roopeshchinnakampalli** [comment]
I see a branch 5.7.0 with the fix, can someone tell me when you will be releasing it?

**Comment by daniloff200** [comment]
hey @roopeshreddy 
Yes, 5.7.0 has it, but, it was not released, because, has no support for Angular 10, so, we deciced to release a major update in 6.0.0.

**Comment by roopeshchinnakampalli** [comment]
Hi @daniloff200 
Thanks for the update. We're upgrading to Angular v10 and this is blocking us. Is there any timeline for  the 6.0.0?

**Comment by roopeshchinnakampalli** [comment]
> hey @roopeshreddy
> Yes, 5.7.0 has it, but, it was not released, because, has no support for Angular 10, so, we deciced to release a major update in 6.0.0.

Also, the fix which you guys made in v5.7.0 should resolve the issue which I mentioned. May be try considering this interim version release!

**Comment by daniloff200** [comment]
I hope, that 6.0.0 will be available in next few days

**Comment by roopeshchinnakampalli** [comment]
> I hope, that 6.0.0 will be available in next few days

Thank you @daniloff200

**Comment by daniloff200** [comment]
6.0.0 was released and now available on npm

**Comment by munaretto** [comment]
Hey @daniloff200! I went to the npm repo and it says that the most recent version is 5.6.1, even though your [changelog](https://github.com/valor-software/ngx-bootstrap/blob/development/CHANGELOG.md) says the 6.0.0 was released. Can you help me with that?

**Comment by daniloff200** [comment]
@munaretto  5.6.1 is the version with the latest tag
6.0.0 released with a next tag

If you open versions tab on npm, you will see that 6.0.0 is also available
Feel free to use 6.0.0 in your package.json :)
