### ISSUE TITLE
Typeahead does not support apostrophe

### ISSUE THREAD

**Issue by rtaft** [valor-software/ng2-bootstrap#5852]
Bug description:

I am using typeahead to search for names.  The O'Lastnames are not returning properly.  For instance, If I search for O'Henry, and type O'H, it will return anything that has OH but NOT O'Henry. 

Plunker/StackBlitz that reproduces the issue:

https://stackblitz.com/edit/angular-fqlcqu?file=src/app/my-autocomplete/my-autocomplete.component.ts

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.6.1

Angular: 7.2.3

Bootstrap: 4.4.1

Build system: Angular CLI

**Expected behavior**

I expect to be able to search for names with apostrophes in them

**Comment by Moncleared** [comment]
Having a similar issue on my end, searching for anything with an apostrophe or single quote causes issues with the typeahead

**Comment by Moncleared** [comment]
So not long after commenting, I stumbled upon some documentation that referenced an apostrophe and took a look:
https://valor-software.com/ngx-bootstrap/#/typeahead#TypeaheadDirective

If you check out the property typeaheadSingleWords which is defaulted to try it seems to cause an issue with the defaulted settings of typeaheadPhraseDelimiters. Long story short, set typeaheadSingleWords to false and apostrophe works from there on.  Sorry this isn't a great technical answer of why it does/doesn't work, but that appears to have resolved my issue.

Best of luck!

**Comment by rtaft** [comment]
Thank you, that resolved my issue.  I'll leave the ticket open given that the documentation for that field is talking about spaces and does not mention that apostrophes are completely ignored in that mode.

**Comment by rtaft** [comment]
Ah, I see it now, its the default delimiter in that mode.  Good to know.
