### ISSUE TITLE
compatibility table is incorrect

### ISSUE THREAD

**Issue by marckassay** [valor-software/ng2-bootstrap#5854]
**Description:**

This [table](https://valor-software.com/ngx-bootstrap/#/documentation#compatibility) claims that ngx-bootstrap 4.x.x is compatible with, at least, Angular 6.x.x. ngx-bootstrap 4.0.0, its [package.json](https://github.com/valor-software/ngx-bootstrap/blob/v4.0.0/package.json), seems to have a dependency with at least Angular 7. If all of that is true, than the chart is incorrect.

**Comment by valorkin** [comment]
some versions are backward compatible, I would say most of them
because we have tests running with n-1, n, n+1 versions of angular
it helps us to migrate applications to a newer ngx-bootstrap or angular version with lesser pain

**Comment by valorkin** [comment]
https://unpkg.com/browse/ngx-bootstrap@4.0.0/package.json
it will give a peer dependency warning but will work
I hope this does make sense
