### ISSUE TITLE
The modals demo on the official website cannot be opened

### ISSUE THREAD

**Issue by xumoqiu** [valor-software/ng2-bootstrap#5855]
http://ngx-bootstrap.com/#/Modals , Can anyone fix it?

**Comment by daniloff200** [comment]
hey @xumoqiu 
That's completely wrong url!  This site was made by some other people, and, can be dangerous
And also, yes, it's completely broken

Please, use https://valor-software.com/ngx-bootstrap/#/ , the one and only official site with demos & docs

**Comment by xumoqiu** [comment]
thank you
