### ISSUE TITLE
v5.7.0 not on NPM

### ISSUE THREAD

**Issue by Theyssen** [valor-software/ng2-bootstrap#5869]
**Description:**
Version 5.7.0 is mentioned in CHANGELOG.md, but does not appear to be available on NPM. 
![image](https://user-images.githubusercontent.com/2998814/88159676-e95c4180-cc0d-11ea-955f-3cf82a08f680.png)

**Comment by daniloff200** [comment]
Yes, you're correct.
We've faced various build issues, because of Angular 10 support, and 5.7.0 was completely broken, that's why it was not published to npm
All changes, that were in 5.7.0 + Angular 10 support was published in 6.0.0

**Comment by pavankjadda** [comment]
And also when I do `ng update --all` I still see `5.6.1` as the latest version. I had to manually install `6.0.0` using `npm i ngx-bootstrap@6.0.0`

**Comment by daniloff200** [comment]
@pavankjadda  screenshot is the issue shows exactly the same, that, 5.6.1 is with the latest tag, and 6.0.0 is next

After 6.0.1 release 6.0.0 will be with the latest tag

**Comment by Theyssen** [comment]
@daniloff200 I am running Angular 8 so upgrading to 6.0.0 is not an option. I was hoping to get the Typeahead bug fixes in 5.7.0.

**Comment by szh** [comment]
@daniloff200  I am in the same situation as @Theyssen - also needing the typeahead fix but using Angular 9. Is it safe to install the package from git like this?
```
"ngx-bootstrap": "git+https://github.com/valor-software/ngx-bootstrap.git#v5.7.0"
```

**Comment by daniloff200** [comment]
Not sure, but, you can try :)

**Comment by szh** [comment]
So I ran `npm i https://github.com/valor-software/ngx-bootstrap.git#v5.7.0` and I ended up with this:
![image](https://user-images.githubusercontent.com/546965/88422409-367c1700-cdb8-11ea-9104-262a491d8345.png)
I see now that the package.json for the ngx-bootstrap package is in /src and I'm pretty sure you can't install an npm package from a subfolder in a git repo, so I guess I'll also have to wait.
