### ISSUE TITLE
Add "pointer-events: none;" doesn't work if any link placed inside tooltip ,I'm not able to click on the link inside tooltip 

### ISSUE THREAD

**Issue by kavyai** [valor-software/ng2-bootstrap#5873]
Add "pointer-events: none;" to the tooltip css, problem solved!

`.tooltip {
	pointer-events: none;
}`

_Originally posted by @rokdazone in https://github.com/valor-software/ngx-bootstrap/issues/3075#issuecomment-363461060_

**Comment by daniloff200** [comment]
already done in https://github.com/valor-software/ngx-bootstrap/pull/4660, use more new versions, please
