### ISSUE TITLE
[Safari/WebKit] Datepicker. The gray highlight is missing when hovering the mouse cursor on the date.  

### ISSUE THREAD

**Issue by evgeniypolevyk** [valor-software/ng2-bootstrap#5875]
Bug description: in WebKit browsers (Safari browser (macOS), epiphany browser (Linux Mint)) the gray highlight is missing when hovering the mouse cursor on the date.  

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.6.2 and higher

Angular: 10

Bootstrap: 4

**Actual result:** the gray highlight is missing when hovering the mouse cursor on the date
![actual_res_datepick](https://user-images.githubusercontent.com/66252583/88520264-01600680-cffc-11ea-875f-2b78d4592b33.gif)

**Expected result:** the gray highlight should be present when hovering the mouse cursor on the date 
![expected_res_datepick](https://user-images.githubusercontent.com/66252583/88520546-60be1680-cffc-11ea-87c3-43b03295f7f1.gif)

**Comment by anastasia-priymak** [comment]
Verified that
- hover on datepicker works in Safari and Chrome
- dates on datepicker can be selected by a single tap on iOS/Safari
