### ISSUE TITLE
Aria attribute prefixed twice, should read "aria-expanded"

### ISSUE THREAD

**Issue by kompuser** [valor-software/ng2-bootstrap#5880]
https://github.com/valor-software/ngx-bootstrap/blob/63b7545c4446b63cd6f2cebd4b1da87aaf7bd513/src/typeahead/typeahead.directive.ts#L38

**Comment by daniloff200** [comment]
Woah!
Thanks for finding that, and another one issue!
Idk, how we missed that in March

Gonna be fixed, and, available in next release
