### ISSUE TITLE
Max date range feature in daterangepicker

### ISSUE THREAD

**Issue by Shyam268** [valor-software/ng2-bootstrap#5894]
i have similar issue https://github.com/valor-software/ngx-bootstrap/issues/5562
I am using ngx-bootstrap version 5.6.1. i dont see `maxDateRange` propert in `bs-datepicker.config.ts `? in which version it will available?

**Comment by daniloff200** [comment]
You have to wait.
The latest available version is 6.0.0 -> https://www.npmjs.com/package/ngx-bootstrap/v/6.0.0
And the max date range feature was merged 20 days ago, and new version was not released since  that time.

I hope, we made a new release in 10-15 days

**Comment by hemchudgar** [comment]
Does this feature is available now in version 6.0.0?

**Comment by hemchudgar** [comment]
When this feature will be available?

**Comment by daniloff200** [comment]
6.1.0 was released today, and now, available @hemchudgar
