### ISSUE TITLE
Translate the "Today Button" in the Datepicker

### ISSUE THREAD

**Issue by llutti** [valor-software/ng2-bootstrap#5896]
I need to translate the new "Today Button" in the Datepicker, but I din´t found how to in the documentation.

**Comment by daniloff200** [comment]
Yes, because there's no way to do it for now.

**Comment by Dassderdie** [comment]
The same should be done for the "Clear"-button #5837

**Comment by boloboloda** [comment]
The "Custom Range" button in feather of Quick select ranges  has same issue.
This is the link. https://stackblitz.com/edit/angular-ivy-zb5yk1?file=src/app/app.component.html

**Comment by fhuschle** [comment]
If nobody has already started I could take a look at that
