### ISSUE TITLE
[datepicker] Asymmetrical paddings and unecessary border when not using today or clear button

### ISSUE THREAD

**Issue by Dassderdie** [valor-software/ng2-bootstrap#5909]
This screenshot is  from [the documentation](https://valor-software.com/ngx-bootstrap/#/datepicker#inline-datepicker).
![image](https://user-images.githubusercontent.com/18506183/90784826-f601b180-e301-11ea-8be5-d92f0c1cf64f.png)

If no additional button is used the `.bs-datepicker-buttons`-div is still visible. This worsens the design.

ngx-bootstrap: 6.0.0

**Comment by daniloff200** [comment]
ah, yes, thanks for finding that
I'm gonna merge a PR with a fix right now, it will be available in 6.1.0
