### ISSUE TITLE
Setting current page of paginator results in a different page selected in paginator

### ISSUE THREAD

**Issue by pp6024** [valor-software/ng2-bootstrap#5913]
Items array has 8 elements or a given type.

ngx-bootstrap version:      "ngx-bootstrap": "^5.6.1",

// Typescript 
  itemsPerPage = 2;
  currentPage = 1;

 setPage(page: number) {
    this.currentPage = page;
    this.cd.detectChanges();
  }

 pageChanged(event: PageChangedEvent): void {
    const startItem = (event.page - 1) * event.itemsPerPage;
    const endItem = event.page * event.itemsPerPage;
    this.pagedItems = this.items.slice(startItem, endItem);   //Retrieve items for page
    this.cd.detectChanges();
  }

// HTML Template

<tbody>
    <tr *ngFor="let account of pagedItems ">

<pagination
    [totalItems]="items.length"            // Total items array
    [itemsPerPage]="itemsPerPage"
    [boundaryLinks]="true"
    [directionLinks]="true"
    [maxSize]="5"
    [(ngModel)]="currentPage"
    name="currentPage"
    (pageChanged)="pageChanged($event)"
    (pageBoundsCorrection)="pageChanged($event)">
</pagination>

<button
    (click)="this.setPage(3)">
    Go To Page 3
</button>

Notes:

Clicking Button "Go To Page 3" once results in Active page being set to 2
Oddly, clicking "Go To Page 3" twice always causes page 3 to become active. 
![image](https://user-images.githubusercontent.com/70034434/90944944-6afae700-e3e7-11ea-88fc-ae2691f6d1da.png)

Clicking "Last" results in Active page being set to 3 of 4 pages
![image](https://user-images.githubusercontent.com/70034434/90944975-94b40e00-e3e7-11ea-971a-8f64f55d80eb.png)

**Comment by fhuschle** [comment]
I have created an example but cannot reproduce it - did i miss something? https://stackblitz.com/edit/angular-ngx-bootstrap-5913

**Comment by apotapcukv** [comment]
Dear pp6024!
As per our check this issue is fixed in the latest version, so we’re closing the issue.
Please don’t hesitate to let us know if you face further issues.
