### ISSUE TITLE
Datepicker reverse order (aka. Material Datepicker "startView")

### ISSUE THREAD

**Issue by rlmestre** [valor-software/ng2-bootstrap#5920]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to reverse the order of selection of the parts of a date. In other words, set the "start view" to year and work the other way around. This is ideal for drastic year change scenarios (eg. birth dates.)

**Describe the solution you'd like**

Something similar to what Angular Material does.
https://material.angular.io/components/datepicker/overview#setting-the-calendar-starting-view

**Describe alternatives you've considered**

Angular Material is the only Angular datepicker which currently provides this functionality (out of the box). Not ng-bootstrap, ng-lightning, PrimeNG.

**Additional context**

Unfortunately switching libraries or forking this one are out of the question for now.

**Comment by daniloff200** [comment]
Can it be related to https://github.com/valor-software/ngx-bootstrap/issues/5816 ???

**Comment by rlmestre** [comment]
Yes, it appears to be the same issue. I'll close this. Thank you!
