### ISSUE TITLE
bsDatepicker Format Issue

### ISSUE THREAD

**Issue by KevinSRobinson** [valor-software/ng2-bootstrap#5921]
This date 
21-09-2020

Using This 
  <input type="text" [(ngModel)]="expiryDate" class="form-control" bsDatepicker
        [bsConfig]="{dateInputFormat: 'DD-MM-YYYY' }">

Produces
![image](https://user-images.githubusercontent.com/1537210/92236113-ae0b8e80-eeac-11ea-838e-1543812e4ec5.png)

**Comment by daniloff200** [comment]
Looks like, now it's fine
Tested with the latest 7.1.2 version
