### ISSUE TITLE
5.7.0 no match to NPM

### ISSUE THREAD

**Issue by chrispcb** [valor-software/ng2-bootstrap#5922]
Hello,

5.7.0 is unknow to NPM.

**Comment by daniloff200** [comment]
5.7.0 was not published to npm, because, was broken because of Angular 10 incompatibilty.
All fixes and features from 5.7.0 was released in 6.0.0

**Comment by chrispcb** [comment]
hi,

Too bad, I needed the "today" button. I am on angular 8. It is not possible to add this functionality on the plugin compatible angular 8?
