### ISSUE TITLE
Cannot read property 'length' of undefined -in this._matches.length

### ISSUE THREAD

**Issue by anusreemn** [valor-software/ng2-bootstrap#5926]
**Bug Description:**

_Cannot read property 'length' of undefined_ TypeError thrown at [typeahead.directive.ts#L324](https://github.com/valor-software/ngx-bootstrap/blob/6a5df49a9138a9c9c69119bae2b64bca1334f4f0/src/typeahead/typeahead.directive.ts#L324) when blurred out of the autocomplete field.

Console error stack is -
TypeError: Cannot read property 'length' of undefined
    at TypeaheadDirective.onBlur (ngx-bootstrap-typeahead.js:2014)
    at TypeaheadDirective_blur_HostBindingHandler (ngx-bootstrap-typeahead.js:2398)

**Versions of ngx-bootstrap, Angular, and Bootstrap:**

ngx-bootstrap: ^5.0.0
Angular: ^10.0.9
Bootstrap: 3.3.7
Build system: Angular CLI

**Expected behavior**
Blurred out of field without any console errors

**Possible solution**

Add additional check at [typeahead.directive.ts#L324](https://github.com/valor-software/ngx-bootstrap/blob/6a5df49a9138a9c9c69119bae2b64bca1334f4f0/src/typeahead/typeahead.directive.ts#L324)  as below:
`if (!this.container && this._matches && this._matches.length === 0) {`

Identified the code snippet was introduced in commit [#c4f5236](https://github.com/valor-software/ngx-bootstrap/commit/c4f52369b3d84b9855b0928543ff4625153c43ff) contained within [PR#5629](https://github.com/valor-software/ngx-bootstrap/pull/5629) (_v5.6.0_)

@dmitry-zhemchugov @daniloff200

**Comment by daniloff200** [comment]
That was fixed already, and released with 6.0.0
You use Angular 10, so, this version should be fine for you. Could you please try it, and post and update, was it helpful or not?
