### ISSUE TITLE
Button Radio - Shift+Tab not work

### ISSUE THREAD

**Issue by samshay** [valor-software/ng2-bootstrap#5927]
Problem : When i use keybord to navigate in radio button, it's impossible to tab back with "shift+tab".
The focus stay at the button radio.

Browser : Chrome 85 and Firefox 79

Test : Ngx-bootstrap Documentation 6.1.0 https://valor-software.com/ngx-bootstrap/#/buttons#radio-button-with-group

**Comment by daniloff200** [comment]
Works good on current docs app, with ngx-bootstrap 7.1.2
