### ISSUE TITLE
Managed to run the files but only blank page is shown

### ISSUE THREAD

**Issue by MelanieSiw** [valor-software/ng2-bootstrap#5936]
After downloading the template, I managed to run in on the localhost/4200. However, only the header and the side navigation bar is shown, clicking on any of the components from the side bar is not functional and shows only a blank page. Please advice.

![image](https://user-images.githubusercontent.com/48702594/94126575-5b5d3b00-fe8a-11ea-8ecd-85a07c936319.png)

**Comment by valorkin** [comment]
I have a feeling, you are referring to https://www.bootstrapdash.com/product/purple-angular/
please send issue to authors of this template
regards
