### ISSUE TITLE
Receiving 100+ 'Circular source file mapping dependency' warnings with @angular/cli 10.1.4

### ISSUE THREAD

**Issue by DanAtkinson** [valor-software/ng2-bootstrap#5945]
Hi there,

**Bug description:**

After updating from @angular/cli 10.1.2 to @angular/cli 10.1.4, I now receive 125 console warnings relating to ngx-bootstrap when I attempt to run the following command:

    ng build --sourceMap=true --prod=true

I am unable to provide a repro as this happens when building.

I have uploaded the full warning list to pastebin:
https://pastebin.com/6vUE25Zx

Below is a snippet of the first set of warnings:

    Compiling @angular/animations : es2015 as esm2015
    Compiling ngx-bootstrap/mini-ngrx : es2015 as esm2015
    Compiling @angular/core : es2015 as esm2015
    Compiling ngx-bootstrap/chronos : es2015 as esm2015
    Warning: Unable to fully load X:/Path/To/node_modules/ngx-bootstrap/mini-ngrx/ngx-bootstrap-mini-ngrx.d.ts for source-map flattening: Circular source file mapping dependency: X:/Path/To/node_modules/ngx-bootstrap/mini-ngrx/ngx-bootstrap-mini-ngrx.d.ts.map -> X:/Path/To/node_modules/ngx-bootstrap/mini-ngrx/ngx-bootstrap-mini-ngrx.d.ts.map
    Warning: Unable to fully load X:/Path/To/node_modules/ngx-bootstrap/chronos/ngx-bootstrap-chronos.d.ts for source-map flattening: Circular source file mapping dependency: X:/Path/To/node_modules/ngx-bootstrap/chronos/ngx-bootstrap-chronos.d.ts.map -> X:/Path/To/node_modules/ngx-bootstrap/chronos/ngx-bootstrap-chronos.d.ts.map

If I set `--sourceMap=false` then there are no warnings, although I need to output the sourcemaps so this is not a viable solution for me.

**Versions of ngx-bootstrap, Angular, and Bootstrap:**

ngx-bootstrap: 6.1.0
Angular: 10.1.4
Bootstrap: 4.5.2

Build system: Angular CLI, System.js, webpack, starter seed: Angular CLI

**Expected behavior**

There should be no warnings as there weren't any before I updated from Angular CLI 10.1.2.

Thanks!

**Comment by valorkin** [comment]
hello, while fix issue with ngrx is easy.
fixing chronos is hard to say when it will be available
please use `skipLibCheck: true` in ts config in the meanwhile.
it's known issue, and is on my todo list.
closing as duplicate if you don't mind
