### ISSUE TITLE
maxDateRange does not update the enabled range

### ISSUE THREAD

**Issue by angelinuxx** [valor-software/ng2-bootstrap#5946]
**Bug description:**
The option maxDateRange does not work correctly when the start date is selected multiple times in a row.

If for instance maxDateRange is set to 10, picking April 14 as a start date disables dates from April 25 onwards. If instead of picking the end date I click a new start date (let's say April 10), the enabled date range does not update, still allowing me to select up to April 24.

![bug](https://user-images.githubusercontent.com/8066472/94913752-177dbd80-04aa-11eb-9166-4fdf9e9e3aca.gif)

ngx-bootstrap: 6.1.0
Angular: 10.0.5
Bootstrap: 4.5.0

Build system: Angular CLI

**Expected behavior**
The update of the enabled date range

**Comment by crisilva95** [comment]
Hi, I'm having the same issue!
This also applies to the maxDate. If I select a start date and the range to the maxDate is lower than the maxDateRang, the maxDateRange is somehow overlapping the maxDate. Consequently, the days following the maxDate I had set are active (and not disabled as they should be)
