### ISSUE TITLE
[Datepicker] Apply color theme in "Today" and "Clear" buttons

### ISSUE THREAD

**Issue by rafaelss95** [valor-software/ng2-bootstrap#5948]
**Is your feature request related to a problem? Please describe.**
The "Today" and "Clear" buttons apply "btn-success" class no matter what theme you choose for datepicker.

**Describe the solution you'd like**
I would like to see them colored according to chose theme.

**Describe alternatives you've considered**
Override it manually.

**Versions of ngx-bootstrap, Angular, and Bootstrap**:

ngx-bootstrap: 6.1.0
Bootstrap: 4.5.2
Angular CLI: 10.1.4
Node: 13.7.0
OS: darwin x64

Angular: 10.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.4
@angular-devkit/build-angular   0.1001.4
@angular-devkit/core            10.1.4
@angular-devkit/schematics      10.1.4
@angular/cdk                    10.2.3
@schematics/angular             10.1.4
@schematics/update              0.1001.4
rxjs                            6.6.3
typescript                      4.0.3

**Comment by daniloff200** [comment]
Gonna pick this one, hope to  fix it in next version
