### ISSUE TITLE
ViewMode month in short format [Ex: January = Jan]

### ISSUE THREAD

**Issue by mithila07** [valor-software/ng2-bootstrap#5950]
I'm trying to show short month view on ngx-datepicker month view. But so far no references found. Currently month picker is showing full name of the month.

**Comment by daniloff200** [comment]
Hello, @mithila07 !
Formatting are the same, as in moment.js, and it's mentioned in our [docs](https://valor-software.com/ngx-bootstrap/#/datepicker#format)

So, if you want to show, for example,` 8 Oct 2020,`  you need to use `MMM Do YYYY` in dateInputFormat property, like this

` [bsConfig]="{ dateInputFormat: 'MMM Do YYYY }">`

**Comment by mithila07** [comment]
Thanks for the quick reply @daniloff200,

I think you didn't understand my requirement. So check below picture.
![screenshot-localhost_4200-2020 10 09-09_11_39](https://user-images.githubusercontent.com/49783939/95540869-7e9df380-0a0f-11eb-98f2-493fdd44af8f.png)

I want my month picker looks like this. Not the placeholder that shows in input-box

**Comment by daniloff200** [comment]
Ah, that's what @mithila07 
You also can do it

Try such option
 `       [bsConfig]="{  monthLabel: 'MMM' }">`

**Comment by mithila07** [comment]
Its working perfectly the way I want. Thanks a lot @daniloff200. You're a saviour

**Comment by daniloff200** [comment]
@mithila07  glad, that I was able to help :) good luck !
