### ISSUE TITLE
TypeError when clearing daterange with active showPreviousMonth option

### ISSUE THREAD

**Issue by tinogo** [valor-software/ng2-bootstrap#5951]
Bug description:

1. Instantiate a daterangepicker instance with the `showPreviousMonth` set to `true`, e.g. https://valor-software.com/ngx-bootstrap/#/datepicker#daterangepicker-previous-month
2. Set a valid daterange
3. Open the browser developer tools --> Console-Tab
4. Remove the set daterange within the input field completly
5. Blur the input field
6. Look into the browser console. You will see the error "TypeError: e.selectedRange is null"

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: Internally we are using ngx-bootstrap 5.6.1, but the bug is still present in the current version (v6.1.0 as of writing this).

Angular: 8.2.14

Bootstrap: 4.4.2

Build system: Angular CLI

**Expected behavior**

No error within the console

**Comment by daniloff200** [comment]
Thanks for finding that.
Will be fixed in the next available version
