### ISSUE TITLE
ModalOptions "id" not filled with unique number

### ISSUE THREAD

**Issue by larini** [valor-software/ng2-bootstrap#5954]
ngx-bootstrap: 6.1.0
Angular: 10

When doing modalservice.show, the "id" property is always filled with same value, causing problems when hiding one specific instance.
According to documentation:  `Allow user to ID for the modal. Otherwise, a unique number will be given`, but its not what's happening.

**Comment by luca-nardelli** [comment]
This happened to us as well today, we spent much time debugging it :( I created a reproducible example here https://github.com/luca-nardelli/ngx-bootstrap-modal-issue

I wasn't able to make stackblitz work with Ivy, but cloning the repo and running ng-serve should be sufficient

**Comment by psmontoto** [comment]
I am also seeing this issue. The problem started when I upgraded to Angular 10 and ngx-bootstrap 6.1.0. Modals that used to work fine started exhibiting this issue. For now, I am manually assigning unique ids to modals as a work-around.

**Comment by leo6104** [comment]
#5939 will fix the issue. It will be apply on next version. Until that, please see https://github.com/valor-software/ngx-bootstrap/issues/5919#issuecomment-700586206 solutions.

**Comment by valorkin** [comment]
Fix is merged and will be released with 6.2 or 7 next week
cc @daniloff200
