### ISSUE TITLE
btnRadioGroup emits value changes twice

### ISSUE THREAD

**Issue by aleesaan** [valor-software/ng2-bootstrap#5958]
Bug description:
When changing value in the `btnRadioGroup`, the new value is emitted twice. This happens both when subscribing to `valueChanges`, and with the `ngModelChange` event (also in template-driven forms).

Plunker/StackBlitz that reproduces the issue:
https://stackblitz.com/edit/btnradiogroup-double-emit-reactive
https://stackblitz.com/edit/btnradiogroup-double-emit-template-driven

Versions of ngx-bootstrap, Angular, and Bootstrap:
ngx-bootstrap: 6.x.x
Angular: 10.x.x
Bootstrap: 4.x.x

**Expected behavior**
The new value should only be emitted once.

**Comment by rekna1** [comment]
I'm having the same issue in template driven ... any solution yet ?

**Comment by aleesaan** [comment]
> I'm having the same issue in template driven ... any solution yet ?

@rekna1  Not really a solution, but at the moment I just do `control.valueChanges.pipe(distinctUntilChanged())` to not emit the same value multiple times...

**Comment by rekna1** [comment]
@aleesaan I have done something similar but this should be relatively simple to solve by ngx-bootstrap self ? Can't imagine this is a very complex component...
