### ISSUE TITLE
Is it possible to not display the calendar if isDisabled = true?

### ISSUE THREAD

**Issue by chrispcb** [valor-software/ng2-bootstrap#5960]
Hi,

There is an isDisabled configuration to disable the calendar, but it still shows up. I don't really see the point of displaying a calendar picker and not being able to select anything.

If the entry is read-only or disabled or [isDisabled] = true, I wouldn't want to display calandar.

How can I do ?

thanks,

**Comment by daniloff200** [comment]
Well, isDisabled can be useful in cases, when you want just to show some dates in calendar for specific months, but, don't want dates or months to be changed

If you want to hide a calendar in some cases, you can just override the styles, something like:

`
bs-datepicker-container {
 display: none !important
}
`

**Comment by Xambey** [comment]
+1 add 'display' property
