### ISSUE TITLE
[Documentation] Error in TimePicker doc

### ISSUE THREAD

**Issue by simfyz** [valor-software/ng2-bootstrap#5966]
**Description:**
There is a documentation miswording in the following, Please check the screenshot.
Found this in Time picker documentation https://valor-software.com/ngx-bootstrap/#/timepicker#timepicker-config

_Minute step_ is incorrectly worded as _hours step_. Please change the documentation 

![image](https://user-images.githubusercontent.com/29760893/96851322-8761e100-1475-11eb-9a9f-3d0797b57b28.png)

**Comment by valorkin** [comment]
@simfyz this docs are generated from comments in code, your welcome to create PR

**Comment by daniloff200** [comment]
fixed in #5962
