### ISSUE TITLE
Using a modal to open another nested modal, then closing the nested one, causes the parent modal to be hidden.

### ISSUE THREAD

**Issue by mytamimi** [valor-software/ng2-bootstrap#5967]
**Bug description:**

Please refer to the following repository to reproduce the issue: https://github.com/mytamimi/ngx-bootstrap-nested-modals-bug

The example demonstrates a page that opens a modal, which in turn contains a button to open another modal.
Both modals are shown using the **BsModalService** method with components.

If the user attempts to close the child (top-most) modal, the parent modal would be hidden while the backdrop remains, pressing ESC only closes the backdrop.

This behavior is replicated using v6.1.0, it does not occur using v6.0.0.

**Versions of ngx-bootstrap, Angular, and Bootstrap:**

ngx-bootstrap: 6.1.0

Angular: 9.1.12

Bootstrap: 4.1.1

Build system: Angular CLI 9.1.12

**Expected behavior**

Closing the child modal should not affect the state of the parent modal, the parent modal should remain displayed until it is closed by some command.

**Comment by thorstenv** [comment]
had the same problem. when debugging it seemed to me the parent and child have the same internal id.
a workaround is to manually provide the child id when opening the modal

    this.bsModalRef = this.modalService.show(
      component,
      Object.assign({}, { class: 'modal-lg', keyboard: false, ignoreBackdropClick: true, id: 9996 })
    );

at least that worked for us

**Comment by jeff-jacobs** [comment]
I presume it has to do with the fix that was made here https://github.com/valor-software/ngx-bootstrap/pull/5939? It was about a month after v6.1.0 was released.

**Comment by valorkin** [comment]
fix should be released soon

**Comment by javed-tz** [comment]
> had the same problem. when debugging it seemed to me the parent and child have the same internal id. a workaround is to manually provide the child id when opening the modal
> 
> ```
> this.bsModalRef = this.modalService.show(
>   component,
>   Object.assign({}, { class: 'modal-lg', keyboard: false, ignoreBackdropClick: true, id: 9996 })
> );
> ```
> 
> at least that worked for us

Thanks, Its work for me

**Comment by raviagheda** [comment]
> had the same problem. when debugging it seemed to me the parent and child have the same internal id. a workaround is to manually provide the child id when opening the modal
> 
> ```
> this.bsModalRef = this.modalService.show(
>   component,
>   Object.assign({}, { class: 'modal-lg', keyboard: false, ignoreBackdropClick: true, id: 9996 })
> );
> ```
> 
> at least that worked for us

Thanks, worked for me as well 😊 🚀

**Comment by Middle-cod3** [comment]
where to put this code , can someone help me, while opening a 2nd modal i dont want to hide parent modal.

**Comment by raviagheda** [comment]
> where to put this code , can someone help me, while opening a 2nd modal i dont want to hide parent modal.

So you can pass id: \<UNIQUE\_NUMBER> in config ( ModalOption ) of modalService.show method!  
  
```typescript
this.modalService.show(<COMPONENT>, { id: <UNIQUE_NUMBER> });
```

**Comment by Middle-cod3** [comment]
Thank you so much for your kind gesture .
