### ISSUE TITLE
DatePicker maxDateRange configuration ignores maxDate option

### ISSUE THREAD

**Issue by pachabelle** [valor-software/ng2-bootstrap#5979]
In the date range picker, when both the maxDate and the maxDateRange options are set, when the first date is selected, the maxDateRange configuration option kicks in, however it disregards the maxDate configuration option. For instance:

maxDate = today
maxDateRange = 10

If I selected yesterday as the starting date, the selectable days options become (yesterday + 9 days).  The expectation is that only (yesterday - today) should be allowed because the maxDate was set.  The maxDateRange should respect what maxDate option is set to.

**Comment by rafaelss95** [comment]
I just faced the same issue today.

Stackblitz to demonstrate: https://stackblitz.com/edit/ngx-bootstrap-issue-5979

This relates to https://github.com/valor-software/ngx-bootstrap/issues/5946
