### ISSUE TITLE
Publish 6.2.0 version to NPM

### ISSUE THREAD

**Issue by rafaelss95** [valor-software/ng2-bootstrap#5981]
**Description:**
Apparently the version 6.2.0 hasn't been published. You can check by running e.g. `npm show`:

`npm show ngx-bootstrap version`

It shows 6.1.0 as the last version.

**Comment by daniloff200** [comment]
![Selection_126](https://user-images.githubusercontent.com/13692220/98470144-84dce680-21ec-11eb-88df-818131f936f9.png)

It's actually published, with the next tag

You can install it with ` npm i ngx-bootstrap@6.2.0` or `npm i ngx-bootstrap@next`
