### ISSUE TITLE
Add support for Angular 11

### ISSUE THREAD

**Issue by pavankjadda** [valor-software/ng2-bootstrap#5982]
**Description:**
After upgrading to Angular 11 I see following error message when using modal service
```
TS2345: Argument of type 'ElementRef<any>' is not assignable to parameter of type 'string | TemplateRef<any> | (new (...args: any[]) => any)'.   Type 'ElementRef<any>' is not assignable to type 'new (...args: any[]) => any'.     Type 'ElementRef<any>' provides no match for the signature 'new (...args: any[]): any'.
```
and the line that's causing the issue is here 
```
this.modalRef = this.modalService.show(this.elementView, this.modalConfig);
```

**Comment by valorkin** [comment]
hello, folks. We will try to deliver this asap.
most likely till the end of this week - early next one.
from 2 maintainers - one with covid, second with hard flu >.<

**Comment by samir-kamble** [comment]
I am getting same issue. Are we having any solution for this yet?
