### ISSUE TITLE
ngx -bootstrap tooltip going out of window

### ISSUE THREAD

**Issue by puneeth-91** [valor-software/ng2-bootstrap#5989]
Hi,
Am using ngx bootstrap tooltip(with large content) in my angular application,my ngx version 5.6.1,can anyone help me to solve  this here is the code which I had tried
  #tooltip tooltip="{{data[field]}}"container="body" containerClass="customClass"  [adaptivePosition]="false" placement="left"  triggers="click:mouseleave" (mouseenter)="onMouseEnter()">
{{data[field]}}

**Comment by apotapcukv** [comment]
The similar problem is described in the issue #5707

**Comment by SvetlanaMuravlova** [comment]
@puneeth-91 ,  hi) thank you for your issue. Try to add property "boundariesElement" for each tooltip element
more details you can find in conversation in issue #5707 

let us know if it doesn't help you)
