### ISSUE TITLE
Bootstrap 5 upgrade

### ISSUE THREAD

**Issue by JorgeFeijoom** [valor-software/ng2-bootstrap#5995]
Hi there,

We are thinking of integrating ngx-bootstrap to our angular based project. The current version presents a problem to us using jquery and we wonder if it is pending to update to bootstrap 5 which has some improvements, among others, the removal of jquery.

We know that it is still in beta, but we would like to know if it will be updated soon.

**Comment by valorkin** [comment]
I would say end of January is a something realistic to target, to release a support of bs5 templates

**Comment by delafer** [comment]
There is a main ngx-bootstrap competitor and it's name ng-bootstrap and whey are already working to support a new  BS version. 
new bootstrap version will be released anyway as soon as possible, Bootstrap 5 is already a beta version and where are a lot of youtube tutorials for BS5.  Who takes the lead ? ng-bootstrap or ngx-bootstrap ?  the one who will faster add a support for BS5. It is a obvious thing.
[BS5 Migration GUIDE](https://getbootstrap.com/docs/5.0/migration/)

**Comment by MickL** [comment]
@delafer You posted the same in the ng-bootstrap BS5 issue and what you wrote does not add anything useful for this issue or the discussion on that topic

**Comment by erickmcarvalho** [comment]
@valorkin Have you ever thought about how the BS5 implementation will be?

I mean, Bootstrap 5 no longer makes use of jQuery, and today its APIs are entirely native JavaScript.

Do you intend to keep the ngx-bootstrap code as your own implementation, as it is today, or to rewrite a new version that will only be "wrappers" for the BS5 native API itself?

**Comment by delafer** [comment]
> @delafer You posted the same in the ng-bootstrap BS5 issue and what you wrote does not add anything useful for this issue or the discussion on that topic

I only ask if there are such plans in both threads and confirm about the interest from people using such frameworks/libraries. Is it forbidden?
Perhaps you instead of making advices and dislikes under my posts will support such project? That would be pretty constructive, wouldn't it? 
I have posted a link with migration guide BS4 -> BS5, it's not much, but more than your meaningless comments. Thanks.

**Comment by ayoubkhan558-zz** [comment]
Please add support for Bootstrap 5, as it works without jQuery.
Its currently v5.0.0-beta1, But I think its right time to update now.

**Comment by valorkin** [comment]
https://github.com/valor-software/ngx-bootstrap/pull/6040 sorry folks my litle preparation PR took a bit longer then expected

**Comment by vinilanzoni** [comment]
@valorkin when will it be available to use in production with BS 5?

**Comment by oliverw** [comment]
So, Bootstrap 5 is out. What's the current story of ngx-bootstrap and BS5? 

**Update:** Looking at the code, there's currently no story. So in absence of any official response to this, I'd say BS5 support is quite far away.

**Comment by roger-urbano** [comment]
ng-boostrap to added BS5 with version beta and ngx-bootstrap nothing

**Comment by valorkin** [comment]
BS5 is in PRs already, with v7 release it should be pretty quick merge, test, release

**Comment by sulhome** [comment]
@valorkin Thank you. The release notes for version 7 is not mentioning anything about bootstrap 5. 
https://github.com/valor-software/ngx-bootstrap/blob/development/CHANGELOG.md

**Comment by oliverw** [comment]
> BS5 is in PRs already, with v7 release it should be pretty quick merge, test, release

What happened?

**Comment by juanchavezlive** [comment]
> already, with v7 release it should be pretty quick merge, test, release

Any news about this @valorkin ? 🤔

**Comment by valorkin** [comment]
watch this PR https://github.com/valor-software/ngx-bootstrap/pull/6115

PS where did half of year just disappeared

**Comment by daniloff200** [comment]
now, available in v 7.1.0

check this out, please :sweat_smile: 
 if something wrong - create issues, we will groom those next week and will release patch version with fixes

**Comment by RedactedProfile** [comment]
Just installed ngx-bootstrap a moment ago with Angular 12, and it brings in Bootstrap 4 still when using the angular cli `add` recipe 

![image](https://user-images.githubusercontent.com/1039911/133695085-aefeac70-c0b8-43ba-83b5-5dfb27cf018e.png)

![image](https://user-images.githubusercontent.com/1039911/133695108-e1048d58-69d7-4366-9d4a-870de2ca9490.png)

**Comment by valorkin** [comment]
Supported, doesn't mean default.
Bootstrap 5 will be default in ngx-bootstrap v8
