### ISSUE TITLE
Add option to allow timepicker to be cleared without being invalid

### ISSUE THREAD

**Issue by clepore** [valor-software/ng2-bootstrap#6003]
**Is your feature request related to a problem? Please describe.**

Clearing a timepicker (as seen [here](https://valor-software.com/ngx-bootstrap/#/timepicker#dynamic)) reports  as invalid because it tries to convert `void` to a date.

**Describe the solution you'd like**

An option to allow a timepicker to be optional or "empty". They initially load as empty without reporting as invalid, but once they have been changed, they cannot be cleared in a valid manner. Maybe `[isRequired]=false`?

**Describe alternatives you've considered**

A possible workaround could be to return which part of the timepicker is invalid, minutes and/or hours. Then custom validation could choose what is valid or not.

I tried to use custom validation, but `$event` only returns a boolean as a whole, so I can't tell if one, the other, or both fields are empty or not.

**Additional context**

| Desc | Screenshot |
| --- | --- |
| Valid with populated inputs | <img width="676" alt="Screen Shot 2020-12-28 at 12 08 51 PM" src="https://user-images.githubusercontent.com/742319/103231344-89c53900-4905-11eb-87a8-70f6ccd9223a.png"> |
| Invalid when cleared | <img width="577" alt="Screen Shot 2020-12-28 at 12 09 02 PM" src="https://user-images.githubusercontent.com/742319/103231366-9cd80900-4905-11eb-8542-6d6b597983c8.png"> |

**Comment by joehansen** [comment]
Hey, any updates on this issue? We are facing the same. Thanks
