### ISSUE TITLE
Import NgbModule in app.module.ts

### ISSUE THREAD

**Issue by glokesh94** [valor-software/ng2-bootstrap#6009]
Import NgbModule in app.module.ts

`import {NgbModule} from '@ng-bootstrap/ng-bootstrap';`

`@NgModule({
 imports: [NgbModule],
})
export class YourAppModule {
}`

_Originally posted by @glokesh94 in https://github.com/valor-software/ngx-bootstrap/issues/975#issuecomment-756274144_

**Comment by daniloff200** [comment]
`ng-bootstrap/ng-bootstrap`

`ngx-bootstrap`

:thinking:  :thinking:  :thinking:  :thinking: 

I think you need to go https://github.com/ng-bootstrap/ng-bootstrap here with that issue :)
