### ISSUE TITLE
Scrollable ng-boostrap-tabs is not working

### ISSUE THREAD

**Issue by kanisubu** [valor-software/ng2-bootstrap#6015]
Custom class with scrollable tab is not working.

**Comment by daniloff200** [comment]
Hi, @kanisubu 
I would like to get some more info about this, maybe, some code, or, repro

Also, it's not `ng-bootstrap` repo, it's `ngx`, so maybe, you have chosen the wrong library repo :(

**Comment by daniloff200** [comment]
Closed because of inactivity.
Feel free to drop me a message for reopen, if it's still an issue @kanisubu
