### ISSUE TITLE
Does carousel support swipe with gestures on mobile device?

### ISSUE THREAD

**Issue by szhang6** [valor-software/ng2-bootstrap#6022]
I have used the carousel component on desktop page and it works fine. While now i need to support carousel on mobile device, too. 

So, i have hidden the left and right arrow on the sides of the carousel. And at the same time, i need to let the carousel on mobile device support swipe with gestures.

My question is: 
1. Do we support this "swipe" feature now on mobile device? 
2. If yes, how to use it?

**Comment by szhang6** [comment]
Update:

I've found an issue which is similar with this one:
[https://github.com/valor-software/ngx-bootstrap/issues/885](https://github.com/valor-software/ngx-bootstrap/issues/885)


While, it seems does not support to click circularly. e.g. Always swipe from one side to another. It seems does not support this feature yet.

Do we support this feature yet?

**Comment by szhang6** [comment]
i have added some logic for handling swipe the slides cyclically.

``` javascript
private onTouchMove(e: TouchEvent): void {
        if (this.stillMoving) {
            const x = e.touches[0].pageX;
            const difference = this.start - x;
            if (Math.abs(difference) >= this.swipeThreshold) {
                this.cancelTouch();
                if (difference > 0) {
                    if (
                        this.carousel.activeSlide <
                        this.carousel.slides.length - 1
                    ) {
                        this.carousel.activeSlide =
                            this.carousel.activeSlide + 1;
                    } else if (
                        this.carousel.activeSlide ===
                        this.carousel.slides.length - 1
                    ) {
                        this.carousel.activeSlide = 0;
                    }
                } else {
                    if (this.carousel.activeSlide > 0) {
                        this.carousel.activeSlide =
                            this.carousel.activeSlide - 1;
                    } else if (this.carousel.activeSlide === 0) {
                        this.carousel.activeSlide =
                            this.carousel.slides.length - 1;
                    }
                }
            }
        }
    }
```

**Comment by szhang6** [comment]
This isssue has been fixed and added some feature as above. So, will close this issue now.

**Comment by muhammadali1995** [comment]
> i have added some logic for handling swipe the slides cyclically.
> 
> ```js
> private onTouchMove(e: TouchEvent): void {
>         if (this.stillMoving) {
>             const x = e.touches[0].pageX;
>             const difference = this.start - x;
>             if (Math.abs(difference) >= this.swipeThreshold) {
>                 this.cancelTouch();
>                 if (difference > 0) {
>                     if (
>                         this.carousel.activeSlide <
>                         this.carousel.slides.length - 1
>                     ) {
>                         this.carousel.activeSlide =
>                             this.carousel.activeSlide + 1;
>                     } else if (
>                         this.carousel.activeSlide ===
>                         this.carousel.slides.length - 1
>                     ) {
>                         this.carousel.activeSlide = 0;
>                     }
>                 } else {
>                     if (this.carousel.activeSlide > 0) {
>                         this.carousel.activeSlide =
>                             this.carousel.activeSlide - 1;
>                     } else if (this.carousel.activeSlide === 0) {
>                         this.carousel.activeSlide =
>                             this.carousel.slides.length - 1;
>                     }
>                 }
>             }
>         }
>     }
> ```


@szhang6 Is this code released ?
