### ISSUE TITLE
typeahead typeaheadOnBlur not working

### ISSUE THREAD

**Issue by rekna1** [valor-software/ng2-bootstrap#6025]
Event not triggered ?

see demo page https://valor-software.com/ngx-bootstrap/#/typeahead#on-blur
Option on blur:  
remains for ever empty....

**Comment by daniloff200** [comment]
hi, @rekna1 
Maybe, you're doing something wrong? 

Because, for me, it works


https://user-images.githubusercontent.com/13692220/107057105-bd846000-67db-11eb-88b2-eece5304451d.mp4
