### ISSUE TITLE
Please add support for Bootstrap 5

### ISSUE THREAD

**Issue by ayoubkhan558-zz** [valor-software/ng2-bootstrap#6026]
Please add support for Bootstrap 5, as it works without jQuery.
Its currently v5.0.0-beta1, But I think its right time to update now.

https://getbootstrap.com/

**Comment by kewur** [comment]
does this issue being closed mean that it's supported?

**Comment by Dassderdie** [comment]
> does this issue being closed mean that it's supported?

I guess this issue was closed as a duplicate of https://github.com/valor-software/ngx-bootstrap/issues/5995
