### ISSUE TITLE
Carousel - Multilist - Clicking on empty view displays blue border

### ISSUE THREAD

**Issue by jamesawer3** [valor-software/ng2-bootstrap#6027]
**Description:**
         When pressing on the empty view of carousel I can see a blue border around the div. How to remove it???

**Before Pressing:**
![Screenshot 2021-02-03 at 9 13 59 PM](https://user-images.githubusercontent.com/43437378/106771236-c0a91000-6664-11eb-83d3-c85b6863cbe6.png)

**After Pressing the empty space besides the image:**
![Screenshot 2021-02-03 at 9 15 03 PM](https://user-images.githubusercontent.com/43437378/106771407-ec2bfa80-6664-11eb-8356-566d9e6a378e.png)

**Comment by apotapcukv** [comment]
Dear jamesawer3! As per our check this issue is fixed in the latest version, so we’re closing the issue.
Please don’t hesitate to let us know if you face further issues.
