### ISSUE TITLE
Support Angular 10

### ISSUE THREAD

**Issue by rodrigosanzlongone** [valor-software/ng2-bootstrap#6029]
Bug description:

I just updated Angular to version 10, and now I have an error when trying to use **ng serve**.

Error:

`ERROR in Failed to find exported name of node (class ButtonRadioGroupDirective {
    constructor(el, cdr) {
        this.el = el;
        this.cdr = cdr;
        this.onChange = Function.prototype;
        this.onTouched = Function.prototype;
    }
    get value() {
        return this._value;
    }
    set value(value) {
        this._value = value;
    }
    writeValue(value) {
        this._value = value;
        this.cdr.markForCheck();
    }
    registerOnChange(fn) {
        this.onChange = fn;
    }
    registerOnTouched(fn) {
        this.onTouched = fn;
    }
}) in 'C:/Users/rsanz/Angular/node_modules/ngx-bootstrap/bundles/ngx-bootstrap.es2015.js'.`

(Versions of ngx-bootstrap, Angular, and Bootstrap)
My package.json:

`{
  "name": "rtp-front-end",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^10.2.4",
    "@angular/common": "^10.2.4",
    "@angular/compiler": "^10.2.4",
    "@angular/core": "^10.2.4",
    "@angular/forms": "^10.2.4",
    "@angular/localize": "^10.2.4",
    "@angular/platform-browser": "^10.2.4",
    "@angular/platform-browser-dynamic": "^10.2.4",
    "@angular/router": "^10.2.4",
    "@auth0/angular-jwt": "^3.0.1",
    "@ng-bootstrap/ng-bootstrap": "^7.0.0",
    "@popperjs/core": "^2.6.0",
    "angular-font-awesome": "^3.1.2",
    "bootstrap": "^4.6.0",
    "bpmn-js": "^3.0.1",
    "bpmn-js-properties-panel": "^0.33.2",
    "core-js": "^2.5.4",
    "diagram-js-minimap": "^1.3.0",
    "dom-to-image": "^2.6.0",
    "ej-angular2": "^16.2.46",
    "file-saver": "^2.0.0",
    "font-awesome": "^4.7.0",
    "font-awesome-filetypes": "^2.0.1",
    "highcharts": "^7.0.2",
    "highcharts-angular": "^2.4.0",
    "moment": "^2.23.0",
    "ngx-bootstrap": "5.3.2",
    "ngx-cookie-service": "^2.3.0",
    "ngx-loading": "^2.0.1",
    "ngx-quill": "^13.0.1",
    "popper.js": "^1.16.1",
    "quill": "^1.3.7",
    "quill-image-resize-module": "^3.0.0",
    "rx-observable-update": "^1.0.0",
    "rxjs": "^6.6.3",
    "rxjs-compat": "^6.3.2",
    "syncfusion-javascript": "^16.3.21",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1002.1",
    "@angular/cli": "~10.2.1",
    "@angular/compiler-cli": "^10.2.4",
    "@angular/language-service": "^10.2.4",
    "@types/ej.web.all": "^16.2.1",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.3.6",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "sass-lint": "^1.12.1",
    "ts-node": "~5.0.1",
    "tslint": "~6.1.0",
    "typescript": "~4.0.5"
  }
}
`

**Comment by fchiumeo** [comment]
see the [Compatibility](https://github.com/valor-software/ngx-bootstrap#compatibility)

**Comment by rodrigosanzlongone** [comment]
Thanks for your link, however, I just updated to 
`    "ngx-bootstrap": "^6.2.0",`

but nothing changed, I still have the same error.
Maybe, I need also to update another package?

**Comment by fchiumeo** [comment]
eliminaste node_module?
yo tengo instalado angular 11 y funcionada bien
