### ISSUE TITLE
Add a card component support

### ISSUE THREAD

**Issue by ryanrw** [valor-software/ng2-bootstrap#6030]
**Is your feature request related to a problem? Please describe.**

I've just found that this library doesn't have a card component yet, so I want to suggest implementing it.

**Describe the solution you'd like**

Add a "Card" component.

Ref: [Bootstrap's Card Component](https://getbootstrap.com/docs/4.0/components/card)

**Comment by Dassderdie** [comment]
Wouldn't it be better (code-style, extensibility, performance, bundle-size) to just use the correct bootstrap classes instead of making a separate component for cards? - Are there actually any benefits of a cards-component? Cards do not have any JS-code behind them...

**Comment by ryanrw** [comment]
> Wouldn't it be better (code-style, extensibility, performance, bundle-size) to just use the correct bootstrap classes instead of making a separate component for cards? - Are there actually any benefits of a cards-component? Cards do not have any JS-code behind them...

That's true. I think it would be better to just use a bootstrap class. Thank you for your advice.
