### ISSUE TITLE
Daterangepicker validation mutate the value

### ISSUE THREAD

**Issue by rkusuma** [valor-software/ng2-bootstrap#6034]
Bug description:

When using `ngrx` with `strictStateImmutability: true` config and passing the array of date to daterangpicker from ngrx state, it will throw an error:

```
Error: Uncaught (in promise): TypeError: Cannot assign to read only property '0' of object '[object Array]'
TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at Array.sort (<anonymous>)
    at BsDaterangepickerInputDirective.validate (ngx-bootstrap-datepicker.js:6166)
```

the root cause is in [here](https://github.com/valor-software/ngx-bootstrap/blob/development/src/datepicker/bs-daterangepicker-input.directive.ts#L152), in method validate it is mutate the array via `_value.sort()` method.
It is better not to mutate the value.

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 6.1.0

Angular: 10.2.1

Bootstrap: 3.4.1

Build system: Angular CLI

**Expected behavior**

It should not mutate the value instead, make a copy and then sort it.

**Comment by ajitsinghkaler** [comment]
@rkusuma create a copy of that array and pass it will work
