### ISSUE TITLE
Timepicker Dynamic Fails removing red error border when valid date is applyed to ngmodel

### ISSUE THREAD

**Issue by probfacile** [valor-software/ng2-bootstrap#6038]
**Bug description**: https://valor-software.com/ngx-bootstrap/#/timepicker#dynamic if you set time using button to 14:00 and then you put a wrong value in hour (eg. KK) it will not validate (red border) allright.
Now if you press again set to 14:00 it will fill ngmodel with correct value but the input box still have red error border.

**Plunker/StackBlitz that reproduces the issue**: Don't need it reproduces in your **examples**.

ngx-bootstrap: any

Angular: not relevant

Bootstrap: not relevant
 
Build system: Angular CLI, System.js, webpack, starter seed: your demo page

**Expected behavior**

The correct value should reset the error border

**Comment by Phoenix-Alpha** [comment]
Anyone fixed this issue?
Hi @probfacile, did you happen to find solution?

**Comment by Phoenix-Alpha** [comment]
https://user-images.githubusercontent.com/71273009/109223771-5561e200-77bb-11eb-8669-aeb70d3df9a7.mp4

**Comment by Phoenix-Alpha** [comment]
As I investigated, there is no validation update when writing value for ngmodel.
This may solve the problem.
![image](https://user-images.githubusercontent.com/71273009/109224530-5a736100-77bc-11eb-9f6d-942fe1d7cfed.png)

**Comment by Phoenix-Alpha** [comment]
@valorkin, any update for this?

**Comment by probfacile** [comment]
> Anyone fixed this issue?
> Hi @probfacile, did you happen to find solution?

hi, still no solutions found by me, and they did not update on this with a solution

**Comment by davebednarski** [comment]
+1
