### ISSUE TITLE
Range date incorrect styles css

### ISSUE THREAD

**Issue by Adam-Michalski** [valor-software/ng2-bootstrap#6041]
"ngx-bootstrap": "^5.6.0",

Few problems with styles in range picker causing incorrect display. I cannot find any changes in my project to this classes but reproduction is not exacly as my problem

In my project it looks like this
![image](https://user-images.githubusercontent.com/5684123/108205625-9e63c780-7125-11eb-9897-c07606e48d07.png)

Line between start and end so all elements with class `in-range` has empty space it was caused with `left: -2` instead of `left: -3`:
```
  .bs-datepicker-body table td:before,
  .bs-datepicker-body table td span:before {
    left: -2px; // I do not know why this param was set to -2
  }
```
I do not know if this is caused by changes in my code but I did not found any so I think you can check this one to.
But reproduction does not have this empty space beetween `in-range` classes

I fixed it with below override

```
  .bs-datepicker-body table td:before,
  .bs-datepicker-body table td span:before {
    left: -3px;
  }
```
First `in-range` and `selection-start` has not combine to one, we can see edges of first element cause in-range is hidden on `selection-start` there is also z-index set to 2 instead of auto like in selection-end
`selection-end` in reproduction works but in my case it has the same problem like with selection-start but in opposite direction.

I fixed it with below overrides

```
  // below code is workaround to incorrect range selection
  .bs-datepicker-body table.days span.select-end:before,
  .bs-datepicker-body table.days span.in-range.select-end:before {
    right: 4px;
    left: -3px;
    background: #e9edf0;
  }

  .bs-datepicker-body table td span.select-start:before  {
    right: -4px;
    left: 6px;
    background: #e9edf0;
  }

  .bs-datepicker-body table.days span.select-start {
    z-index: auto;
  }
```
[Reproduction](https://stackblitz.com/edit/angular-uvp5jl?file=app%2Fngx-bootstrap-demo.component.ts)

![image](https://user-images.githubusercontent.com/5684123/108205451-62c8fd80-7125-11eb-915c-070ca09eba5b.png)

**Comment by daniloff200** [comment]
it looks kinda the same, as https://github.com/valor-software/ngx-bootstrap/issues/5868, which was fixed in https://github.com/valor-software/ngx-bootstrap/pull/5871  exactly with 3px change.

This fix is available from 6.1.0, so, feel free to test some new versions
