### ISSUE TITLE
Vulnerability issue

### ISSUE THREAD

**Issue by RajanDhinoja** [valor-software/ng2-bootstrap#6045]
Bug description:

There is Cross-site Scripting issue :

https://snyk.io/test/npm/ngx-bootstrap/6.2.0

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 6.2.0

Angular: 11

Bootstrap: 4

Build system: Angular CLI, System.js, webpack, starter seed:

**Expected behavior**

There should not be vulnerability.

**Comment by daniloff200** [comment]
I think it's the same as https://github.com/valor-software/ngx-bootstrap/issues/5190 , so, also will be closed
