### ISSUE TITLE
DateRangePicker maxDateRange select earlier date after selecting from-Value doesn't update range

### ISSUE THREAD

**Issue by RobertPabst792** [valor-software/ng2-bootstrap#6052]
Bug description:
Set the maxDateRange to 20 like in your example at https://valor-software.com/ngx-bootstrap/#/datepicker#daterangepicker-max-date-range.
Select the FromDate and instead of selecting a valid UntilDate, select a date, that is earlier than the previously selected FromDate. The selected value is used as the new FromDate but the dateRange doesn't update. It is still set to 20 Days from your initial FromDate.

Plunker/StackBlitz that reproduces the issue:
Can be reproduced at https://valor-software.com/ngx-bootstrap/#/datepicker#daterangepicker-max-date-range 

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:6.1.0

Angular:10.2.1

Bootstrap:3.4.1

**Expected behavior**

Update the valid dateRange after selecting an UntilDate that is earlier than your previously selected FromDate.

**Comment by daniloff200** [comment]
it looks like, can be related to https://github.com/valor-software/ngx-bootstrap/issues/5979 and https://github.com/valor-software/ngx-bootstrap/issues/5946

We have a fix for it in https://github.com/valor-software/ngx-bootstrap/pull/6033

**Comment by RobertPabst792** [comment]
Thank you, looks like mine actually is a duplicate of #5946
