### ISSUE TITLE
Daterangepicker: max date range does not care min and max date after selection first value in range

### ISSUE THREAD

**Issue by dmytro-afonin** [valor-software/ng2-bootstrap#6056]
Steps to reproduce:
1. add daterangepicker to your template
2. set up next config `{minDate: new Date(2020, 01, 01), maxDate: new Date(2020, 01, 10), maxDateRange: 4}`
3. open Daterangepicker
4. you can see that all dates further than 2020/01/10 are disabled
5. select first date in range - 2020/01/10
Expected result:
further dates are still disabled
Actual result:
further dates are become enabled

**Comment by daniloff200** [comment]
hello, @dmitri-afonin 
does https://github.com/valor-software/ngx-bootstrap/issues/5979 or https://github.com/valor-software/ngx-bootstrap/issues/5946 can be related to this one?

**Comment by daniloff200** [comment]
I can confirm it was fixed, according to scenario, which was  introduced in the issue, and, fix is available from 7.0.0 version, but, my advice to use the latest version
