### ISSUE TITLE
Upgrading 5->6 breaks modal creation with initialState

### ISSUE THREAD

**Issue by esoyke** [valor-software/ng2-bootstrap#6059]
Upgrading from ngx-bootstrap 5 to 6 is causing a compiler error with my old code that sent initialState to a modal with a component. This used to work, and looks pretty much like the example in the docs:

    const initialState = {
        clientID: 123,
        username: 'foo',
    };
    this.modalRef = this.modalService.show(MyComponent, {initialState});

The error:
**Type '{ clientID: number; username: any; }' is not assignable to type 'Partial<OneTimePasscodeComponent>'.
  Types of property 'clientID' are incompatible.
    Type 'number' is not assignable to type 'string'.ts(2322)
modal-options.class.d.ts(38, 5): The expected type comes from property 'initialState' which is declared here on type 'ModalOptions<OneTimePasscodeComponent>'**

I can't create a Plunker or StackBlitz as both fail to install version 6.2.0 of ngx-bootstrap, the templates are for old versions and both sandboxes cannot seem to install v6.

I'm using Angular 9, bootstrap 4, ngx-bootstrap 6.2.0

**Comment by justinweathersby** [comment]
Im having a very similar issue..

**Comment by Jakartoine** [comment]
Hey @esoyke,

All is working fine from my side. Maybe posting your code may help?

Thanks

**Comment by grichards23** [comment]
Same issue - simple code I've used a millions times prior to version 6.
In version 6, this works:
```javascript
const opts = {
   class: 'modal-lg',
   initialState: {
      config: {
         id: 123
       } as FooBar
   }
};
```
This does not - only difference is I'm supplying ModalOptions as the Type:
```javascript
const opts: ModalOptions = {
   class: 'modal-lg',
   initialState: {
      config: {
         id: 123
       } as FooBar
   }
};
```
Using Type assertion also works:
```javascript
const opts = {
   class: 'modal-lg',
   initialState: {
      config: {
         id: 123
       } as FooBar
   }
} as ModalOptions;
```

**Comment by Et3rnal** [comment]
Same issue!
thanks to @grichards23 adding ` as ModalOptions` fix it

```
    const authModalConfig: ModalOptions = {
      keyboard: false,
      backdrop: false,
      ignoreBackdropClick: true,
      initialState: {
        lockIt: lockRequest
      }
    } as ModalOptions;
```
I don't know why the documentation doesn't use the type! it should
