### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by NickWemekamp** [valor-software/ng2-bootstrap#6061]
When will the next release of ngx-bootstrap be?

I'm looking for a release that has https://github.com/valor-software/ngx-bootstrap/pull/5521/ in it. Currently having performance issues for some users that open a lot of datepickers.

**Comment by leo6104** [comment]
I also waiting for next release. Wait for `closeInterceptor` feature in modal.

**Comment by daniloff200** [comment]
I suppose it should be available in latest version, it's 7.1.0 for now
