### ISSUE TITLE
Datepickerange not working min and max date

### ISSUE THREAD

**Issue by nchizhov** [valor-software/ng2-bootstrap#6068]
Bug description: When set config to minMode 'year' and set min and max date - user can select years before and after min/max dates.

Versions of ngx-bootstrap, Angular, and Bootstrap: 

ngx-bootstrap: 6.2.0

Angular: 11.1.0

Bootstrap: 3.4.1

Build system: Angular CLI

**Comment by valorkin** [comment]
sry, closing as can't reproduce
please use latest ngx-bootstrap version and stackblitz to provide a reproduction
