### ISSUE TITLE
Class "modal-open" is not removed from body when modal's closed.

### ISSUE THREAD

**Issue by devOneto** [valor-software/ng2-bootstrap#6076]
**Bug description:**

- When the modals open with a click that invokes BsModalService.show the class "modal-open" is added into a global <body> tag. But when the modal's closed that class it's not removed from there. It cases, for exemple, that the scrollbar dissapear in the all application "pages". 

ngx-bootstrap: ^5.6.1
Angular: 9.1.12
Bootstrap: 4.5.0

**Comment by SvetlanaMuravlova** [comment]
it seems it is resolved) https://images.zenhubusercontent.com/40403310/6a84af7e-51a9-4f0e-ac47-f69c61e264d1/modal_open.mp4

**Comment by devOneto** [comment]
Hello Svetlana Pavlova! Thanks for attention. That issue occurs in Angular 9.

**Comment by valorkin** [comment]
sorry, we don't backport to older versions of ngx-bootstrap
you should try v7, it will, most likely, work with angular 9

**Comment by devOneto** [comment]
Okay @valorkin! Thank you! My team was able to update the version in Project! :)

**Comment by valorkin** [comment]
That's awesome :)
