### ISSUE TITLE
Documentation to nx

### ISSUE THREAD

**Issue by why-asia** [valor-software/ng2-bootstrap#6094]
Move pages and sections to _libs_ folder, update the dependencies accordingly.

Structure:
lib -> doc_pages -> [Accordion, Alerts, Buttons, Carousel, Collapse, Datepicker, Dropdowns, Modals, Pagination, Popover, Progressbar, Rating, Sortable, Tabs, Timepicker, Tooltip, Typeahead ]; 
lib-> doc_section -> [demo, header, footer, etc]

Desired outcome: the dependency tree with documentation modules/sections is updated, at project build the documentation is built per module

**Comment by SvetlanaMuravlova** [comment]
Finalize structure after implementation 
Structure:
libs -> doc_pages -> [Accordion, Alerts, Buttons, Carousel, Collapse, Datepicker, Dropdowns, Modals, Pagination, Popover, Progressbar, Rating, Sortable, Tabs, Timepicker, Tooltip, Typeahead ];
libs-> common-docs -> [api-docs, common, demo-section, demo-section-components, docs-section, models, theme, tokens]
