### ISSUE TITLE
feat(datepicker): Only part of the days are enabled by default for 'Max Date Range in Daterangepicker' example

### ISSUE THREAD

**Issue by edchai** [valor-software/ng2-bootstrap#6111]
https://images.zenhubusercontent.com/40403310/0122eb50-9e74-4ed0-965b-3adf264fd009/max_date_range.mov

**Comment by valorkin** [comment]
@edchai as designed, because there are `[bsConfig]="{ maxDateRange: 25 }` set in this demo :)
