### ISSUE TITLE
Date range picker year and month calendar view incorrectly applies selected style when clicking on disabled year/month

### ISSUE THREAD

**Issue by m1kl** [valor-software/ng2-bootstrap#6149]
Bug description:

When using mix and max date, Date range picker year and month calendar view applies the selected style when clicking on disabled year / month cell.

[Video reproducing the bug](https://streamable.com/nmncew)

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 7.0.0-rc.0

Angular: 11.2.0

Bootstrap: 3 and 4

Build system: Angular CLI, System.js, webpack, starter seed:

**Expected behavior**

Clicking on the disabled years and months should not apply the selected style.

**Comment by apotapcukv** [comment]
Dear m1kl! 
As per our check this issue is fixed in the latest version, so we’re closing the issue.
Please don’t hesitate to let us know if you face further issues.
