### ISSUE TITLE
Is there any code breaking changes in v7.0.0 from v5.6.x

### ISSUE THREAD

**Issue by ambujkhanna** [valor-software/ng2-bootstrap#6175]
**Description:**
I am currently using v5.6.1 in Angular 8 project but I have just upgraded it to Angular v11 and I faced an issue with dropdown. It is not opening on first click. After second click it is start working properly. I find **root cause is `open` class is not adding in first time**
![image](https://user-images.githubusercontent.com/3599739/121809215-90f4bf00-cc79-11eb-80fb-ab22a3d7af36.png)

May be due to lower version and my concern is **If I will upgrade my version so Is there code breaking changes or something like that in latest version????**

**Comment by daniloff200** [comment]
hi, @ambujkhanna 
I should say, there're bunch of changes in 7.0.0 version, we've upgraded app to Angular 12 and made some fixes, full list available in the link below:
https://valor-software.com/articles/ngx-bootstrap-v7-0-0-is-officially-released.html
