### ISSUE TITLE
NgbTooltip instantly closes on iOS devices using Angular 11

### ISSUE THREAD

**Issue by Eddudavid** [valor-software/ng2-bootstrap#6176]
Bug description:

Having an ngbTooltip on a span element, on iOS devics the tooltip auto closes right after it opened.

Plunker/StackBlitz that reproduces the issue:

https://angular-ivy-el4yvx.stackblitz.io

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 9.1.2

Angular: 11.1.0

Bootstrap: 4.5.3

**Expected behavior**

Like on desctop, and android devices, the tooltip should stay open.

**Comment by daniloff200** [comment]
ngb-tooltip looks like a tooltip from ng-bootstrap. Also, we don't have version 9.1.2 :)
