### ISSUE TITLE
how to update data in already opened modal

### ISSUE THREAD

**Issue by zuberspathan** [valor-software/ng2-bootstrap#6185]

**Comment by Dassderdie** [comment]
I think this should not be an issue but instead a question on stackoverflow...

You could just inject a Service in your Modal and use the data the service provides.

You can do it also directly via `BsModalRef.content`. 
> Reference to a component inside the modal. Null if modal's been created with TemplateRef

Here is an example:
```ts
    const bsModalRef = bsModalService.show(
        MyModalComponent,
        {
            initialState,
            class: 'modal-lg',
        }
    );
    bsModalRef.content!.aPropertyInMyModal = newValue;
```
Depending on the ChangeDetectionStrategy in the modal it could be better to call a public function in the modal or solve this via a Subject.
