### ISSUE TITLE
Modal is not always hidden after calling .hide()

### ISSUE THREAD

**Issue by gregoire-rouillon** [valor-software/ng2-bootstrap#6195]
**Bug description**

Calling the `.hide()` method on a modal will not hide it if the opening animation (150ms by default) is not finished yet.

**Plunker/StackBlitz that reproduces the issue**

StackBlitz: https://stackblitz.com/edit/ngx-bootstrap-csh27l?file=src%2Fapp%2Fapp.component.ts

**Versions of ngx-bootstrap, Angular, and Bootstrap**

ngx-bootstrap: 6.2.0
Angular: 10.0.2
Bootstrap: 3.3.7

**Expected behavior**

The modal should hide

**Comment by dezsiszabi** [comment]
I see there is a merged PR for this, so I assume it'll be available in 10.x.
Any chance of backporting this to 9.x and 8.x?
I encountered the same issue in my project (which is still on 8.x) and having this fix would be really nice.

**Comment by renaldas-kerpe-arria** [comment]
Is this fixed in 9.x or 10.x?

**Comment by renaldas-kerpe-arria** [comment]
Which version was this fixed in? I see the same issue in 8.x.

Looks like this issue might have been re-introduced https://github.com/valor-software/ngx-bootstrap/issues/6195

**Comment by gregoire-rouillon** [comment]
Fixed by #6518 in 10.1.0
