### ISSUE TITLE
Dropdown is not closed after clicking on another one since 7.0.0

### ISSUE THREAD

**Issue by 7185** [valor-software/ng2-bootstrap#6248]
Bug description:

When I click on a dropdown button after another dropdown is opened, the first dropdown is not closed.

Plunker/StackBlitz that reproduces the issue:
https://valor-software.com/ngx-bootstrap/#/dropdowns

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 7.0.0

Angular: 12.1.0

Bootstrap: 4.6.0

**Expected behavior**

The first dropdown should be closed after a click on the second button, just like in version 6.2.0 :
https://valor-software.com/ngx-bootstrap/old/6.2.0/#/dropdowns

**Comment by bjaminp** [comment]
It looks like an event.stopPropagation was added to the click host listener in the toggle directive that is causing this. #6154

**Comment by 1-0-1** [comment]
This is a breaking change.

**Comment by valorkin** [comment]
@1-0-1 yes, and it was released in major version
we still need this behavior but it will be optional thx

**Comment by fwitkowski** [comment]
I have the same issue with version 7.1.0
