### ISSUE TITLE
Setting datesDisabled breaks inline datepicker bsValueChange-Event

### ISSUE THREAD

**Issue by evilstiefel** [valor-software/ng2-bootstrap#6263]
**Bug description**:

When using `bs-datepicker-inline`, disabling dates "asynchronously" (e.g., after the component has been created) breaks firing of `bsValueChange`.

**Plunker/StackBlitz that reproduces the issue**:

https://stackblitz.com/github/evilstiefel/ngx-bootstrap-datepicker-repro

**Versions of ngx-bootstrap, Angular, and Bootstrap**:

ngx-bootstrap: 7.0.0

Angular: 12.2.0

Bootstrap: 5.1.0

**Expected behavior**

I would expect to be able to set the `datesDisabled` property at any time, disabling dates, and not breaking change detection or the EventEmitter for `bsValueChange`.

**Comment by evilstiefel** [comment]
Apparently this already has an open PR and several tickets related to it (e.g. #5888, #5914). This is the PR: #6201 - hopefully this can be looked at and merged ASAP.

**Comment by rfrcarvalho** [comment]
This is also happening when setting the `dateCustomClasses` asynchronously (e.g., after the component has been created). If I hide the component with an *ngIf and then show it again, it will display the custom classes correctly. Is there any ETA on a resolution for this?
