### ISSUE TITLE
PaginationConfig texts are ignored

### ISSUE THREAD

**Issue by pmelisko** [valor-software/ng2-bootstrap#6264]
Bug description:
After migrating to ngx-bootstrap 7.0.0 override of pagination.config.ts doesn't work. It is caused by defaults, that were added in pagination and paginator components. i.e:
[https://github.com/valor-software/ngx-bootstrap/blob/development/src/pagination/pagination.component.ts](https://github.com/valor-software/ngx-bootstrap/blob/development/src/pagination/pagination.component.ts)
` @Input() firstText = 'First';`
older versions have just types (i.e. v 6.2.0)
`@Input() firstText: string;`

logic how texts are selected:
```
  getText(key: string): string {
    // tslint:disable-next-line:no-any
    return (this as any)[`${key}Text`] || (this as any).config[`${key}Text`];
  }
```
so config that should provide default values will be ignored, because there are already default values on component.

Plunker/StackBlitz that reproduces the issue:
[https://stackblitz.com/edit/ngx-bootstrap-ykyada](https://stackblitz.com/edit/ngx-bootstrap-ykyada)

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 7.0.0

Angular: 12.2.1

Bootstrap: 4

**Expected behavior**
PaginationConfig should provide default values not component.

**Comment by daniloff200** [comment]
hi, @pmelisko 
You can use https://valor-software.com/ngx-bootstrap/#/pagination#custom-links-content for such functionality
