### ISSUE TITLE
Accordion group (isOpenEvent) event not fired

### ISSUE THREAD

**Issue by amb-jarek** [valor-software/ng2-bootstrap#6266]
Accordion group `isOpenEvent` not fired in version 7.0.0. Reverting to v6.2.0 fix the issue.

https://stackblitz.com/edit/ngx-bootstrap-ksnvfx?file=package.json

ngx-bootstrap: 7.0.0
Angular: 12.2.1

**Comment by ceciliaporro** [comment]
Happens to me too
Angular: 12.2.0
ngx-bootstrap: 7.0.0
I'll revert too until this will be fixed

**Comment by valorkin** [comment]
it actually works in your sample

**Comment by amb-jarek** [comment]
Today it works indeed. Fu***in magic! 😃

**Comment by valorkin** [comment]
Loool :)
