### ISSUE TITLE
Datepicker v7.1.0 changing value of bsValue in code does not update input control value

### ISSUE THREAD

**Issue by mcair** [valor-software/ng2-bootstrap#6274]
Added a button that increments the bsValue variable by +1 day. The dropdown calendar will reflect the new date, but the input control value does not. Tried with bsValue and using [(ngModel)] binding, neither work.

https://stackblitz.com/edit/angular-y8atb1?file=app/date-initial-state.html

**Comment by valorkin** [comment]
the reason is simple, you are mutating Date object, angular is not able to detect this change
popup shows a new date cuz it's renders on click and show a new value
change `add` function in your sample to
```
  add(arg:number) {
    const newDate = new Date(this.bsValue);
    newDate.setDate(this.bsValue.getDate() + 1);
    this.bsValue = newDate;
  }
```
