### ISSUE TITLE
Datepicker modifies initial value after update from 6.2.0 to 7.0.0

### ISSUE THREAD

**Issue by exe-atewinkel** [valor-software/ng2-bootstrap#6276]
**Bug description:**
After updating from 6.2.0 to 7.0.0, the datepicker changes the time of any `Date` value that is set to the users current local time. This also happens when the datepicker is used in a form and an initial value is set. This causes the initial form value to change, while the user has not made any changes. Also, setting the time of the `Date` value to the current time makes no sense, since the time of selection is not in any way relevant to the selected date.

The commit that causes this: https://github.com/valor-software/ngx-bootstrap/commit/bc188d69bf17010dadd924673bfa13eef3944833

I suggest that this behaviour be removed again. Alternatively, it might make more sense to set the time to start of day on the selected date.

**Versions of ngx-bootstrap, Angular, and Bootstrap:**

ngx-bootstrap: 7.0.0

Angular: 12.1.4

Bootstrap: 4.5.3

**Expected behavior**

Expected behaviour would be that the initial `Date` value is set without modifications.

**Comment by valorkin** [comment]
I would agree that this feature https://github.com/valor-software/ngx-bootstrap/commit/bc188d69bf17010dadd924673bfa13eef3944833 doesn't make any sense to me

**Comment by defra91** [comment]
Good morning,

the problem seems to persist in v7.2.0. Today I was forced to downgrade to v6.2.0, which does not have the bug.

Apparently the option `initCurrentTime` is not working correctly.

Can you please provide some feedback?

**Comment by exe-atewinkel** [comment]
If I'm not mistaken this fix has not yet been released. We are waiting to upgrade as well. Am I correct?

**Comment by valorkin** [comment]
should be in v8 which is published to npm already

**Comment by defra91** [comment]
Thank you very much for your reply. Looking forward for a stable release of v8!
