### ISSUE TITLE
Documentation: Unclear reference to "Getting started guide"

### ISSUE THREAD

**Issue by Chealer** [valor-software/ng2-bootstrap#6287]
**Is your feature request related to a problem? Please describe.**

[The _Getting Started_ section of the "Documentation" page](https://valor-software.com/ngx-bootstrap/#/documentation#getting-started) contains:

> Check our Getting started guide if it's your first project with Angular Bootstrap.

It is unfortunately unclear how that guide can be accessed.

**Describe the solution you'd like**

If the guide is available online, I suppose the text "our Getting started guide" should become a link to it.

**Describe alternatives you've considered**
If not, a description of how to obtain that guide could be added, for example in a footnote or in a parenthesis.

**Additional context**

**Comment by valorkin** [comment]
Fix merged, docs will be updated with next release
