### ISSUE TITLE
Daterangepicker doesn't handle manually entered date if format contains minus sign, eg YYYY-MM-DD

### ISSUE THREAD

**Issue by andersb** [valor-software/ng2-bootstrap#6293]
**Bug description:**

Daterangepicker doesn't handle manually entered date if format contains minus sign  , eg YYYY-MM-DD

Goto
https://valor-software.com/ngx-bootstrap/#/datepicker#locales

Change locale to Swedish, sv 
Select a date in the daterangepicker, then modify the date manually and leave the input field.
The date will be swapped to something like 2001-01-01.
It will work if the locale is English, en, and the format is MM/DD/YYYY

This used to work in 6.2.0 but something have changed in 7.x.x.

If you subscribe to bsValueChange, you will see around 5-6 values being emitted when manually entered but there should be only two.

**Versions of ngx-bootstrap, Angular, and Bootstrap:**

ngx-bootstrap: 7.1.1

Angular: 11

Bootstrap: 4

**Expected behavior**

Entering a date manually should work even if the format uses minus signs

**Comment by daniloff200** [comment]
Thanks for reporting that one!
That happened because of https://github.com/valor-software/ngx-bootstrap/pull/6014

It worked fine, but, for Swedish and Netherlands locales there's an issue, because of multiple `-` in an input!
I have a fix for that

**Comment by andersb** [comment]
Thank you @daniloff200 for coming up with a solution. I hope it will find itself into 7.1.2 shortly :)
