### ISSUE TITLE
Position issue if two same components(datepicker and tooltip are used )

### ISSUE THREAD

**Issue by sr-26** [valor-software/ng2-bootstrap#6296]
If the multidaterangepicker is opened in my dom and if i move the cursor to an element which have tooltip property binded.The transform property changes making the datepicker to fluctuate to the right side.Is this the bug if two components are used since both of them are having the top class?

Versions of ngx-bootstrap, Angular:

ngx-bootstrap: 6..2.0

Angular: 11.1

**Comment by SvetlanaMuravlova** [comment]
@Sachinrana99 , hi) thank you for your issue, we can't reproduce your it, can you, please,  try to reproduce it on stackblitz with the last version of library ?

![Untitled](https://user-images.githubusercontent.com/83700465/165898965-cae6b306-b1b4-484c-8c48-4432ebc660ca.png)

if you will be able to do it, let us know again)
