### ISSUE TITLE
Dropdown stopOnClickPropagation property cannot be applied properly

### ISSUE THREAD

**Issue by Divanhost** [valor-software/ng2-bootstrap#6304]
**Bug description:**
After updating from 7.1.0 to 7.1.1 i can't use stopOnClickPropogation feature of dropdown  because property is not provided by
BsDropdownDirective (But it's presented in BsDropDownConfig). Also, could you change spelling to Prop**A**gation? :)

We can use **stopOnClickPropogation="true"** in directive but we can't do  **[stopOnClickPropogation]="true"**

Versions of ngx-bootstrap, Angular, and Bootstrap:

**ngx-bootstrap**: 7.1.1

**Angular**: 12.2.5

**Bootstrap**: 3.4.1

Pls fix it, Thanks)

**Comment by SvetlanaMuravlova** [comment]
@Divanhost hi)

**Comment by SvetlanaMuravlova** [comment]
@Divanhost hi)
stopOnClickPropogation should be used as dropdown config
so try to use such property in your component in this way
 providers: [{ provide: BsDropdownConfig, useValue: { stopOnClickPropogation: true} }]

as example you can use https://valor-software.com/ngx-bootstrap/#/dropdowns#animated

thank you for using our library)

**Comment by apotapcukv** [comment]
Hi, Divanhost! We haven’t heard from you in a while, so we suppose that the issue in question is resolved and are closing it. Please don’t hesitate to let us know if you face further issues. Thank you for using our library).
