### ISSUE TITLE
https://valor-software.com/ngx-bootstrap is not working

### ISSUE THREAD

**Issue by anilkumarb123** [valor-software/ng2-bootstrap#6310]
Dear Valor software team,

I keep getting the error 182.79.218.34 unexpectedly closed the connection when I try to open valor-software website. Kindly look into this issue.

Best Regards,
Anil Kumar B

**Comment by valorkin** [comment]
we know that some providers in India is blocking us, please write to your provider request to unblock in
and cc me at my working email dmitriy.shekhovtsov@valor-software.com
