### ISSUE TITLE
The ngx-bootstrap document site stopped working since a month

### ISSUE THREAD

**Issue by mukuljai** [valor-software/ng2-bootstrap#6320]
Documentation of ngx-bootsrap not opening since month https://valor-software.com/ngx-bootstrap/ 

Bug description:

Try opening https://valor-software.com/ngx-bootstrap/  and after a while site says as below.
![image](https://user-images.githubusercontent.com/51748155/136142300-4b12b357-ea56-4dc8-a195-5bf97bbdd5b7.png)
or
Kept showing Loading...
Pls look into it with priority or provide alternative since folks @ slack too reported it.

**Comment by daniloff200** [comment]
hi, @mukuljai 
I assume, you're from India? 

We have some issues with providers from India, more info here -> https://github.com/valor-software/ngx-bootstrap/issues/6310
