### ISSUE TITLE
Update library for angular 13

### ISSUE THREAD

**Issue by SvetlanaMuravlova** [valor-software/ng2-bootstrap#6330]
Update library for angular 13, library should be with enable Ivy mode

-------
update by @valorkin it will be released as soon as nx 13.3 will be released
https://github.com/nrwl/nx/releases

PR for it is here https://github.com/valor-software/ngx-bootstrap/pull/6364

**Comment by AmirSavand** [comment]
+1

**Comment by cosminatomei** [comment]
+1

**Comment by Darrow8** [comment]
+1

**Comment by Darrow8** [comment]
Has this happened yet? I keep getting the error `An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
See "/private/var/folders/n0/3hy73lxs3xs_fv3ms7fp0s7h0000gs/T/ng-0hqxdN/angular-errors.log" for further details.`

**Comment by SvetlanaMuravlova** [comment]
ngx-bootstrap library isn't updated for angular 13, pr is prehearing for it)

**Comment by shendbajgora** [comment]
@SvetlanaMuravlova 

I'm using angular 13 for a project, and I really need ngx-bootstrap to support angular-13.
I was wondering when will the library support angular 13?

**Comment by FrancescoBorzi** [comment]
@SvetlanaMuravlova hey, are there any news about this?

**Comment by LoveDuckie** [comment]
> @SvetlanaMuravlova hey, are there any news about this?

@FrancescoBorzi it seems like there is a PR for this in-flight, but it appears to be failing some e2e tests.

**Comment by LoveDuckie** [comment]
I would also love for this library to be upgraded to Angular 13. :)

**Comment by AmirSavand** [comment]
Please make this happen ❤️

Do we have any date for completion?

**Comment by shendbajgora** [comment]
Guys I had no other options, had to move into ng-bootstrap.
They already pushed RC for Bootstrap 4 and Beta version for bootstrap 5.

Good luck!

**Comment by FrancescoBorzi** [comment]
> Guys I had no other options, had to move into ng-bootstrap. They already pushed RC for Bootstrap 4 and Beta version for bootstrap 5.
> 
> Good luck!

@valorkin @SvetlanaMuravlova can we do something about this? we are losing users this way...

**Comment by valorkin** [comment]
@FrancescoBorzi we have bs5 for a while actually, since 7.1 :\
https://valor-software.com/ngx-bootstrap/#/documentation
click on bs5 in themes switcher

**Comment by valorkin** [comment]
our plans to migrate to angular 13 quickly failed cuz we depend on nx
and nx doesn't yet properly support ng 13 build

**Comment by sugihartolim** [comment]
I'm confused by the status of this issue. Does the last message by @valorkin above mean we shouldn't expect Angular13 support anytime soon (since the holidays are coming etc) ? Is there a published roadmap somewhere? Thanks. 

For context, nx claimed to support Angular13 in 13.2.0, which was released 2-3 weeks ago. As of today they're on 13.3.0-beta.4.  The issue opened by @SvetlanaMuravlova in the nx repo was closed.  (e.g. https://github.com/nrwl/nx/issues/7549)

**Comment by valorkin** [comment]
@sugihartolim if version mentioned by me will not be released next we, we will hack around, I want to cut v8 to unblock us

**Comment by codingisacopingstrategy** [comment]
Thanks for the updates and the swell library. Looks like we got nx 13.3.0 and 13.3.1 this weekend! https://github.com/nrwl/nx/releases

**Comment by innoveltec** [comment]
Hello, I upgraded my nx framework to the latest today which is 13.3.4. It has proper angular 13 support. Any timing when ngx bootstrap will be compatible with angular v13 since i was also using ngx bootstrap inside my nx repo and my npm install is now failing because ngx bootstrap 7.1 does not support angular v13.

**Comment by valorkin** [comment]
let's see ;)
https://github.com/valor-software/ngx-bootstrap/actions/runs/1588374797

**Comment by LoveDuckie** [comment]
Still seems to be failing on the publish step. Do you have to do this instead?

**Comment by valorkin** [comment]
had to change a build folder structure, with v13 it gone sideways a lot
https://github.com/valor-software/ngx-bootstrap/actions/runs/1602452196
works good locally

**Comment by samkbit** [comment]
any updates on ngx-bootstrap support for ng 13?

**Comment by valorkin** [comment]
Released a week or 2 ago

**Comment by codingisacopingstrategy** [comment]
Can confirm it works fine for me now, thanks !
(The one change I had to make on my end, is to manually specify my bootstrap version, as explained in the docs, whereas before it recognised my Bootstrap 3 automatically. Better to be explicit anyways.)

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by AmirSavand** [comment]
Works for my projects as well. All good. Thanks, ngx-bootstrap!

**Comment by valorkin** [comment]
@codingisacopingstrategy had to drop automatic check of bs3, now it checks only v4 and v5
