### ISSUE TITLE
Invalid date locks withTimepicker control until manually reset with null

### ISSUE THREAD

**Issue by SarahKeigTelent** [valor-software/ng2-bootstrap#6336]
Bug description:  If you enter an invalid date into the picker OR if you select a valid date and then manually delete it, you are then unable to select a date from the calendar.

**First Repro Steps:**
1. Type in an invalid date to the picker (i.e. just type a string like 'test')
2. Attempt to select a date from the calendar

Observe that the date will not be selected

**Second Repro Steps:**
1. Select a valid date from the calendar in the picker
2. Click into the date field and press backspace to clear date and time out
3. Attempt to select another date from the calendar

Observe that the date will not be selected

Plunker/StackBlitz that reproduces the issue:

Plunker outdated and StackBlitz not able to install ngx-bootstrap version required - 7.1.2 (only 7.1.1 available)

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 7.1.2

Angular: 11.2.14

Bootstrap: 4.3.1

Build system: Angular CLI, System.js, webpack, starter seed: Angular CLI

**Expected behavior**
Picker should be interactable even if user manually deletes the date/time or inputs an incorrect format date

**Comment by SvetlanaMuravlova** [comment]
@SarahKeigTelent , it seems issue is fixed
if you are still available to reproduce this issue in the last version, let us know, please)
