### ISSUE TITLE
When is the latest version going to published to npm?

### ISSUE THREAD

**Issue by devin5885** [valor-software/ng2-bootstrap#6337]
When is the latest version going to published to npm?

The version on npm is still 7.1.0.

**Comment by daniloff200** [comment]
Hi. @devin5885

![Selection_007](https://user-images.githubusercontent.com/13692220/139449398-824d92b0-7c33-4f67-ad3f-aae83d68b271.png)
version 7.1.1 and 7.1.2 are alvo available, 7.1.2 with next tag

**Comment by devin5885** [comment]
Why are .7.1.1 and 7.1.2 marked as next instead of latest?
