### ISSUE TITLE
Animated accordion & content height change

### ISSUE THREAD

**Issue by adros** [valor-software/ng2-bootstrap#6354]
(probably related to #5202, which claims to be fixed)

When content of an accordion with animation changes, the high does not adapt.

Can be easily demonstrated on https://valor-software.com/ngx-bootstrap/#/accordion#dynamic-body. When I change the content in dev tools inspector, the result is broken.

![image](https://user-images.githubusercontent.com/914548/140311731-5c98c3d3-72a1-4307-818b-694012a2ca78.png)

**Comment by valorkin** [comment]
@adros no idea, just tried, works as expected
tested in chrome
closing as not reproducible

check this https://stackblitz.com/edit/angular-7byvyx?file=app%2Fanimated.html

**Comment by SvetlanaMuravlova** [comment]
@adros , may be you can try some of these ways to resolve your issue?
https://stackblitz.com/edit/angular-7byvyx?file=app%2Fanimated.html

**Comment by adros** [comment]
I have sample where yo can see the issue.

https://stackblitz.com/edit/angular-7byvyx-xfswze?file=app/wrapper.component.ts

It is must be related to change detection and ng-content, cause it only appears with OnPush strategy which I use (of course it has no sense in this simplified sample)
