### ISSUE TITLE
ngx changes main page view 

### ISSUE THREAD

**Issue by nagkumar** [valor-software/ng2-bootstrap#6363]
The original view, which is not using any of ngx looks like this..

![image](https://user-images.githubusercontent.com/332234/141111065-4b70d4f0-6881-43d3-acaf-7c4dc72229bc.png)

However, once I open a dialog, that uses ngx, the background view changes 

![image](https://user-images.githubusercontent.com/332234/141111204-55c7ce32-82fa-40a6-ae6d-091958e26666.png)

Once the dialog is closed, again the main view table changes to normal. Can any share why the style of the main page changes when I use ngx dialog.

Object the gap between Price and Tax columns, it has increased a lot in 2nd image

**Comment by valorkin** [comment]
`modal-open` class on body element

**Comment by nagkumar** [comment]
valorkin, can you pl. explain further how t fix this..do we need to fix the CSS? if yes how.. if it is a framework issue, would this fixed the latest version?

**Comment by valorkin** [comment]
I would not call this an issue, but you can check that ngx is simply following a behavior of original components
https://getbootstrap.com/docs/5.1/components/modal/

**Comment by valorkin** [comment]
could be something else ofc, you should check which css classes are affecting your elements
