### ISSUE TITLE
ngx-bootstrap angular 13 needs to be made

### ISSUE THREAD

**Issue by JDL1995** [valor-software/ng2-bootstrap#6365]
I want to use ngx-bootstrap in my projects and I also want to use angular 13.

I'm sure I'm not alone in this.

here are the codes I receive when installing it with angular cli 13.

please let me know if there's anything I can do to help create additions to bring this package to compatibility with angular 13.
email: Jonatollah@gmai.com

**Description:**
jonathanlathrop@Jonathans-Mac-mini components % npm install --save ngx-bootstrap
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: compute-smooth@0.0.0
npm ERR! Found: @angular/animations@13.0.1
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"~13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"^11.0.0 || ^12.0.0" from ngx-bootstrap@7.1.0
npm ERR! node_modules/ngx-bootstrap
npm ERR!   ngx-bootstrap@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/jonathanlathrop/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonathanlathrop/.npm/_logs/2021-11-11T16_08_18_192Z-debug.log
jonathanlathrop@Jonathans-Mac-mini components % npm install @ngx/bootstrap
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@ngx%2fbootstrap - Not found
npm ERR! 404 
npm ERR! 404  '@ngx/bootstrap@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonathanlathrop/.npm/_logs/2021-11-11T16_08_38_449Z-debug.log
jonathanlathrop@Jonathans-Mac-mini components % npm install --save ngx-bootstrap
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: compute-smooth@0.0.0
npm ERR! Found: @angular/animations@13.0.1
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"~13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"^11.0.0 || ^12.0.0" from ngx-bootstrap@7.1.0
npm ERR! node_modules/ngx-bootstrap
npm ERR!   ngx-bootstrap@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/jonathanlathrop/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonathanlathrop/.npm/_logs/2021-11-11T16_09_14_608Z-debug.log
jonathanlathrop@Jonathans-Mac-mini components % npm install devecxtreme-angular
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/devecxtreme-angular - Not found
npm ERR! 404 
npm ERR! 404  'devecxtreme-angular@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonathanlathrop/.npm/_logs/2021-11-11T16_10_09_335Z-debug.log
jonathanlathrop@Jonathans-Mac-mini components % npm install --save ngx-bootstrapng add ngx-bootstrap
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: compute-smooth@0.0.0
npm ERR! Found: @angular/animations@13.0.1
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"~13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"^11.0.0 || ^12.0.0" from ngx-bootstrap@7.1.0
npm ERR! node_modules/ngx-bootstrap
npm ERR!   ngx-bootstrap@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/jonathanlathrop/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonathanlathrop/.npm/_logs/2021-11-11T16_14_26_468Z-debug.log
jonathanlathrop@Jonathans-Mac-mini components % npm install --save ngx-bootstrapng add ngx-bootstrap --legacy-peer-deps
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/ngx-bootstrapng - Not found
npm ERR! 404 
npm ERR! 404  'ngx-bootstrapng@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by dafranklin** [comment]
Same problem with 7.1.2.

**Comment by TheBoyCC** [comment]
The workaround will be to downgrade the angular version to 12

**Comment by JDL1995** [comment]
Any idea when it will be updated? I want to work in angular 13. I offer to volunteer to work on developing for angular 13 compatability.

-Jonathan Lathrop
B.S CIS U of H, Frontend-backend javascript engineer

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by air2** [comment]
#6358 A future version according to this ticket. Not very clear. Would hope on some more detailed time-path

**Comment by air2** [comment]
Follow #6330 for more info I guess.

**Comment by pkcinna01** [comment]
We also need clarity about long-term plans and expected delay for new release after a major version of Angular is released.   Angular material UI releases are in step with release dates of Angular.   Also,  the ngx-bootstrap compatibility table at https://www.npmjs.com/package/ngx-bootstrap has not been updated in a while.  Maybe that should just be a link to github readme so same info is not maintained in two spots.

**Comment by LoveDuckie** [comment]
@pkcinna01 is this project being deprecated?! That's the first I've heard.

**Comment by pkcinna01** [comment]
Sorry.  I could have worded that better.  The ask is just more clarity on how long it takes to get a new release after a new angular release.  It would also be nice to get an idea of commitments and plans from the volunteers working on ngx-bootstrap.  We are using it on a large project and crucial dependencies like rxdb cannot be upgraded until we use Angular 13.  Without clarity about project outlook we will most likely have to rework entire app.

**Comment by LoveDuckie** [comment]
@pkcinna01 I share your frustration. I'm waiting for Angular 13 support as well, but I'm in half the mind to roll my sleeves up and give it a go at upgrading the project source myself.

**Comment by pkcinna01** [comment]
That sounds like best approach (instead of removing dependency from large project).  Please give an update if there is a working fork of this project.   I will do the same if I have time and no one has got it working by then.

**Comment by lerich** [comment]
Hi guys. Is there any news?

**Comment by marioproietti1995** [comment]
Are there alternatives to ngx-bootstrap, for Angular 13?

**Comment by LoveDuckie** [comment]
> Are there alternatives to ngx-bootstrap, for Angular 13?

There's ng-bootstrap, but their release for Angular 13 is in BETA, I think. @marioproietti1995

**Comment by marioproietti1995** [comment]
> BETA

Oh yeah I figured it yet, and I'm going to use this.

Thanks for your reply

**Comment by pkcinna01** [comment]
Looks like v8 is almost there based on git activity.  Not sure if there is a list of pros/cons to using ngx-bootstrap but in hindsight I would have used pure bootstrap without a dependency.

**Comment by valorkin** [comment]
v8 released as `next` version on npm

**Comment by valorkin** [comment]
testing/polishing in real apps and will move to latest

**Comment by amanyzohair** [comment]
try `ng add ngx-bootstrap@8.0.0` Or `npm install ngx-bootstrap@@8.0.0 --legacy-peer-deps`
