### ISSUE TITLE
https://valor-software.com/ngx-bootstrap is down

### ISSUE THREAD

**Issue by adnan333bd** [valor-software/ng2-bootstrap#6367]
**Description:**
Cant read the doc for ngx bootstrap in google chrome

**Comment by eswarvijji** [comment]
Getting error 
The website has been blocked as per order of Ministry of Electronics and Information Technology under IT Act, 2000.

**Comment by valorkin** [comment]
if you know where to write a message to unblock this, please welcome to comments in #6377 6377
