### ISSUE TITLE
Doc site https://valor-software.com/ngx-bootstrap issue

### ISSUE THREAD

**Issue by vinothvkr** [valor-software/ng2-bootstrap#6379]
Documentation website  valor-software.com/ngx-bootstrap either not accessible or navigation is not working.

**Comment by Itrulia** [comment]
Works fine for me.

**Comment by madhukudala** [comment]
![image](https://user-images.githubusercontent.com/7322186/147234477-fd673e6f-ec9a-4460-87d4-e901bcd3999e.png)

Unable to access the documentation!

**Comment by valorkin** [comment]
sry folks, was updating design and build\pipe process for nx13
resolved now
