### ISSUE TITLE
Dropdown is not closing

### ISSUE THREAD

**Issue by elementalTIMING** [valor-software/ng2-bootstrap#6385]
The Dropdown menu is not closing when having multiple dropdown elements in a component and clicking between them.
Explain it in a different way: 

Component with 3 elements:
	Dropdown #1
	Dropdown #2
	Element

Scenario 1 (works well):
Clicking on "Dropdown #1" opens the menu. 
Clicking on "Element" closes the "Dropdown #1" menu

Scenario 2 (buggy):
Clicking on "Dropdown #1" opens the menu. 
Clicking on "Dropdown #2" opens the menu but the "Dropdown #1" menu is not closing

Simplified used code:

	<div class="input-group-append" dropdown>
		<button class="btn dropdown-toggle btn-outline-secondary dropdown-toggle" dropdownToggle>
			Dropdown Title
		</button>
		<div class="dropdown-filter-menu dropdown-menu dropdown-menu-right text-info" *dropdownMenu>
			...
		</div>
	</div>

Thx for a fix or an advice how to make it to work properly.
regards,
Lars

**Comment by asjamsuri** [comment]
Have you tried to update the latest version? (7.1.2)

I think I got a similar issue before.

> Scenario 2 (buggy):
Clicking on "Dropdown #1" opens the menu.
Clicking on "Dropdown #2" opens the menu but the "Dropdown #1" menu is not closing

And upgrading the `ngx-bootstrap` to 7.1.2 solved it.

Hope it helps.

**Comment by elementalTIMING** [comment]
> Hope it helps.

@asjamsuri oh yes that helped. Strange because v7.1.2 is not shown when I was checking for updates with `npm outdated`. I had to install it manually. But now it works, like a charm. Thx a lot!

**Comment by valorkin** [comment]
@asjamsuri thanks a lot
