### ISSUE TITLE
adaptivePosition not working

### ISSUE THREAD

**Issue by LHattingh** [valor-software/ng2-bootstrap#6386]
From version 7, when apativePosition=true, the datepicker appears to the right and left of the input box, instead of the top.

It is still okay in version 6.2.0.  

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 7.0.0

Angular: 12

Bootstrap: 4

**Comment by LHattingh** [comment]
It seems the problem is with this code in the function computeAutoPlacement:

```
const rects = {
        top: {
            width: (_a = boundaries.width) !== null && _a !== void 0 ? _a : 0,
            height: refRect.top && boundaries.top ? refRect.top - boundaries.top : 0
        },
        right: {
            width: boundaries.right && refRect.right ? boundaries.right - refRect.right : 0,
            height: (_b = boundaries.height) !== null && _b !== void 0 ? _b : 0
        },
        bottom: {
            width: (_c = boundaries.width) !== null && _c !== void 0 ? _c : 0,
            height: boundaries.bottom && refRect.bottom ? boundaries.bottom - refRect.bottom : 0
        },
        left: {
            width: refRect.left && boundaries.left ? refRect.left - boundaries.left : 0,
            height: (_d = boundaries.height) !== null && _d !== void 0 ? _d : 0
        }
    };
```

For instance, boundaries.top is zero, and therefore top.height = 0, which will result in the datepicker never having a placement  top

**Comment by valorkin** [comment]
was fixed in v8+, checked with bs4 and bootstrap 5
please check https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview

**Comment by valorkin** [comment]
https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview#adaptive-position
