### ISSUE TITLE
Datepicker not working on documentation page

### ISSUE THREAD

**Issue by mayhew3** [valor-software/ng2-bootstrap#6390]
Bug description: I'm trying to play around with Datepicker on the documentation page: https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview

I'm finding that the datepicker appears when clicking into the "Basic" fields only, and I don't see the popup for any of the other examples, including those where the trigger is a button. I've tried this on the latest Firefox and Chrome, on multiple computers. Am I the only one seeing this?

Plunker/StackBlitz that reproduces the issue: N/A, issue present on existing page.

**Expected behavior**

I expected a little calendar popup when clicking into the datepicker fields, and nothing happened.

**Comment by valorkin** [comment]
it's related to new design, already fixed, should be deployed today

**Comment by valorkin** [comment]
https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview

**Comment by mayhew3** [comment]
Confirmed! Thanks.
