### ISSUE TITLE
bsDatePicker changes the date value that was used to reset its value

### ISSUE THREAD

**Issue by amiram** [valor-software/ng2-bootstrap#6399]
Bug description:
When using bsDatePicker in reactive form, the date picker is changing the date variable that was used to reset the form. I've created a sample here https://stackblitz.com/edit/ngx-bootstrap-spjuat?file=app/app.component.html
You can see that once you use a date to reset the date picker, it is changing the time to the current time, and although the same date is used to reset the following time picker, the time picker is showing the current time, as was altered by the date picker.
Workaround: set the form field value to `new Date(originalValue)` which clones the date object. You can see it works in the second part of the form.
Another example with antd without this issue https://stackblitz.com/edit/angular-zygzuc?file=src/app/app.component.ts

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:
7.1.2
Angular:
12
Bootstrap:
4.5
Build system: Angular CLI, System.js, webpack, starter seed:
Angular cli

**Expected behavior**
A date object used to reset a reactive form field shouldn't be changed.

**Comment by MartinGodzina** [comment]
This seems to be fixed since version 8.0.0. At least i could not reproduce this behavior based on the previous stackblitz. https://stackblitz.com/edit/ngx-bootstrap-lbcq2o?file=app%2Fapp.component.html

**Comment by amiram** [comment]
@MartinGodzina Yes you are right. It looks like it is fixed in 8.0.0.
Thanks!
