### ISSUE TITLE
Dropdown not closing automatically if clicked in another dropdown of ngx-bootstrap

### ISSUE THREAD

**Issue by somuda86** [valor-software/ng2-bootstrap#6400]
Its working in 7.0.0-rc1 and not working in 7.0.0-rc2. I am using Angular 12. I see no documentation mentioning the change

**Comment by SvetlanaMuravlova** [comment]
@somuda86 , hi) try version 7.0.0  this behavior should be default in this version, but if you prefer to switch off it - use config 'stopOnClickPropagation' for it

**Comment by somuda86** [comment]
7.1.1 Also have the problem, >=7.1.2 doesnt have that problem.

**Comment by SvetlanaMuravlova** [comment]
@somuda86 , so use, please newer versions, where it is fixed))

**Comment by somuda86** [comment]
I know its fixed, but I guess docs are a little misleading when it was fixed thats all. You can close the issue.

**Comment by SvetlanaMuravlova** [comment]
@somuda86 , i got your point, so i set it as enhancement)
