### ISSUE TITLE
latest version still gives me compatibilty errors with angular 13

### ISSUE THREAD

**Issue by jonnytest1** [valor-software/ng2-bootstrap#6404]
Before opening an issue, please search for duplicates (opened and closed) https://github.com/valor-software/ngx-bootstrap/issues There's no need to open an issue here if you want to ask general question, use StackOverflow or Slack instead

Bug description:

on `npm install` with @angular library versioned at 13.1.1 i get the following error 

Found: @angular/forms@13.1.1
npm WARN node_modules/@angular/forms
npm WARN   @angular/forms@"^13.1.1" from the root project
npm WARN   1 more (@ng-bootstrap/ng-bootstrap)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer **@angular/forms@"^11.0.0 || ^12.0.0" from ngx-bootstrap@7.1.2**
npm WARN node_modules/ngx-bootstrap
npm WARN   ngx-bootstrap@"^7.1.2" from the root project

@angular/forms@"^11.0.0 || ^12.0.0" from ngx-bootstrap@7.1.2
i think there are some version flags not set correctly

**Comment by SvetlanaMuravlova** [comment]
@jonnytest1 Am i right, are you trying to use version ^7.1.2 of ngx-bootstrap with angular 13?

**Comment by jonnytest1** [comment]
yes
it seems to be the latest version on npm

**Comment by air2** [comment]
7.1.2 is NOT compatible with angular 13, 8.x will be compatible, but is still a release candidate. Please check that version to see it it works for u.

**Comment by SvetlanaMuravlova** [comment]
@jonnytest1 , yeah it is, but it isn't compatible with angular 13, you can see it there https://valor-software.com/ngx-bootstrap/#/documentation#compatibility 
For angular 13 you can use our next version on npm, or you can wait for release of 8 version)
