### ISSUE TITLE
Error in the datepicker week numbers

### ISSUE THREAD

**Issue by Sheylune** [valor-software/ng2-bootstrap#6410]
Hello everyone, I think the problem in 2021 about the weeknumbers wrong display still remain at 2022. In the stackblitz you will see the datepicker, but when you go to the 1st of January it is bound to week number 1 and the 2nd January is bound to week number 2 of 2022 but they are both week number 52 of 2021!!!

the stackblitz : https://stackblitz.com/edit/ngx-bootstrap-datepicker

I'm actually working on an angular project (angular 11 and ngx-bootstrap 6.2.0)

Happy new year all !

**Comment by valorkin** [comment]
this stackblitz uses ngx-bootstrap 1.9.3
which was released years ago
