### ISSUE TITLE
Slackblitz examples are missing 'zone.j' package (needs to be js)

### ISSUE THREAD

**Issue by Serdarrr** [valor-software/ng2-bootstrap#6430]
Hi,

**First issue:**
I tried a few Stackblitz examples, but I keep getting the message "Can't find package: **zone.j**"

Example: https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview#min-mode

**Fix for first issue:**
Incorrect path to file import: zone.j . Replace **.j** with **.js** in file _polyfills.ts_

**Second issue:**
Also for some reason (after the fix applied) its stuck on 'Loading ngx-bootstrap...', no datepicker is shown.

**Fix for second issue:**
I had to downgrade dependency @angular/animations from **13.2.2** to **12.1.0** in file _package.json_

**Comment by Serdarrr** [comment]
Solved issues myself, but you have to fix on your website.

**Comment by kovtib** [comment]
How on earth they can leave a bug like this in their stackblitz for more than a half year?
Thx @Serdarrr for the fixing steps.
