### ISSUE TITLE
An unhandled exception occurred: ENOENT: no such file or directory, lstat 'C:\[YOUR_PATH]\dist'

### ISSUE THREAD

**Issue by vctdiniz** [valor-software/ng2-bootstrap#6444]
**Bug description:**

> After run the command `ng add ngx-bootstrap` on Angular CLI the error ocurred when start the server `npm start` or `ng serve`.

**Versions of ngx-bootstrap, Angular, and Bootstrap:**

> - ngx-bootstrap: 8.0.0
> - Angular: 13.2.0
> - Bootstrap: 5.1.3

**Expected behavior**

> After analyzing the error, i noticed that in file `angular.json` was added an incorrect path `./dist/...` . 
> Maybe the procedure of "ng add ngx-bootstrap" added it automatically. 

> ```
> "styles": [
>    "./dist/ngx-bootstrap/datepicker/bs-datepicker.css",
>    ...
> ]
> ```

> The problem was solved just by renaming the path:
`./dist/ngx-bootstrap/datepicker/bs-datepicker.css`  to `./node_modules/ngx-bootstrap/datepicker/bs-datepicker.css`

**Comment by italoant** [comment]
thank u so much <333333

**Comment by AF2B** [comment]
Thank you so much!

**Comment by tinlevn** [comment]
Wow this works! Thank you so much, that's a tricky bug to catch

**Comment by panyann** [comment]
Thank you. It should be in the documentation...

**Comment by Alsammoue** [comment]
Thank you so much .. . . . . . . so much

**Comment by omidrah** [comment]
save my time. thank u
