### ISSUE TITLE
The tooltip position is sometimes incorrect and only correct itself once the user hovers over the tooltip

### ISSUE THREAD

**Issue by KthProg** [valor-software/ng2-bootstrap#6458]
This will probably be very hard to reproduce and I'll do my best to add to this issue over time, but we have a bunch of buttons inside a scrolling container. The elements inside the scrolling container change based on a toggle. Initially, the tooltips show in the correct place (on focus of the buttons). When we toggle to show the other elements, the first tooltip is rendered incorrectly (above where it should be) and only updates after a user hovers over it. This happens regardless of whether the adaptive positioning is on or not. The tooltip is using a template and the boundaries element is set to viewport.

**Comment by SvetlanaMuravlova** [comment]
@KthProg hi) thank you for your issue, but can you share with version of ngx-bootstrap in your project?
does your issue connect with such issue #5992 ?

**Comment by SvetlanaMuravlova** [comment]
@KthProg check fix issue in #5992 , please
if it doesn't resolve your problem, let us know)
