### ISSUE TITLE
How do I edit variables in datepicker's css themes?

### ISSUE THREAD

**Issue by GitHubish** [valor-software/ng2-bootstrap#6461]
I can't figure out how to modify the variables defined in `@import 'utils/scss/variables';` to have the datepicker word theme customized to my application color. And I can't find anything about this possibility in the documentation. 

I tried to import in my `styles.scss` my variable file in which I redefine for example `$theme-green` or even `$theme-list` and then import the `~ngx-bootstrap/datepicker/bs-datepicker.scss` file but it does not work.

How do I do it?
Thanks

**Comment by Ilkhom-S** [comment]
If you import styles.css from package. You can redefine colors and much more. After you need include your css not package. All should work
