### ISSUE TITLE
Error with css in datapicker angular13 webpack 5

### ISSUE THREAD

**Issue by wrss2** [valor-software/ng2-bootstrap#6462]
I have  problem with datapicker 

Package path ./datepicker/bs-datepicker.css is not exported from package

**Comment by SvetlanaMuravlova** [comment]
@wrss2, hi)
 did you use schematic command to install library?

**Comment by SvetlanaMuravlova** [comment]
@wrss2 , you could get it because of schematics command, it will be fixed in version 10, it will be soon, so can you instal lib with npm command, please
