### ISSUE TITLE
datepicker issue when using with option of 'withTimepicker: true', time selection not working

### ISSUE THREAD

**Issue by BehnamAbdy** [valor-software/ng2-bootstrap#6469]
even in the official sample the selected time is not selected after selecting the date, and always it returns the current time
u can try it at live
https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview#with-timepicker

**Comment by ismcagdas** [comment]
@ErikYu do you have any comments about this ? Is there a workaround which we can apply ? Thanks in advance.

**Comment by Gillardo** [comment]
Any fix for this?? Experiencing the same issue

**Comment by Gillardo** [comment]
Updated to latest version, seems to work, only problem is that the datepicker/timepicker closes everytime you use the time selectors

**Comment by lautaro826** [comment]
Which version fixes this problem? My current version is 7.2.1 and I have the problem mentioned

**Comment by Gillardo** [comment]
> Which version fixes this problem? My current version is 7.2.1 and I have the problem mentioned

i am using version 9.0.0 and it works, but time picker bug (closing everytime you click) happens

**Comment by lautaro826** [comment]
> 

Thank you. @Gillardo.

**Comment by h1nson** [comment]
how to solve this bug, closing everytime when i click it.

**Comment by SvetlanaMuravlova** [comment]
https://github.com/valor-software/ngx-bootstrap/issues/6433#issuecomment-1331706005

**Comment by SvetlanaMuravlova** [comment]
#6433
