### ISSUE TITLE
Datepicker weird behavior when isDisabled is true.

### ISSUE THREAD

**Issue by Salketer** [valor-software/ng2-bootstrap#6471]
Reproducible directly in the doc: https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview#disabled-datepicker

The datepicker, when enabled looks like this:
![image](https://user-images.githubusercontent.com/11193702/172824340-1a7aa9a2-00d1-49ad-973d-5806a0f9e2b9.png)

When isDisabled is set to true, the arrows to change month are hidden:
![image](https://user-images.githubusercontent.com/11193702/172824514-53901a0c-87f5-4ce3-801d-75e6680c1514.png)

Furthermore, if we click on the year or month labels we are brought to a selection of year or month respectively, but the selection is also disabled, so we are stuck there.

This is not so bad in the datepicker, but as soon as you display a range that spans more than 1 month, the user will not be able to see where exactly the range ends:
![image](https://user-images.githubusercontent.com/11193702/172825033-73d9f38c-fc82-47bd-a90c-8c5dfca75177.png)

I expected isDisabled to either not allow navigation at all by graying out the year/month labels also. But thinking about it, the range problem would still exist. So I suggest that isDisable prevents any new user input but keeps allowing all the calendar interactions.

Either way, I think that both options are needed and in any case the current state should be considered flawed.

**Comment by PhanindraNath** [comment]
I couldn't understand why the read-only attribute is being removed from datepicker, when added by the developer. Please help me understand this PR. 

In my project, we use the read-only attribute to suppress users from inputting random text into the date field, particularly to **suppress browser autocomplete suggestions**. Now after this PR version, the read-only attribute is being removed.

**Comment by Salketer** [comment]
Looking at the changes, it does not really remove it. It's just that it is
now linked to the disabled attribute. Which is pretty much the same feature
wise. Could you please try to switch to disabled and see if it is ok for
your use case?

**Comment by PhanindraNath** [comment]
I tried with disabled, but it's not working. Shockingly, if I remove the 'read-only" attribute, the date picker input element is not rendering at all. I could not find the reason yet. I will try to share an example of the issue.
