### ISSUE TITLE
Angular v14 support

### ISSUE THREAD

**Issue by dabbabi** [valor-software/ng2-bootstrap#6473]
Hi, when you'll add support for Angular v14, please?

**Comment by merabchik** [comment]
Waiting also

**Comment by mgafur** [comment]
still waiting support ngx v14, but may be is long for this release.
we try install with add flag --force is successfull and use some component also running normally. 
"npm install ngx-bootstrap --save --force"

**Comment by merabchik** [comment]
> still waiting support ngx v14, but may be is long for this release.
> we try install with add flag --force is successfull and use some component also running normally. 
> "npm install ngx-bootstrap --save --force"

It's not recommended

**Comment by mgafur** [comment]
it's not recomended but it's way to use ngx component for this moment. in ngx we only need modal component.
while waiting release official.

**Comment by dabbabi** [comment]
how to raise up this point, please? It seems there's no one following our requests from project team :(

**Comment by sterjoski** [comment]
For anyone wondering PR #6477 by @SvetlanaMuravlova is waiting for a review.

**Comment by maro1993** [comment]
With the core team currently residing in eastern Ukraine i want to raise the question if this repo gets maintained in the near future? Last release was in january before the war started. Does anyone have information?

**Comment by dionatan-g** [comment]
There isnt a single person outside Ukraine to review pull requests?

**Comment by maro1993** [comment]
I hope to not spread confusion. As we can see there are several closed PR's in the last 30 days. I assume things just go slower than usual.

**Comment by lagranjadigital** [comment]
Any new?

**Comment by dionatan-g** [comment]
Up!!!!

**Comment by valorkin** [comment]
9.0.0-RC.2 is on npm
available as https://github.com/next version
this week testing, if nothing critical related to ng14 - releasing as @latest on Friday
mention me if you will find anything

**Comment by fatmamasmoudy** [comment]
https://github.com/danidelgadoz/ngx-admin?fbclid=IwAR2thCyhhuWF0um4OyOOjZCunlC-ELZPcpu6tlSn-aRkEqYKYO3CknRNDjU
