### ISSUE TITLE
Package "ngx-bootstrap" was found but does not support schematics.

### ISSUE THREAD

**Issue by kasir-barati** [valor-software/ng2-bootstrap#6481]
Bug description:
Hello, I tried to install the package `ng add ngx-bootstrap` but I got a weird behavior. I just did this:
```cmd
$ ng new app-name --package-manager pnpm
```
And then:
```cmd
[kasir@kasir go-back-to-score-one-in-learning-angular]$ ng add ngx-bootstrap
ℹ Using package manager: pnpm
✔ Found compatible package version: ngx-bootstrap@0.0.1.
✔ Package information loaded.

The package ngx-bootstrap@0.0.1 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Package "ngx-bootstrap" was found but does not support schematics.
[kasir@kasir go-back-to-score-one-in-learning-angular]$ ng add ngx-bootstrap
Skipping installation: Package already installed
Package "ngx-bootstrap" was found but does not support schematics.
[kasir@kasir go-back-to-score-one-in-
[kasir@kasir go-back-to-score-one-in-learning-angular]$ 
```

It installs **0.0.1** via angular CLI. And [in the doc you've said I can use Angular CLI way](https://valor-software.com/ngx-bootstrap/#/documentation#installation). My preference as far as it is possible.

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap:
0.0.1
Angular:
- @angular/cli: ~14.0.5
- Angular: ^14.0.0

**Expected behavior**

0.0.1 is installed but I wanted latest version which ATM is 8.0.0

# latest point
IDK whether this is a bug in my OS or it is a bug in angular cli or it is just not updated documentation

:warning:And also if I do `pnpm add ngx-bootstrap@8.0.0` it will be installed but:
```cmd
[kasir@kasir go-back-to-score-one-in-learning-angular]$ pnpm add ngx-bootstrap
 WARN  deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
Packages: +1 -238
+--------------------------------------------------------------------------------------------------------------------------
Progress: resolved 867, reused 846, downloaded 1, added 1, done

dependencies:
- ngx-bootstrap 0.0.1
+ ngx-bootstrap 8.0.0

 WARN  Issues with peer dependencies found
.
└─┬ ngx-bootstrap
  ├── ✕ unmet peer @angular/animations@^13.0.0: found 14.0.5
  ├── ✕ unmet peer @angular/core@^13.0.0: found 14.0.5
  ├── ✕ unmet peer @angular/common@^13.0.0: found 14.0.5
  └── ✕ unmet peer @angular/forms@^13.0.0: found 14.0.5
```

**Comment by t-macabee** [comment]
Have you found the solution to the problem?

**Comment by kasir-barati** [comment]
@t-macabee nope. I finally did install it using normal way -- npm i

**Comment by SvetlanaMuravlova** [comment]
@kasir-barati , hi) thank you for your issue. We've tested it with angular 13 and it works fine, according doc ngx-bootstrap 8 is not compatible with angular 14.
Actually, there is a pr with fixies for schematic in new version https://github.com/valor-software/ngx-bootstrap/pull/6508
you can try it after the release and if you will have some issue let us know, please)
