### ISSUE TITLE
Useless hover effect in date-range-picker

### ISSUE THREAD

**Issue by AndriiTsybrukh** [valor-software/ng2-bootstrap#6483]
In date-range-picker years section when we hover on date-range in header we can see some hover effect that look likes clickable, but when we click it do nothing. In my point of view it would be better to remove this hover effect.

![Screenshot from 2022-07-15 12-05-58](https://user-images.githubusercontent.com/13647466/179193954-7ebb0a66-4ecf-4fff-9431-a677b5db86b5.png)

**Comment by SvetlanaMuravlova** [comment]
@AndriiTsybrukh hi, thank you for your issue, but i can't confirm such issue
check it, please, on our site https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=overview
or add more details to your issue and reopen it)
