### ISSUE TITLE
9.0.0-RC.1 still requires Angular 13 as a peer dependency

### ISSUE THREAD

**Issue by mpab1410** [valor-software/ng2-bootstrap#6484]
I tried using the new package posted today, and it installed fine on a fresh project though it's still throwing errors about requiring Angular 13 as a peer dependency. Looks like a file might have been missed?

https://github.com/valor-software/ngx-bootstrap/blob/2bae2bfb6a4bd6738b230f2d3265c23f702424ac/src/root/package.json

![image](https://user-images.githubusercontent.com/22943068/179780387-ea8e9678-e1f5-4183-a0b6-0b8acf5078ae.png)

**Comment by valorkin** [comment]
my bad, was focused on fixing cypress at CI
https://github.com/valor-software/ngx-bootstrap/pull/6485

**Comment by valorkin** [comment]
9.0.0-RC.2 is on npm
if you will face any issues, mention me
