### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by joelmuskwe** [valor-software/ng2-bootstrap#6486]
Bug description:
On Datepicker for Daterangepicker with timepicker after selecting a range updating the time parts not working either using the up/down chevron icons or the hour and time inputs

StackBlitz: https://stackblitz.com/edit/angular-ivy-dcjwgp

Versions:
ngx-bootstrap: v8.0.0

Angular: v14.0.6

Bootstrap: v5.1.0

Build system: Angular CLI

**Expected behavior**

One should be able to edit the time sections using the timepicker component.

**Comment by SvetlanaMuravlova** [comment]
@joelmuskwe hi) thannk you for your issue, but it seems it is resolved in 9.0.0 version, try, please
