### ISSUE TITLE
NPM readme compatibility matrix outdated

### ISSUE THREAD

**Issue by jonnytest1** [valor-software/ng2-bootstrap#6491]
Before opening an issue, please search for duplicates (opened and closed) https://github.com/valor-software/ngx-bootstrap/issues There's no need to open an issue here if you want to ask general question, use StackOverflow or Slack instead

Bug description:
the compatibility matrix over on 
https://www.npmjs.com/package/ngx-bootstrap#Compatibility
is outdated (only going up to version 6)
=> /src/root/README.md (probably)

(with release 9 the readme in the root directory is also outdated)
=> /README.md

**Comment by SvetlanaMuravlova** [comment]
@jonnytest1 , hi, thank you for your issue, fixes are in this pr https://github.com/valor-software/ngx-bootstrap/pull/6506, so it will be fixed in the nearest release
