### ISSUE TITLE
Virtual Scroll "breaks" user experience after ShowElement() - Forcing Document to Scroll to Top

### ISSUE THREAD

**Issue by dontboyle** [valor-software/ng2-bootstrap#6493]
https://github.com/valor-software/ngx-bootstrap/blob/development/src/modal/modal.directive.ts

In the file above in your showElement() method.

          this._renderer.setProperty(
            this._element.nativeElement,
            'scrollTop',
            0
          );
          
 This code breaks virtual scrolling by resetting page ;/ regular bootstrap doesn't move to top.
  
Stackblitz example - regular bootstrap: 

https://stackblitz.com/edit/angular-bootstrap-modal-service-3rigvr?file=src/app/app.component.html

**Comment by dontboyle** [comment]
Adding this works (hoping someone else will find this helpful)

Minor change in your code base.

   
        this._renderer.setStyle(document.documentElement, 'height', '100vh');
        this._renderer.setStyle(document.documentElement, 'overflow', 'visible');

    
![image](https://user-images.githubusercontent.com/8333350/184211477-891bbc42-77fd-4e06-9714-de0992009316.png)

and (back to normal on hide)


          this._renderer.setStyle(document.documentElement, 'height', '');
          this._renderer.setStyle(document.documentElement, 'overflow', 'visible auto');
          
          
![image](https://user-images.githubusercontent.com/8333350/184213522-c4400b05-8a21-4715-b8d6-3ff3c686239d.png)

**Comment by dontboyle** [comment]
If you're using AppBsModalDirective ontop of this Library:

`

   import { Directive, ElementRef, Renderer2, ViewContainerRef } from '@angular/core';
   import { ModalDirective } from 'm3-custom-ngx-bootstrap-modal/src/modal';
   import { ComponentLoaderFactory } from 'ngx-bootstrap/component-loader';
   import { ModalDirective, ModalOptions } from 'ngx-bootstrap/modal';
   import { document } from 'ngx-bootstrap/utils';

   @Directive({
    selector: '[appBsModal]',
    exportAs: 'bs-modal',
   }) 
 export class AppBsModalDirective extends ModalDirective {
    private renderer: Renderer2;

    constructor(element: ElementRef, viewContainerRef: ViewContainerRef, renderer: Renderer2, clf: ComponentLoaderFactory, modalDefaultOption: ModalOptions) {
        super(element, viewContainerRef, renderer, clf, modalDefaultOption);
        this.renderer = renderer;
    }

    showElement(): void {
        this.beforeShowModal();
        super.showElement();
        this.setZIndexes();
    }
    hideModal(): void {
        super.hideModal();
        this.afterHideModal();
    }

    /**
     * This method prevents breaking of virtual scroll
     */
    beforeShowModal() {
        this.renderer.setStyle(document.documentElement, 'height', '100vh');
        this.renderer.setStyle(document.documentElement, 'overflow', 'visible');
    }

    /**
     * This method resets bsModal to Default
     */
    afterHideModal() {
        this.renderer.setStyle(document.documentElement, 'height', '');
        this.renderer.setStyle(document.documentElement, 'overflow', 'visible auto');
    }

    setZIndexes(): void {
        let newZIndex = this.setAndGetModalZIndex();
        this.setBackDropZIndex(newZIndex - 1);
    }

    setAndGetModalZIndex(): number {
        let modalBaseZIndex = 1050;
        //let modalsLength = document.querySelectorAll('.modal.fade.show').length;
        let modalsLength = document.querySelectorAll('.modal.in.show').length; //mod: This is the new version
        let newZIndex = modalBaseZIndex + modalsLength * 2;
        (this as any)._element.nativeElement.style.zIndex = newZIndex.toString();
        return newZIndex;
    }

    setBackDropZIndex(zindex: number): void {
        setTimeout(() => {
            //let modalBackdrops = document.querySelectorAll('.modal-backdrop.fade.show');
            let modalBackdrops = document.querySelectorAll('.modal-backdrop.in.show'); //mod:This is the new version
            (modalBackdrops[modalBackdrops.length - 1] as HTMLElement).style.zIndex = zindex.toString();
        }, 500);
    }
   }


`

**Comment by SvetlanaMuravlova** [comment]
hi, @dontboyle ) thank you for your issue, but i am not agree with you, sorry
As i can see it is native behaviour  of bootstrap. 
https://getbootstrap.com/docs/5.2/components/modal/
So i will close it, if we are wrong let us know it)
