### ISSUE TITLE
Missing version compatibility information for 9.0.0

### ISSUE THREAD

**Issue by knulpi** [valor-software/ng2-bootstrap#6498]
**Description:**
The version compatibility matrix currently misses information for version `9.0.0`. When trying to install it along with Angular v13, npm fails, since 9.0.0 seems to need Angular v14. I am confused, and I bet others are, too.
What versions of BS and Ng is 9.0.0 compatible with? Would make a PR if I go this piece of information.

**Comment by hakimio** [comment]
It now depends on Angular v14 based on `package.json`.
```json
"peerDependencies": {
    "@angular/animations": "^14.0.0",
    "@angular/core": "^14.0.0",
    "@angular/common": "^14.0.0",
    "@angular/forms": "^14.0.0",
    "rxjs": "^6.5.3 || ^7.4.0"
  }
```
Bootstrap compatibility should be unchanged.
