### ISSUE TITLE
TabSet display: none for not active pane blocks any modal to be visible

### ISSUE THREAD

**Issue by adurmus** [valor-software/ng2-bootstrap#6507]
```
<tabset>
<tab class="active">
 <modal1> <modal1>
</tab>
<tab >
<modal2> <modal2>
</tab>
</tabset>
```
if you have some components that is in tabs that are not active then those modalsv(modal2 in the above example) cannot be used. Backdrop works but the modal is not visible  as  the following in place.
```
.tab-content > .tab-pane {
  display: none;
}
```
Is there any way to avoid this issue other than moving all components outside of `tab`?

**Comment by SvetlanaMuravlova** [comment]
@adurmus hi) thank you for your issue) We need more details. 
As ex. you can look at our documentation site. There we use tabs and modals together and it works fine.
https://valor-software.com/ngx-bootstrap/#/components/modals?tab=overview
