### ISSUE TITLE
Documentation of 8.0.0 is unavailable

### ISSUE THREAD

**Issue by theSmokingFrog** [valor-software/ng2-bootstrap#6510]
**Description:**
While trying to access the documentation for 8.0.0 a few minutes ago, the documentation seems not to be available. While the `index.html` seems to be present, `runtime.js`, `polyfills.js` and `main.js` are responding with a 404.

The screenshot below shows the exact behaviour with URL and Network Monitor. This has been verified with multiple Browsers (and without Extensions) to ensure nothing is accidentally blocked.

![Screenshot 2022-09-19 at 16 26 02](https://user-images.githubusercontent.com/6443744/191041508-d0c27758-e4ac-4c7c-84ab-1927a1f33f83.png)

I'm trying to solve my issues using 9.x docs but it is highly unfortunate to not have documentation available.

**Comment by SvetlanaMuravlova** [comment]
Now it is fixed
