### ISSUE TITLE
latest not compatible with angular 14.2.0

### ISSUE THREAD

**Issue by mzramna** [valor-software/ng2-bootstrap#6519]
trying to install using `ng add ngx-bootstrap` but returns `/node_modules/@schematics/angular/utility/test.js`

**Comment by markwilx** [comment]
I'm seeing the same thing.  I'm trying to upgrade from Angular 13.3.12 to Angular 14.2.0 using the command:
$ ng update @angular/core@14 @angular/cli@14

Among others, I receive the following errors:
Package "ngx-bootstrap" has an incompatible peer dependency to "@angular/animations" (requires "^11.0.0 || ^12.0.0" (extended), would install "14.2.12").

I hope this information is helpful.

Mark

**Comment by SvetlanaMuravlova** [comment]
yeah, it is true, you will be able to do it with version 10, i believe it will be soon
