### ISSUE TITLE
Rating aria attribute valid values

### ISSUE THREAD

**Issue by Aryan576** [valor-software/ng2-bootstrap#6564]
<rating class="start-yellow"  [(ngModel)]="item.rating" name="most_popular_rating" [max]="numberStar" [readonly]="true">
                                                            </rating>

how can i solve the problem for given code regrading rating tag of ngx-bootstrap

**Comment by SvetlanaMuravlova** [comment]
@Aryan576 ,  hi, thank you for issue, but i don't understand your problem with rating, create, please, stackblitz reproduce or share with more info, please

**Comment by SvetlanaMuravlova** [comment]
@Aryan576 , reopen, please, this issue with all needed details
