### ISSUE TITLE
How to make btnRadio active on two values

### ISSUE THREAD

**Issue by Et3rnal** [valor-software/ng2-bootstrap#6578]
**Is your feature request related to a problem? Please describe.**

I'm updating a simple radio button view to use `btnRadioGroup` however I have one radio which need to be selected if the value is 2 and 3
This doesn't seem to be possible using something like `[btnRadio]="2 || 3"` with or without `btnRadioGroup`
It works fine if the value is 2 but doesn't if the value is 3

**Describe the solution you'd like**
Allow for logical options somehow! like the above or `"radioModel == 2 || radioModel == 3"` or a function

**Describe alternatives you've considered**
I tried the above, and also tried using a function like `[btnRadio]="isSelected(radioModel)"` and `[btnRadio]="isSelected(radioModel) == 'yes'"` but nothing seems to do it

Currently, I have 2 labels for each option and only show one based one which is selected, not sure yet if this will have any issues

**Additional context**
[Example](https://stackblitz.com/edit/angular-a8xbxw?file=src%2Fmain.ts)

**Comment by lexasq** [comment]
It doesn't work because this is also a value that should be provided on click on this option. You got to remove 2way binding on your model, and "manually" update your model on radio button click with the specific function, then it should work, but generally don't do that.
