### ISSUE TITLE
Datepicker (or any other component) fails during runtime

### ISSUE THREAD

**Issue by vyagi** [valor-software/ng2-bootstrap#6580]
I am trying to use DatePicker and added the following to the app.module.ts:

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { BsDatepickerModule } from 'ngx-bootstrap/datepicker';

and also

imports: [
    BrowserAnimationsModule,
    BsDatepickerModule.forRoot(),

but in runtime I get in the console log:

caught TypeError: (0 , tslib__WEBPACK_IMPORTED_MODULE_5__.__metadata) is not a function
    at 618 (ngx-bootstrap-tooltip.mjs:335:15)
    at __webpack_require__ (bootstrap:19:1)
    at 863 (ngx-bootstrap-component-loader.mjs:337:1)
    at __webpack_require__ (bootstrap:19:1)
    at 6747 (app.component.html:45:101)
    at __webpack_require__ (bootstrap:19:1)
    at 4431 (environment.ts:3:2)
    at __webpack_require__ (bootstrap:19:1)
    at __webpack_exec__ (template.module.ts:20:20)
    at template.module.ts:20:20
6

**Comment by ravinderwalkover** [comment]
Hi @vyagi ,

Were you able to solve the issue?

**Comment by vyagi** [comment]
No

**Comment by ravinderwalkover** [comment]
@vyagi Just install "webpack": "5.78" as dev dependency and it should work.

let me know

**Comment by ravinderwalkover** [comment]
@vyagi it worked for me when i removed tslib from tsconfig.json

"tslib" : [
    "./node_modules/tslib/tslib.d.ts"
]
            
Just remove above code from tsconfig.json if you have.

**Comment by KaniramKumawat** [comment]
@vyagi it working for me also after removed tslib from tsconfig.json and re-run app

"tslib" : [
"./node_modules/tslib/tslib.d.ts"
]
