### ISSUE TITLE
Issue with BsDropdownModule

### ISSUE THREAD

**Issue by Gem-DeebanPari** [valor-software/ng2-bootstrap#6587]
error NG6002: 'BsDropdownModule' does not appear to be an NgModule class.

 47   imports: [
               ~
 48     BrowserModule,
    ~~~~~~~~~~~~~~~~~~
...
 54     BsDropdownModule.forRoot()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 55   ],
    ~~~

2 export declare class BsDropdownModule {
                           ~~~~~~~~~~~~~~~~
    This likely means that the library (ngx-bootstrap/dropdown) which declares BsDropdownModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
![BsDropdownModule](https://github.com/valor-software/ngx-bootstrap/assets/121025987/e1dc21cb-5d21-4755-a789-8a0f7f0a018d)

**Comment by Sereena27** [comment]
i am also have this error. 'BsDropdownModule' does not appear to be an NgModule class.

**Comment by Gem-DeebanPari** [comment]
> i am also have this error. 'BsDropdownModule' does not appear to be an NgModule class.

did u get any solution?

**Comment by swaggoo** [comment]
You need to update ngx-bootrstap:

`npm i ngx-bootstrap@10.3.0 --save`

v10.x.x is compatible with Angular 15.x.x

For other versions, please refer to the version compatibility list:
[Versions compatibility list](https://valor-software.com/ngx-bootstrap/#/documentation#compatibility)

**Comment by fantasyhwp** [comment]
but my angular version is 16.0.4 how can i choose bootrstap?


> You need to update ngx-bootrstap:
> 
> `npm i ngx-bootstrap@10.3.0 --save`
> 
> v10.x.x is compatible with Angular 15.x.x
> 
> For other versions, please refer to the version compatibility list: [Versions compatibility list](https://valor-software.com/ngx-bootstrap/#/documentation#compatibility)

**Comment by Jalpesh31** [comment]
> but my angular version is 16.0.4 how can i choose bootrstap?
> 
> > You need to update ngx-bootrstap:
> > `npm i ngx-bootstrap@10.3.0 --save`
> > v10.x.x is compatible with Angular 15.x.x
> > For other versions, please refer to the version compatibility list: [Versions compatibility list](https://valor-software.com/ngx-bootstrap/#/documentation#compatibility)

you need to update ngx-bootsrap
npm i ngx-bootstrap@11.0.0 --save
