### ISSUE TITLE
Module not found after update to v11

### ISSUE THREAD

**Issue by MPapini91** [valor-software/ng2-bootstrap#6596]
After updating to v.11 I can't serve my project, getting "Failed to compile". For every module I get a message like:
`Module not found: Error: Can't resolve 'ngx-bootstrap/modal'`.
I'm using a module for importing ngx-bootstrap components:
```
@NgModule({
  declarations: [],
  imports: [
    AlertModule.forRoot(),
    BsDropdownModule.forRoot(),
    ModalModule.forRoot(),
    TabsModule.forRoot(),
    TooltipModule.forRoot(),
    AccordionModule.forRoot(),
    RatingModule.forRoot(),
    TypeaheadModule.forRoot(),
    PaginationModule.forRoot(),
    ProgressbarModule.forRoot()
  ],
  exports: [
    AlertModule,
    BsDropdownModule,
    ModalModule,
    TabsModule,
    TooltipModule,
    AccordionModule,
    RatingModule,
    TypeaheadModule,
    PaginationModule,
    ProgressbarModule
  ]
})
export class BootstrapImportModule { }
```

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 11.0.0

Angular: 16

Bootstrap: 5.2.3

**Comment by swapnil0545** [comment]
Facing same issues. Was about to raise the same issue.

**Comment by ELHARROUCHI** [comment]
> After updating to v.11 I can't serve my project, getting "Failed to compile". For every module I get a message like: `Module not found: Error: Can't resolve 'ngx-bootstrap/modal'`. I'm using a module for importing ngx-bootstrap components:
> 
> ```
> @NgModule({
>   declarations: [],
>   imports: [
>     AlertModule.forRoot(),
>     BsDropdownModule.forRoot(),
>     ModalModule.forRoot(),
>     TabsModule.forRoot(),
>     TooltipModule.forRoot(),
>     AccordionModule.forRoot(),
>     RatingModule.forRoot(),
>     TypeaheadModule.forRoot(),
>     PaginationModule.forRoot(),
>     ProgressbarModule.forRoot()
>   ],
>   exports: [
>     AlertModule,
>     BsDropdownModule,
>     ModalModule,
>     TabsModule,
>     TooltipModule,
>     AccordionModule,
>     RatingModule,
>     TypeaheadModule,
>     PaginationModule,
>     ProgressbarModule
>   ]
> })
> export class BootstrapImportModule { }
> ```
> 
> Versions of ngx-bootstrap, Angular, and Bootstrap:
> 
> ngx-bootstrap: 11.0.0
> 
> Angular: 16
> 
> Bootstrap: 5.2.3

the same :(

**Comment by riiight** [comment]
Same here.

**Comment by cgcdoss** [comment]
Same issue here

**Comment by mrjohnr** [comment]
same here

**Comment by JasonWeinzierl** [comment]
There's something wrong with the "exports" paths in `node_modules/ngx-bootstrap/package.json`.  They seem to be pointing to folders which don't exist.

I was able to fix it locally by find-and-replacing fesm2020 with fesm2022.

**Comment by swapnil0545** [comment]
Thanks @JasonWeinzierl I was not knowing much about these things. Was wondering about same until I found your comment and this reference for docs 
https://angular.io/guide/angular-package-format
Is anyone working on a PR or raised any?

**Comment by omarrezk98** [comment]
Facing same issues. Was about to raise the same issue.

**Comment by MPruntel** [comment]
#6599

**Comment by tstaals** [comment]
We face the same issue, and really need a fix, locally we can rename, but not in our build pipelines

**Comment by kevinlinar** [comment]
Same issue here.

**Comment by malcomm** [comment]
Same

**Comment by orlandoburli** [comment]
> There's something wrong with the "exports" paths in `node_modules/ngx-bootstrap/package.json`. They seem to be pointing to folders which don't exist.
> 
> I was able to fix it locally by find-and-replacing fesm2020 with fesm2022.

This fix works for me. Also there is the PR #6599 to fix it.

**Comment by kevinlinar** [comment]
This issue was closed, but I still have the same problem. Any recommendations?

**Comment by mrjohnr** [comment]
I've updated to 11.0.1 but the same problem

**Comment by omarrezk98** [comment]
I've updated to 11.0.1 but the same problem

**Comment by valorkin** [comment]
this is super weird, do you have some small repo so I could check

**Comment by valorkin** [comment]
finally, found it

**Comment by valorkin** [comment]
v11.0.2 works for me, please try

**Comment by kevinlinar** [comment]
> v11.0.2 funciona para mí, intente

Perfect.

**Comment by wojciechpolak** [comment]
Unfortunately, v11.0.2 doesn't yet fully solve the problem.

14 07 2023 08:21:49.963:INFO [karma-server]: Karma v6.4.1 server started at http://localhost:9876/
14 07 2023 08:21:49.967:INFO [launcher]: Launching browsers ChromeHeadlessCustom with concurrency unlimited
14 07 2023 08:21:49.972:INFO [launcher]: Starting browser ChromeHeadless
14 07 2023 08:21:50.487:INFO [Chrome Headless 114.0.5735.133 (Linux x86_64)]: Connected on socket v_CBf7CMwfnW3AtKAAAB with id 91243169
Chrome Headless 114.0.5735.133 (Linux x86_64) ERROR
  Uncaught Error: Cannot find module 'ngx-bootstrap/modal'
  at http://localhost:9876/_karma_webpack_/main.js:114104:50
  
  Error: Cannot find module 'ngx-bootstrap/modal'
      at webpackMissingModule (http://localhost:9876/_karma_webpack_/main.js:114104:50)
      at Module.78105 (http://localhost:9876/_karma_webpack_/main.js:114104:144)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.23475 (http://localhost:9876/_karma_webpack_/main.js:115209:80)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.53745 (http://localhost:9876/_karma_webpack_/main.js:115546:84)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.63708 (http://localhost:9876/_karma_webpack_/main.js:108525:88)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.51499 (http://localhost:9876/_karma_webpack_/main.js:102824:79)

ngx-bootstrap: 11.0.2
angular: 16.1

(there is no problem with ngx-bootstrap v9.0.0 from which I try to upgrade)

**Comment by kevinlinar** [comment]
> 

Delete the node_modules folder and run npm i.

**Comment by kevinlinar** [comment]
> Desafortunadamente, v11.0.2 aún no resuelve completamente el problema.
> 
> 14 07 2023 08:21:49.963:INFO [karma-server]: servidor Karma v6.4.1 iniciado en http://localhost:9876/ 14 07 2023 08:21:49.967:INFO [lanzador]: lanzamiento de navegadores ChromeHeadlessCustom con concurrencia ilimitada 14 07 2023 08:21:49.972:INFO [launcher]: navegador de inicio ChromeHeadless 14 07 2023 08:21:50.487:INFO [Chrome Headless 114.0.5735.133 (Linux x86_64)]: conectado en el socket identificación 9 1243169 Cromado Sin Cabeza 114.0 .5735.133 (Linux x86_64) ERROR Error no detectado: no se puede encontrar el módulo 'ngx-bootstrap/modal' en http://localhost:9876/_karma_webpack_/main.js:114104:50
> 
> Error: no se puede encontrar el módulo 'ngx-bootstrap/modal' en webpackMissingModule ( http://localhost:9876/_karma_webpack_/main.js:114104:50 ) en Module.78105 ( [http://localhost:9876/_karma_webpack_ /main.js:114104:144](http://localhost:9876/_karma_webpack_/main.js:114104:144) ) en **webpack_require** ( http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1 ) en Module.23475 ( [http://localhost:9876/_karma_webpack_/main. js:115209 :80](http://localhost:9876/_karma_webpack_/main.js:115209:80) ) en **webpack_require** ( http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1 ) en Module.53745 ( [http://localhost:9876/_karma_webpack_/main.js:115546 :84](http://localhost:9876/_karma_webpack_/main.js:115546:84)) en **webpack_require** ( [http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1 )](http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1) en Module.63708 ( http://localhost:9876/_karma_webpack_/main.js:108525:88 ) en **webpack_require** ( http://localhost:9876/_karma_webpack_/webpack:/webpack/bootstrap:19:1 ) en Module.51499 ( http://localhost:9876/_karma_webpack_/main.js:102824:79 )
> 
> ngx-bootstrap: 11.0.2 angular: 16.1
> 
> (no hay problema con ngx-bootstrap v9.0.0 desde el cual trato de actualización)

Delete the node_modules folder and run npm i.

**Comment by valorkin** [comment]
@wojciechpolak I don't use Karma for a while, please create a small repo to reproduce issue

**Comment by wojciechpolak** [comment]
Ok, I was able to solve it. A small change is tsconfig.json for "module" from es2020 to es2022 did the trick.
