### ISSUE TITLE
Could not resolve dependency: npm ERR! peer @angular/animations@"^15.0.0" from ngx-bootstrap@10.3.0

### ISSUE THREAD

**Issue by nagkumar** [valor-software/ng2-bootstrap#6601]
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular-cofee-shop@0.0.10
npm ERR! Found: @angular/animations@16.1.5
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"~16.1.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"^15.0.0" from ngx-bootstrap@10.3.0
npm ERR! node_modules/ngx-bootstrap
npm ERR!   ngx-bootstrap@"^10.3.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\nagku\AppData\Local\npm-cache\_logs\2023-07-16T08_52_06_203Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\nagku\AppData\Local\npm-cache\_logs\2023-07-16T08_52_06_203Z-debug-0.log
```

**Comment by hakimio** [comment]
You have to update to `11.0.2`

**Comment by nagkumar** [comment]
npmjs registry shows only 10.2.0 as the latest..

<img width="1229" alt="image" src="https://github.com/valor-software/ngx-bootstrap/assets/332234/9503d5d5-0979-419a-9432-78b11acb2011">

also `npm install -g npm-check-updates` unable discover that there is 11.0.2

In any case, I did manually change the package json to use 	`"ngx-bootstrap": "^11.0.2",`

and it works.. Thank You.

If you could further clarify the doubts that would be most helpful. i.e. how far can we trust npm check-updates and npmjs website..to know the latest packages.

**Comment by hakimio** [comment]
That's because 11.0.2 is marked as pre-release on npm.
Tagged as "Next": https://www.npmjs.com/package/ngx-bootstrap?activeTab=versions
