### ISSUE TITLE
Documentation:  TooltipDirective is missing from API documentation

### ISSUE THREAD

**Issue by davebednarski** [valor-software/ng2-bootstrap#6610]
Bug description:
TooltipDirective is missing from API documentation in current (v11.0.2).  See here:
https://valor-software.com/ngx-bootstrap/#/components/tooltip?tab=api

**Expected behavior**
Should have TooltipDirective documentation like other previous versions have.

**Comment by hansireit** [comment]
This might be removed on purpose, because the 'TooltipConfig' already contains the properties that the directive has. If someone can clarify this, I can fix it.
