### ISSUE TITLE
Angular v17 support. 

### ISSUE THREAD

**Issue by JeanMeche** [valor-software/ng2-bootstrap#6618]
Just an issue to track the support for v17.

**Comment by singatias** [comment]
For individuals who, like me, are impatient and wish to update or initiate a new project in Angular 17 while incorporating ngx-bootstrap, you can proceed with the manual installation steps. Ensure to utilize the `--force` parameter when installing packages from now on with your package manager until valor-software makes it fully compatible with Angular v17. I recommend this method only to users with experience, as it can become quite messy if you are not familiar with the process.

edit:
Here a cleaner way to do it, add the following to your `package.json` so it stop throwing errors every time you install a new package:

```json
"overrides": {
    "ngx-bootstrap": {
      "@angular/animations": "17.0.4",
      "@angular/common": "17.0.4",
      "@angular/core": "17.0.4",
      "@angular/forms": "17.0.4"
    }
}
  ```

**Comment by ELHARROUCHI** [comment]
> For individuals who, like me, are impatient and wish to update or initiate a new project in Angular 17 while incorporating ngx-bootstrap, you can proceed with the manual installation steps. Ensure to utilize the `--force` parameter when installing packages from now on with your package manager until valor-software makes it fully compatible with Angular v17. I recommend this method only to users with experience, as it can become quite messy if you are not familiar with the process.
> 
> edit: Here a cleaner way to do it, add the following to your `package.json` so it stop throwing errors every time you install a new package:
> 
> ```json
> "overrides": {
>     "ngx-bootstrap": {
>       "@angular/animations": "17.0.4",
>       "@angular/common": "17.0.4",
>       "@angular/core": "17.0.4",
>       "@angular/forms": "17.0.4"
>     }
> }
> ```

P.R. Plz

**Comment by mischah** [comment]
Hej @g-cheishvili @valorkin, thanks for taking care.

@valorkin Any idea when this will be released 😗

**Comment by FrancescoBorzi** [comment]
@valorkin please prioritise this one, needs to be released with high prio or apps depending on ngx-bootstrap cannot update to Angular 17

**Comment by mischah** [comment]
Seems to be released with v12 🎉 

https://www.npmjs.com/package/ngx-bootstrap?activeTab=versions

**Comment by g-cheishvili** [comment]
Folks, tag me if anything wrong with ng17 compatibility 🤞

**Comment by mischah** [comment]
It would be awesome it the releases page here at GitHub would reflect the versions published to npm 😖 🙏🏻 

That would make things easier (more transparent) 😊 

Compare:
https://github.com/valor-software/ngx-bootstrap/releases
(Latest Release: v11.0.0 from Jul 11)

with:
https://www.npmjs.com/package/ngx-bootstrap?activeTab=versions
(Latest Release: v12.0.0 from Dec 10)

**Comment by Pavlo-0** [comment]
@g-cheishvili 

Thank you for ther answer, 
Yep, my mistake, and wrong library from my side 

...removed unrelevant comment...

**Comment by mischah** [comment]
@Pavlo-0 

’ng-bootstrap’ !=== ’ngx-bootstrap’ 🤪🤓

**Comment by sathiyanathanR82** [comment]
just use npm i bootstrap@5.3.3 from here you can get the document https://getbootstrap.com/
everything works fine for me...

**Comment by singatias** [comment]
> just use npm i bootstrap@5.3.3 from here you can get the document https://getbootstrap.com/ everything works fine for me...

wrong repository, ngx-bootstrap is a project to have javascript functionality with angular natively.
