### ISSUE TITLE
ngx-bootstrap 11.0.2 issue in pagination using Angular 16

### ISSUE THREAD

**Issue by AnwarAlhamzah** [valor-software/ng2-bootstrap#6623]
ngx-bootstrap pagination bug when navigate to next page angular for e.g.:
pageSize= 5
totalCount = 6
first page it contain 5 of 6 and  create 2 navigation pages each page only and it correct
but when I navigate to next page I create 6 navigation pages each page with pageSize =1
kindly find the attache print screen for page=1 and page = 2

export class PagingNavComponent {

  @Input() pageIndex: number;
  @Input() pageSize: number;
  @Input() totalCount: number;

  @Output() pageSizeCahnge = new EventEmitter<number>();
  @Output() pageNavigateChange = new EventEmitter<number>();

  ngAfterViewInit() {
    console.log('after', this.pageIndex, this.pageSize, this.totalCount)
  }

  onPageSizeChange(event: any) {
    this.pageSizeCahnge.emit(event);
  }

  onPageNavChange(event: any) {
    console.log('nav', this.pageIndex, this.pageSize, this.totalCount)
    this.pageNavigateChange.emit(event.page);
  }
}

<footer
  class="d-flex flex-wrap justify-content-between"
  *ngIf="this.totalCount && this.totalCount > 0"
>
  <div class="d-flex-1 align-items-center">
    <select
      class="form-select me-2"
      aria-label="Page size"
      (change)="onPageSizeChange($any($event.target).value)"
    >
      <option value="5" selected>5</option>
      <option value="10">10</option>
      <option value="25">25</option>
      <option value="50">50</option>
    </select>

    <div class="hint-text">
      Page
      <b>
        {{ (this.pageIndex - 1) * this.pageSize + 1 }}
        -
        {{
          this.pageIndex * this.pageSize > this.totalCount
            ? this.totalCount
            : this.pageIndex * this.pageSize
        }}
      </b>
      out of
      <b>
        {{ this.totalCount }}
      </b>
      Pages
    </div>

    <div *ngIf="this.totalCount === 0">
      There are
      <b> 0 </b>
      <b>result of</b> Pages
    </div>
  </div>

  <pagination
    [boundaryLinks]="true"
    [itemsPerPage]="this.pageSize"
    [totalItems]="this.totalCount"
    (pageChanged)="onPageNavChange($event)"
    previousText="&lsaquo;"
    nextText="&rsaquo;"
    firstText="&laquo;"
    lastText="&raquo;"
    *ngIf="this.totalCount > 0"
  >
  </pagination>
</footer>
![Uploading page1.PNG…]()

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by AnwarAlhamzah** [comment]
#Angular16
#Ngx_Bootstrap11
#Pagination

**Comment by wangxun881217** [comment]
have any solution？

**Comment by AnwarAlhamzah** [comment]
Thank you so much the problem was from back-end
