### ISSUE TITLE
Error installing ngx-bootstrap with angular 17

### ISSUE THREAD

**Issue by Zizou84** [valor-software/ng2-bootstrap#6632]
Hello,

I'm starting with angular/bootstrap
Just installing ngx-bootstrap using :_ng add ngx-bootstrap_
**Could not find the project main file inside of the workspace config (src)**
Any idea please?

**Comment by OdeStaples** [comment]
Hi,

I believe this version is compatible with angular v17.0.4 and below, make sure your angular version is same as this one's.

**Comment by LainExperiments** [comment]
Same error here but not idea. I am confused because apparently the installation was success.
```
`✔ Packages successfully installed.
    ✅️ Added "bootstrap
    ✅️ Added "ngx-bootstrap
Could not find the project main file inside of the workspace config (src)`
```

**Comment by hakimio** [comment]
Most likely the library schematics are not compatible with standalone Angular applications where there is no `AppModule`.

**Comment by anderson361163** [comment]
Does anyone know if there were any debugs related to installing ngx-boostrap for angular 17?

**Comment by Wabinab** [comment]
There's a temporary resolve from this stackoverflow: https://stackoverflow.com/questions/77835848/could-not-find-the-project-main-file-inside-of-the-workspace-config-src

To summarize: 
- Add `"main": "src/main.ts"` under "architect/build/options" inside `angular.json`.
- Run `ng add ngx-bootstrap`
- Remove `"main": "src/main.ts"` (he/she mentioned you can't run `ng-serve` if not removed, and your editor might warns you that "main" is not allowed.)

**Comment by sathiyanathanR82** [comment]
Hello everyone,

I use <npm i bootstrap@5.3.3> insted of ngx-bootstrap you can get it from here https://getbootstrap.com/

Its working fine for me

Thanks in Advance
