### ISSUE TITLE
Using ngx-bootstrap v >=10 with bootstrap v3

### ISSUE THREAD

**Issue by tenderserg** [valor-software/ng2-bootstrap#6644]
**Description:**
Good day!
Could you please update the peer-dependency for version 9 so that I can at least use this library with bootstrap v3 and Angular v >= 16?

It is necessary like this:
```
"peerDependencies": {
   "@angular/animations": ">=14.0.0",
   "@angular/common": ">=14.0.0",
   "@angular/core": ">=14.0.0",
   "@angular/forms": ">=14.0.0",
   "rxjs": "^6.5.3 || ^7.4.0"
}
```

Or tell me how to use bootstrap v3 in version ngx-bootstrap version >=10 ?

ngx-bootstrap: 11.0.2
Angular: 16.2.12
Bootstrap: 3.3.7

**Comment by lexasq** [comment]
Bootstrap v3 is deprecated for the higher versions, you should use v4 or v5 only.
