### ISSUE TITLE
Version 11 of your online docs does not load

### ISSUE THREAD

**Issue by djfuzzy** [valor-software/ng2-bootstrap#6649]
Bug description: Trying to access [v11.0.2 docs](https://valor-software.com/ngx-bootstrap/old/11.0.2/#/documentation) shows a loading message and the page never loads. It doesn't matter the browser, type of computer, or internet connection.

**Expected behavior**

The docs load

**Comment by lexasq** [comment]
Thanks for the report, now fixed!
