### ISSUE TITLE
Add support for Angular v18

### ISSUE THREAD

**Issue by eneajaho** [valor-software/ng2-bootstrap#6652]

**Comment by tasdpp** [comment]
Is this something that is going to be addressed, or should I look for an alternative?

**Comment by Sabbacus** [comment]
> Is this something that is going to be addressed, or should I look for an alternative?

There is a pull request for Angular 18. Always look there.
https://github.com/valor-software/ngx-bootstrap/pull/6653

**Comment by vharny** [comment]
When will the new release be available?

**Comment by Pax90** [comment]
A few hours ago, v18.0.0 was released as next via npm [click](https://www.npmjs.com/package/ngx-bootstrap/v/18.0.0?activeTab=versions). I assume that the final version will be released in the next few days.

By the way, I really like the synchronization of the version numbers.
