### ISSUE TITLE
ngx-bootstrap-positioning.mjs - CSP blocking inline styling

### ISSUE THREAD

**Issue by klinges** [valor-software/ng2-bootstrap#6654]
Using the Popover feature, when clicking the button to show the popup, my CSP is not allowing the inline styling to happen. Research shows this is due to the use of Javascript's setAttribute('style','') method. If the method of element.style is used, this won't flag. I'm not going to put "unsafe-inline" in my CSP.

Angular 16.2.6
ngx-bootstrap 11.0.2

![Screenshot 2024-05-30 at 4 05 11 PM](https://github.com/valor-software/ngx-bootstrap/assets/25484879/4006840f-8a6e-4af3-a4a5-ee568ef79e68)

**Comment by klinges** [comment]
Angular 16.2.6
ngx-bootstrap 11

**Comment by evilaliv3** [comment]
@klinges : in @globaleaks we are incurring in the same situation.

How have you achieved to solve the problem in your case?
