### ISSUE TITLE
Modal transition animation not working after Angular 12 (ngx-bootstrap 6.1.0) to Angular 17 (ngx-bootstrap 12.0.0) migration

### ISSUE THREAD

**Issue by danielmcm98** [valor-software/ng2-bootstrap#6675]
My animation for my login modal relies on the fade.in class but after my migration it seems to be stuck on "show" so the transition does not occur. When I manually input "in" into the html via inspector I can see the transition occur correctly but it does not work on its own as it had done previously. The modal is still functional but it does not center itself in the screen it remains stuck on 
.show {
  display: block !important;
}

**Comment by andy840119** [comment]
Guess related to the https://github.com/valor-software/ngx-bootstrap/issues/6547 ?
Also, there's [a PR](https://github.com/valor-software/ngx-bootstrap/pull/6565) trying to fix that, but it's not fix the whole issue.
