### ISSUE TITLE
v18.1.0 breaking change - doesn't work when imported into a non-standalone app.module.ts

### ISSUE THREAD

**Issue by ryanrapini** [valor-software/ng2-bootstrap#6688]
Bug description:

With the update to ngx-bootstrap v18.1.0 from v18.0.0 and no other changes to our code, our project breaks on `ng serve` with the error:
```
Application bundle generation failed. [5.344 seconds]

✘ [ERROR] NG8002: Can't bind to 'popover' since it isn't a known property of 'button'. [plugin angular-compiler]

    src/app/app.component.html:4:2:
      4 │   [popover]="'Vivamus sagittis lacus vel augue laoreet rutrum fauci...
        ╵   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Error occurs in the template of component AppComponent.

    src/app/app.component.ts:5:15:
      5 │   templateUrl: './app.component.html',
        ╵                ~~~~~~~~~~~~~~~~~~~~~~


✘ [ERROR] TS-991010: Value at position 2 in the NgModule.imports of AppModule is not a reference
  Value could not be determined statically. [plugin angular-compiler]

    src/app/app.module.ts:9:11:
      9 │   imports: [BrowserModule, CommonModule, PopoverModule.forRoot()],
        ╵            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Unable to evaluate this expression statically.

    src/app/app.module.ts:9:41:
      9 │   imports: [BrowserModule, CommonModule, PopoverModule.forRoot()],
        ╵                                          ~~~~~~~~~~~~~~~~~~~~~~~

  A value for 'forRoot' cannot be determined statically, as it is an external declaration.

    src/app/app.module.ts:9:41:
      9 │   imports: [BrowserModule, CommonModule, PopoverModule.forRoot()],
        ╵                                          ~~~~~~~~~~~~~~~~~~~~~

```

Plunker/StackBlitz that reproduces the issue:

[Working example with v18.0.0](https://stackblitz.com/edit/stackblitz-starters-qpreq8?file=src%2Fapp%2Fapp.module.ts)

[Non-working example with v18.1.0](https://stackblitz.com/edit/stackblitz-starters-4jecfs?file=src%2Findex.html,src%2Fapp%2Fapp.module.ts)

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: v18.1.0

Angular: 18

Bootstrap: 5

Build system: Angular CLI

**Expected behavior**

Not to break when importing into our non-standalone angular project.

If this breaking change was intended, prevent it from occurring for users who are installing this package with `"^18.0.0"`

**Comment by lexasq** [comment]
@ryanrapini thanks for the report, try removing `.forRoot()` call for now. Looks like there's some miscomunication between angular modules.

**Comment by songokudbz** [comment]
Same issue here.

**Comment by lexasq** [comment]
New release is available, Hope your experience with `ngx-bootstrap will be pleasant.
