### ISSUE TITLE
Dropdown with container is not working anymore!

### ISSUE THREAD

**Issue by elementalTIMING** [valor-software/ng2-bootstrap#6691]
maybe I'm the only one but my dropdowns with a given `container="body"` are not working anymore. I also tested the dropdown example on https://valor-software.com/ngx-bootstrap/#/components/dropdowns?tab=overview#nested-dropdowns and it fails too. The code was running for some years untouched.

Please, can anybody confirm that it isn't working anymore and is there a work-arround?

**Comment by lexasq** [comment]
Hey, I'm aware of this issue, it is addressed and will be released today.

**Comment by lexasq** [comment]
Fixed in 18.1.2
