### ISSUE TITLE
Datepicker locale npt applied

### ISSUE THREAD

**Issue by evil1** [valor-software/ng2-bootstrap#6693]
Since Angular 18 the locale is not applied on BsDatepickerModule.
Even on your official components page `https://valor-software.com/ngx-bootstrap/#/components/datepicker?tab=examples` it is not working.

**Comment by lexasq** [comment]
Hey, thatnks for your report this will be addressed ASAP.

**Comment by lexasq** [comment]
Fixed in 18.1.2

**Comment by evil1** [comment]
> Fixed in 18.1.2

Wow! That was impressively fast! 👍
