### ISSUE TITLE
Wrong docs?

### ISSUE THREAD

**Issue by TymoteuszMH** [valor-software/ng2-bootstrap#6699]
**Description:**
Hi, I was reading documentation and I saw something weird. Few API's shows that I need to import module from datepicker. Here is example from dropdowns:
<img width="382" alt="Zrzut ekranu 2024-10-26 102115" src="https://github.com/user-attachments/assets/9c484d2f-e231-4cf8-ad8a-8e53b553bff5">
Of course it isn't working, because datepicker doesn't contain dropdowns, at least that's what VSC said.
![image](https://github.com/user-attachments/assets/c5fd9d3d-d528-45d2-926b-1860bdf667a1)
So is the documentation wrong? Because when I import it from it's correct place, it works just fine.

**Comment by lexasq** [comment]
Yeah, seems like a typo, thanks!
