### ISSUE TITLE
Sortable drag and drop is broken in 18.1.x

### ISSUE THREAD

**Issue by slubowsky** [valor-software/ng2-bootstrap#6701]
Use ngx-bootstrap demo sortable page - https://valor-software.com/ngx-bootstrap/#/components/sortable?tab=overview
Try to drag something from left column to right column. Doesn't work. Change version to earlier than 18.1.x, works (and it works in 18.0.x)

**Comment by lexasq** [comment]
Thanks for your report, it'll be fixed

**Comment by lexasq** [comment]
Fixed in v19,0,1
