### ISSUE TITLE
Add support for Angular v19

### ISSUE THREAD

**Issue by MatthiasHuygelen** [valor-software/ng2-bootstrap#6710]

**Comment by MatthiasHuygelen** [comment]
Probably have to wait until nx releases support for ng19
https://github.com/nrwl/nx/pull/28847

**Comment by lexasq** [comment]
You guys are sure fast, we'll definitely get there once it settles.

**Comment by iseliweb** [comment]
Basically everything works with Angular 19 as it is. But for sass @import should be replaced with @use to omit the deprecation warnings. Will see whether I can provide a pull request these days.

**Comment by K-e-l-v-i-n-12** [comment]
> Probably have to wait until nx releases support for ng19 [nrwl/nx#28847](https://github.com/nrwl/nx/pull/28847)

The new version has been released in the meantime and now also supports angular 19 🥳

**Comment by mrjohnr** [comment]
I've updated to  ngx-bootstrap v19.0.0 but got:

```
npm error Could not resolve dependency:
npm error peer @angular/animations@"^18.0.1" from ngx-bootstrap@19.0.0
npm error node_modules/ngx-bootstrap
npm error   ngx-bootstrap@"19.0.0" from the root project
```

**Comment by iseliweb** [comment]
Same here, but as a workaround update the package-lock.json manually and update the peers to 19.0.1

**Comment by lexasq** [comment]
That is weird, thanks for the feedback, I'll look into it.

**Comment by Laess3r** [comment]
Hello!
I just wanted to report that I am facing the same issue.

```
npm error Could not resolve dependency:
npm error peer @angular/animations@"^18.0.1" from ngx-bootstrap@19.0.0
npm error node_modules/ngx-bootstrap
npm error   ngx-bootstrap@"19.0.0" from the root project

```

**Comment by lexasq** [comment]
v19.0.1 is up with fix, sorry for inconvenience.

**Comment by Laess3r** [comment]
Thank you very much, it's working! 😄
